### PR TITLE
Fixes projectiles fired by clients always hitting on the chest

### LINKED ISSUE #7499: All projectiles hit the chest indiferent of where you aimed
### Environment
- Game Version: Staging 21093018 
- OS Version: Arch Linux

### Detailed description of bug

as the title says all guns when shot will always hit the chest without taking in consideration if you aimed for a different limb.

https://user-images.githubusercontent.com/80334192/135702642-07592516-7830-4063-a116-12a693aeb898.mp4

### Steps to reproduce

1. take gun and shoot aiming at any limb that isnt the chest 
2. shoot at yourseft or someone else
3. check health

### PR DESCRIPTION
**Pull request by Aranclanos**
### Purpose
CL: [Fix] Fixes projectiles fired by clients always hitting on the chest
Fixes #7499

It was using the server's target, and in headless it never changes

### CODE REVIEW

File: UnityProject/Assets/Scripts/Messages/Client/Interaction/RequestInteractMessage.cs [hunk 1]
```diff
@@ -787,6 +789,7 @@ public static void Serialize(this NetworkWriter writer, RequestInteractMessage.N
 			{
 				writer.WriteVector2(message.TargetVector);
 				writer.WriteBool(message.MouseButtonState == MouseButtonState.PRESS);
+				writer.WriteInt((int) message.TargetBodyPart);
```
Comment (ThatDan123) [inline UnityProject/Assets/Scripts/Messages/Client/Interaction/RequestInteractMessage.cs]:
```suggestion
				writer.WriteUInt(message.TargetBodyPart);
```
Would be better as the reader is UInt?

Comment (Aranclanos) [reply UnityProject/Assets/Scripts/Messages/Client/Interaction/RequestInteractMessage.cs]: but its not an uint

**Review by Bod9001 — APPROVED** [review]

**Review by ThatDan123 — APPROVED** [review]
