### PR TITLE
Overlay fixes

### LINKED ISSUE #6429: Overlays don't match sprite rotation
### Environment
- Game Version: 21042400
- OS Version: Windows 10

### Detailed description of bug
When electrocuted or set on fire, the overlay will not match the player's rotation, whether flipping or falling on the ground.

I tested on a build from a little while ago, and the bug didn't show up on that. From this, I think it's rather likely that this bug was caused by #6387.

### Steps to reproduce

1. Spawn as Engi
2. Hack a door without gloves to get electrocuted
3. Set yourself on fire with a plasma flood. Escape the flood (This is easiest on SquareStation) and do flips / drop to the floor

### PR DESCRIPTION
**Pull request by Semuca**
### Purpose
This PR fixes bugs that I noticed while looking at plasma fires, like player overlays, tile overlays, and Unity throwing modified collection errors in TileList.cs.

### Explanation:
Screenshot 2021-05-09 194229
Overlays are now stored under the sprite gameobject in players, so they rotate whenever the player body rotates. This fixes #6429.

Tile overlays like windows smashing were added too many times because the system was not checking if an overlay was already added correctly. I overwrote the .Equals() function so they can compare in a more functional way.

Tile overlays now have a const which determines the maximum overlays allowed per tile, and some weird code has been cleaned up. Previously, the z position of overlays was increased in this order: 1, 2, 4, 7, 11. Now, they'll increase in a normal ascending order (1, 2, 3, etc).

### Changelog:
CL: Fixed fire and electrocution overlay not matching the player's rotation
CL: Fixed tiles having too many overlays

### CODE REVIEW

File: UnityProject/Assets/Scripts/Tilemaps/Behaviours/Layers/MetaTileMap.cs [hunk 1]
```diff
@@ -954,15 +956,15 @@ public bool HasTile(Vector3Int position, LayerType layerType)
 
 			TileLocation tileLocation = null;
 			OverlayTile overlayTile = null;
-			position.z = 1;
+			position.z = 0;
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/Tilemaps/Behaviours/Layers/MetaTileMap.cs]: the reason it starts at one is because 0 is occupied by non-overlay tiles

Comment (Bod9001) [reply UnityProject/Assets/Scripts/Tilemaps/Behaviours/Layers/MetaTileMap.cs]: but since it's checking for a OverlayTile it doesn't technically clash

Comment (Semuca) [reply UnityProject/Assets/Scripts/Tilemaps/Behaviours/Layers/MetaTileMap.cs]: Since it's incremented at the beginning of the while loop anyway the first position checked is when z = 1

**Comment by ThatDan123** [comment]
"some weird code" who would do such a thing, thanks for fixing it.

**Comment by corp-0** [comment]
> so they rotate whenever the player body rotates

shouldn't flames always be upright?

File: UnityProject/Assets/Scripts/Player/PlayerSprites.cs [hunk 2]
```diff
@@ -91,6 +91,8 @@ public class PlayerSprites : MonoBehaviour
 
 	public bool RootBodyPartsLoaded = false;
 
+	public GameObject OverlaySprites;
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Player/PlayerSprites.cs]: is any other script going to interact with this field? If not, make it private and add ``SerializeField`` attribute instead of making it public.

File: UnityProject/Assets/Scripts/Tilemaps/Behaviours/Layers/MetaTileMap.cs [hunk 3]
```diff
@@ -1165,15 +1167,15 @@ public bool HasOverlay(Vector3Int position, LayerType layerType, OverlayTile ove
...
 
 			if (Layers.TryGetValue(layerType, out var layer))
 			{
-				//Only check 20 as its unlikely to ever have more than 20 overlays
+				//Go through overlays under the overlay limit. The first overlay checked will be at z = 1.
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Tilemaps/Behaviours/Layers/MetaTileMap.cs:1169]: this loop seems to be used a lot and only slightly different each time. Can you extract it into another method to avoid duping code?

File: UnityProject/Assets/Scripts/Tilemaps/Behaviours/Layers/MetaTileMap.cs (hunk 1 above)
Comment (corp-0) [reply UnityProject/Assets/Scripts/Tilemaps/Behaviours/Layers/MetaTileMap.cs]: then the intention would be read better if you started at one and incremented the z at the end

File: UnityProject/Assets/Scripts/Tilemaps/Behaviours/Layers/MetaTileMap.cs (hunk 3 above)
Comment (Semuca) [reply UnityProject/Assets/Scripts/Tilemaps/Behaviours/Layers/MetaTileMap.cs:1169]: Not really, because each loop does something different depending on the function it's in

**Comment by Semuca** [comment]
> > so they rotate whenever the player body rotates
> 
> shouldn't flames always be upright?

But otherwise when the player drops the outline of the player on fire will just be left standing. If you mean wanting to have the fire rise up no matter what rotation the player is at, that's quite a big task which to me isn't all that noticeable. For now I think just rotating the overlay with the player is fine.

File: UnityProject/Assets/Scripts/Tilemaps/Behaviours/Layers/MetaTileMap.cs (hunk 3 above)
Comment (corp-0) [reply UnityProject/Assets/Scripts/Tilemaps/Behaviours/Layers/MetaTileMap.cs:1169]: yes, just slightly different and as you could experience yourself now when you had to make some changes, you had to do the same changes in all loops. Try extracting the part that is identical in all instances, return what the different methods need and operate with that returned value, that way if we need to change the loop we only change it in one place.

**Comment by NoooneyDude** [comment]
> > > so they rotate whenever the player body rotates
> > 
> > 
> > shouldn't flames always be upright?
> 
> But otherwise when the player drops the outline of the player on fire will just be left standing. If you mean wanting to have the fire rise up no matter what rotation the player is at, that's quite a big task which to me isn't all that noticeable. For now I think just rotating the overlay with the player is fine.

Yeah some sort of dynamic flame sprite generation based on the current object sprite would be nice. Could be split into individual, small flame sprites determined by fire stacks and object sprite existence in that area. Could get pretty complicated.

File: UnityProject/Assets/Scripts/Tilemaps/Behaviours/Layers/MetaTileMap.cs (hunk 3 above)
Comment (NoooneyDude) [reply UnityProject/Assets/Scripts/Tilemaps/Behaviours/Layers/MetaTileMap.cs:1169]: I would suggest a `Func` delegate (take to `PlayerList` `getInternal()` and its callers for an example) however I suspect it creates garbage.

Comment (NoooneyDude) [reply UnityProject/Assets/Scripts/Tilemaps/Behaviours/Layers/MetaTileMap.cs:1169]: Actually should be fine if you only create the delegate objects once.

**Comment by corp-0** [comment]
@Semuca do you think you can make the requested changes? Let us know if you find any trouble when trying.

**Comment by Semuca** [comment]
Sorry about all that, I was up to my neck in schoolwork. I need to learn about delegate functions, but that shouldn't be too much. I'll see if I can do that change on Friday.

**Comment by NoooneyDude** [comment]
> Sorry about all that, I was up to my neck in schoolwork. I need to learn about delegate functions, but that shouldn't be too much. I'll see if I can do that change on Friday.

I've decided to merge this now - probably shouldn't keep player prefab in limbo. A followup PR with the refactor would be greatly appreciated, still.
