### PR TITLE
Fixes antags stealing objectives failing

### LINKED ISSUE #7814: Some Objectives are broken
Reported on discord 

image

Player said they had the items and were on the shuttle when docked.

-Might be an issue with the recursive container checking, for the items.
-Unsure of the escape one as that code seems like it should work, needs debugging.

Needs investigating, unsure if you can just spawn as traitor using admin tools and then seeing if objectives complete.

### PR DESCRIPTION
**Pull request by MaxIsJoe**
fixes #7814

Also adds in a new console command for quick debugging without having to end the round every single time to test objectives.

CL: [Fix] fixes a bug causing steal objectives to fail.

### CODE REVIEW

File: UnityProject/Assets/IngameDebugConsole/Scripts/DebugLogUnitystationCommands.cs [hunk 1]
```diff
@@ -20,6 +18,28 @@ namespace IngameDebugConsole
...
+			if (playerSpawned == false)
+			{
+				Logger.LogError("Player has not spawned yet to be able to check for their objectives!");
+				return;
+			}
+			if (PlayerManager.LocalPlayerScript.mind.IsAntag == false)
+			{
+				Logger.LogError("Player is not an antagonist!");
+				return;
+			}
```
Comment (NoooneyDude) [inline UnityProject/Assets/IngameDebugConsole/Scripts/DebugLogUnitystationCommands.cs:34]: Does this still work if you're a ghost?

**Review by NoooneyDude — APPROVED** [review]

File: UnityProject/Assets/IngameDebugConsole/Scripts/DebugLogUnitystationCommands.cs (hunk 1 above)
Comment (Bod9001) [reply UnityProject/Assets/IngameDebugConsole/Scripts/DebugLogUnitystationCommands.cs:34]: works if you're a ghost

**Review by Bod9001 — APPROVED** [review]
