### PR TITLE
SBR lag fix

### LINKED ISSUE #8312: Big Lag With Station Bounced Radios.
### Environment
- Game Version: UnityStationDevelop22013106
- OS Version: gen2

### Detailed description of bug

When there are many station bounced radios next to eachother, a lag spike is caused whenever someone speaks. 

### Steps to reproduce

1. Be admin.
2. Spawn a bunch of station bounced radios (15 should be good).
3. Speak. 
4. Lag.
5. Cry.

### PR DESCRIPTION
**Pull request by MaxIsJoe**
Should fix #8312

CL: [Fix] fixed an issue with station bounced radios causing recursive messages, leading to a lot of lag.

### CODE REVIEW

File: UnityProject/Assets/Scripts/Core/Chat/ChatRelay.cs [hunk 1]
```diff
@@ -252,13 +255,15 @@ private void CheckForRadios(ChatEvent chatEvent)
...
 				{
+					if (SBRSpamCheck == true) break;
 					foreach (var slot in slots)
 					{
 						if (slot.IsEmpty) continue;
 						if (slot.Item.TryGetComponent<LocalRadioListener>(out var listener)
 						    && listener != chatEvent.originator)
 						{
 							listener.SendData(chatEvent);
+							SBRSpamCheck = true;
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/Core/Chat/ChatRelay.cs:250]: where is this Reset?

File: UnityProject/Assets/Scripts/Core/Chat/ChatRelay.cs [hunk 2]
```diff
@@ -234,6 +235,7 @@ private void CheckForRadios(ChatEvent chatEvent)
 		foreach (Collider2D coll in Physics2D.OverlapCircleAll(chatEvent.position,
 			radioCheckRadius, itemsMask))
 		{
+			if (SBRSpamCheck == true) break;
```
Comment (NoooneyDude) [inline UnityProject/Assets/Scripts/Core/Chat/ChatRelay.cs]: ~~`SBRSpamCheck` is always false at this point.~~ Nevermind, read it as `== false` : )

File: UnityProject/Assets/Scripts/Core/Chat/ChatRelay.cs [hunk 3]
```diff
@@ -252,13 +255,15 @@ private void CheckForRadios(ChatEvent chatEvent)
 			{
 				foreach (var slots in playerScript.DynamicItemStorage.ServerContents.Values)
 				{
+					if (SBRSpamCheck == true) break;
```
Comment (ThatDan123) [inline UnityProject/Assets/Scripts/Core/Chat/ChatRelay.cs:242]: You can add this check to line 251 as well, in case it got blocked before

File: UnityProject/Assets/Scripts/Core/Chat/ChatRelay.cs (hunk 1 above)
Comment (ThatDan123) [reply UnityProject/Assets/Scripts/Core/Chat/ChatRelay.cs:250]: It doesnt need to be.

The whole spam prevention is that it only finds one nearby radio and thats it, don't bother searching for more

**Comment by ThatDan123** [comment]
The other way to fix the issue would be to have some static HashSet of radios and add a radios as they are used and clear at the end of the frame

**Comment by MaxIsJoe** [comment]
Alright, it has been tested and after spawning exactly 30 SBRs i no longer find any framerate drops.
approvals pls

**Comment by MaxIsJoe** [comment]
> The other way to fix the issue would be to have some static HashSet of radios and add a radios as they are used and clear at the end of the frame

the issue seems to be fixed right now so i don't see a point of trying to do that currently.

**Review by Bod9001 — APPROVED** [review]

**Review by corp-0 — APPROVED** [review]
