### PR TITLE
Three fixes and two QoL additions 

### LINKED ISSUE #6728: Gateway Stops working
Staging - linux

currently on staging gateways have a tenancy to completely stop working completely

Reproduction by ?????
start round, run it for 30-50 minutes
try gateway
profit?
Screenshot at 2021-06-05 11-53-43

### LINKED ISSUE #6905: Shuttle piloting consoles don't have working fuel gauges.
### Environment
- Game Version: Production 4119
- OS Version: Windows 10

### Detailed description of bug
The shuttle piloting console's UI has a fuel gauge. Unfortunately, the fuel gauge doesn't actually work. The needle will never move no matter how much fuel is left remaining in the plasma canister connected to the shuttle. This means that players have no idea how much fuel they have which can lead to them being stuck in space when they suddenly run out.

### Steps to reproduce
1. Get onto a pilotable shuttle that requires fuel, wrench a plasma canister onto the fuel connector.
2. Fly around for a bit. Notice that the fuel gauge hasn't changed at all.

### PR DESCRIPTION
**Pull request by MaxIsJoe**
- ~~fixes #6905~~
- fixes #6728
- Fixes error spam regarding metatiles in the editor
CL: [Fix] fixed the gateway failing to work after a period of time.
CL: [Improvement] Supply console will now play a sound when your credits update.
CL: [Improvement] The pilot's shuttle will now play a sound upon items entering the radars' range.

Sounds are made by me

### CODE REVIEW

File: UnityProject/Assets/Scripts/Shuttles/ShuttleFuelSystem.cs [hunk 1]
```diff
@@ -21,16 +21,15 @@ public class ShuttleFuelSystem : MonoBehaviour
...
 
-		protected void OnEnable()
+		private void Awake()
 		{
-			if (MatrixMove == null)
-			{
-				MatrixMove = this.GetComponent<MatrixMove>();
-				MatrixMove.RegisterShuttleFuelSystem(this);
-			}
+			if(MatrixMove == null) MatrixMove = GetComponent<MatrixMove>();
```
Comment (Ahion) [inline UnityProject/Assets/Scripts/Shuttles/ShuttleFuelSystem.cs:26]:
```suggestion
			if (MatrixMove == null)
			{
				MatrixMove = this.GetComponent<MatrixMove>();
			}
			if (MatrixMove)
			{
				MatrixMove.RegisterShuttleFuelSystem(this);
			}
```

Comment (Ahion) [reply UnityProject/Assets/Scripts/Shuttles/ShuttleFuelSystem.cs:26]: I decided it like this. The fuel gauge did not work because `MatrixMove.RegisterShuttleFuelSystem(this)` didn't work. It was because `MatrixMove` not equal to null when `OnEnable()` colled.

Comment (Ahion) [reply UnityProject/Assets/Scripts/Shuttles/ShuttleFuelSystem.cs:26]: And why are you change `OnEnable()` to` Awake()` ?

Comment (Ahion) [reply UnityProject/Assets/Scripts/Shuttles/ShuttleFuelSystem.cs:26]: And I didn't need to change code in `MatrixMove.cs`

File: UnityProject/Assets/Scripts/UI/Objects/Shuttles/GUI_ShuttleControl.cs [hunk 2]
```diff
@@ -302,17 +306,19 @@ private IEnumerator Refresh()
...
 					fuelGauge.SetValueServer((100).ToString());
 				}
 
 			}
-			else
+			else if(FuelSystemReference.Connector != null && FuelSystemReference.Connector.canister != null
+			&& FuelSystemReference.Connector.canister.GasContainer != null)
 			{
-				fuelGauge.SetValueServer(Math.Round((MatrixMove.ShuttleFuelSystem.FuelLevel * 100)).ToString());
+				string value = $"{(FuelSystemReference.FuelLevel / 100f * FuelSystemReference.Connector.canister.GasContainer.MaximumMoles)}";
```
Comment (Ahion) [inline UnityProject/Assets/Scripts/UI/Objects/Shuttles/GUI_ShuttleControl.cs]:
```suggestion
				string value = $"{(FuelSystemReference.FuelLevel * 100f)}";
```
`FuelLevel` is already the ratio of the amount of fuel to the maximum capacity. Just multiply by 100 and it should work, shouldn't it?

File: UnityProject/Assets/Scripts/Shuttles/ShuttleFuelSystem.cs (hunk 1 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Shuttles/ShuttleFuelSystem.cs:26]: OnEnable didn't work reliably for some reason, `Awake()` should give consistent results.

File: UnityProject/Assets/Scripts/UI/Objects/Shuttles/GUI_ShuttleControl.cs (hunk 2 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/UI/Objects/Shuttles/GUI_ShuttleControl.cs]: I'll take a look at it in a few hours

**Review by Bod9001 — DISMISSED** [review]

**Comment by MaxIsJoe** [comment]
Solved merge conflicts

File: UnityProject/Assets/Scripts/Shuttles/MatrixMove.cs [hunk 3]
```diff
@@ -318,7 +322,7 @@ private void RecheckThrusters()
 
 	public void RegisterShuttleFuelSystem(ShuttleFuelSystem shuttleFuel)
```
Comment (ThatDan123) [inline UnityProject/Assets/Scripts/Shuttles/MatrixMove.cs:323]: is this used?

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Shuttles/MatrixMove.cs:323]: I don't think so, will have a look in a few.

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Shuttles/MatrixMove.cs:323]: Now it should.

**Comment by MaxIsJoe** [comment]
review again pls

**Comment by corp-0** [comment]
How did you fix #6728?

**Review by Bod9001 — APPROVED** [review]

**Comment by MaxIsJoe** [comment]
> How did you fix #6728?

I just added the missing wire Dan mentioned

**Review by corp-0 — APPROVED** [review]
