### PR TITLE
Fixes admin audio player not working

### LINKED ISSUE #6235: global sound player missing sounds
Staging and release- linux

99% of sounds aren't listed in the global sound player making it virtually useless now
it would also be nice to have a larger selection of sounds for admins to use with events

### LINKED ISSUE #8882: Global Music not work
**Environment**

**- Game Version:** 22-06-17-04
**- OS Version:** Lubuntu 18.04.6x64
**- Linux version**  `5.17.0-14.1-liquorix-amd64 (steven@liquorix.net) (gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, GNU ld (GNU Binutils for Ubuntu) 2.30) #1 ZEN SMP PREEMPT liquorix 5.17-18ubuntu1~bionic (2022-06-10)`
**- Server:** Locale

**Detailed description of bug**
**Context**
Head Officer, in Fallstation, 

on admin modes
open"global music" menu
select a sond
and ear nothing

**the music player  seems to be broken**
I assume this is related to the broken jukebox

### PR DESCRIPTION
**Pull request by MaxIsJoe**
fixes #6235
fixes #8882

CL: [Improvement] The game will no longer use static references to audio clips inside the admin audio player. An Important step to allow future server forks to let them play their own audio clips without re-building the entire game just to update a single asset file.
CL: [Improvement] The Admin Audio windows have been unified under one window. Expect it to be updated further in the future.
CL: [Improvement] Admins now have access to the entire audio library the game has. Most of these are not useable currently due to how they're designed, but in the future; admins will be able to fine tune the properties of audio clips to suit their needs.
CL: [Fix] Fixed weaver issues that caused the game to crash or not compile under some platforms when using `AddressableAudioSource`
CL: [Fix] Admins can now play addressable audio again via their global sound tools.
CL: [Fix] Fixed an issue regarding global audio not working on Linux due to how windows defines paths differently.

### CODE REVIEW

File: UnityProject/Assets/Scripts/UI/Systems/AdminTools/AdminGlobalAudio.cs [hunk 1]
```diff
@@ -12,35 +16,111 @@ namespace AdminTools
...
-			DoLoadAudio(audioAddressables);
+
+			Refresh();
+			DoLoadAudio(catalogueData);
+		}
+
+		public static List<string> GetCataloguePath()
+		{
+			var path = Application.dataPath.Remove(Application.dataPath.IndexOf("/Assets"));
+			path += "/AddressablePackingProjects";
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/UI/Systems/AdminTools/AdminGlobalAudio.cs]: isn't this only for the editor?

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/UI/Systems/AdminTools/AdminGlobalAudio.cs]: let me make a build and check

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/UI/Systems/AdminTools/AdminGlobalAudio.cs]: image

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/UI/Systems/AdminTools/AdminGlobalAudio.cs]: I fixed it

File: UnityProject/Assets/Scripts/UI/Systems/AdminTools/AdminGlobalAudio.cs [hunk 2]
```diff
@@ -12,35 +17,116 @@ namespace AdminTools
...
+			DoLoadAudio(catalogueData);
+		}
+
+		private static List<string> GetCataloguePath()
+		{
+#if UNITY_EDITOR
+			var path = Application.dataPath.Remove(Application.dataPath.IndexOf("/Assets", StringComparison.Ordinal));
+			path = Path.Combine(path, "AddressablePackingProjects");
+#else
+			var path = Path.Combine(Application.streamingAssetsPath, "AddressableCatalogues");
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/UI/Systems/AdminTools/AdminGlobalAudio.cs:47]: it might be better to, get it from the bundle is loaded instead of the local bundles, so if someone has a custom bundle it will automatically update

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/UI/Systems/AdminTools/AdminGlobalAudio.cs:47]: no idea how to do that
