### PR TITLE
Playtest additions and fixes

### LINKED ISSUE #9366: [CARGO] order PDA
There is no way in game to collect a new PDA, except by stealing one from a corpse in medbay.

It would also be nice if, instead of ordering it from a cargo ship, you could print it out.

### PR DESCRIPTION
**Pull request by AtnerNT**
Closes #9366 #9333 #9332 #9331 #9330 #9323

### Changelog:
CL: [Fix] Fixed brain dead bots
CL: [Fix] Fixed speech having no chat bubbles
CL: [Fix] Fixed NRE with artifacts interacting with non-human players
CL: [Fix] Fixed sickness event manager having a missing input field
CL: [Fix] Fixed players wearing disease protective gear being able to spread it to players without
CL: [Fix] Fixed interactions with viro machines not working

CL: [Improvement] Sickness will now be shown with the smily face on med hud
CL: [Improvement] Reorganised Player Manager Admin Page
CL: [Improvement] Admins can now cure diseases
CL: [Improvement] Viro machines now have more descriptive descriptions
CL: [Improvement] Players can no longer stand up if buckled to an object

CL: [New] PDAs, Labeller Refills, Folders & Pens can now be ordered from cargo

### CODE REVIEW

File: UnityProject/Assets/Scripts/UI/Systems/AdminTools/PlayerManagePage.cs [hunk 1]
```diff
@@ -30,23 +30,23 @@ public class PlayerManagePage : AdminPage
 
 		[SerializeField] private Toggle OnWatchlist = null;
 
-		[SerializeField] private TMP_Text JailText;
+		[SerializeField] private Text JailText;
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/UI/Systems/AdminTools/PlayerManagePage.cs:33]: TMP is what we want to use in the future, Text is considered deprecated due to its low fidelity when scaled up

Comment (AtnerNT) [reply UnityProject/Assets/Scripts/UI/Systems/AdminTools/PlayerManagePage.cs:33]: Made this change as the button text on the admin UI is small so the difference between TMP and regular text aint that much but its just more performant.
Also the rest of the UI is just regular text so the TMP stuff looks weird in contrast
