### PR TITLE
Fix for hostile AI going braindead when they spot a player, bots being non-functional

### LINKED ISSUE #3884: Xenos are brain dead
# Xenos are brain dead

## Description
Xenos don't attack players anymore. They don't even move. Looks like something happen with mobs AI.

### PR DESCRIPTION
**Pull request by CodeKalias**
### Purpose
Fixes #3884
Also bots will once again move around and perform their tasks

### Notes:
- [x] Code is sufficiently commented
- [x] Code is indented with tabs and not spaces
- [x] The PR does not include any unnecessary .meta, .prefab or **.unity (scene) changes**
- [x] The PR does not bring up any new compile errors
- [x] The PR has been tested in editor
- [x] The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)
- [x] The PR has been tested with round restarts.

### CODE REVIEW

**Comment by CodeKalias** [comment]
Should be good to go

File: UnityProject/Assets/Scripts/NPC/AI/MobAgent.cs [hunk 1]
```diff
@@ -130,13 +130,26 @@ protected virtual void AgentServerStart()
...
-			return;
+			if ((health.IsDead || health.IsCrit || health.IsCardiacArrest))
+			{
+				//can't do anything this NPC is not capable of movement
+				return;
+			}
+		}
+		else //Bot
+		{
+			if (integrity.integrity <= 0)
```
Comment (fomalsd) [inline UnityProject/Assets/Scripts/NPC/AI/MobAgent.cs:144]: integrity can be null which will give an NRE

Comment (CodeKalias) [reply UnityProject/Assets/Scripts/NPC/AI/MobAgent.cs:144]: Line 133 should mean it can't get there if integrity is null
edit- since health would have to be null at 138, so integrity can't be as well
