### PR TITLE
Reduces maintroom chances + Balances bomb damage

### LINKED ISSUE #9803: [BUG] Maintrooms chances are way too high.
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

Current

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

I got sent to Maintrooms twice in thirty minutes on the same round.

### What should have happened instead?

Should be a 0.1% or so.

### Steps to reproduce the issue

1. Literally just play on squarestation

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MaxIsJoe**
fixes #9803

CL: [Improvement] Added juddering as a side effect to bomb trauma to balance out how deadly explosions are currently. Juddering is when the body receives a shockwave or extreme vibrations to the body which causes internal damage.
CL: [Improvement] Reduced the chances of getting randomly teleported to the maint-rooms.

### CODE REVIEW

File: UnityProject/Assets/Scripts/Objects/Gateway/TransportUtility.cs [hunk 1]
```diff
@@ -22,14 +22,12 @@ public class TransportUtility : NetworkBehaviour //Would be a regular static cla
...
-		public static void TransportObject(UniversalObjectPhysics objectPhysics, Vector3 transportTo, bool doTileStep = true, float maintRoomChanceModifier = 0.5f)
+		public static void TransportObject(UniversalObjectPhysics objectPhysics, Vector3 transportTo, bool doTileStep = true, float maintRoomChanceModifier = 0.25f)
 		{
 			if (objectPhysics == null) return; //Don't even bother...
 
 			var dest = transportTo;
-
-			var RandomChance = Random.Range(0, 100000) / 1000f; //100000 / 1000 = 100
-			if (SubSceneManager.Instance.IsMaintRooms && RandomChance <= maintRoomChanceModifier)
+			if (SubSceneManager.Instance.IsMaintRooms && DMMath.Prob(maintRoomChanceModifier))
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/Objects/Gateway/TransportUtility.cs]: Modified to something like
DMMath.Prob(0.001 * maintRoomChanceModifier)

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Objects/Gateway/TransportUtility.cs]: done :+1:

**Review by corp-0 — APPROVED** [review]
