### PR TITLE
Fixed blood spots to not cause gravity

### LINKED ISSUE #2582: Blood spots cause gravity
If you go out into space and bleed, the tile that has blood on it is treated as having gravity. Blood splats should have absolutely no effect on movement logic.

### PR DESCRIPTION
**Pull request by nikopetr**
### Purpose
Fixed blood spots to not cause gravity, fixes #2582.

### Notes:
Followed @chairbender guidance and added a public method in PushPull, called CausesGravity()  for it.

### CODE REVIEW

File: UnityProject/Assets/Scripts/Objects/PushPull.cs [hunk 1]
```diff
@@ -491,6 +492,17 @@ public RightClickableResult GenerateRightClickOptions()
 			}
 		};
 	}
+	/// <summary>
+	/// Return true if the object causes gravity, otherwise false.
+	/// <returns>bool that represents if the object must cause gravity or not.</returns>
+	/// </summary>
+	public bool CausesGravity()
+    {
+		if (isNotPushable == true || floorDecal!= null)
```
Comment (chairbender) [inline UnityProject/Assets/Scripts/Objects/PushPull.cs]: Not quite right, this causes lockers to stop when pushed out into space.
```suggestion
		if (!isNotPushable || floorDecal!= null)
```

The previous logic is - if an object is not pushable, it causes gravity, thus returning true from this method. Currently it would return false from this method if an object is not pushable. The suggested change fixes that.

**Review by chairbender — CHANGES_REQUESTED** [review]
Thanks for looking into this @nikopetr . The blood splat issue is fixed, however there's a regression introduced by this. 
Try pushing an object such as a locker into space. It should keep drifting, but it stops. This issue doesn't happen on latest develop.

I believe that something may be inverted in the boolean logic in your changed lines. See my comment.

File: UnityProject/Assets/Scripts/Objects/PushPull.cs (hunk 1 above)
Comment (nikopetr) [reply UnityProject/Assets/Scripts/Objects/PushPull.cs]: Thanks for the review @chairbender! You are right. I just wonder why does that happen on lockers since CausesGravity() method is only used by MetaTileMap.IsNoGravityAt() at the moment. Did you try using that method on other objects as well?

**Comment by nikopetr** [comment]
Thanks for the review @chairbender! You are right. I have commited the requested changes. Just wondering why does that happen on lockers since CausesGravity() method is only used by MetaTileMap.IsNoGravityAt() at the moment. Did you try using that method on other objects as well?

**Comment by chairbender** [comment]
Nice, fixed 👍 

It would happen on any impassable but pushable object, such as canisters.
