### PR TITLE
Fixes NREs and issues triggered by protips triggering outside the player's own gameObject and clamped search radius for protips

### LINKED ISSUE #8730: Protip NRE
```
NullReferenceException: Object reference not set to an instance of an object
Learning.ProtipObject.TriggerConditions () (at /root/UnityProject/Assets/Scripts/Learning/ProtipObject.cs:37)
Learning.ProtipObject.TriggerTip () (at /root/UnityProject/Assets/Scripts/Learning/ProtipObject.cs:44)
Pickupable.PickupAnim (UnityEngine.GameObject interactor) (at /root/UnityProject/Assets/Scripts/Systems/Inventory/Pickupable.cs:221)
Pickupable+<ServerPerformInteractionLogic>d__26.MoveNext () (at /root/UnityProject/Assets/Scripts/Systems/Inventory/Pickupable.cs:171)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at /home/bokken/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Pickupable:ServerPerformInteraction(HandApply) (at /root/UnityProject/Assets/Scripts/Systems/Inventory/Pickupable.cs:160)
```

### PR DESCRIPTION
**Pull request by MaxIsJoe**
Fixes #8730

CL: [Fix] - Protips will no longer try to trigger when called on other player objects that the player is not controlling.
CL: [Fix] - Clamped the magnitude of protips' search radius and switched over strictly to client positions. This should finally solve the NRE spam on clients.

### CODE REVIEW

**Review by Bod9001 — DISMISSED** [review]

File: UnityProject/Assets/Scripts/Learning/ProtipObjectTypes/ProtipObjectOnEnterRadius.cs [hunk 1]
```diff
@@ -25,15 +28,16 @@ private void CheckForNearbyItems()
 			foreach (var target in possibleTargets)
 			{
 				if(gameObject == target.gameObject) continue;
-				if (MatrixManager.Linecast(gameObject.RegisterTile().WorldPosition, LayerTypeSelection.Walls,
+				
+				if (MatrixManager.Linecast(Vector3.ClampMagnitude(gameObject.RegisterTile().LocalPositionClient, SearchRadius), LayerTypeSelection.Walls,
```
Comment (Alainx277) [inline UnityProject/Assets/Scripts/Learning/ProtipObjectTypes/ProtipObjectOnEnterRadius.cs]: I think this should clamp the difference between the object and the target.

**Review by Alainx277 — CHANGES_REQUESTED** [review]

File: UnityProject/Assets/Scripts/Learning/ProtipObjectTypes/ProtipObjectOnEnterRadius.cs (hunk 1 above)
Comment (NoooneyDude) [reply UnityProject/Assets/Scripts/Learning/ProtipObjectTypes/ProtipObjectOnEnterRadius.cs]: Linecast takes two world positions, not a local position.

You can return earlier if the magnitude exceeds the square of the radius and avoid the linecast. Though, that shouldn't ever be the case with physics circle overlap.. odd.

I would also suggest caching a reference to the player's `RegisterTile` while you're here - it uses a component fetch under the hood.

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Learning/ProtipObjectTypes/ProtipObjectOnEnterRadius.cs]: Fixed it and I found a solution to stopping the linecast from causing errors by using `Vector3.Distance()` before calling that funciton

**Comment by MaxIsJoe** [comment]
review pls

File: UnityProject/Assets/Scripts/Learning/ProtipObject.cs [hunk 2]
```diff
@@ -30,18 +30,22 @@ private void Awake()
 			if(saved == "true" || TipSO == null) Destroy(this);
 		}
 
-		protected virtual bool TriggerConditions()
+		protected virtual bool TriggerConditions(GameObject triggeredBy)
 		{
+			//To avoid issues with NREs, Protips should only trigger if a PlayerScript exists.
+			if (PlayerManager.LocalPlayerScript == null) return false;
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Learning/ProtipObject.cs:36]: does it exist for players controlling say... AI's or Ghosts?

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Learning/ProtipObject.cs:36]: AIs have local scripts, but do ghosts not have it? Either way ghosts shouldn't receive tips by design, only when the player is still dead in his body.

Comment (corp-0) [reply UnityProject/Assets/Scripts/Learning/ProtipObject.cs:36]: why not? Maybe we do want to tell them stuff like how the ghost roles work or interactions they might be able to do in the future.

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Learning/ProtipObject.cs:36]: we can probably make an protip object specfic to ghosts then since protips currently rely on the existence of a local script and the game likes to complain if it cant find it.

Comment (corp-0) [reply UnityProject/Assets/Scripts/Learning/ProtipObject.cs:36]: alright

**Review by Bod9001 — APPROVED** [review]
