### PR TITLE
Fixed shooting and meleeing windows

### LINKED ISSUE #1534: Shooting and meleeing windows doesn't do any damage B: 25
# Description
When shooting or meleeing a window, no cracks appear. However, throwing DOES damage windows, and some windows on syndicate shuttle are damageable via melee.

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Host in editor.
2. Grab a gun.
3. Try meleeing and shooting a window and see that no cracks appear.

### PR DESCRIPTION
**Pull request by vlandemart**
### Purpose
_Fixes #1534_
Just few bugfixes.
The problem on bullets were that they: a) Didn't get BulletBehaviour from collision correctly, b) Didn't get the right tile.
On the melee a problem was that the TileTrigger switch was trying to use Grill tile map on Window case.

I've tested it on station, on syndicate shuttle - seems to be working. Didn't test with rotated matrix, but it should be fine.

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [x]  This PR has been tested in multiplayer

### Notes:
There is a "KeyNotFoundException" error on destroying grills. TileManager > GetTile cant get destroyed grill. I couldn't find what the problem was, so I'd be happy if someone would point me at the right direction, or look that problem up.

### CODE REVIEW

File: UnityProject/Assets/Scripts/Tilemaps/Behaviours/TilemapDamage.cs [hunk 1]
```diff
@@ -38,26 +38,25 @@ public void OnCollisionEnter2D(Collision2D coll)
...
 		Vector2 dirOfForce = (firstContact.point - (Vector2) coll.transform.position).normalized;
-		DetermineAction(coll.gameObject, dirOfForce);
+		DetermineAction(coll.gameObject, dirOfForce, firstContact.point);
 	}
 
-	private void DetermineAction(GameObject objectColliding, Vector2 forceDirection)
+	private void DetermineAction(GameObject objectColliding, Vector2 forceDirection, Vector3 hitPos)
 	{
-		BulletBehaviour bulletBehaviour = objectColliding.GetComponent<BulletBehaviour>();
+		BulletBehaviour bulletBehaviour = objectColliding.transform.parent.GetComponent<BulletBehaviour>();
```
Comment (krille90) [inline UnityProject/Assets/Scripts/Tilemaps/Behaviours/TilemapDamage.cs:48]:
```suggestion
		BulletBehaviour bulletBehaviour = objectColliding.GetComponentInParent<BulletBehaviour>();
```

Comment (krille90) [reply UnityProject/Assets/Scripts/Tilemaps/Behaviours/TilemapDamage.cs:48]: nvm, doesnt actually work for some reason.
