### PR TITLE
fixes MagBoots not working

### LINKED ISSUE #8812: magboot are sticky
Magboot (all) sticks you to the ground

### PR DESCRIPTION
**Pull request by Bod9001**
fixes ghost moovement of long ranges
fixes maximum speed
fixes : #8812

### CODE REVIEW

File: UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs [hunk 1]
```diff
@@ -176,6 +178,21 @@ public ObjectContainer ContainedInContainer
 
 	[PlayModeOnly] public Vector2 newtonianMovement; //* attributes.Size -> weight
 
+
+	public Vector2 SetNewtonianMovement
```
Comment (Alainx277) [inline UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs]: It seems misleading to prefix a property with `Set`. Why not just call it `NewtonianMovement`?

If the name is too similar to `newtonianMovement`, the convention is to prefix the backing field with an underscore.

File: UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs [hunk 2]
```diff
@@ -61,6 +61,8 @@ public class UniversalObjectPhysics : NetworkBehaviour, IRightClickable
 
 	[PrefabModeOnly] public bool Intangible = false;
 
+	[PlayModeOnly] public bool CanNotBeWindPushed = false;
```
Comment (Alainx277) [inline UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs]: Booleans with `Not` in their names tend to cause confusion. Could it be something like `WindImmunity` instead?

If it were inverted, it could just be called `CanBeWindPushed`.

File: UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs [hunk 3]
```diff
@@ -1060,16 +1077,8 @@ public void PullSet(UniversalObjectPhysics toPull, bool byClient, bool synced =
...
-			{
-				//Logger.LogError("  momentum boost");
-			}
 
-			newtonianMovement += worldDirection * speed;
-			if (newtonianMovement.magnitude > MAX_SPEED)
-			{
-				newtonianMovement *= (MAX_SPEED / newtonianMovement.magnitude);
-			}
+			SetNewtonianMovement = newtonianMovement + worldDirection * speed;
```
Comment (Alainx277) [inline UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs]: Why not use the new property here too? It could then be simplified to just:
```suggestion
			SetNewtonianMovement += worldDirection * speed;
```

File: UnityProject/Assets/Scripts/Player/MovementV2/MovementSynchronisation.cs [hunk 4]
```diff
@@ -330,11 +330,17 @@ public void Update()
...
 			CheckWindOtherPush();
 		}
-
+		else
+		{
+			if (PushingData.magnitude != 0)
+			{
+				PushingData = Vector2.zero;
+			}
+		}
```
Comment (Alainx277) [inline UnityProject/Assets/Scripts/Player/MovementV2/MovementSynchronisation.cs]:
```suggestion
		else if (PushingData.magnitude != 0)
		{
			PushingData = Vector2.zero;
		}
```

File: UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs (hunk 2 above)
Comment (Bod9001) [reply UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs]: find inverted would also be more confusing maybe?

File: UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs (hunk 1 above)
Comment (Bod9001) [reply UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs]: it's the one you want to use when you want to set newtonianMovement,   Since it has the cap on it

File: UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs (hunk 2 above)
Comment (Alainx277) [reply UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs]: I think `CanBeWindPushed` is clearer than `CanNotBeWindPushed == false`, in the second case you have two negations.

File: UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs (hunk 1 above)
Comment (Alainx277) [reply UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs]: It's a property, so you can read from it too, in that case `Set` makes no sense. I assume `newtonianMovement` should never exceed the `MAX_SPEED`, so making it private and only using the property seems better?

Comment (corp-0) [reply UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs]: yeah, that's exactly what properties are for. Make the field private and wrap it with the property which has the cap when you set a value to it, return the private field when you get it.

File: UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs (hunk 2 above)
Comment (corp-0) [reply UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs]: agree

**Review by Alainx277 — APPROVED** [review]
