### PR TITLE
Fixes and improve sounds for food processors

### LINKED ISSUE #5906: Add sound to food processors.
Right now food processors are fully functional gameplay wise, but are lacking a sound and the shaking animation that occurs while it's actively processing food.

The basic functions for the animation are already in FoodProcessor.cs, but due to a LeanTween build error it was commented out. 

Right now there is a syncvar that changes to true while the processor is on and false while the processor is off, and is used to play a looping sound, which was taken from Microwave.cs. However in light of the new sound addressable system both food processors and microwaves do not play sounds while active, probably meaning the function needs to be adjusted to fit the new system.

- [x] add shaking animation
- [x] add sound effect

### PR DESCRIPTION
**Pull request by MaxIsJoe**
closes #5906
CL: [Fix] fixes and improves sounds for food processors

### CODE REVIEW

**Comment by corp-0** [comment]
I think this is fine but not quite sure, Daniel knows better how to loop sounds. We could use with a method from the sound manager in the future that easily loops sounds so we don't have to repeat all of these steps. I will approve and wait for Daniel to confirm.

**Review by corp-0 — DISMISSED** [review]

File: UnityProject/Assets/Scripts/Objects/Machines/FoodProcessor.cs [hunk 1]
```diff
@@ -253,17 +258,22 @@ private void RpcShake(float duration, float distance, float delayBetweenShakes)
 			shaker.StartShake(duration, distance, delayBetweenShakes);
 		}
 
-		private void OnSyncPlayAudioLoop(bool oldState, bool newState)
+		private async void HandleAudio(float duration)
 		{
-			if (newState)
+			if(CustomNetworkManager.IsServer == false) return;
```
Comment (ThatDan123) [inline UnityProject/Assets/Scripts/Objects/Machines/FoodProcessor.cs]:
```suggestion
```

Not really need as it is already checked at line 235

**Review by ThatDan123 — APPROVED** [review]

**Review by corp-0 — APPROVED** [review]
