### PR TITLE
Two fixes + Exposing the customization API Part 1

### LINKED ISSUE #7350: Dismembering arms and heads doesn't drop items when they should be.
### Environment
- Game Version: Staging 21090215
- OS Version: Windows 10

### Detailed description of bug
Title. Dismembering arms and heads doesn't certain held items when they should be dropped. Items held in hands aren't dropped on the floor when you dismember the relevant arm and just seem to disappear. The same happens with items attached to the head (hats, masks, glasses, earpieces, neckwear) but their sprites remain on the attacked character's body unlike with held items while being still inaccessible in the examine menu.

### Steps to reproduce
1. Obtain a traitor's energy sword.
2. Decapitate someone wearing a hat.
3. Notice that the hat sprite still appear's on their body even though they have been beheaded.

### PR DESCRIPTION
**Pull request by MaxIsJoe**
fixes #7350 
fixes an issue related to moth and lizard numbers being wrong for trauma damage.

This PR is the first step for exposing the customization functions to be able to create fully customizable characters during runtime.
This is more meant for things like NPCs, Dummy characters, changing your underwear and hair style when interacting with a mirror or drawer, etc.

### Changelog :
CL : [Fix] - Moths will no longer turn their hands into burnt sticks by just touching light bulbs
CL : [Fix] - Fixed an issue where lizard heads were weaker than humans
CL : [Fix] - Fixed an issue where you wouldn't drop the items you were holding in your hand upon getting your limbs dismembered.

### CODE REVIEW

File: UnityProject/Assets/Scripts/UI/Systems/Lobby/CharacterCustomization.cs [hunk 1]
```diff
@@ -1511,6 +1475,120 @@ private void RefreshRace()
...
+			if (raceSkinColors.Count != 0)
+			{
+				return "#" + ColorUtility.ToHtmlStringRGB(raceSkinColors[UnityEngine.Random.Range(0, raceSkinColors.Count - 1)]);
+			}
+			return "#" + ColorUtility.ToHtmlStringRGBA(new Color(UnityEngine.Random.Range(0.1f, 1f),
+					UnityEngine.Random.Range(0.1f, 1f),
+					UnityEngine.Random.Range(0.1f, 1f), 1f));
+		}
+
+		public static string RandomizeCharacterName(CharacterSettings data, bool isNotPlayerDebug = true)
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/UI/Systems/Lobby/CharacterCustomization.cs]: I think it might be good idea to move the stuff within character settings,
so you can just do character settings. Randomise, 
You wouldn't be able do this for the body part customisations though

**Review by Bod9001 — DISMISSED** [review]

File: UnityProject/Assets/Scripts/UI/Systems/Lobby/CharacterCustomization.cs (hunk 1 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/UI/Systems/Lobby/CharacterCustomization.cs]: Done 👍

**Review by Bod9001 — DISMISSED** [review]

**Comment by MaxIsJoe** [comment]
this should be done, review pls

File: UnityProject/Assets/Scripts/HealthV2/Living/BodyParts/BodyPart.cs [hunk 2]
```diff
@@ -324,7 +324,23 @@ public void TryRemoveFromBody(bool beingGibbed = false)
...
+				|| bodyPart.DeathOnRemoval)
+				{
+					DynamicItemStorage storge = HealthMaster.playerScript.DynamicItemStorage;
+					foreach (ItemSlot itemSlot in storge.GetNamedItemSlots(NamedSlot.leftHand))
+					{
+						Inventory.ServerDrop(itemSlot);
+					}
+					foreach (var itemSlot in storge.GetNamedItemSlots(NamedSlot.rightHand))
+					{
+						Inventory.ServerDrop(itemSlot);
```
Comment (NoooneyDude) [inline UnityProject/Assets/Scripts/HealthV2/Living/BodyParts/BodyPart.cs]: Cool, but what about item slots on other limbs, like feet? Or are only hands affected?

Is there a way to get item slots from the bodypart? That'd be nice.

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/HealthV2/Living/BodyParts/BodyPart.cs]: why would you drop items from your feet when you die?
Do feet now hold items as well?

Comment (NoooneyDude) [reply UnityProject/Assets/Scripts/HealthV2/Living/BodyParts/BodyPart.cs]: The issue mentioned headwear disappearing on decapitation, so I assume it'd be the same case for all limbs that have associated slots.

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/HealthV2/Living/BodyParts/BodyPart.cs]: hm, I'll re-check this and see what I can do.

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/HealthV2/Living/BodyParts/BodyPart.cs]: Done 👍

**Review by Bod9001 — APPROVED** [review]

**Comment by MaxIsJoe** [comment]
merge_my_pr

**Review by NoooneyDude — APPROVED** [review]
