### PR TITLE
Networks emote commands

### LINKED ISSUE #9617: [BUG] Emote window doesn't work on headless servers when connected as client.
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

2/16/2023 Staging

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

Emotes don't get triggered on client when connected to a headless server.

### What should have happened instead?

Emotes should trigger when their corresponding button is pressed.

### Steps to reproduce the issue

1. Open Emote Window while connected to staging.
2. Use emote
3. don't trigger

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MaxIsJoe**
fixes #9617

CL: [Improvement] Changed the default emote window button to `backslash` to avoid the backlash of all the angry gamers that I've upset with my preference and are now planning on using the gulitone I created against me.
CL: [Fix] Emote window works now on headless servers.

### CODE REVIEW

File: UnityProject/Assets/Scripts/Core/Input System/KeybindManager.cs [hunk 1]
```diff
@@ -443,7 +443,7 @@ public DualKeyCombo Clone()
 
 		{ KeyAction.RadialScrollForward,	new DualKeyCombo(new KeyCombo(KeyCode.E, KeyCode.LeftShift), null)},
 		{ KeyAction.RadialScrollBackward,	new DualKeyCombo(new KeyCombo(KeyCode.Q, KeyCode.LeftShift), null)},
-		{ KeyAction.EmoteWindowUI,	new DualKeyCombo(new KeyCombo(KeyCode.T, KeyCode.LeftShift), null)},
+		{ KeyAction.EmoteWindowUI,	new DualKeyCombo(new KeyCombo(KeyCode.Backslash), null)},
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Core/Input System/KeybindManager.cs:446]: mind this change won't affect anyone who opened the game already, because their key is already set.

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Core/Input System/KeybindManager.cs:446]: > Changed the default emote window button

I'm aware.

File: UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs [hunk 2]
```diff
@@ -990,4 +983,10 @@ public void CmdServerReplaceItemInInventory(GameObject gameObjectSent, uint id,
 			Inventory.ServerTransfer(gameObjectSent.PickupableOrNull().ItemSlot, slot, ReplacementStrategy.DropOther);
 		}
 	}
+
+	[Command]
+	public void CmdDoEmote(GameObject player, string emoteName)
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs]: get the GameObject player,  
 As this.game object because a hacked client could send any player  to do emote

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs]: done

**Review by Bod9001 — APPROVED** [review]
