### PR TITLE
Fixed having no hub config stopping rcon config from running.

### LINKED ISSUE #2884: RconManager requires hub credentials.
## Description
RconManager only works if hub credentials are supplied.

### Detailed Bug Report
It loads the `config.json` and then calls `SendServerStatus`, however if `HubUser` or `HubPass` is empty it will set `config` to `null`.
https://github.com/unitystation/unitystation/blob/f6b6803b3963a2a3fe44bb9aac442c3b700cf030/UnityProject/Assets/Scripts/Database/ServerData.ServerStatus.cs#L74-L79
This means that when `RconManager` tries to get `ServerConfig` it just gets `null` so it destroys itself.
https://github.com/unitystation/unitystation/blob/f6b6803b3963a2a3fe44bb9aac442c3b700cf030/UnityProject/Assets/Scripts/RCON/RconManager.cs#L60-L64

### PR DESCRIPTION
**Pull request by Charlese2**
# Pull Request Template

### Purpose
Fixes #2884 
If you didn't have hub credentials set in the config but you had rcon set up you it would just skip the code to look at the rcon config.

### Notes:
Without HubUser set in the config, the hub communication loop code will not run.

### Please make sure you have followed the self checks below before submitting a PR:

- Code is sufficiently commented
- Code is indented with tabs and not spaces
- The PR does not include any unnecessary .meta, .prefab or <b>.unity (scene) changes</b>
- The PR does not bring up any new compile errors
- The PR has been tested in editor
- Any new files are named using PascalCase (to avoid issues on case sensitive file systems)
- Any new / changed components follow the [Component Development Checklist](https://github.com/unitystation/unitystation/wiki/Component-Development-Checklist)
- Any new objects / items follow the [Creating Items and Objects Guide](https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants) (especially concerning the use of prefab variants)
- The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)
- The PR has been tested with round restarts.
- The PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)

### CODE REVIEW

File: UnityProject/Assets/Scripts/Database/ServerData.cs [hunk 1]
```diff
@@ -96,8 +96,10 @@ void OnDisable()
 		void Update()
 		{
 			if (config != null)
-			{
-				MonitorServerStatus();
+				if (!string.IsNullOrEmpty(config.HubUser))
```
Comment (RedlineTriad) [inline UnityProject/Assets/Scripts/Database/ServerData.cs]: In order to replicate previous behavior, it should probably check the same things.
```suggestion
				if (!string.IsNullOrEmpty(config.HubUser) && !string.IsNullOrEmpty(config.HubPass))
```

Comment (Charlese2) [reply UnityProject/Assets/Scripts/Database/ServerData.cs]: I think I messed up the formatting.

Comment (RedlineTriad) [reply UnityProject/Assets/Scripts/Database/ServerData.cs]: It looks like it does not have enough curly braces.

**Comment by DooblyNoobly** [comment]
@RedlineTriad you are still reviewing this?

**Comment by RedlineTriad** [comment]
@DooblyNoobly no.

**Comment by Charlese2** [comment]
I'm considering changing to this. If only one of the config variables is missing it would still be caught by the check with logging. (In `ServerData.ServerStatus.cs`) The logging would repeat every 10 seconds instead of every frame.
```C#		
void Update()
{
	//If there is a config loaded, check whether HubUser and/or HubPass are set.
	if (!string.IsNullOrEmpty(config?.HubUser) || !string.IsNullOrEmpty(config?.HubPass))
	{
		MonitorServerStatus();
	}
}
```
