### PR TITLE
Defib Paddles will retract back into their storage when dropped or thrown

### LINKED ISSUE #9591: [BUG] Defibrillator paddles can be dropped
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

b1ee3d3b9700771e10143ed7de1679ecdc2b9b38

### I was

Client

### OS

Linux

### What happened?

I can drop the defibrillator paddles and walk away from them with the defibrillator still in my hand.

https://user-images.githubusercontent.com/5573038/216858304-541f0f01-2559-43ef-8146-84b4a08943d0.mp4

### What should have happened instead?

These paddles are attached via wires to the defibrillator so you shouldn't be able to drop and walk away from them.

### Steps to reproduce the issue

1. Pick up a defibrillator.
2. Remove the paddles.
3. Drop them on a table and walk away.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MaxIsJoe**
fix #9591 

CL: [Improvement] Defib Paddles will retract back into their storage when dropped or thrown.

### CODE REVIEW

File: UnityProject/Assets/Scripts/Items/Medical/DefibrillatorPaddles.cs [hunk 1]
```diff
@@ -1,128 +1,157 @@
...
+				_ = SoundManager.PlayNetworkedAtPosAsync(soundReady, gameObject.AssumedWorldPosServer());
+				return;
+			}
+
+			Chat.AddExamineMsg(interaction.Performer,
+				$"<color=green>The {gameObject.ExpensiveName()} is charged and ready to be used.</color>");
 		}
-		if (isReady == false)
+
+		public void OnDropOrThrow(GameObject droppedObject)
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/Items/Medical/DefibrillatorPaddles.cs]: ok,  there's a few byond items that have a funny behaviour defibrillator  paddles and cyborg items I think it might be worth making a standard component to Simplify it?

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Items/Medical/DefibrillatorPaddles.cs]: huh?

**Comment by MaxIsJoe** [comment]
Done

**Comment by MaxIsJoe** [comment]
Done

**Review by Bod9001 — APPROVED** [review]
