### PR TITLE
Fixes gib getting interrupted by NRE

### LINKED ISSUE #8964: Bumping into an unsecured supermatter doesnt kill you
Bumping into an unsecured supermatter doesnt kill you.

Bumping into a secured one does kill you, seems like theres an issue with IBumpable

1. Spawn supermatter
2. Walk into it
3. You won't die

### PR DESCRIPTION
**Pull request by MaxIsJoe**
## Changelog:

CL: [Fix] - Fixed issue that caused gib logic to get interrupted by an NRE.

### CODE REVIEW

File: UnityProject/Assets/Scripts/Systems/Inventory/Inventory.cs [hunk 1]
```diff
@@ -130,12 +131,12 @@ public static bool ServerDrop(ItemSlot fromSlot, Vector2? worldTargetVector = nu
 	/// <returns>true if successful</returns>
 	public static void ServerDropAll(DynamicItemStorage playerStorage, Vector2? worldTargetVector = null)
 	{
-		var playerItems = playerStorage.GetItemSlots();
+		var playerItems = playerStorage.GetItemSlots().ToList();
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Systems/Inventory/Inventory.cs:134]: what type does ``GetItemSlots`` return that you need to cast to list?

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Systems/Inventory/Inventory.cs:134]: IEnumerable

Comment (corp-0) [reply UnityProject/Assets/Scripts/Systems/Inventory/Inventory.cs:134]: by recent discussion on github, I think ``Count`` works on that

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Systems/Inventory/Inventory.cs:134]: wdym?

Comment (corp-0) [reply UnityProject/Assets/Scripts/Systems/Inventory/Inventory.cs:134]: meaning you might not need to cast to list

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Systems/Inventory/Inventory.cs:134]: you can't `EnumerableList[index]`

File: UnityProject/Assets/Scripts/Systems/Inventory/Inventory.cs [hunk 2]
```diff
@@ -130,12 +131,12 @@ public static bool ServerDrop(ItemSlot fromSlot, Vector2? worldTargetVector = nu
...
 
-		foreach (var playerItemSlot in playerItems)
```
Comment (Alainx277) [inline UnityProject/Assets/Scripts/Systems/Inventory/Inventory.cs:135]: Why not leave everything as is and change this to:
```csharp
foreach (var playerItemSlot in playerItems.NotNull())
```

Comment (Alainx277) [reply UnityProject/Assets/Scripts/Systems/Inventory/Inventory.cs:135]: Read your comment on discord, you still need to use the `ToList` because it's modifying the collection.

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Systems/Inventory/Inventory.cs:135]: `NotNull()` doesn't work. NRE still appears

Comment (Alainx277) [reply UnityProject/Assets/Scripts/Systems/Inventory/Inventory.cs:135]: That's very strange. Can you paste the error here?

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Systems/Inventory/Inventory.cs:135]: Disconnecting connId=0 to prevent exploits from an Exception in MessageHandler: InvalidOperationException Collection was modified; enumeration operation may not execute.
  at System.Collections.Generic.List`1+Enumerator[T].MoveNextRare () [0x00013] in <6073cf49ed704e958b8a66d540dea948>:0 
  at System.Collections.Generic.List`1+Enumerator[T].MoveNext () [0x0004a] in <6073cf49ed704e958b8a66d540dea948>:0 
  at System.Linq.Enumerable+WhereListIterator`1[TSource].MoveNext () [0x0004e] in <1e18c5a6594041c9844bfd0b6618ee4a>:0 
  at Inventory.ServerDropAll (DynamicItemStorage playerStorage, System.Nullable`1[T] worldTargetVector) [0x00030] in D:\Projects\UnityProjects\OS\unitystation\UnityProject\Assets\Scripts\Systems\Inventory\Inventory.cs:136 
  at HealthV2.PlayerHealthV2.OnGib () [0x00000] in D:\Projects\UnityProjects\OS\unitystation\UnityProject\Assets\Scripts\HealthV2\Living\PlayerHealthV2.cs:78 
  at AdminCommands.AdminCommandsManager.UserCode_CmdSmitePlayer__String__NetworkConnectionToClient (System.String userToSmite, Mirror.NetworkConnectionToClient sender) [0x000a9] in D:\Projects\UnityProjects\OS\unitystation\UnityProject\Assets\Scripts\Managers\AdminCommandsManager.cs:366 
  at AdminCommands.AdminCommandsManager.InvokeUserCode_CmdSmitePlayer__String__NetworkConnectionToClient (Mirror.NetworkBehaviour obj, Mirror.NetworkReader reader, Mirror.NetworkConnectionToClient senderConnection) [0x00022] in <7facd9da5e034efe9d930e987429d6c2>:0 
  at Mirror.RemoteCalls.RemoteProcedureCalls.Invoke (System.Int32 functionHash, Mirror.RemoteCalls.RemoteCallType remoteCallType, Mirror.NetworkReader reader, Mirror.NetworkBehaviour component, Mirror.NetworkConnectionToClient senderConnection) [0x00025] in D:\Projects\UnityProjects\OS\unitystation\UnityProject\Library\PackageCache\org.unitystation.spacemirror@ecddb4bbbd\Runtime\RemoteCalls.cs:122 
  at Mirror.NetworkIdentity.HandleRemoteCall (System.Int32 componentIndex, System.Int32 functionHash, Mirror.RemoteCalls.RemoteCallType remoteCallType, Mirror.NetworkReader reader, Mirror.NetworkConnectionToClient senderConnection) [0x00069] in D:\Projects\UnityProjects\OS\unitystation\UnityProject\Library\PackageCache\org.unitystation.spacemirror@ecddb4bbbd\Runtime\NetworkIdentity.cs:1162 
  at Mirror.NetworkServer.OnCommandMessage (Mirror.NetworkConnectionToClient conn, Mirror.CommandMessage msg, System.Int32 channelId) [0x00085] in D:\Projects\UnityProjects\OS\unitystation\UnityProject\Library\PackageCache\org.unitystation.spacemirror@ecddb4bbbd\Runtime\NetworkServer.cs:982 
  at (wrapper delegate-invoke) System.Action`3[Mirror.NetworkConnectionToClient,Mirror.CommandMessage,System.Int32].invoke_void_T1_T2_T3(Mirror.NetworkConnectionToClient,Mirror.CommandMessage,int)
  at Mirror.MessagePacking+<>c__DisplayClass6_0`2[T,C].<WrapHandler>b__0 (Mirror.NetworkConnection conn, Mirror.NetworkReader reader, System.Int32 channelId) [0x0007d] in D:\Projects\UnityProjects\OS\unitystation\UnityProject\Library\PackageCache\org.unitystation.spacemirror@ecddb4bbbd\Runtime\MessagePacking.cs:127 
UnityEngine.Debug:LogError (object)
Mirror.MessagePacking/<>c__DisplayClass6_0`2<Mirror.CommandMessage, Mirror.NetworkConnectionToClient>:<WrapHandler>b__0 (Mirror.NetworkConnection,Mirror.NetworkReader,int) (at Library/PackageCache/org.unitystation.spacemirror@ecddb4bbbd/Runtime/MessagePacking.cs:131)
Mirror.NetworkServer:UnpackAndInvoke (Mirror.NetworkConnectionToClient,Mirror.NetworkReader,int) (at Library/PackageCache/org.unitystation.spacemirror@ecddb4bbbd/Runtime/NetworkServer.cs:475)
Mirror.NetworkServer:OnTransportData (int,System.ArraySegment`1<byte>,int) (at Library/PackageCache/org.unitystation.spacemirror@ecddb4bbbd/Runtime/NetworkServer.cs:538)
Mirror.LocalConnectionToServer:Send (System.ArraySegment`1<byte>,int) (at Library/PackageCache/org.unitystation.spacemirror@ecddb4bbbd/Runtime/LocalConnectionToServer.cs:45)
Mirror.NetworkConnection:Send<Mirror.CommandMessage> (Mirror.CommandMessage,int) (at Library/PackageCache/org.unitystation.spacemirror@ecddb4bbbd/Runtime/NetworkConnection.cs:137)
Mirror.NetworkBehaviour:SendCommandInternal (string,Mirror.NetworkWriter,int,bool) (at Library/PackageCache/org.unitystation.spacemirror@ecddb4bbbd/Runtime/NetworkBehaviour.cs:263)
AdminCommands.AdminCommandsManager:CmdSmitePlayer (string,Mirror.NetworkConnectionToClient)
AdminTools.PlayerManagePage:SendSmitePlayerRequest () (at Assets/Scripts/UI/Systems/AdminTools/PlayerManagePage.cs:105)
AdminTools.AreYouSurePage:OnProceed () (at Assets/Scripts/UI/Systems/AdminTools/AreYouSurePage.cs:46)
UnityEngine.EventSystems.EventSystem:Update () (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/EventSystem.cs:501)

Comment (Alainx277) [reply UnityProject/Assets/Scripts/Systems/Inventory/Inventory.cs:135]: That's not an NRE and has nothing to do with null objects.
Did you leave in the `ToList()`? That's what prevents the iteration error.

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Systems/Inventory/Inventory.cs:135]: Done.

**Comment by MaxIsJoe** [comment]
Merge pls

**Review by Alainx277 — APPROVED** [review]
