### PR TITLE
Adds empty hand interactions and makes various changes/fixes

### LINKED ISSUE #1845: Unable to attack with bare hands B: 40
# Description
You can't attack other players/mobs/windows with your bare hands while in the harm intent.

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Set intent to harm
2. Attack Ian/runtime/windows/another player
3. Notice nothing happens

### LINKED ISSUE #1941: CPR for unconscious players
# Description
At the moment there's no way to recover players from deep crit, oxygen loss keeps rising and they die eventually.
Need to add ability to CPR crit players to make them breathe again, preferably with a progress bar

### PR DESCRIPTION
**Pull request by Itsnotjames**
Fixes knifes and scalpels not working on animals/players.
Adds CPR.
Adds disarms.
Adds hugs.
Adds punches.
Adds the method InventoryManager.DropItemInSlot(). This drops the item in a specific slot (needed for disarm).
Changes PostToChatMessage.SendItemAttackMessage to SendAttackMessage. This makes it more generic so it can now be used for punches and other attacks in the future.

### Purpose
Fixes #1845
Fixes #1941

### Open Questions and Pre-Merge TODOs

- [X]  This fix is tested on the same branch it is PR'ed to.
- [X]  I correctly commented my code
- [X]  My code is indented with tabs and not spaces
- [X]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [X]  This PR does not bring up any new compile errors
- [X]  This PR has been tested in editor
- [X]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### CODE REVIEW

**Comment by Itsnotjames** [comment]
Not sure how to resolve a prefab merge conflict

**Comment by Itsnotjames** [comment]
It adds three scripts to the player prefab, CPRable, Disarmable, and Hugable.

**Comment by DooblyNoobly** [comment]
Resolved conflict, all ready for a review

File: UnityProject/Assets/Scripts/Weapons/WeaponNetworkActions.cs [hunk 1]
```diff
@@ -158,12 +160,79 @@ public void CmdUnloadWeapon(GameObject gunObject)
...
+		{
+			// The punch hit.
+			victimHealth.ApplyDamage(gameObject, (int) fistDamage, DamageType.Brute, damageZone);
+			if (fistDamage > 0)
+			{
+				PostToChatMessage.SendAttackMessage(gameObject, victim, (int) fistDamage, damageZone);
+			}
+
+			// Make a random punch hit sound.
+			switch (rng.Next(1, 4))
```
Comment (fomalsd) [inline UnityProject/Assets/Scripts/Weapons/WeaponNetworkActions.cs]:
```suggestion
SoundManager.PlayNetworkedAtPos("Punch"+rng.Next(1, 4), victimRegisterTile.WorldPosition);
```
;)

File: UnityProject/Assets/Scripts/Weapons/WeaponNetworkActions.cs [hunk 2]
```diff
@@ -137,6 +138,7 @@ public void CmdUnloadWeapon(GameObject gunObject)
 				playerMove.allowInput = false;
 				attackTarget.Harvest();
 				SoundManager.PlayNetworkedAtPos( "BladeSlice", transform.position );
+				SoundManager.PlayNetworkedAtPos("BladeSlice", transform.position);
```
Comment (fomalsd) [inline UnityProject/Assets/Scripts/Weapons/WeaponNetworkActions.cs]: why do it twice?

Comment (Itsnotjames) [reply UnityProject/Assets/Scripts/Weapons/WeaponNetworkActions.cs]: Thats a mistake

File: UnityProject/Assets/Scripts/Weapons/WeaponNetworkActions.cs [hunk 3]
```diff
@@ -158,12 +160,79 @@ public void CmdUnloadWeapon(GameObject gunObject)
...
+		}
+		else
+		{
+			// The punch missed.
+			string victimName = victim.Player()?.Name;
+			SoundManager.PlayNetworkedAtPos("PunchMiss", transform.position);
+			ChatRelay.Instance.AddToChatLogServer(new ChatEvent
+			{
+				channels = ChatChannel.Local,
+				message = $"{attackerName} has attempted to punch {victimName}!"
```
Comment (fomalsd) [inline UnityProject/Assets/Scripts/Weapons/WeaponNetworkActions.cs]: apparently attackerName is empty
(and is it needed at all?)
img

File: UnityProject/Assets/Scripts/Weapons/WeaponNetworkActions.cs [hunk 4]
```diff
@@ -204,7 +204,7 @@ public void CmdUnloadWeapon(GameObject gunObject)
 			}
 
 			// Make a random punch hit sound.
-			switch (rng.Next(1, 4))
+SoundManager.PlayNetworkedAtPos("Punch"+rng.Next(1, 4), victimRegisterTile.WorldPosition);
```
Comment (fomalsd) [inline UnityProject/Assets/Scripts/Weapons/WeaponNetworkActions.cs]: nonono, that wouldn't compile unless you remove switch case below

File: UnityProject/Assets/Scripts/Weapons/Meleeable.cs [hunk 5]
```diff
@@ -24,18 +24,34 @@ private void Start()
...
+			    handItem.itemType == ItemType.Shoes ||
+			    handItem.itemType == ItemType.Suit ||
+			    handItem.itemType == ItemType.Uniform)
+			{
 				return false;
 			}
 
 			//special case
-			//We don't melee if we are wielding a gun with ammo and clicking ourselves (we will instead shoot ourselves)
+			//We don't melee if wse are wielding a gun with ammo and clicking ourselves (we will instead shoot ourselves)
```
Comment (fomalsd) [inline UnityProject/Assets/Scripts/Weapons/Meleeable.cs]: hehe, introducing typos

File: UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs [hunk 6]
```diff
@@ -869,4 +871,140 @@ public void CmdRequestPaperEdit(GameObject paper, string newMsg)
...
+	{
+		// Stop the in progress CPR.
+		doingCPR = false;
+	}
+
+	/// <summary>
+	/// Performs a disarm attempt from one player to another.
+	/// </summary>
+	[Command]
+	public void CmdRequestDisarm(GameObject disarmer, GameObject playerToDisarm)
```
Comment (fomalsd) [inline UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs:960]: apparently you can disarm other people while being dead, lol
also for some reason disarmed players keep their inhand sprites (at least when tested in multiplayer) so I'm not sure if `InventoryManager.DropItemInSlot()` is correct

File: UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs [hunk 7]
```diff
@@ -869,4 +871,140 @@ public void CmdRequestPaperEdit(GameObject paper, string newMsg)
...
+			message = $"{rescuer.Player()?.Name} is trying to perform CPR on {cardiacArrestPlayer.Player()?.Name}.",
+			position = cardiacArrestPlayerRegister.WorldPosition.To2Int()
+		});
+	}
+
+	[Server]
+	private void DoCPR(GameObject rescuer, GameObject CardiacArrestPlayer)
+	{
+		var CardiacArrestPlayerRegister = CardiacArrestPlayer.GetComponent<RegisterPlayer>();
+		CardiacArrestPlayer.GetComponent<PlayerHealth>().bloodSystem.oxygenDamage -= 7f;
```
Comment (fomalsd) [inline UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs:939]: Idk what are classic values for CPR, but it's really hard to revive a person if you're the only one performing CPR
if it's supposed to be this way, it's fine, otherwise maybe double this value?

**Review by fomalsd — CHANGES_REQUESTED** [review]
Really good stuff! just needs a couple small bugs fixed, and stricter validation in some places (so you couldn't rob others as a dead person etc)

**Comment by DooblyNoobly** [comment]
Please be aware there are conflicts now on this PR. they are all script ones so I will resolve them when the PR is ready to be merged

File: UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs (hunk 7 above)
Comment (Itsnotjames) [reply UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs:939]: It is a bit low, I don't think CPR is very good.
In tg's /mob/living/carbon/human/proc/do_cpr(mob/living/carbon/C) it heals 7 oxy damage until oxy damage is 0.
Here is a picture with the healing code highlighted:
Nz1lupd
Which goes to:
zxqNqEk

Comment (Aranclanos) [reply UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs:939]: remember that you can spam cpr on a person and only get the mob clicking cd, you can do several cpr at the same time

File: UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs (hunk 6 above)
Comment (Itsnotjames) [reply UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs:960]: Ah turns out the function that drops an item in a specific slot is PlayerNetworkActions.DropItem(slot).
Fixed this in next commit.

File: UnityProject/Assets/Scripts/Weapons/WeaponNetworkActions.cs (hunk 3 above)
Comment (Itsnotjames) [reply UnityProject/Assets/Scripts/Weapons/WeaponNetworkActions.cs]: 0mqzssR
Fixed in next commit

File: UnityProject/Assets/Scripts/Weapons/Meleeable.cs (hunk 5 above)
Comment (Itsnotjames) [reply UnityProject/Assets/Scripts/Weapons/Meleeable.cs]: Fixed

**Review by fomalsd — APPROVED** [review]
Very nice!

**Comment by fomalsd** [comment]
it's good to merge
