### PR TITLE
 Fix for  #8789

### LINKED ISSUE #8789: Sliding glass doors need to be manually opened from their back side
### Environment
- Game Version: 22060401
- OS Version: win10

### Detailed description of bug

Walking through a sliding glass door from its front causes it to open automatically as intended. However, walking into it from the other side does not open it automatically, having you open it manually by clicking on it

### Steps to reproduce

1. Go behind a sliding glass door
2. Walk into it
3. Go to medical to patch up your head bruise damage

### PR DESCRIPTION
**Pull request by coolcat1711**
### Purpose
Fixes #8789

### Notes:
Adds a second layer of bump checking for tiles that have directional occlusion. This allows you to trigger bumps on non-creature objects on the same tile.

### Changelog:

CL: [Fix] Allows creatures to trigger bump actions for directional objects in the same tile (Windoors).

### CODE REVIEW

**Comment by corp-0** [comment]
looks good to me but I will wait on Bod's review since he designed the physics and collisions code. @Bod9001

File: UnityProject/Assets/Scripts/Tilemaps/Behaviours/Layers/ObjectLayer.cs [hunk 1]
```diff
@@ -138,6 +138,23 @@ public float GetObjectResistanceAt(Vector3Int position, bool isServer)
 				}
 			}
 
+			//If you can't bump anything on an adjacent tile, you may be blocked by a bumpable object on your current tile (probably a windoor)
+			if (!Bumps.Any())
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/Tilemaps/Behaviours/Layers/ObjectLayer.cs]: Bumps.Any() == false

File: UnityProject/Assets/Scripts/Tilemaps/Behaviours/Layers/ObjectLayer.cs [hunk 2]
```diff
@@ -138,6 +138,23 @@ public float GetObjectResistanceAt(Vector3Int position, bool isServer)
...
+			{
+				foreach (var objectOnTile in Matrix.Get<UniversalObjectPhysics>(originalFrom, CustomNetworkManager.IsServer))
+				{
+					if (objectOnTile.Intangible) continue;
+					//Prevents living creatures from bumping themselves (or other living creatures) if on the same tile.
+					if (objectOnTile.GetComponent<HealthV2.HealthStateController>() != null) continue;
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/Tilemaps/Behaviours/Layers/ObjectLayer.cs:148]: Might be better to use context instead

**Comment by Bod9001** [comment]
otherwise looks good

File: UnityProject/Assets/Scripts/Tilemaps/Behaviours/Layers/ObjectLayer.cs (hunk 2 above)
Comment (coolcat1711) [reply UnityProject/Assets/Scripts/Tilemaps/Behaviours/Layers/ObjectLayer.cs:148]: Which piece would context replace? objectOnTile and context are both "UniversalObjectPhysics" classes and I think context only accounts for the current player/creature moving instead of any additional creatures occupying a tile (which would want to ignore being bumped if they're on the same tile)

Comment (Bod9001) [reply UnityProject/Assets/Scripts/Tilemaps/Behaviours/Layers/ObjectLayer.cs:148]: ok, fair enough

**Review by Bod9001 — APPROVED** [review]
