### PR TITLE
Fixes Rejoining in locker bug and snaps the camera to the locker

### LINKED ISSUE #1765: Leaving and rejoining the game while in a locker places you in space B: 20
# Description

Join as client, get into a locker, then log out.

When rejoining, you show up out in the middle of space (HiddenPos) until someone pulls you out of the locker.

Expected behavior is that your camera would focus on the locker you were in when you logged out.

A bounty of 20usd will be awarded to the contributor on a successful merge of a solution to this bug.

### PR DESCRIPTION
**Pull request by Itsnotjames**
Fixes bug where the camera is at 0,0 when rejoining in a locker, and snaps the camera to the locker with 0 dampening, then goes to the normal 2f dampening when the camera hits the locker.

### Purpose
#Fixes #1765 

### Open Questions and Pre-Merge TODOs

- [X]  This fix is tested on the same branch it is PR'ed to.
- [X]  I correctly commented my code
- [X]  My code is indented with tabs and not spaces
- [X]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [X]  This PR does not bring up any new compile errors
- [X]  This PR has been tested in editor
- [X]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### CODE REVIEW

File: UnityProject/Assets/Scripts/Managers/NetworkManagement/SpawnHandler.cs [hunk 1]
```diff
@@ -58,6 +58,13 @@ public static void TransferPlayer(NetworkConnection conn, short playerController
 		{
 			playerScript.PlayerSync.NotifyPlayers(true);
 		}
+
+		var playerObjectBehavior = newBody.GetComponent<ObjectBehaviour>();
+		if (playerObjectBehavior.parentContainer)
+		{
+			ClosetHandlerMessage.Send(newBody, playerObjectBehavior.parentContainer.gameObject);
```
Comment (Jibbajabbafic) [inline UnityProject/Assets/Scripts/Managers/NetworkManagement/SpawnHandler.cs:67]: I think some comments explaining why this is being done would be very helpful to anyone looking at this in the future.

File: UnityProject/Assets/Scripts/Closets/ClosetPlayerHandler.cs [hunk 2]
```diff
@@ -38,6 +40,13 @@ public void Init(ClosetControl closetCtrl)
 		}
 	}
 
+	IEnumerator WaitForCameraToReachCloset()
+	{
+		yield return new WaitUntil(() =>
```
Comment (Jibbajabbafic) [inline UnityProject/Assets/Scripts/Closets/ClosetPlayerHandler.cs:51]: A little /// comment explaining why this function is needed would be great

**Review by Jibbajabbafic — CHANGES_REQUESTED** [review]
The camera's fixed but when you rejoin there's a brief moment where the character isn't in the locker. 
Would you be able to fix that somehow? If not we'll make a separate issue and fix it another time.

I think it would be good to include a couple comments too to explain the fix so people know why it's there in future.

Other than that it's good, thanks!

**Comment by Jibbajabbafic** [comment]
Awesome thanks!

**Review by Jibbajabbafic — APPROVED** [review]
