### PR TITLE
Block Spectator Revive

### LINKED ISSUE #6592: Revive Button Disconnect
If you click the revive button as a spectator it force disconnects you and you can not join the server again.

Serverside error when it happens:

> Exception in MessageHandler: NullReferenceException Object reference not set to an instance of an object
  at PlayerSpawn.ServerSpawnInternal (Mirror.NetworkConnection connection, Occupation occupation, CharacterSettings characterSettings, Mind existingMind, System.Nullable`1[T] spawnPos, System.Boolean spawnItems, System.Boolean willDestroyOldBody, System.Boolean showBanner) [0x0000c] in /root/UnityProject/Assets/Scripts/Core/Lifecycle/PlayerSpawn.cs:132 
  at PlayerSpawn.ServerRespawnPlayer (Mind forMind) [0x00032] in /root/UnityProject/Assets/Scripts/Core/Lifecycle/PlayerSpawn.cs:77 
  at PlayerNetworkActions.ServerRespawnPlayer (System.String occupation) [0x00066] in /root/UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs:563 
  at PlayerNetworkActions.UserCode_CmdRespawnPlayer (System.String adminID, System.String adminToken) [0x0001f] in /root/UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs:538 
  at PlayerNetworkActions.InvokeUserCode_CmdRespawnPlayer (Mirror.NetworkBehaviour obj, Mirror.NetworkReader reader, Mirror.NetworkConnectionToClient senderConnection) [0x00028] in <6845e1599cf6454e8095c69ec28b42c1>:0 
  at Mirror.RemoteCalls.RemoteCallHelper.InvokeHandlerDelegate (System.Int32 cmdHash, Mirror.MirrorInvokeType invokeType, Mirror.NetworkReader reader, Mirror.NetworkBehaviour invokingType, Mirror.NetworkConnectionToClient senderConnection) [0x00019] in /root/UnityProject/Assets/Mirror/Runtime/RemoteCallHelper.cs:148 
  at Mirror.NetworkIdentity.HandleRemoteCall (System.Int32 componentIndex, System.Int32 functionHash, Mirror.MirrorInvokeType invokeType, Mirror.NetworkReader reader, Mirror.NetworkConnectionToClient senderConnection) [0x00069] in /root/UnityProject/Assets/Mirror/Runtime/NetworkIdentity.cs:1111 
  at Mirror.NetworkServer.OnCommandMessage (Mirror.NetworkConnection conn, Mirror.CommandMessage msg) [0x00082] in /root/UnityProject/Assets/Mirror/Runtime/NetworkServer.cs:1058

### PR DESCRIPTION
**Pull request by ThatDan123**
Fixes #6592

-Also send admin check fail to the webhook

-Fix pivot sync

-Fix gasp message

-Mirror fills the `NetworkConnectionToClient sender = null` parameter on commands so you dont need to fill them manually

### CODE REVIEW

**Comment by corp-0** [comment]
I feel like we should just don't allow them to revive

**Comment by ThatDan123** [comment]
yeah thats probably better

File: UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs [hunk 1]
```diff
@@ -183,7 +183,7 @@ private bool BreatheIn(GasMix breathGasMix, ReagentMix blood, float efficiency)
 			RelatedPart.HealthMaster.HealthStateController.SetSuffocating(true);
 			if (Random.value < 0.2)
 			{
-				Chat.AddActionMsgToChat(gameObject, "You gasp for breath", $"{RelatedPart.HealthMaster.gameObject.ExpensiveName()} gasps");
+				Chat.AddActionMsgToChat(RelatedPart.HealthMaster.gameObject, "You gasp for breath", $"{RelatedPart.HealthMaster.gameObject.ExpensiveName()} gasps");
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs:186]: what is this change?

File: UnityProject/Assets/Scripts/Shuttles/MatrixMove.cs [hunk 2]
```diff
@@ -353,9 +353,9 @@ private void SyncInitialPosition(Vector3 oldPos, Vector3 initialPos)
 		networkedMatrix.MatrixSync.SyncInitialPosition(oldPos, initialPos);
 	}
 
-	public void SyncPivot(Vector3 oldPivot, Vector3 pivot)
+	private void SyncPivot(Vector3 oldPivot, Vector3 pivot)
 	{
-
+		networkedMatrix.MatrixSync.SyncPivot(oldPivot, pivot);
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Shuttles/MatrixMove.cs:358]: and this one?

Comment (ThatDan123) [reply UnityProject/Assets/Scripts/Shuttles/MatrixMove.cs:358]: forgot it from the matrix PR, and might have been causing scene issues

File: UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs (hunk 1 above)
Comment (ThatDan123) [reply UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs:186]: The player would always see "You gasp for breath", $"{RelatedPart.HealthMaster.gameObject.ExpensiveName()} gasps"instead of "You gasp for breath" as the lungs object isnt the right performer player gameobject
