### PR TITLE
Wrapped/Locker Fixes

### LINKED ISSUE #6937: Player Camera does not follow people who are in wrapped up lockers.
### Environment
- Game Version: Production 4119
- OS Version: Windows 10

### Detailed description of bug
If the locker you are in is wrapped up, then the camera will no longer follow you and will stick to the tile where the locker was when it got wrapped. If the locker you are in is unwrapped then the camera will return to your position. Additionally, if you try moving while in the wrapped up locker you will appear from its current position, exiting it, and the camera will return to you as well.

Below, camera is fixated on the tile right of the oxygen locker while the player is in the wrapped up locker that the captain is dragging.
image

### Steps to reproduce
1. Have someone put you in a locker and have wrap the locker up with wrapping paper.
2. Have the locker be moved, The camera will not move from the tile where the locker was wrapped up.
3. Move. You will appear from where the wrapped up locker currently is.

### LINKED ISSUE #7618: mobs placed inside lockers will teleport to 0,0 and still be active
### Environment
- Game Version: Staging 21101813
- OS Version: Arch Linux

### Detailed description of bug

when a mob is placed inside a locker this one is teleported to 0,0 and then roams free around space

https://user-images.githubusercontent.com/80334192/137837295-65ff4312-e702-4720-8c86-c13cd4d714be.mp4

tested with mokey and xeno queen

### Steps to reproduce

1. find mob
2. place it inside locker
3. tada! magic done

### LINKED ISSUE #7634: Trying to move in a wrapped-up locker teleports you to 0,0.
### Environment
- Game Version: Staging 21101813
- OS Version: Windows 10

### Detailed description of bug
Title. Trying to move while in a wrapped-up locker teleports you to 0,0. This usually kills the player since 0,0 is often at the vacuum of space.

### Steps to reproduce
1. Have someone put you in a locker and have them wrap the locker up with wrapping paper.
2. Try to move in the wrapped up locker.
3. Get sent to 0,0. Likely end up in space and start dying.

### LINKED ISSUE #7760: Recursive lockers
### Environment
- Game Version: Staging 21110423
- OS Version: Arch Linux

### Detailed description of bug

you can place lockers and crates inside other lockers

https://user-images.githubusercontent.com/80334192/140616185-ab2a87d1-2c6a-48d8-b760-8450dee2fbce.mp4

### Steps to reproduce

1. take locker
2. place locker inside locker
3. repeat step 2 until not possible anymore

### PR DESCRIPTION
**Pull request by pyrosshade**
### Purpose
Fixes #7760
Fixes #7618
Fixes #7634 
Fixes #6937

### Changelog:
CL: [Fix] Attempting movement in a wrapped Container no longer spaces you.
CL: [Fix] Chests and lockers and closets cannot contain each other anymore. The player will receive examine text about another container in the way.
CL: [Fix] Attempting escape in a wrapped locker will use the escape procedure of the container that's wrapped
CL: [Fix] Camera now follows player when in wrapped Containers

### CODE REVIEW

File: UnityProject/Assets/Scripts/Items/Cargo/Wrapping/WrappableObject.cs [hunk 1]
```diff
@@ -61,11 +63,14 @@ private void FinishWrapping(WrappingPaper paper)
...
 
-			result = Spawn.ServerPrefab(result, gameObject.AssumedWorldPosServer()).GameObject;
-			var wrap = result.GetComponent<WrappedObject>();
+			GameObject toSpawn;
+			toSpawn = Spawn.ServerPrefab(result, gameObject.AssumedWorldPosServer()).GameObject;
+			var wrap = toSpawn.GetComponent<WrappedObject>();
 			wrap.SetContent(gameObject);
-
+			GetComponent<ObjectContainer>().TransferObjectsTo(wrap);
+			GetComponent<PushPull>().parentContainer = wrap.GetComponent<PushPull>();
```
Comment (NoooneyDude) [inline UnityProject/Assets/Scripts/Items/Cargo/Wrapping/WrappableObject.cs:71]: These are pretty much the same component, could reduce these two to one component fetch, if you like.

Edit: actually, I see you've changed the base to inherit from ObjectContainer, so you could even make the `objectBehaviour` field protected and use that.

File: UnityProject/Assets/Scripts/Items/Cargo/Wrapping/WrappedBase.cs [hunk 2]
```diff
@@ -24,25 +26,23 @@ public abstract class WrappedBase: MonoBehaviour
...
 		{
-			content = toWrap.GetComponent<PushPull>();
+			StoreObject(toWrap);
 			var exportCost = toWrap.GetComponent<Attributes>().ExportCost;
 			UpdateExportCost(exportCost);
-			content.parentContainer = pushPull;
-			content.VisibleState = false;
+			toWrap.GetComponent<PushPull>().VisibleState = false;
+			toWrap.GetComponent<ObjectBehaviour>().parentContainer = GetComponent<ObjectBehaviour>();
+			Debug.Log(GetOrGenerateContent());
```
Comment (NoooneyDude) [inline UnityProject/Assets/Scripts/Items/Cargo/Wrapping/WrappedBase.cs]:
```suggestion
```

File: UnityProject/Assets/Scripts/Items/Cargo/Wrapping/WrappedBase.cs [hunk 3]
```diff
@@ -24,25 +26,23 @@ public abstract class WrappedBase: MonoBehaviour
...
 		public void SetContent(GameObject toWrap)
 		{
-			content = toWrap.GetComponent<PushPull>();
+			StoreObject(toWrap);
 			var exportCost = toWrap.GetComponent<Attributes>().ExportCost;
 			UpdateExportCost(exportCost);
-			content.parentContainer = pushPull;
-			content.VisibleState = false;
+			toWrap.GetComponent<PushPull>().VisibleState = false;
+			toWrap.GetComponent<ObjectBehaviour>().parentContainer = GetComponent<ObjectBehaviour>();
```
Comment (NoooneyDude) [inline UnityProject/Assets/Scripts/Items/Cargo/Wrapping/WrappedBase.cs]: I see you're using the two here too. We should really drop one of these at some point.

File: UnityProject/Assets/Scripts/Objects/ObjectContainer.cs [hunk 4]
```diff
@@ -258,5 +264,22 @@ private void ReparentStoredObjects(uint parentNetId)
...
+
+		/// <summary>
+		/// Checks for Other ObjectContainers in the vicinity of the tile this ObjectContainer is in.
+		/// </summary>
+		/// <returns>Returns true if at least one ObjectContainer exists on the same tile.</returns>
+		public bool IsAnotherContainerNear()
+		{
+			foreach (var entity in registerTile.Matrix.Get<ObjectBehaviour>(registerTile.LocalPositionServer, true))
+			{
+				if (entity.GetComponent<ObjectContainer>() && entity != GetComponent<ObjectBehaviour>())
```
Comment (NoooneyDude) [inline UnityProject/Assets/Scripts/Objects/ObjectContainer.cs]:
```suggestion
				if (entity.GetComponent<ObjectContainer>() && entity != objectBehaviour)
```

File: UnityProject/Assets/Scripts/Objects/Closets/ClosetControl.cs [hunk 5]
```diff
@@ -245,23 +245,33 @@ public void ReleaseObjects()
...
 				SetDoor(Door.Opened);
+				ifCompleted?.Invoke();
 				return;
 			}
 
+			GameObject sourceobjbehavior = gameObject;
+			RegisterObject sourceregisterobject = registerObject;
+			if (GetComponent<ObjectBehaviour>().parentContainer != null)
+			{
+				sourceobjbehavior = GetComponent<ObjectBehaviour>().parentContainer.gameObject;
```
Comment (NoooneyDude) [inline UnityProject/Assets/Scripts/Objects/Closets/ClosetControl.cs]: You can use the cached reference assigned to `pushPull`. We're pretty big on caching component references.
```suggestion
			if (pushPull.parentContainer != null)
			{
				sourceobjbehavior = pushPull.parentContainer.gameObject;
```

**Review by NoooneyDude — COMMENTED** [review]
Thank you!

File: UnityProject/Assets/Scripts/Items/Cargo/Wrapping/WrappedBase.cs (hunk 3 above)
Comment (pyrosshade) [reply UnityProject/Assets/Scripts/Items/Cargo/Wrapping/WrappedBase.cs]: Fair enough, replaced ObjectBehavior in this instance with PushPull

File: UnityProject/Assets/Scripts/Items/Cargo/Wrapping/WrappableObject.cs (hunk 1 above)
Comment (pyrosshade) [reply UnityProject/Assets/Scripts/Items/Cargo/Wrapping/WrappableObject.cs:71]: This is in context of Wrapp(ABLE) though, which does NOT derive from ObjectContainer, so making it protected in ObjectContainer would do nothing. Not sure if we want to make it public, but if we want i could do a getter?

Comment (NoooneyDude) [reply UnityProject/Assets/Scripts/Items/Cargo/Wrapping/WrappableObject.cs:71]: Sorry, I read ObjectContainer as ObjectBehaviour : /

File: UnityProject/Assets/Scripts/Items/Cargo/Wrapping/WrappedBase.cs [hunk 6]
```diff
@@ -24,25 +26,22 @@ public abstract class WrappedBase: MonoBehaviour
...
 
 		public void SetContent(GameObject toWrap)
 		{
-			content = toWrap.GetComponent<PushPull>();
+			StoreObject(toWrap);
 			var exportCost = toWrap.GetComponent<Attributes>().ExportCost;
 			UpdateExportCost(exportCost);
-			content.parentContainer = pushPull;
-			content.VisibleState = false;
+			toWrap.GetComponent<PushPull>().VisibleState = false;
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Items/Cargo/Wrapping/WrappedBase.cs]: I have an uneducated question, since this is now using ObjectContainer to handle *containing* objects inside another, why is it needed to manually move the content to hidden zone and assign the container as parent? Doesn't ObjectContnainer already do that?

Comment (pyrosshade) [reply UnityProject/Assets/Scripts/Items/Cargo/Wrapping/WrappedBase.cs]: You are correct, that's a good catch. This is something that escaped my cleanup/review. Just a paranoid holdover from poking and prodding.

**Review by Bod9001 — APPROVED** [review]

**Review by corp-0 — COMMENTED** [review]
Looks good to me, but I would like to know what Nooney thinks

**Review by NoooneyDude — APPROVED** [review]
