### PR TITLE
Door Improvements: Welding to fix doors, Door Sound Manager implementation, and various bugfixes

### LINKED ISSUE #6980: Forcing open powered airlocks with the jaws of life should play a different opening sound.
### Description
In /tg/, when powered airlocks are forced open with the jaws of life they play a different opening sound. The sound in question is "airlockforced.ogg" (found in tgstation's repo under "\sound\machines"). Similar to #6911, although powered airlocks that are forced open still show opening lights unlike what is described in that issue.

### PR DESCRIPTION
**Pull request by Bobtheapple**
### Purpose
Adds repairing doors using the welding tool.  Consolidates sound effect code from the various door modules into a new Door Sound Manager. Fixes a number of door related bugs.

### Notes:
I loaded into the game for the first time in a while and a door looked at me funny, this'll show it who's boss.

### Changelog:
CL: [New] Welders can now repair doors when in Help intent.
CL: [Improvement] Door sounds are now handled more robustly to make future improvements easier.
CL: [Improvement] Walking through opening or closing doors is now handled better.
CL: [Balance] Default delay to move through doors that are opening/closing increased to 50% of opening/closing time (typically 300ms), up from a static 100ms.
CL: [Fix] Fixed a bug where clicking on a door rather than bumping into the door bypassed the delay to move through altogether.
CL: [Fix] Fixed a bug where crowbars and jaws of life wouldn't always attack doors when using the harm intent.
CL: [Fix] Fixed a bug where crowbars could close doors even if they were bolted open.
CL: [Fix] Fixed a bug where powerful entities that can pry open doors couldn't close doors.
CL: [Fix] Fixed a bug where some interactions with doors would falsely say the the door was jammed.
CL: [Fix] Fixed a bug where welding doors would not use the proper object name in messages.
CL: [Fix] Fixed a bug where jaws of life could open welded doors, leaving the weld sprite floating in the air.
CL: [Fix] Fixed a bug where crowbars sometimes ignored welds on doors that were bolted.
CL: [Fix] Fixed a bug where using a welder with disarm intent on a door would do nothing, now opens the door.
CL: [Fix] Fixed a bug where doors could be interacted with while their animations were still playing.
CL: [Fix] Fixed a bug where floor tiles could be interacted with under a closed door by clicking rapidly.
CL: [Fix] Fixed a bug where door's lights would flash when pried opened by force regardless of power state.
CL: [Fix] Fixed a bug where crowbars and jaws of life could sometimes play the same sound as each other when prying doors.

There's probably a pile of other more obscure bugs that were fixed to, but these are the most obvious ones.

### Issues Addressed
#10196 - Resolved
#6980 & #6911 - Partially Resolved (the pry sound is implemented and the framework is there, but a placeholder sound is being used for the sound that plays when a door is finally pried open, I'll add the requested SFX in a separate PR that deals with addressables, wanted to limit this PR to strictly code changes)

### CODE REVIEW

File: UnityProject/Assets/Scripts/Objects/Doors/DoorSoundController.cs [hunk 1]
```diff
@@ -0,0 +1,134 @@
...
+			AccessDenied,
+			PressureWarn,
+            ToolPry,
+            JawsPry,
+            HandPry,
+            BoltsDown,
+            BoltsUp,
+		}
+
+        private AddressableAudioSource getSound(DoorSoundType sound)
```
Comment (MaxIsJoe) [inline UnityProject/Assets/Scripts/Objects/Doors/DoorSoundController.cs]: All functions use CamelCase, so it should be `GetSound()`

File: UnityProject/Assets/Scripts/Objects/Doors/Modules/WeldModule.cs [hunk 2]
```diff
@@ -27,51 +39,75 @@ public override void ClosedInteraction(HandApply interaction, HashSet<DoorProces
...
 					break;
+
+				// Help intent repairs the door
 				case Intent.Help:
-					//TODO add repairing door logic here
+					if (integrity.PercentageDamaged < 95)
+					{
+						//Scale repair time based off of percent damage
+						//TODO use time multipliers from welder tools
+						float time = repairTime - repairTime * integrity.PercentageDamaged / 100f;
```
Comment (MaxIsJoe) [inline UnityProject/Assets/Scripts/Objects/Doors/Modules/WeldModule.cs]: time is unused here?

**Review by MaxIsJoe — CHANGES_REQUESTED** [review]
High quality PR, good work 👍 
just check these two things I pointed out.

**Comment by Bobtheapple** [comment]
Good catch, welding time should scale properly now.  I cut the time save in half because it was too fast now.

**Review by MaxIsJoe — DISMISSED** [review]
LGTM.
Merge after tests pass.

File: UnityProject/Assets/Scripts/Objects/Doors/Modules/CrowbarModule.cs [hunk 3]
```diff
@@ -11,177 +11,162 @@ public class CrowbarModule : DoorModuleBase
...
+			if (interaction is { Intent: Intent.Help })
 			{
-				if ((crowbarRequiresNoPower && master.HasPower) &&
-				    (Validations.HasItemTrait(interaction.HandObject, CommonTraits.Instance.CanPryDoor) == false))
+				//If its hands that can pry doors, attempt to open the door
+				//TODO Currently hard coded to not allow larva, when prying with hands is moved to body parts just have larva not have the pry ability and update this
+				if (interaction.HandObject == null
+					&& interaction.PerformerPlayerScript.PlayerTypeSettings.CanPryDoorsWithHands &&
+					(interaction.PerformerPlayerScript.TryGetComponent<AlienPlayer>(out var alienPlayer) == false ||
+					 alienPlayer.IsLarva == false))
```
Comment (AtnerNT) [inline UnityProject/Assets/Scripts/Objects/Doors/Modules/CrowbarModule.cs:39]: Not something for this PR as aliens are there whole own bag of worms. But noting for future this shouldn't be hardcoded for Aliens/Alien Larvae. Would be better for aliens to just alter the CanPryDoorsWithHands directly on a stage by stage basis

File: UnityProject/Assets/Scripts/Objects/Doors/Modules/CrowbarModule.cs [hunk 4]
```diff
@@ -11,177 +11,162 @@ public class CrowbarModule : DoorModuleBase
...
+			if (interaction is { Intent: Intent.Help } && weldModule.IsWelded == false)
 			{
-				if ((crowbarRequiresNoPower && master.HasPower) &&
-				    (Validations.HasItemTrait(interaction.HandObject, CommonTraits.Instance.CanPryDoor) == false))
+				//If its hands that can pry doors, attempt to pry the door
+				//TODO Currently hard coded to not allow larva, when prying with hands is moved to body parts just have larva not have the pry ability and update this
+				if (interaction.HandObject == null
+					&& interaction.PerformerPlayerScript.PlayerTypeSettings.CanPryDoorsWithHands &&
+					(interaction.PerformerPlayerScript.TryGetComponent<AlienPlayer>(out var alienPlayer) == false ||
+					 alienPlayer.IsLarva == false))
```
Comment (AtnerNT) [inline UnityProject/Assets/Scripts/Objects/Doors/Modules/CrowbarModule.cs:65]: Same thing here

File: UnityProject/Assets/Scripts/Objects/Doors/Modules/CrowbarModule.cs [hunk 5]
```diff
@@ -11,177 +11,162 @@ public class CrowbarModule : DoorModuleBase
...
 
-		private void TryPryHand(HandApply interaction)
+		private void TryPry(HandApply interaction, bool useTool, bool isClosing)
 		{
-			if (master.IsClosed == false && master.IsPerformingAction == false)
+			//Refuse if door is in motion
+			if (master.IsPerformingAction) return;
+
+			//Refuse if its a crowbar and the door has power
+			else if ((crowbarRequiresNoPower && master.HasPower) &&
```
Comment (AtnerNT) [inline UnityProject/Assets/Scripts/Objects/Doors/Modules/CrowbarModule.cs]: At the end of each of these if's you return. So they dont actually need to be an else-if chain as the further code won't execute anyways. Codacy notes this as redundant jumps.

File: UnityProject/Assets/Scripts/Objects/Doors/Modules/CrowbarModule.cs (hunk 3 above)
Comment (Bobtheapple) [reply UnityProject/Assets/Scripts/Objects/Doors/Modules/CrowbarModule.cs:39]: Yeah, this is how it was already implemented in the original CrowbarModule code with a "TODO: Fix this later".  I am not familiar enough with the current state of the Xenos code so I decided to let it be for now.

File: UnityProject/Assets/Scripts/Objects/Doors/Modules/CrowbarModule.cs (hunk 5 above)
Comment (Bobtheapple) [reply UnityProject/Assets/Scripts/Objects/Doors/Modules/CrowbarModule.cs]: Fixed!

**Review by MaxIsJoe — APPROVED** [review]
