### PR TITLE
Fix energy weapons and implements switchable firemodes

### LINKED ISSUE #5273: Energy weapons no longer fire projectiles after being "reloaded".
## Description
Right now, energy weapons (laser guns, proto-kinetic accelerators, plasma cutters etc.) no longer fire projectiles after they are "reloaded" via recharging. The screen will shake to represent recoil, but no firing sound will play and no projectile appear.

The following error appears when you fire an energy gun that "fires" broken ammo.
image

### Steps to Reproduce
1.  Spawn in a proto-kinetic accelerator.
2.  Fire it once. Observe the screen shake, the kinetic force sprite appearing, and the sound that plays.
3.  After it audibly recharges, fire again. The screen will shake but no sound will play nor kinetic force sprite will appear to signify that the projectile came out and hit something.

### PR DESCRIPTION
**Pull request by AutumnNova**
fixes #5273

### CODE REVIEW

File: UnityProject/Assets/Scripts/Items/Weapons/GunElectrical.cs [hunk 1]
```diff
@@ -0,0 +1,139 @@
+using System;
+﻿using System.Collections;
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/Items/Weapons/GunElectrical.cs:2]: Codacy found an issue: [Remove this unnecessary 'using'.](https://app.codacy.com/gh/unitystation/unitystation/pullRequest?prid=6327776)

**Comment by Bod9001** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 1
           

Complexity increasing per file
==============================
- UnityProject/Assets/Scripts/Items/Weapons/GunElectrical.cs  12
- UnityProject/Assets/Scripts/Items/Weapons/MagazineBehaviour.cs  1
         

Complexity decreasing per file
==============================
+ UnityProject/Assets/Scripts/Items/Weapons/PlasmaRefill.cs  -2
         

Clones added
============
- UnityProject/Assets/Scripts/Items/Weapons/GunElectrical.cs  3
- UnityProject/Assets/Scripts/Items/Weapons/Gun.cs  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/unitystation/unitystation/pullRequest?prid=6327776&bid=20563142)
