### PR TITLE
Limb reattachment surgery hotfix

### LINKED ISSUE #7435: reattaching limbs kicks everyone out of the server
### Environment
- Game Version: Staging 21091918
- OS Version: Arch Linux

### Detailed description of bug

This works too if any of your limbs get chopped off with a sword or mob.
Example:

https://user-images.githubusercontent.com/80334192/134098087-ad1cf1a6-35fe-4719-b99f-752580ee19b7.mp4

### Steps to reproduce

1. As show in the video, chop of a limb by any means possible
2. try to reattach it 
3. when its attached back everyone will be kicked out of the server

### PR DESCRIPTION
**Pull request by Aranclanos**
### Purpose
CL: [Fix] Hotfixes players being disconnecting themselves after a removed limb is reattached through surgery.
Fixes #7435

### Notes:
the reattachment wont be visible for clients

### CODE REVIEW

**Review by ThatDan123 — APPROVED** [review]

File: UnityProject/Assets/Scripts/Messages/Server/SpritesMessages/SpriteUpdateMessage.cs [hunk 1]
```diff
@@ -356,7 +356,12 @@ public static SpriteUpdateMessage.NetMessage Deserialize(this NetworkReader read
 						Color TheColour = reader.ReadColor();
 						if (ProcessSection)
 						{
-							SP.SetColor(TheColour, false);
+							if (SP)
+							{
+								//TODO: remove this check - registering arrives after the sprite update, all clients will disconnect after a runtime
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/Messages/Server/SpritesMessages/SpriteUpdateMessage.cs:361]: it is because SP = null, 
looks like the problem is the original SP is not unregistered 
so it returns a destroyed instance of it

**Review by Bod9001 — APPROVED** [review]
