### PR TITLE
Ai chat

### LINKED ISSUE #7207: AI don't receive certain messages from speech or actions when they should be able to.
### Environment
- Game Version: Staging 21080118
- OS Version: Windows 10

### Detailed description of bug
For some reason, AIs don't receive messages in chat when they should in certain instances.

- [x]  AIs don't receive messages for actions such as pointing, emotes, or attacks they see on camera.
- [ ] AIs don't receive messages for actions nor non-radio speech if they're on an IntelliCard. This includes the AI's own speech.

AIs receive messages for non-radio speech and actions they occur at their core. AI also don't receive messages for non-radio speech through cameras but that is intentional game design both here and in /tg/.

### Steps to reproduce
1. Be an AI.
2. Find a person using your camera.
3. Have them attack a wall or window. You will see their sprite moving during the attack but you will not receive any message in chat.

### PR DESCRIPTION
**Pull request by ThatDan123**
Partially completes: #7207

Fixes Ai's not seeing action/combat messages at cameras

Note: Hasnt been tested

### CODE REVIEW

File: UnityProject/Assets/Scripts/Core/Chat/ChatRelay.cs [hunk 1]
```diff
@@ -86,21 +92,50 @@ public void PropagateChatToClients(ChatEvent chatEvent)
...
 				{
-					//Player in the list is too far away for local chat, remove them:
+					//Distance check failed so if we are Ai, then try send action and combat messages to their camera location
+					//as well as if possible
+					if (chatEvent.channels.HasFlag(ChatChannel.Local) == false &&
+					    players[i].Script.PlayerState == PlayerScript.PlayerStates.Ai &&
+					    players[i].Script.TryGetComponent<AiPlayer>(out var aiPlayer) &&
+					    aiPlayer.IsCarded == false)
+					{
+						playerPosition = players[i].Script.gameObject.AssumedWorldPosServer();
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Core/Chat/ChatRelay.cs:106]: shouldn't everyone use AssumedWorldPosition?

Comment (ThatDan123) [reply UnityProject/Assets/Scripts/Core/Chat/ChatRelay.cs:106]: they'll use and check it at line 93, but Ai uses its core there. The core isnt actually the player for the Ai, so line 106, checks the player for Ai
