### PR TITLE
Player Emotes, Animations, and Leantween Networking Bounty

### LINKED ISSUE #6157: Player Emotes, Animations, and Leantween Networking Bounty B:100
## Description

This bounty calls for the addition of all the most common player emotes, including the ones that have accompanying animations. It also requires animations for when players pick up items and for when players for down as depicted here #6074. 

_Furthermore this bounty should include a generic or standard way to network leantween animations so it is easier for contributors to implement new animations that all clients should be able to see_

## What is needed to fulfill the bounty:

- [x] add all of /tg/'s player emotes.
- [x] add all appropriate character animations for said emotes, where applicable
- [x] add an animation for picking up items.
- [x] add an animation for characters falling to the ground.
- [x] add a generic way to network leantween animation.

### LINKED ISSUE #6173: Food processor sprite disappears when food is put through
### Environment
- Game Version: 21030400
- OS Version: Mac OS Catalina

### Detailed description of bug

When putting any food into the food processor and activating it, upon completion the sprite for the processor will completely disappear when the food is dispensed leaving some to think the processor has disappeared all together.
### Steps to reproduce

1.  Aquire any type of food, (meat, cutlets etc)
2. Put it inside the processor and activate it.
3. Find that the processor sprite has disappeared completely when finished.
Screenshot 2021-03-04 at 22 00 34

### PR DESCRIPTION
**Pull request by MaxIsJoe**
### Purpose
closes #6157. Adds in 34 emotes from /TG/, Animations to some actions and a way to write clean synced LeanTween animations.

### Notes:
- [Animations] The health merge has totally screwed up damage which made me unable to test the shaking animation for the players when they get shocked. pls fix.
- [Emotes] I did not add the /me beep emote as I don't think we have playable robots yet or a check to see what race the player is right now.
- [Animations] The floating effect is working, But it's not working as the way I intended. There is no way to easily check if the player is standing on a no gravity tile and let the animation run forever until they gain some gravity back again so I had to add this stupid solution in `update()` which i'm 100% not proud of. Someone else should fix this.
- [Emotes] Emotes have no sounds for now, but the functionality to play sounds is there.

### Changelog:

- NetworkedLeanTween has been added.

CL: Adds new animations
- - Players who fall or rest on the ground will now have an animation for it as well as for getting up.
- - Picking up items now has an animation.
- - [Untested] When shocked, your character will shake just like how they do on /TG/
- - [Broken?] Players will float when not affected by gravity.

CL: Added Emotes (Based off /TG/'s Emotes).
- - Emotes will do a gender check to play the correct sounds.
- - Emotes that reference hands will check if your character actually has hands to do that action.
- - To make Unitystation far more superior than any SS13 server or project out there. Emotes have special text for when the player is in crit condition. Praise us for having better RP mechanics.

CL: closes #6173 as it is fixed.

### CODE REVIEW

**Comment by corp-0** [comment]
The code conflict can be solved but you will have to redo whatever you did for the player prefab

File: UnityProject/Assets/Scripts/Player/EmoteScripts/Surrender.cs [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+
+
+[CreateAssetMenu(fileName = "Emote", menuName = "ScriptableObjects/RP/Emotes/Surrender")]
+public class Surrender : EmoteSO
+{
+	public override void Do(GameObject player)
+	{
+		if(player.GetComponent<RegisterPlayer>() == null)
+		{
+			Debug.LogError("RegisterPlayer could not be found!");
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Player/EmoteScripts/Surrender.cs]: can you use ``Logger.LogError`` instead?

**Comment by corp-0** [comment]
To make your changes go into the changelog file type the keyword followed by a colon and then a description of your change, for example:
> CL: Added Emotes (Based off /TG/'s Emotes).

You can add more than one line per PR description, just make sure all of them start with ``CL:``

**Comment by corp-0** [comment]
I will review this tomorrow

File: UnityProject/Assets/Scripts/HealthV2/Living/LivingHealthMasterBase.cs [hunk 2]
```diff
@@ -793,4 +793,28 @@ public virtual string GetExamineText()
...
+					if (bodyPart.bodyPartType == bodyPartType)
+					{
+						return true;
+					}
+				}
+			}
+		}
+
+		return false;
+	}
```
Comment (ThatDan123) [inline UnityProject/Assets/Scripts/HealthV2/Living/LivingHealthMasterBase.cs]: This can be removed bod added one in https://github.com/unitystation/unitystation/pull/6210

**Comment by ThatDan123** [comment]
Also i dont think this been networked right, did you build test with a headless server and connected client?

File: UnityProject/Assets/Resources/ScriptableObjects/Emotes/basicEmotes/stretch.asset [hunk 3]
```diff
@@ -0,0 +1,18 @@
...
+  m_PrefabInstance: {fileID: 0}
+  m_PrefabAsset: {fileID: 0}
+  m_GameObject: {fileID: 0}
+  m_Enabled: 1
+  m_EditorHideFlags: 0
+  m_Script: {fileID: 11500000, guid: 1b9c037cd481c0f4db1c77e9cdf31787, type: 3}
+  m_Name: stretch
+  m_EditorClassIdentifier: 
+  emoteName: stretch
+  viewText: stretches theri arms.
```
Comment (corp-0) [inline UnityProject/Assets/Resources/ScriptableObjects/Emotes/basicEmotes/stretch.asset]:
```suggestion
  viewText: stretches their arms.
```

File: UnityProject/Assets/Resources/ScriptableObjects/Emotes/basicGenderedEmotes/Scream.asset [hunk 4]
```diff
@@ -0,0 +1,22 @@
...
+  m_PrefabInstance: {fileID: 0}
+  m_PrefabAsset: {fileID: 0}
+  m_GameObject: {fileID: 0}
+  m_Enabled: 1
+  m_EditorHideFlags: 0
+  m_Script: {fileID: 11500000, guid: 1a1e9a7021acd5343ab7777f5bdc00ff, type: 3}
+  m_Name: Scream
+  m_EditorClassIdentifier: 
+  emoteName: 
+  viewText: did something!
```
Comment (corp-0) [inline UnityProject/Assets/Resources/ScriptableObjects/Emotes/basicGenderedEmotes/Scream.asset]:
```suggestion
  viewText: Screams!
```
I imagine that what it should be.

File: UnityProject/Assets/Resources/ScriptableObjects/Emotes/basicGenderedEmotes/cough.asset [hunk 5]
```diff
@@ -0,0 +1,22 @@
...
+  m_Name: cough
+  m_EditorClassIdentifier: 
+  emoteName: 
+  viewText: did something!
+  youText: 
+  defaultSounds: []
+  maleSounds: []
+  femaleSounds: []
+  audioToUse: []
+  critViewText: screams in pain!
```
Comment (corp-0) [inline UnityProject/Assets/Resources/ScriptableObjects/Emotes/basicGenderedEmotes/cough.asset]: you didn't change the text here

File: UnityProject/Assets/Resources/ScriptableObjects/Emotes/basicGenderedEmotes/cry.asset [hunk 6]
```diff
@@ -0,0 +1,22 @@
...
+  m_PrefabInstance: {fileID: 0}
+  m_PrefabAsset: {fileID: 0}
+  m_GameObject: {fileID: 0}
+  m_Enabled: 1
+  m_EditorHideFlags: 0
+  m_Script: {fileID: 11500000, guid: 1a1e9a7021acd5343ab7777f5bdc00ff, type: 3}
+  m_Name: cry
+  m_EditorClassIdentifier: 
+  emoteName: 
+  viewText: did something!
```
Comment (corp-0) [inline UnityProject/Assets/Resources/ScriptableObjects/Emotes/basicGenderedEmotes/cry.asset]: also here

File: UnityProject/Assets/Resources/ScriptableObjects/Emotes/basicGenderedEmotes/gag.asset [hunk 7]
```diff
@@ -0,0 +1,22 @@
...
+  m_PrefabInstance: {fileID: 0}
+  m_PrefabAsset: {fileID: 0}
+  m_GameObject: {fileID: 0}
+  m_Enabled: 1
+  m_EditorHideFlags: 0
+  m_Script: {fileID: 11500000, guid: 1a1e9a7021acd5343ab7777f5bdc00ff, type: 3}
+  m_Name: gag
+  m_EditorClassIdentifier: 
+  emoteName: 
+  viewText: did something!
```
Comment (corp-0) [inline UnityProject/Assets/Resources/ScriptableObjects/Emotes/basicGenderedEmotes/gag.asset]: and here

File: UnityProject/Assets/Resources/ScriptableObjects/Emotes/basicGenderedEmotes/gasp.asset [hunk 8]
```diff
@@ -0,0 +1,22 @@
...
+  m_PrefabInstance: {fileID: 0}
+  m_PrefabAsset: {fileID: 0}
+  m_GameObject: {fileID: 0}
+  m_Enabled: 1
+  m_EditorHideFlags: 0
+  m_Script: {fileID: 11500000, guid: 1a1e9a7021acd5343ab7777f5bdc00ff, type: 3}
+  m_Name: gasp
+  m_EditorClassIdentifier: 
+  emoteName: 
+  viewText: did something!
```
Comment (corp-0) [inline UnityProject/Assets/Resources/ScriptableObjects/Emotes/basicGenderedEmotes/gasp.asset]: ye

File: UnityProject/Assets/Resources/ScriptableObjects/Emotes/basicGenderedEmotes/giggle.asset [hunk 9]
```diff
@@ -0,0 +1,22 @@
...
+  m_PrefabInstance: {fileID: 0}
+  m_PrefabAsset: {fileID: 0}
+  m_GameObject: {fileID: 0}
+  m_Enabled: 1
+  m_EditorHideFlags: 0
+  m_Script: {fileID: 11500000, guid: 1a1e9a7021acd5343ab7777f5bdc00ff, type: 3}
+  m_Name: giggle
+  m_EditorClassIdentifier: 
+  emoteName: 
+  viewText: did something!
```
Comment (corp-0) [inline UnityProject/Assets/Resources/ScriptableObjects/Emotes/basicGenderedEmotes/giggle.asset]: lots of screaming

File: UnityProject/Assets/Resources/ScriptableObjects/Emotes/basicGenderedEmotes/inhale.asset [hunk 10]
```diff
@@ -0,0 +1,22 @@
...
+  m_PrefabInstance: {fileID: 0}
+  m_PrefabAsset: {fileID: 0}
+  m_GameObject: {fileID: 0}
+  m_Enabled: 1
+  m_EditorHideFlags: 0
+  m_Script: {fileID: 11500000, guid: 1a1e9a7021acd5343ab7777f5bdc00ff, type: 3}
+  m_Name: inhale
+  m_EditorClassIdentifier: 
+  emoteName: 
+  viewText: did something!
```
Comment (corp-0) [inline UnityProject/Assets/Resources/ScriptableObjects/Emotes/basicGenderedEmotes/inhale.asset]: seems like non of the gendered ones have the proper text.

File: UnityProject/Assets/Resources/ScriptableObjects/FloorSound/DefaultFloorSound.asset [hunk 11]
```diff
@@ -14,31 +14,31 @@ MonoBehaviour:
   m_EditorClassIdentifier: 
   Barefoot:
   - SetLoadSetting: 0
-    AssetAddress: Assets/Prefabs/footsteps/floor/hardbarefoot1.prefab
+    AssetAddress: null
```
Comment (corp-0) [inline UnityProject/Assets/Resources/ScriptableObjects/FloorSound/DefaultFloorSound.asset]: looks like you accidentally made the barefoot sounds null

File: UnityProject/Assets/Scripts/Core/Chat/EmoteActionManager.cs [hunk 12]
```diff
@@ -0,0 +1,34 @@
...
+using UnityEngine;
+
+public class EmoteActionManager : MonoBehaviour
+{
+    [SerializeField]
+    private List<EmoteSO> emotes;
+
+    public static bool FindEmote(string emote, EmoteActionManager instance)
+    {
+		var emoteArray = emote.Split(' ');
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Core/Chat/EmoteActionManager.cs]: does this mean the emote won't work if I use ``*emote`` instead of ``/me emote``?

File: UnityProject/Assets/Scripts/Core/Chat/EmoteActionManager.cs [hunk 13]
```diff
@@ -0,0 +1,34 @@
...
+            {
+                return true;
+            }
+        }
+        return false;
+    }
+
+    public static void DoEmote(string emote, GameObject player, EmoteActionManager instance)
+    {
+		foreach (var e in instance.emotes)
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Core/Chat/EmoteActionManager.cs]: indentation looks weird

File: UnityProject/Assets/Scripts/Core/Input System/InteractionV2/Validations.cs [hunk 14]
```diff
@@ -741,4 +741,18 @@ public static bool HasTarget(TargetedInteraction interaction)
 	{
 		return interaction.TargetObject != null;
 	}
+
+	public static bool HasHand(GameObject player)
+	{
+		LivingHealthMasterBase bodyParts = PlayerManager.LocalPlayerScript.GetComponent<LivingHealthMasterBase>();
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Core/Input System/InteractionV2/Validations.cs]:
```suggestion
		if(player.TryGetComponent<LivingHealthMasterBase>(out var bodyParts)
```
You weren't used the passed argument anywhere and if for whatever reason the component was null, it would fail.

File: UnityProject/Assets/Scripts/Effects/FloatingEffect.cs [hunk 15]
```diff
@@ -0,0 +1,38 @@
+﻿using System.Collections;
+using System.Collections.Generic;
+using UnityEngine;
+
+public class FloatingEffect : LTEffect
+{
+	public bool willAnimate;
+	private float speed = 1.1f;
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Effects/FloatingEffect.cs]: is this a constant value?

File: UnityProject/Assets/Scripts/Effects/FloatingEffect.cs [hunk 16]
```diff
@@ -0,0 +1,38 @@
+﻿using System.Collections;
+using System.Collections.Generic;
+using UnityEngine;
+
+public class FloatingEffect : LTEffect
+{
+	public bool willAnimate;
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Effects/FloatingEffect.cs]: do we need to read this from anywhere else?

File: UnityProject/Assets/Scripts/Effects/LTEffect.cs [hunk 17]
```diff
@@ -0,0 +1,52 @@
...
+{
+    /// <summary>
+    /// The base class for all animated effects that requires LeanTween to sync between all clients.
+    /// </summary>
+
+    [HideInInspector]
+    public Vector3 originalPosition;
+
+    [Tooltip("Which Axis will the animation play on?")]
+    public NetworkedLeanTween.Axis axisMode = NetworkedLeanTween.Axis.X;
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Effects/LTEffect.cs]: whenever possible, prefer to use ``private`` and ``[SerializedField]``

File: UnityProject/Assets/Scripts/Effects/RotateEffect.cs [hunk 18]
```diff
@@ -0,0 +1,63 @@
...
+using System.Collections.Generic;
+using UnityEngine;
+using Mirror;
+
+public class RotateEffect : LTEffect
+{
+    private int flips;
+    private float animTime;
+    private float rotationAngle;
+	private bool isRandom = true;
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Effects/RotateEffect.cs]: indentation

File: UnityProject/Assets/Scripts/Effects/Shake.cs [hunk 19]
```diff
@@ -1,53 +1,51 @@
...
+using Mirror;
 
-public class Shake : MonoBehaviour
+public class Shake : LTEffect
 {
     /// <summary>
-    /// A shake effect that comes in two modes, SPRITE and GAMEOBJECT
-    /// SPRITE animates a given sprite only.
-    /// GAMEOBJECT animates the entire object's position.
+    /// A shake effect that shakes an entire GameObject or it's sprites only.
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Effects/Shake.cs]: what's the benefit of being able to choose between object and sprite?

File: UnityProject/Assets/Scripts/Player/PlayerEffectsManager.cs [hunk 20]
```diff
@@ -0,0 +1,49 @@
...
+		}
+		if(PlayerManager.PlayerScript.PlayerSync.isFloatingClient == false && floatingEffect.willAnimate == true)
+		{
+			AnimateFloating();
+		}
+	}
+
+	public void AnimateFloating()
+	{
+		if (floatingEffect.willAnimate)
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Player/PlayerEffectsManager.cs]: publics use PascalCase.

File: UnityProject/Assets/Scripts/ScriptableObjects/RP/EmoteSO.cs [hunk 21]
```diff
@@ -0,0 +1,113 @@
...
+	[Tooltip("A list of sounds that can be played when this emote happens.")]
+	public List<AddressableAudioSource> defaultSounds = new List<AddressableAudioSource>();
+
+	[Tooltip("A list of sounds for male characters.")]
+	public List<AddressableAudioSource> maleSounds = new List<AddressableAudioSource>();
+
+	[Tooltip("A list of sounds for female characters.")]
+	public List<AddressableAudioSource> femaleSounds = new List<AddressableAudioSource>();
+
+	[SerializeField, Range(0.1f, 2)]
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/ScriptableObjects/RP/EmoteSO.cs]:
```suggestion
	[SerializeField, MinMaxSlider(0.1f, 2)]
```

File: UnityProject/Assets/Scripts/ScriptableObjects/RP/EmoteSO.cs [hunk 22]
```diff
@@ -0,0 +1,113 @@
...
+	private RangeAttribute pitchRange = new RangeAttribute(0.7f, 1f); //This doesn't want to appear in the inspector for some reason.
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/ScriptableObjects/RP/EmoteSO.cs]:
```suggestion
	private Vector2 pitchRange = new Vector2(0.7f, 1f);
```

File: UnityProject/Assets/Scripts/ScriptableObjects/RP/EmoteSO.cs [hunk 23]
```diff
@@ -0,0 +1,113 @@
...
+			Chat.AddActionMsgToChat(player, $"{failText}", $"");
+		}
+		else
+		{
+			Chat.AddActionMsgToChat(player, $"{youText}", $"{player.ExpensiveName()} {viewText}.");
+			playAudio(defaultSounds, player);
+		}
+	}
+
+	public void playAudio(List<AddressableAudioSource> audio, GameObject player)
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/ScriptableObjects/RP/EmoteSO.cs]: methods name use PascalCase

File: UnityProject/Assets/Scripts/ScriptableObjects/RP/EmoteSO.cs [hunk 24]
```diff
@@ -0,0 +1,113 @@
...
+	{
+		List<AddressableAudioSource> audioList = audio;
+
+		//If there is no audio in the audio list, exit out of this function.
+		if (audioList.Count == 0)
+		{
+			Debug.LogWarning("[EmoteSO/" + $"{this.name}] - " + "No audio files detected!.");
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/ScriptableObjects/RP/EmoteSO.cs]:
```suggestion
			Logger.LogWarning("[EmoteSO/" + $"{this.name}] - " + "No audio files detected!.");
```

File: UnityProject/Assets/Scripts/ScriptableObjects/RP/EmoteSO.cs [hunk 25]
```diff
@@ -0,0 +1,113 @@
...
+			return;
+		}
+
+		AudioSourceParameters audioSourceParameters = new AudioSourceParameters(pitch: Random.Range(pitchRange.min, pitchRange.max));
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/ScriptableObjects/RP/EmoteSO.cs]:
```suggestion
		AudioSourceParameters audioSourceParameters = new AudioSourceParameters(pitch: Random.Range(pitchRange.x, pitchRange.y));
```

File: UnityProject/Assets/Scripts/ScriptableObjects/RP/EmoteSO.cs [hunk 26]
```diff
@@ -0,0 +1,113 @@
...
+			default:
+				audioToUse = defaultSounds;
+				break;
+		}
+	}
+
+
+	public bool CheckHandState(GameObject player)
+	{
+		if (!PlayerManager.LocalPlayerScript.playerMove.IsCuffed)
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/ScriptableObjects/RP/EmoteSO.cs]: all of these checks only work on client btw

File: UnityProject/Assets/Scripts/Systems/Inventory/Pickupable.cs [hunk 27]
```diff
@@ -146,29 +147,41 @@ public void ServerRollbackClient(HandApply interaction)
 	}
 
 	public virtual void ServerPerformInteraction(HandApply interaction)
+	{
+		StartCoroutine(serverPreformInteractionLogic(interaction));
+	}
+
+	private IEnumerator serverPreformInteractionLogic(HandApply interaction)
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Systems/Inventory/Pickupable.cs:157]: PascalCase

File: UnityProject/Assets/Scripts/Systems/Inventory/Pickupable.cs [hunk 28]
```diff
@@ -146,29 +147,41 @@ public void ServerRollbackClient(HandApply interaction)
...
 	{
 		//we validated, but object may only be in extended range
 		var cnt = GetComponent<CustomNetTransform>();
 		var ps = interaction.Performer.GetComponent<PlayerScript>();
 		var extendedRangeOnly = !ps.IsRegisterTileReachable(cnt.RegisterTile, true);
 
+		float animTime = 0.2f;
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Systems/Inventory/Pickupable.cs]: make it a constant of the class or you could even make it a serialized field if we wanted to change the speed eventually.

File: UnityProject/Assets/Scripts/Systems/Inventory/Pickupable.cs [hunk 29]
```diff
@@ -146,29 +147,41 @@ public void ServerRollbackClient(HandApply interaction)
...
+		LeanTween.move(gameObject, interaction.Performer.transform, animTime);
+		LeanTween.scale(gameObject, new Vector3(0, 0), animTime);
+		yield return new WaitForSeconds(animTime);
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Systems/Inventory/Pickupable.cs]:
```suggestion
		yield return WaitFor.Seconds(animTime);
```

File: UnityProject/Assets/Scripts/Systems/Inventory/Pickupable.cs [hunk 30]
```diff
@@ -146,29 +147,41 @@ public void ServerRollbackClient(HandApply interaction)
...
+			cnt.Nudge(new NudgeInfo
 			{
 				OriginPos = worldPosition - trajectory,
 				Trajectory = trajectory,
 				SpinMode = SpinMode.Clockwise,
 				SpinMultiplier = 15,
 				InitialSpeed = 2
 			} );
-			Logger.LogTraceFormat( "Nudging! server pos:{0} player pos:{1}", Category.Security,
+			Logger.LogTraceFormat( "Nudging! server pos:{0} player pos:{1}", Category.Movement,
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Systems/Inventory/Pickupable.cs]: why movement?

File: UnityProject/Assets/Scripts/Util/NetworkedLeanTween.cs [hunk 31]
```diff
@@ -0,0 +1,182 @@
+﻿using UnityEngine;
+using Mirror;
+
+/// <summary>
+/// Handles syncing common variables used in animations.
+/// </summary>
+
+public class NetworkedLeanTween : NetworkBehaviour
+{
+	[SyncVar]
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Util/NetworkedLeanTween.cs]: SyncVars only work when the trigger is server, you have a couple calls using client side code.

File: UnityProject/Assets/Scripts/Util/NetworkedLeanTween.cs [hunk 32]
```diff
@@ -0,0 +1,182 @@
...
+	}
+
+	public enum AnimType
+	{
+		MOVEMENT,
+		COLOR
+	}
+
+	private void Awake() {
+		if(target == null){ target = this.transform;}
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Util/NetworkedLeanTween.cs]:
```suggestion
		if(target == null)
		{
		    target = this.transform;
		}
```

**Review by corp-0 — CHANGES_REQUESTED** [review]
I gave it an oversight, still need to build in my computer but I can only do that later today.

File: UnityProject/Assets/Resources/ScriptableObjects/Emotes/basicGenderedEmotes/Scream.asset (hunk 4 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Resources/ScriptableObjects/Emotes/basicGenderedEmotes/Scream.asset]: odd, why didn't the viewText get commited?

File: UnityProject/Assets/Resources/ScriptableObjects/FloorSound/DefaultFloorSound.asset (hunk 11 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Resources/ScriptableObjects/FloorSound/DefaultFloorSound.asset]: how did I even do that, what

File: UnityProject/Assets/Scripts/Effects/FloatingEffect.cs (hunk 16 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Effects/FloatingEffect.cs]: yes

File: UnityProject/Assets/Scripts/Effects/LTEffect.cs (hunk 17 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Effects/LTEffect.cs]: we could need to change the axisMode of the component via script in the future so it's best to leave it public.

File: UnityProject/Assets/Scripts/Effects/Shake.cs (hunk 19 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Effects/Shake.cs]: If an object doesn't have a sprite handler or has multiple objects that need to shake GAMEOBJECT mode makes sure that the object will be shaken correctly, there's also some gameplay benefits like synced hitboxes and stuff like that.
GAMEOBJECT mode is there for those "what if" moments so people in the future don't have to worry about coding it themselves or even worse coding their own solution outside a script that already exists for it.

File: UnityProject/Assets/Scripts/Systems/Inventory/Pickupable.cs (hunk 30 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Systems/Inventory/Pickupable.cs]: > why movement?

I have no idea, that's what the merge conflict said. ask whoever edited this file in develop.

**Comment by MaxIsJoe** [comment]
whewh, that's a lot fixes to do.

Going to do them when I'm back on my PC.

File: UnityProject/Assets/Scripts/Core/Input System/InteractionV2/Validations.cs [hunk 33]
```diff
@@ -744,7 +744,7 @@ public static bool HasTarget(TargetedInteraction interaction)
 
 	public static bool HasHand(GameObject player)
 	{
-		LivingHealthMasterBase bodyParts = PlayerManager.LocalPlayerScript.GetComponent<LivingHealthMasterBase>();
+		if(player.TryGetComponent<LivingHealthMasterBase>(out var bodyParts)
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Core/Input System/InteractionV2/Validations.cs]: don't just commit the suggestion, add the brackets!

**Comment by corp-0** [comment]
problem with just committing the suggestion is I can't use tabs when suggesting in github

File: UnityProject/Assets/Scripts/Effects/LTEffect.cs (hunk 17 above)
Comment (corp-0) [reply UnityProject/Assets/Scripts/Effects/LTEffect.cs]: alright, that's fine. I'm just seeing a lot of publics in your code when I feel it isn't needed. Use publics sparingly and only when you intend it to be accessed and modified from an arbitrary script, otherwise always restrict the access to read only or make setters.

File: UnityProject/Assets/Scripts/Core/Chat/EmoteActionManager.cs (hunk 12 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Core/Chat/EmoteActionManager.cs]: Tested and noticed it didn't work so I pushed a fix.

File: UnityProject/Assets/Scripts/Core/Chat/EmoteActionManager.cs (hunk 13 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Core/Chat/EmoteActionManager.cs]: image
nothing seems wrong on my end.

Comment (corp-0) [reply UnityProject/Assets/Scripts/Core/Chat/EmoteActionManager.cs]: more than likely, it is combining spaces and tabs. Get an extension to tab the entire thing.

File: UnityProject/Assets/Scripts/Effects/FloatingEffect.cs (hunk 16 above)
Comment (corp-0) [reply UnityProject/Assets/Scripts/Effects/FloatingEffect.cs]: good, make it PascalCase

File: UnityProject/Assets/Scripts/Effects/RotateEffect.cs (hunk 18 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Effects/RotateEffect.cs]: no problems on my end

File: UnityProject/Assets/Scripts/Systems/Inventory/Pickupable.cs (hunk 27 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Systems/Inventory/Pickupable.cs:157]: Not my function, not going to change it.

Comment (corp-0) [reply UnityProject/Assets/Scripts/Systems/Inventory/Pickupable.cs:157]: it actually is your coroutine. You named it.

File: UnityProject/Assets/Scripts/Player/PlayerEffectsManager.cs [hunk 34]
```diff
@@ -26,16 +26,16 @@ private void Update()
...
 		}
 		if(PlayerManager.PlayerScript.PlayerSync.isFloatingClient == false && floatingEffect.willAnimate == true)
 		{
-			AnimateFloating();
+			animateFloating();
 		}
 	}
 
-	public void AnimateFloating()
+	public void animateFloating()
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Player/PlayerEffectsManager.cs]: You did the opposite of PascalCase. I was referring to the public field you're using inside the if statement, ``willAnimate```is using camelCase when it should be PascalCase.

**Comment by MaxIsJoe** [comment]
done more clean up

**Comment by corp-0** [comment]
I'm finishing a build, I will start a new one after that is done with your latest changes and test in multiplayer.

**Comment by MaxIsJoe** [comment]
image
As of right now I'm stuck with the backflip animation not working, can't seem to find a solution to fix it.
I'm going to hop off for a few hours so until then if anyone knows a way to solve this issue in the screenshot feel free to share.

**Comment by MaxIsJoe** [comment]
I have no idea how, I have no Idea why, I shouldn't have to ask how and why, but using commands just breaks an entire emote for no reason what so ever and makes Unity set an object type to a completely wrong one and never throws any errors about it.
To fully understand the pain I was suffering while working on this think of setting a string as an integer like `string smth = 4;`.
the compiler would throw a fit if you did that but somehow it was completely and totally okay with setting a transform as a `RotateEffect` and then when we checked if that transform existed Mirror just said it doesn't exist even though it's referenced.

I have reverted back to the way I synced stuff and all I want is someone to test if it works without any further suggestions that may break Backflip or networkedLeanTween again. once everything is confirmed to be working on at least the server we can worry about syncing things between the client.

**Comment by ThatDan123** [comment]
Im not sure why youre trying to use commands, since all the system needs to do is do a ClientRPC to trigger the clients to do an animation. Also mirror doesnt like nested networked identities so that effects prefab thing on the player will need to be changed as that could also be causing your issues

**Comment by MaxIsJoe** [comment]
> Im not sure why youre trying to use commands, since all the system needs to do is do a ClientRPC to trigger the clients to do an animation. 

[ClientRpc] needs to be [called from the server](https://mirror-networking.gitbook.io/docs/guides/communications/remote-actions) which is why we were using commands.

> Also mirror doesnt like nested networked identities so that effects prefab thing on the player will need to be changed as that could also be causing your issues

Then do I just move the PlayerEffectsManager to the root object of the player and rewrite LTEffects to be a standard monobehavior?

**Comment by ThatDan123** [comment]
> [ClientRpc] needs to be [called from the server](https://mirror-networking.gitbook.io/docs/guides/communications/remote-actions) which is why we were using commands.

You dont need to use commands as the server is the one that detects whether a player is doing an emote through the chat system, after the detection the server needs to do a RPC

**Comment by MaxIsJoe** [comment]
Finally, got [RpcClient] to work. Got rid of all my old code as well since they're no longer needed.

Testing needed now to make sure everything is working correctly.

**Comment by MaxIsJoe** [comment]
also I think codacy is stupid

**Comment by MrAsbestos** [comment]
from what I heard  sometimes codacy just complains for a shitty reason

**Comment by MaxIsJoe** [comment]
This should be the final commit, everything has been tested and working.

can we please finish this now.

**Comment by corp-0** [comment]
I'm reviewing and testing this now

**Comment by corp-0** [comment]
testing in editor, twitch effect makes me invisible after it is done and it twitches the whole game obejct instead of just my sprite which means camera also twitches.

**Comment by corp-0** [comment]
how do I standup after surrendering?

**Comment by corp-0** [comment]
how do I standup after surrendering?

**Comment by corp-0** [comment]
GIF 12-03-2021 15-59-32
this is floating

**Comment by corp-0** [comment]
I made a PR to  your branch with general style clean up.

**Comment by corp-0** [comment]
If I wanted to add a new networked animation, what are the steps? Inheriting from NLE and implementing the appropiate methods?

**Comment by MaxIsJoe** [comment]
> If I wanted to add a new networked animation, what are the steps? Inheriting from NLE and implementing the appropriate methods?

To setup a NTL all you have to apply is the NTL script to an object of your choice and set the target to what you want to animate, leave the target empty if you want to animate the object the script's on.
For adding effects, you need a NTL component if you're planning on syncing these LT effects across all clients. 
image

for setting up LTEffects, use sprite mode if you want to animate sprites only or use GameObject mode if you want to animate the entire gameObject that holds the LTE component. Make sure to reference the sprites when using Sprite mode. After that, choose which axis do you want the object to animate on if you're planning on using Move, LocalMove, Rotate, etc or simply choose which axis from your code using AxisMode enum then choosing an axis.

TLDR :
Add NTL to the thing you want to animate and synced across all objects then call functions from there as long as you're the server, LTEffects let's you write less code and focus on making your animation logic.

**Comment by MaxIsJoe** [comment]
> testing in editor, twitch effect makes me invisible after it is done and it twitches the whole game obejct instead of just my sprite which means camera also twitches.

Found the issue, the player sprite gets sent back to their spawn position. Fixing this now.

**Comment by MaxIsJoe** [comment]
> how do I standup after surrendering?

Forgot that there is no manual rest behavior yet and Jack told me to remove this emote from the emote list until we add a manual resting command. Fixing this now.

**Comment by corp-0** [comment]
About the codacy issues: I disabled the suggestion for if instead of switch in your case. The other two issues are legit.

**Comment by MaxIsJoe** [comment]
> GIF 12-03-2021 15-59-32
> this is floating

It seems like I fixed it in 5b40bc2 
this should also fix the shaky camera problem

**Comment by MaxIsJoe** [comment]
> > GIF 12-03-2021 15-59-32
> > this is floating
> 
> It seems like I fixed it in [5b40bc2](https://github.com/unitystation/unitystation/commit/5b40bc2be6998cb20ac6bde643e62c6d2109fc00)
> this should also fix the shaky camera problem

tested it, yeah it did fix it.

**Comment by corp-0** [comment]
I will review this tomorrow

File: UnityProject/Assets/Resources/ScriptableObjects/FloorSound/DefaultFloorSound.asset [hunk 35]
```diff
@@ -20,25 +20,25 @@ MonoBehaviour:
       m_SubObjectName: 
       m_SubObjectType: 
   - SetLoadSetting: 0
-    AssetAddress: Assets/Prefabs/footsteps/floor/hardbarefoot2.prefab
+    AssetAddress: null
```
Comment (corp-0) [inline UnityProject/Assets/Resources/ScriptableObjects/FloorSound/DefaultFloorSound.asset]: ò.ó

**Comment by corp-0** [comment]
image
Did a backflip on client (right), now I'm stuck like this.

**Comment by corp-0** [comment]
Emote | Server | Client |  
-- | -- | -- | --
backflip | o | x | Client doesn't play animation and their sprite gets stuck inverted
dance | x | x | Makes you look right but no action message is ever sent
surrender | o | o |  
clap | o | o |  
cross | o | o |  
drool | o | o |  
frown | o | o |  
grimace | o | o |  
jump | ? | ? | No animation in either side, intended?
pout | o | o |  
shake | o | o |  
sit | o | o |  
smile | o | o |  
smug | o | o |  
snap | o | o | assuming the sound works
stare | o | o |  
.stretch | o | o |  
sulk | o | o |  
surrenderAlt | o | o |  
sway | o | o |  
tremble | o | x | animation plays for client but not server
twitch | o | x | animation plays for client but not server
scream | o | o | assuming the sound works
cough | o | o | assuming the sound works
cry | o | o |  
gag | o | o |  
gasp | o | o |  
giggle | o | o |  
inhale | o | o |  
laugh | o | o |  
sigh | o | o |  
sneeze | o | o |  
whimper | o | o |  
yawm | x | x | doesn't trigger

My report on testing all emotes on both client and server side by side

**Comment by corp-0** [comment]
Another minor issues:
* Intercept emote text so it is not sent as speech (no speech bubble with the trigger word).
* Make sure custom emotes still work, sending action text instead of the normal speech bubble.

**Comment by MaxIsJoe** [comment]
A couple of notes :

- No Jump animation because it's intentional.
- I have said that dance won't work because you can't call coroutines from inside scriptable objects.
- Backflip is properly not working correctly due to floats looking like this `0.1f` instead of `0.10f` and random being applied. Should be an easy fix.
- I have no plans for adding audio right now as I still don't get how addressable paths work. (Tried importing a few voices and it couldn't find them, someone else setup asset bundles or whatever they're called)
- I thought you guys wanted NTL to behave like this? to only send animations to clients and not the server since that's how RpcClient works. but eh, easy fix. just use normal leantween before NTL functions.

**Comment by MaxIsJoe** [comment]
> Another minor issues:
> 
> * Intercept emote text so it is not sent as speech (no speech bubble with the trigger word).
> * Make sure custom emotes still work, sending action text instead of the normal speech bubble.

I'm sorry it must be my 4AM brain but wdym by these two?

**Comment by corp-0** [comment]
> I have said that dance won't work because you can't call coroutines from inside scriptable objects.

It is inside a coroutine now tho, there is just no waiting time between direction changes. Don't ommit the bit where I said there is no action message broadcasted.

> I'm sorry it must be my 4AM brain but wdym by these two?

When you trigger an emote a speech bubble is created and your character *says* the trigger. So if I type ``*twitch`` I will both send the action message other players can see and I will *say* "twitch".

> I thought you guys wanted NTL to behave like this? to only send animations to clients and not the server since that's how RpcClient works. but eh, easy fix. just use normal leantween before NTL functions.

Now that you mention it, I didn't test with more than one client to see if they all can see the animation.

**Comment by MaxIsJoe** [comment]
> It is inside a coroutine now tho, there is just no waiting time between direction changes. Don't ommit the bit where I said there is no action message broadcasted.

Just checked it, thanks! added it in.

> When you trigger an emote a speech bubble is created and your character _says_ the trigger. So if I type `*twitch` I will both send the action message other players can see and I will _say_ "twitch".

I have no idea how to fix this, it shouldn't even happen in the first place as the code should technically cancel anything afterwards that broadcasts the emote text.

> Now that you mention it, I didn't test with more than one client to see if they all can see the animation.

oh no.

Anyways I fixed yawn not working, fixed outdated text, made dance work, fixed backflip. here's a list of things I'm having trouble with. : 

- ~~[Emotes] Can't find a way to cancel speech bubbles or broadcasting the emote text to other players.~~
- [Animation] backflip has unexplainable behavior where animations don't get called on all clients, which shouldn't happen because backflip is getting called from the server and it triggers [ClientRpc] ~~and it should be the other way around like tremble and twitch.~~
- [Animation] There is no way to check for if the player is floating without using update.

**Comment by MaxIsJoe** [comment]
A note for future peeps :
There is no longer a way to automatically make sure all effects on the player have a NTL component assigned to them so double make sure that your effects are properly setup manually by yourself otherwise you can't call functions from NTL.

File: UnityProject/Assets/Resources/ScriptableObjects/FloorSound/DefaultFloorSound.asset [hunk 36]
```diff
@@ -26,19 +26,19 @@ MonoBehaviour:
       m_SubObjectName: 
       m_SubObjectType: 
   - SetLoadSetting: 0
-    AssetAddress: Assets/Prefabs/footsteps/floor/hardbarefoot3.prefab
+    AssetAddress: null
```
Comment (corp-0) [inline UnityProject/Assets/Resources/ScriptableObjects/FloorSound/DefaultFloorSound.asset]: I can't merge until this file is out of your changes history.

**Comment by Pockets-byte** [comment]
what about slap, weh, and meow

**Comment by PerfectTangent** [comment]
Slap is an action. It's not covered by this bounty. The other two can be added easily afterwards.

**Comment by MrAsbestos** [comment]
what is that "weh" emote? pretty sure it isn't from TG

**Comment by MaxIsJoe** [comment]
> what about slap, weh, and meow

Meow and weh are not from /TG/, I will not add them. + I'm already done with adding new features to this bounty, I want it tested and merged then I'll add extra stuff like sounds and more animations later once we no longer have a feature freeze.

**Comment by MrAsbestos** [comment]
Pretty sure I have seen the "weh" in a furry server on a vid, but yeah understandable and plus I already want to see this awesome animations and emotes

**Comment by Pockets-byte** [comment]
thanks for the clarification. my bad, I didn't realize that they weren't /tg/ 
I'm not completely clear on the difference with actions vs emotes. but thanks all the same

**Comment by MaxIsJoe** [comment]
> thanks for the clarification. my bad, I didn't realize that they weren't /tg/
> I'm not completely clear on the difference with actions vs emotes. but thanks all the same

Once this is merged you can easily create weh and meow yourself btw.
Just create a GenderedEmote SO, set the text and audio, then add the emote to the EmoteManager in the chat prefab. It's that easy.

**Comment by MaxIsJoe** [comment]
While I'm here, I've built the game this morning and tested it myself on the server and client. I couldn't find any issues after testing things over and over again but since I don't trust myself I'd like someone to run their own test as well to detect if there are any issues with animations syncing.

**Comment by corp-0** [comment]
I will, don't worry about it. After my classes today.

**Comment by corp-0** [comment]
after a backflip. Server on left, right is client. Emote was triggered from the client.
image

**Comment by corp-0** [comment]
everything else seems to be working as intended

**Comment by MaxIsJoe** [comment]
> after a backflip. Server on left, right is client. Emote was triggered from the client.
> image

I have said this before, [RpcClient] has some weird behavior all the time that makes stuff inconsistent between the server and client.
I tried fixing this issue but I gave up. Can we leave it at that?

**Comment by MaxIsJoe** [comment]
for reference, here's the list of issues that I can't fix.

> * [Animation] backflip has unexplainable behavior where animations don't get called on all clients, which shouldn't happen because backflip is getting called from the server and it triggers [ClientRpc]
> * [Animation] There is no way to check for if the player is floating without using update.

Updating the first one to :

- [Animation] backflip has unexplainable behavior where animations don't sync correctly between all clients but works fine on the server side, which has no fix as far as I'm aware.

**Comment by corp-0** [comment]
> Can we leave it at that?

Having your character upside down for the rest of the round is not just a minor issue, in my opinion. I have tested 4 times now, every time opening the application from zero and I get exactly the same results: Client character doesn't do anything on server, does flip animation on client but stays upside down.

Maybe @NoooneyDude has some input to do here?

**Comment by MaxIsJoe** [comment]
Opening up unity one more time to try and investigate this issue once more. pushing a possible fix if I can.

**Comment by corp-0** [comment]
Only problem I noticed now is picking up animation only work for server, but that's not really part of the bounty so if you don't want to fix it here I can still merge.

**Review by corp-0 — APPROVED** [review]

**Comment by MaxIsJoe** [comment]
> Only problem I noticed now is picking up animation only work for server, but that's not really part of the bounty so if you don't want to fix it here I can still merge.

I'll fix it later when I have more free time. for now we can merge.

**Comment by waffielz** [comment]
when can i dab and default dance

**Comment by VernaSaurus** [comment]
waff stop commenting on closed prs
