### PR TITLE
Fixes hand-labeler not working with containers

### LINKED ISSUE #9730: [BUG] The Hand Labeler cannot label containers
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

17/3/2023

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

Tried labeling a locker and wooden container, kept opening them instead.

### What should have happened instead?

Should have labeled these containers with the text I gave.

### Steps to reproduce the issue

1. Grab a hand labeler
2. Label a locker or container

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MaxIsJoe**
fixes #9730

CL: [Improvement] hand-labeler can now work with storage containers as they should.
CL: [Fix] Interactions with closets can now be skipped in favor of items that contain the "PriorityHand" trait.

### CODE REVIEW

**Comment by corp-0** [comment]
uhhm, explain your solution

**Comment by MaxIsJoe** [comment]
1. Locker has "WillInteract" return false if it detects a handObject with the item trait "HandPriority" to stop it from interacting and give priority to the hand object.
2. Hand-labeler just now has an extra list of objects that it can be used on, not just prefabs that have `ItemAttributesV2`

File: UnityProject/Assets/Scripts/Items/Bureaucracy/HandLabeler.cs [hunk 1]
```diff
@@ -89,7 +97,7 @@ public void ServerPerformInteraction(InventoryApply interaction)
 		{
 			labelAmount = LABEL_CAPACITY;
 			_ = Despawn.ServerSingle(interaction.UsedObject);
-			Chat.AddExamineMsg(interaction.Performer, $"You insert the {interaction.UsedObject.Item().ArticleName.ToLower()} into the {gameObject.Item().InitialName.ToLower()}.");
+			Chat.AddExamineMsg(interaction.Performer, $"You insert the {interaction.UsedObject.AttributesOrNull().ArticleName.ToLower()} into the {gameObject.AttributesOrNull().InitialName.ToLower()}.");
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Items/Bureaucracy/HandLabeler.cs:102]: what is the string going to be when ``AttributesOrNull``returns null?

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Items/Bureaucracy/HandLabeler.cs:102]: nothing, it shouldn't do anything if attributes is null

Comment (corp-0) [reply UnityProject/Assets/Scripts/Items/Bureaucracy/HandLabeler.cs:102]: that's not what I am reading in the code. It will throw an NRE if ``AttributesOrNull`` returned null.

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Items/Bureaucracy/HandLabeler.cs:102]: yeah i noticed, so i fixed it quickly

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Items/Bureaucracy/HandLabeler.cs:102]: yeah i noticed, so i fixed it quickly

**Review by Bod9001 — APPROVED** [review]
