### PR TITLE
Stranded Ending, Lots of Matrix Bugfixing, Other Fixes

### LINKED ISSUE #2263: Shuttle Rotation Glitches
# Description
Apparently there are still some glitches with matrix rotation.

Try spawning a canister using the dev spawner on a rotated matrix. It will appear sideways. Instead it should appear upright.

This most likely has to do with some failure within the rotation init logic, not properly keeping the canister upright.

Additionally, on client side, none of the objects rotate upright at the end of matrix rotation, making it look really weird (upside down chairs). This used to work fine so must be a pretty easy fix.

### LINKED ISSUE #2265: Player can get stuck on non-station matrices B: 25
# Description
Server movement can somehow stop working on non-station matrix, leaving player with predictive movement and either making him stuck or moving/floating forever without letting him know that something is wrong
image
GIF

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Repeat the trick from the GIF. Only engages when you walk across the top right corner of syndie shuttle

### LINKED ISSUE #2267: Players can predictively initiate walk when they're not supposed to B: 30
# Description
...that results in rollback after a while. But clients shouldn't even try to walk when they're not sticky, as only throwing things should work in such situations
GIF

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Spawn yourself in a void (either move spawnpoint to space or clear up room where you're supposed to spawn in with a few asteroids) to end up in a situation when you can't walk in space. 
Enable `Matrix Check-Matrix-Sticky` gizmo and that you're on non-sticky tile
2. Try walking around, your predictive (green) gizmo will increase step count while red (server) ones stay in place. Eventually you'll get rolled back.

### LINKED ISSUE #2345: Rounds can't end properly if you park something in front of the emergency shuttle B: 25
# Description
If you Park mining shuttle in front of the escape area, the escape shuttle will crash into it and get stuck, resulting in the round never ending

## Steps to Reproduce
1.Grab mining shuttle
2.Fly around to departures
3.Place in front of departures where Emergency escape Shuttle would be
4. Call emergency shuttle
5. Watch as it crashes and get stuck

### LINKED ISSUE #2407: Dead/crit players get back up when stun is over
# Description
image

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Beat yourself up a bit
2. Explode large tanks nearby to get stunned and hit by a few objects to crit/die
3. See your dead/unconscious player get back up after a while

### LINKED ISSUE #2416: Cargo Shuttle crashes into the cargo bay after more than one departure
# Description

## Detailed Bug Report
After making the cargo shuttle depart the bay more than once, it will rotate, crash into the station, and blow a hole into everything.

https://discordapp.com/channels/273774715741667329/312454684021620736/651933912716541962

### LINKED ISSUE #2441: Shuttle console sometimes closes during ship rotation
# Description
Rotating ship while staying adjacent to shuttle console sometimes triggers tab closing.
Consider switching to `SpatialRelationship` system and see if it helps

### LINKED ISSUE #2460: Floor punching really disrupts combat
# Description
90% Of the clicks in combat are Misses, The short pause when hitting the floor really disrupts the combat flow

## Detailed Bug Report
in the byond Version floors and walls don't have a default interaction

## Steps to remedy
New combat system compared to the old version
Removing the interaction
Change up the combat system to include this

### PR DESCRIPTION
**Pull request by chairbender**
### Purpose
NOTE: Please put any bounties this satisfies back into the pool.

Lots of fixes for things that were all tangled together + a new ending for when escape shuttle becomes blocked or engines are destroyed.

Fixes #2460 
Fixes #2441 
Fixes #2416 
Fixes #2407 
Fixes #2345
Fixes #2263 
Fixes #2267 
I think fixes #2265 

Additional fixes / changes worth calling out that weren't in tickets:
- All mapped objects should now always have a local rotation of 0,0,0 (Quaternion.identity). Any objects which want to face a particular direction should make use of the directional component. The only exception right now is objects that have spin rotation due to throwing. This makes it easier to reason about transform rotations and ensures that synchronization works, since Directional is pretty good about client / server sync. Nothing should ever be mapped with a transform local rotation now. Mapping wiki will be updated.
- Adds WallProtrusion component for things like camera, light tube, etc...currently just a marker component but it will eventually have construction related logic in it and I needed it for one of the editor scripts. Or I'll just convert it to an ItemTrait.
- SpriteMatrixRotation is now UprightSprites. Added 2 new components for things that should rotate when their direction changes - DirectionalRotatesSprites (for rotating sprite transforms only) and DirectionalRotatesChildren (for rotating all child transforms). This is used for things like wall protrusions, wall mounts that rotate (such as sensors), and engines / engine fx. This ensures these sprites are in sync according to Directional.
- Various prefabs were modified to make use of those new components. Engines, heaters, collision sensors now have directional, as do all wall protrusions.
- Matrix move initial facings are now set using directional, and they also have a separate facing and flying direction among other changes.
- To deal with matrix / register tile sync / init issues, there's now a NetworkedMatrix component that lives on the "root" transform of a matrix and fixes quite a few inconsistent init issues.
- RegisterTile changed quite a bit to solve various init bugs and also ensure it is reset to a local rotation of 0 when changing parents.
- Refactors interaction reach checking logic so it works more consistently and works better on moving matrices.

Mapping Changes:
- Adds NetworkedMatrix to matrix root transforms
- Used editor script to change all object rotations to upright
- Used editor script to set all wall protrusion directionals
- Fixed directionals of engines / heaters on escape shuttle
- Fix initial facings of shuttles
- Manually fix emergency light directionals (they were mapped backwards from the wall protrusions)
- Add light switch to mining shuttle so lights will be on

Known Issues (will create tickets):
- Warnings when slipping on water from client prediction - it never updates in CheckMovementClient when client slips on water because IsWeightlessClient is false when they're on a matrix. This is probably because client has no way to know  what tiles are slippery, so it can't
predict slipping.
- Spin rotation doesn't reliably sync when dragging a spun object across matrices that are rotated differently. This seems pretty complicated and is merely an effect, so I want to do it in a separate PR
- Light switches / lights are not consistently on and not consistently hooked up to correct switches - the way light switches register is by proximity / facing / luck in the order that the switches initialize. The logic was already pretty sketchy, I don't think I made it worse. Client and server sometimes disagree about which lights go to which switches, especially noticeable on rotated matrices. This logic needs to be made more consistent, possibly done via initial mapping + using some system for defining which lights connect to which switches (such as using multi tool in game). Most noticeable by rotating syndi down as host then joining as client - cockpit lights are off.
- Various matrix movement (not rotation) bugs. Most of these happen when rotating matrix 90 degrees from initial and then traveling at really slow or really fast speed. PR is already big enough so I'll fix these separately. Various issues on moving matrices probably related to using  registered world position coordinates for various logic while on moving matrices. Since these coordinates are rounded and also are jumping while matrix is moving, sometimes things don't happen in the correct tile. Here's ones I noticed so far:
  - Dropping stuff or placing things on tables causes it to lerp into position rather than appearing directly at the correct spot.
  - Thrown things also initially appear in the wrong place but end up in the correct final destination.
  - FOV freaks out when shooting on moving matrix due to the recoil
  - Extinguisher spray - wet tile effect doesn't seem to match up with the actual slippery tiles, and sometimes tiles don't dry. 
  - When constructing (for example a girder), girder shows up in the wrong place.
  - There are probably other unnoticed issues related to this.

### Notes
Recommend testing by adding Syndicate Operative to AllowedOccupations so you can spawn on syndie shuttle.

### Please make sure you have followed the self checks below before submitting a PR:

- Code is sufficiently commented
- Code is indented with tabs and not spaces
- The PR does not include any unnecessary .meta, .prefab or <b>.unity (scene) changes</b>
- The PR does not bring up any new compile errors
- The PR has been tested in editor
- Any new files are named using PascalCase (to avoid issues on case sensitive file systems)
- Any new / changed components follow the [Component Development Checklist](https://github.com/unitystation/unitystation/wiki/Component-Development-Checklist)
- Any new objects / items follow the [Creating Items and Objects Guide](https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants) (especially concerning the use of prefab variants)
- The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)
- The PR has been tested with round restarts.
- The PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)

### CODE REVIEW

**Comment by chairbender** [comment]
one sec...one change to make on naming, grandparent matrix is confusing

**Comment by chairbender** [comment]
good to go

**Comment by chairbender** [comment]
@DooblyNoobly Please put any bounties this satisfies back into the pool.

File: UnityProject/Assets/Scripts/Shuttles/MatrixPositionFilter.cs [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+	}
+
+	/// <summary>
+	/// Sets the saved positions manually to the specified value. Used for start / stop.
+	/// TODO: I'm not sure why this logic even exists but it was there in MatrixMove
+	/// </summary>
+	/// <param name="position"></param>
+	public void SetPosition(Vector3 position)
+	{
+
```
Comment (chairbender) [inline UnityProject/Assets/Scripts/Shuttles/MatrixPositionFilter.cs]: oops

**Comment by chairbender** [comment]
just added a fix for #2267 (also put this back into bounty pool please)

**Comment by chairbender** [comment]
Also seems to fix #2265, can't reproduce it (bounty pool as well)

**Comment by fomalsd** [comment]
bar sign has wrong rotation:
i

cannot get extinguishers from pre-mapped extinguisher cabinets (works with spawned cabinets though):
GIF

File: UnityProject/Assets/Scripts/UI/UIManager.cs [hunk 2]
```diff
@@ -365,4 +366,76 @@ public static void LinkUISlots()
...
+	}
+
+	private IEnumerator WaitForStrandedVideoEnd()
+	{
+		yield return WaitFor.Seconds(11f);
+		//so we don't freak out the lighting system
+		Camera.main.orthographicSize = originalZoom;
+		//turn everything back on
+		yield return null;
+		SoundManager.PlayAmbience();
```
Comment (fomalsd) [inline UnityProject/Assets/Scripts/UI/UIManager.cs:426]: don't need to play ambience here, it's an end of round

File: UnityProject/Assets/Scripts/Player/PlayerSync.Server.cs [hunk 3]
```diff
@@ -523,7 +522,11 @@ private PlayerState NextStateServer(PlayerState state, PlayerAction action)
 		PlayerState nextState = NextState(state, action, true);
 
 		nextState.Speed = SpeedServer;
-		SoundManager.FootstepAtPosition(nextState.WorldPosition);
+		if (!playerScript.IsGhost)
```
Comment (fomalsd) [inline UnityProject/Assets/Scripts/Player/PlayerSync.Server.cs:525]: lol, did ghosts actually make footstep sounds?

File: UnityProject/Assets/Scripts/Shuttles/MatrixMove.cs [hunk 4]
```diff
@@ -9,314 +9,192 @@
...
 	/// <summary>
 	/// If it is currently fuelled
 	/// </summary>
+	[NonSerialized]
 	public bool IsFueled;
 
 	/// <summary>
 	/// Requires Fuel
 	/// </summary>
+	[NonSerialized]
```
Comment (fomalsd) [inline UnityProject/Assets/Scripts/Shuttles/MatrixMove.cs]: why is it NonSerialized now?
some ships do require fuel and some don't, but `true` should be default

**Review by fomalsd — COMMENTED** [review]
feels good to have these bugs gone, especially grateful for solving that sketchy client movement bug and making MatrixMove less of a mess!

there is a side effect that all the shells are horizontal now, but I guess it can be solved with an extra "random rotation" script or something, and can be addressed later
i
also all shuttles can be controlled without plasma tank attached (aka `RequiresFuel = false`), this is not intended

**Comment by chairbender** [comment]
Ty for review. Another bug I noticed is an exception on picking occupation after round restarts while client was a ghost

File: UnityProject/Assets/Scripts/Player/PlayerSync.Server.cs (hunk 3 above)
Comment (Bod9001) [reply UnityProject/Assets/Scripts/Player/PlayerSync.Server.cs:525]: yeah, Should have a random chance to turn off for a little bit Would be spooky : P

File: UnityProject/Assets/Scripts/Shuttles/MatrixMove.cs (hunk 4 above)
Comment (Bod9001) [reply UnityProject/Assets/Scripts/Shuttles/MatrixMove.cs]: I set it to false in case people were trying to map stuff in and they can't work out why it doesn't want to move

**Comment by Bod9001** [comment]
Is it ready to review?

**Comment by chairbender** [comment]
No, got really sick and couldn't work for a few days

**Comment by Bod9001** [comment]
ok cool no problem
