### PR TITLE
Fixes disposal pipes not getting removed by explosions + Explosion damage balance for pipes

### LINKED ISSUE #4676: Explosions dont remove pipes
~Explosion code doesnt remove disposal pipes or damage players currently.~

Last thing to fix is removing pipes currently they are just disabled(#4738).

### PR DESCRIPTION
**Pull request by MaxIsJoe**
fixes #4676

# Changelog:

CL: [Fix] Fixed an issue with bombs not removing disposal pipes when going off.
CL: [Balance] Disposal and Atmos pipes have received a slight buff in resistance against bombs. disposal pipes require 135 bomb strength to go off now, and gas pipes require 200 instead of 100 for both.

### CODE REVIEW

File: UnityProject/Assets/Scripts/Systems/Explosions/NodeTypes/ExplosionNode.cs [hunk 1]
```diff
@@ -127,6 +110,33 @@ public virtual float DoDamage(Matrix matrix, float DamageDealt, Vector3Int v3int
 			return EnergyExpended;
 		}
 
+		protected void DamageLayers(float DamageDealt, Vector3Int v3int)
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Systems/Explosions/NodeTypes/ExplosionNode.cs]:
```suggestion
		protected void DamageLayers(float damageDealt, Vector3Int position)
```
You are turning into Bod

File: UnityProject/Assets/Scripts/Systems/Explosions/NodeTypes/ExplosionNode.cs [hunk 2]
```diff
@@ -127,6 +110,33 @@ public virtual float DoDamage(Matrix matrix, float DamageDealt, Vector3Int v3int
...
+		{
+			if (DamageDealt < 100) return;
+			var Node = matrix.GetMetaDataNode(v3int);
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Systems/Explosions/NodeTypes/ExplosionNode.cs]:
```suggestion
			var node = matrix.GetMetaDataNode(v3int);
```

File: UnityProject/Assets/Scripts/Systems/Explosions/NodeTypes/ExplosionNode.cs (hunk 1 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Systems/Explosions/NodeTypes/ExplosionNode.cs]: I just copy pasted those tbh

File: UnityProject/Assets/Scripts/Systems/Explosions/NodeTypes/ExplosionNode.cs [hunk 3]
```diff
@@ -127,6 +110,33 @@ public virtual float DoDamage(Matrix matrix, float DamageDealt, Vector3Int v3int
...
+			if (Node == null) return;
+			foreach (var electricalData in Node.ElectricalData)
+			{
+				electricalData.InData.DestroyThisPlease();
+			}
+			if (DamageDealt > 135)
+			{
+				foreach (var disposalPipe in Node.DisposalPipeData)
+				{
+					matrix.TileChangeManager.MetaTileMap.RemoveTileWithlayer(disposalPipe.NodeLocation, LayerType.Disposals);
```
Comment (NoooneyDude) [inline UnityProject/Assets/Scripts/Systems/Explosions/NodeTypes/ExplosionNode.cs:126]: Any future plans to spawn broken pipe ends / detached pipe objects?

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Systems/Explosions/NodeTypes/ExplosionNode.cs:126]: does it spawn pipes in ss13? Because I don't recall any items getting dropped when bombs tear through the station.

File: UnityProject/Assets/Scripts/Systems/Explosions/NodeTypes/ExplosionNode.cs (hunk 1 above)
Comment (Bod9001) [reply UnityProject/Assets/Scripts/Systems/Explosions/NodeTypes/ExplosionNode.cs]: oh no the Fox curse : P
