### PR TITLE
Directional Ghost Sprites

### LINKED ISSUE #1275: Add Ghosts directional sprites
# Description

## Category
Feature

## Detailed Bug Report
Currently, there is only one sprite for ghosts moving around, independent of direction.
The others should be added too.

### PR DESCRIPTION
**Pull request by Nader7**
### Purpose
Added directional ghost sprites when moving and clicking a direction
Fixes #1275 

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [x]  This PR has been tested in multiplayer

### CODE REVIEW

File: UnityProject/Assets/Scripts/PlayGroups/PlayerSprites.cs [hunk 1]
```diff
@@ -17,12 +17,32 @@ public class PlayerSprites : NetworkBehaviour
...
+
+			if (s.name == "mob_269")
+				ghostSprites.Add(Orientation.Up, s);
+
+			if (s.name == "mob_270")
+				ghostSprites.Add(Orientation.Right, s);
+
+			if (s.name == "mob_271")
+				ghostSprites.Add(Orientation.Left, s);
+		}
```
Comment (DooblyNoobly) [inline UnityProject/Assets/Scripts/PlayGroups/PlayerSprites.cs]: Consider doing this instead to save on load up time if there is going to be a lot of players in the game:
```cs
ghostSprites.Add(Orientation.Down, SpriteManager.PlayerSprites["mob"][268]);
ghostSprites.Add(Orientation.Up, SpriteManager.PlayerSprites["mob"][269]);
ghostSprites.Add(Orientation.Right, SpriteManager.PlayerSprites["mob"][270]);
ghostSprites.Add(Orientation.Left, SpriteManager.PlayerSprites["mob"][271]);
```

**Review by DooblyNoobly — CHANGES_REQUESTED** [review]

**Comment by Nader7** [comment]
Just changed it, thanks, dont know why that didnt occur to me

**Comment by DooblyNoobly** [comment]
cool testing now
