### PR TITLE
Fixes MassDriver

### LINKED ISSUE #8867: Eject Trash on space
**Environment**

**- Game Version:** 22-06-17-04
**- OS Version:** Lubuntu 18.04.6x64
**- Linux version**  `5.17.0-14.1-liquorix-amd64 (steven@liquorix.net) (gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, GNU ld (GNU Binutils for Ubuntu) 2.30) #1 ZEN SMP PREEMPT liquorix 5.17-18ubuntu1~bionic (2022-06-10)`
**- Server:** EU

**Detailed description of bug**
**Context**
Head Officer, in FallStation, eject area at west

**Manipulation**
- See trash on belt
- Push the lever
- See the trash move to "exit"
- Open Shulter door
- Push "eject button"

**Result**
Nothing

**Expected**
See your trash and body part floated towards the vacuum of space.

### PR DESCRIPTION
**Pull request by Silver-8ce**
### Purpose
Fixes #8867

### Changelog:
 CL: [Fix] The Mass Driver once again throws trash into space.

### CODE REVIEW

File: UnityProject/Assets/Scripts/Objects/Machines/MassDriver.cs [hunk 1]
```diff
@@ -147,7 +147,7 @@ private void ThrowItem(UniversalObjectPhysics item, Vector3 throwVector)
 			Vector3 vector = item.transform.rotation * throwVector;
 			UniversalObjectPhysics itemTransform = item.GetComponent<UniversalObjectPhysics>();
 			if (itemTransform == null) return;
-			itemTransform.NewtonianPush(vector, 1, inAim:BodyPartType.Chest ,inThrownBy : gameObject );
+			itemTransform.NewtonianPush(vector, 30, inAim:BodyPartType.Chest ,inThrownBy : gameObject );
```
Comment (ThatDan123) [inline UnityProject/Assets/Scripts/Objects/Machines/MassDriver.cs:150]: Might wanna increase at lines 156 and 164 too?

Comment (Silver-8ce) [reply UnityProject/Assets/Scripts/Objects/Machines/MassDriver.cs:150]: Sounds good

**Review by ThatDan123 — APPROVED** [review]
