### PR TITLE
Fixed soap scrubbing on occupied tiles by adding checks.

### LINKED ISSUE #7411: Soap can scrub floor through table and other objects
### Environment
- Game Version: UnityStationDevelop-21091418

### Steps to reproduce

1. Pick up soap
2. Click on table
3. Click on office chair
4. Click on lightbulb
5. Click on window tile
6. Click on yourself/other character

### PR DESCRIPTION
**Pull request by apohlman23**
### Purpose
 <br>

Fixes #7411, that is soap being able to scrub through tables and other objects.

### Notes:

Edited the Soap.cs file, adding checks in the WillInteract function to determine when the soap could be used for scrubbing. Added checks to see if an object was in the way of scrubbing the tile, and added a check to see if the tile to interact with was actually a floor, as opposed to a table tile.

### Changelog:

CL: [Fix] Fixed where players could use soap to scrub through tables and other objects by implementing the appropriate checks.

### CODE REVIEW

File: UnityProject/Assets/Scripts/Items/Tool/Soap.cs [hunk 1]
```diff
@@ -33,6 +33,24 @@ public bool WillInteract(PositionalHandApply interaction, NetworkSide side)
...
+            // Check if there is an object in the way of scrubbing the tile
+			var atPosition = MatrixManager.GetAt<RegisterTile>(positionInt, true);
+            if(atPosition.Count != 0) return false;
+
+
+            // Check that the layer scrubbed is a floor, e.g. not a table
+            var metaTileMap = MatrixManager.AtPoint(positionInt, false).MetaTileMap;
+            var tile = metaTileMap.GetTile(metaTileMap.WorldToCell(positionInt), true);
+
+            if (tile != null && tile.LayerType != LayerType.Floors)
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/Items/Tool/Soap.cs:49]: MatrixManager.AtPoint(positionInt, false)

Comment (Bod9001) [inline UnityProject/Assets/Scripts/Items/Tool/Soap.cs]: isn't soap needed on walls to get rid of graffiti?

File: UnityProject/Assets/Scripts/Items/Tool/Soap.cs [hunk 2]
```diff
@@ -33,6 +33,24 @@ public bool WillInteract(PositionalHandApply interaction, NetworkSide side)
 			//can only scrub tiles, for now
 			if (!Validations.HasComponent<InteractableTiles>(interaction.TargetObject)) return false;
 
+            // Get position of interaction as Vector3Int
+            Vector3 position = interaction.WorldPositionTarget;
+            Vector3Int positionInt = Vector3Int.RoundToInt(position);
+
+            // Check if there is an object in the way of scrubbing the tile
+			var atPosition = MatrixManager.GetAt<RegisterTile>(positionInt, true);
```
Comment (ThatDan123) [inline UnityProject/Assets/Scripts/Items/Tool/Soap.cs]: This will block if theres items on the floor, might be better to use `RegisterObject` instead?

File: UnityProject/Assets/Scripts/Items/Tool/Soap.cs [hunk 3]
```diff
@@ -33,6 +33,24 @@ public bool WillInteract(PositionalHandApply interaction, NetworkSide side)
...
+            if(atPosition.Count != 0) return false;
+
+
+            // Check that the layer scrubbed is a floor, e.g. not a table
+            var metaTileMap = MatrixManager.AtPoint(positionInt, false).MetaTileMap;
```
Comment (ThatDan123) [inline UnityProject/Assets/Scripts/Items/Tool/Soap.cs]:
```suggestion
            var metaTileMap = MatrixManager.AtPoint(positionInt, side == NetworkSide.Server).MetaTileMap;
```

**Review by NoooneyDude — DISMISSED** [review]
I suspect this means you can't scrub the floor in an open airlock. That's alright though. We need to add a property somewhere to determine whether an object should block access to the floor (so you can still wrench stuff down in an open airlock e.g. but not when closed).

File: UnityProject/Assets/Scripts/Items/Tool/Soap.cs [hunk 4]
```diff
@@ -33,6 +33,24 @@ public bool WillInteract(PositionalHandApply interaction, NetworkSide side)
 			//can only scrub tiles, for now
 			if (!Validations.HasComponent<InteractableTiles>(interaction.TargetObject)) return false;
 
+            // Get position of interaction as Vector3Int
+            Vector3 position = interaction.WorldPositionTarget;
+            Vector3Int positionInt = Vector3Int.RoundToInt(position);
+
+            // Check if there is an object in the way of scrubbing the tile
+			var atPosition = MatrixManager.GetAt<RegisterObject>(positionInt, true);
```
Comment (ThatDan123) [inline UnityProject/Assets/Scripts/Items/Tool/Soap.cs]:
```suggestion
			var atPosition = MatrixManager.GetAt<RegisterObject>(positionInt, side == NetworkSide.Server);
```
Sorry I missed that one

**Review by Bod9001 — APPROVED** [review]

**Review by ThatDan123 — APPROVED** [review]
