### PR TITLE
Fixes doors not getting their catalogues synced

### LINKED ISSUE #9123: Door flickering when painted only happens on staging on rare occasions
It doesn't always happen but only on staging you'll find that painting an airlock with an airlock painter causes the doors to switch between the old and new sprites when an animation happens.
~~This is hard to replicate,~~ but when it happens once, it happens consistently on all doors.

EDIT : 
This apparently is more common on staging than on another server you are hosting and much more easier to replicate there.

### PR DESCRIPTION
**Pull request by MaxIsJoe**
fixes #9123

## Changelog:

CL: [Fix] - Doors should no longer flicker between the old and new sprites when painted.

### CODE REVIEW

**Review by NoooneyDude — CHANGES_REQUESTED** [review]
Awaiting changes as discussed in Discord (`GetInstanceID()`)

File: UnityProject/Assets/Scripts/Items/Tool/AirlockPainter.cs [hunk 1]
```diff
@@ -109,14 +110,8 @@ public void ServerPaintTheAirlock(GameObject paintableAirlock, GameObject perfor
...
-			DoorAnimatorV2 airlockAnim = paintableAirlock.GetComponent<DoorAnimatorV2>();
-
-			ServerChangeDoorBase(airlockAnim, paintJob);
-			ServerChangeOverlaySparks(airlockAnim, paintJob);
-			ServerChangeOverlayLights(airlockAnim, paintJob);
-			ServerChangeOverlayFill(airlockAnim, paintJob);
-			ServerChangeOverlayWeld(airlockAnim, paintJob);
-			ServerChangeOverlayHacking(airlockAnim, paintJob);
+			AirlockCatalogueSync airlockAnim = paintableAirlock.GetComponent<AirlockCatalogueSync>();
+			airlockAnim.index = currentPaintJobIndex;
```
Comment (NoooneyDude) [inline UnityProject/Assets/Scripts/Items/Tool/AirlockPainter.cs]: I think this would be better served as a method, that way it is more obvious to other developers that there is a cost to using this - that it does more than just setting a value.

File: UnityProject/Assets/Scripts/Core/Sprite Handler/AirlockCatalogueSync.cs [hunk 2]
```diff
@@ -0,0 +1,90 @@
+using System;
+using System.Collections.Generic;
+using Doors;
+using Mirror;
+using UnityEngine;
+
+namespace Core.Sprite_Handler
```
Comment (NoooneyDude) [inline UnityProject/Assets/Scripts/Core/Sprite Handler/AirlockCatalogueSync.cs]: As this is specific to airlocks I would suggest putting it under that folder - perhaps wherever `DoorAnimatorV2` is?

File: UnityProject/Assets/Scripts/Core/Sprite Handler/AirlockCatalogueSync.cs [hunk 3]
```diff
@@ -25,18 +25,28 @@ private void Awake()
...
-			ServerChangeOverlayLights(animatorV2, paintOptions[newValue].GetComponent<DoorAnimatorV2>());
-			ServerChangeOverlayFill(animatorV2, paintOptions[newValue].GetComponent<DoorAnimatorV2>());
-			ServerChangeOverlayWeld(animatorV2, paintOptions[newValue].GetComponent<DoorAnimatorV2>());
-			ServerChangeOverlayHacking(animatorV2, paintOptions[newValue].GetComponent<DoorAnimatorV2>());
+			ServerChangeDoorBase(animatorV2, paintOptions[index].GetComponent<DoorAnimatorV2>());
+			ServerChangeOverlaySparks(animatorV2, paintOptions[index].GetComponent<DoorAnimatorV2>());
+			ServerChangeOverlayLights(animatorV2, paintOptions[index].GetComponent<DoorAnimatorV2>());
+			ServerChangeOverlayFill(animatorV2, paintOptions[index].GetComponent<DoorAnimatorV2>());
+			ServerChangeOverlayWeld(animatorV2, paintOptions[index].GetComponent<DoorAnimatorV2>());
+			ServerChangeOverlayHacking(animatorV2, paintOptions[index].GetComponent<DoorAnimatorV2>());
```
Comment (NoooneyDude) [inline UnityProject/Assets/Scripts/Core/Sprite Handler/AirlockCatalogueSync.cs]: I'd suggest caching this list fetch, then a null check right after in case someone removes one of the door prefabs but doesn't update the list

**Comment by Copern** [comment]
You have two AirlockCatalogueSync's on the _AirlockBase prefab. The recent/last one is setup properly, the first/old one is missing the references. That's probably what is causing issues.

**Comment by MaxIsJoe** [comment]
This is done

**Comment by corp-0** [comment]
can you fix the codacy issues?

**Comment by MaxIsJoe** [comment]
> can you fix the codacy issues?

Done

**Comment by corp-0** [comment]
you forgot to push, likely

**Comment by MaxIsJoe** [comment]
pushed

**Comment by MaxIsJoe** [comment]
what else is needed here? codacy issues has been solved and everything has been tested

**Review by NoooneyDude — APPROVED** [review]
