### PR TITLE
[Critical Fix] - Fixes game no longer generating ores

### LINKED ISSUE #8710: Ores are no longer generating
Pretty self explanatory but ores are no longer generating on lavaland or asteroids.

### PR DESCRIPTION
**Pull request by MaxIsJoe**
Fixes #8710

## Notes :

- **NEVER USE HARDCODED STRINGS FOR SEARCHING FOR ANYTHING BECAUSE THEY WILL CHANGE SOMETIME IN THE FUTURE WITHER YOU LIKE THAT OR NOT**
- I've moved calls to the `IServerSpawn` interface because from my last few PRs in the past few months i've learned the hard way that functions that are meant only for the server usually just cause issues when they're on Awake or Start even if a check from the custom net manager thingy is placed.

# Changelog:

CL: [Fix] - Fixed ore generation on lavaland and asteroids.

### CODE REVIEW

File: UnityProject/Assets/Scripts/Map/LavaLand/LavaLandRandomGenScript.cs [hunk 1]
```diff
@@ -38,7 +38,7 @@ public class LavaLandRandomGenScript : MonoBehaviour
 		[SerializeField]
 		private RandomItemSpot mobPools = null;
 
-		private void Start()
+		private void Awake()
```
Comment (NoooneyDude) [inline UnityProject/Assets/Scripts/Map/LavaLand/LavaLandRandomGenScript.cs]: Is it guaranteed that LavaLandManager's Awake is called prior to this one? Seems fragile to me.

File: UnityProject/Assets/Scripts/Systems/Ore Generation/OreGenerator.cs [hunk 2]
```diff
@@ -122,7 +113,7 @@ private void NodeScatter(Vector3Int location, OreProbability materialSpecified)
 			var chosenLocation = locations[RANDOM.Next(locations.Count)];
 			var ranLocation = chosenLocation + DIRECTIONS[RANDOM.Next(DIRECTIONS.Count)];
 			var tile = metaTileMap.GetTile(ranLocation);
-			if (tile != null && tile.name.Contains("rock_wall"))
+			if (tile != null)
```
Comment (NoooneyDude) [inline UnityProject/Assets/Scripts/Systems/Ore Generation/OreGenerator.cs:116]: A tile adjacent to a mineable tile might not be mineable.

**Comment by NoooneyDude** [comment]
This will mean ore can spawn in any tile of type wall, which isn't great.

File: UnityProject/Assets/Scripts/Map/LavaLand/LavaLandRandomGenScript.cs (hunk 1 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Map/LavaLand/LavaLandRandomGenScript.cs]: You should always use `Awake()` for initializing data in unity and `Start()` for running things that affect the prefab or other game objects.
Also we use `Awake()` everywhere in the project so if it starts causing trouble now that means there's a million other scripts that are also fragile.

**Comment by MaxIsJoe** [comment]
> This will mean ore can spawn in any tile of type wall, which isn't great.

Take a look a few lines ~~below~~ above that

File: UnityProject/Assets/Scripts/Map/LavaLand/LavaLandRandomGenScript.cs (hunk 1 above)
Comment (NoooneyDude) [reply UnityProject/Assets/Scripts/Map/LavaLand/LavaLandRandomGenScript.cs]: Look carefully at LavaLandManager. It uses Awake() too (via parent), in order to instantiate the singleton. Therefore, there might be possibility that this script awakes before the manager awakes (probably hierarchy or scene-dependent) and so we'd get an NRE. That's why this particular case looks fragile - because it depends on load order.

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Map/LavaLand/LavaLandRandomGenScript.cs]: Changed

**Review by Bod9001 — APPROVED** [review]
