### PR TITLE
Reimplements breathing toxic gasses damaging you

### LINKED ISSUE #7483: Plasma inhalation toxin damage needs to be reimplemented
### Environment
- Game Version: Staging Latest
- OS Version: Arch linux

### Detailed description of bug

as the title says plasma gas doesn't cause lung damage anymore
example:

https://user-images.githubusercontent.com/80334192/135127331-bf6bbb33-6d62-475c-b0c8-8d2953b66a36.mp4

### Steps to reproduce

1. breathe in a plasma gas filled room

### PR DESCRIPTION
**Pull request by MaxIsJoe**
fixes #7483

### Notes 
This re-implements the old logic and tries to simplify it and make it condensed and modular
This does not reimplement chat messages or /tg/'s weird hardcoded 90% miss 
In the next PR I'll add chat messages ~~and _maybe_ toxin immunity for races that can breath toxic gases like plasma.~~

CL: [Improvement] Reimplements breathing toxic gasses damaging you

### CODE REVIEW

**Comment by MaxIsJoe** [comment]
Also yes, gas masks work.

**Review by NoooneyDude — DISMISSED** [review]

File: UnityProject/Assets/Scripts/HealthV2/Living/Respiration/RespiratorySystemBase.cs [hunk 1]
```diff
@@ -158,6 +163,27 @@ public GasContainer GetInternalGasMix()
 			return null;
 		}
 
+		/// <summary>
+		/// Checks for toxic gases and if they excede their maximum range before they become deadly
+		/// </summary>
+		/// <param name="gasMix">the gases the character is breathing in</param>
+		/// <param name="gasType">what type of toxic gas we should check?</param>
+		public void ToxinBreathinCheck(GasMix gasMix, GasSO gasType)
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/HealthV2/Living/Respiration/RespiratorySystemBase.cs]: this should be re-implemented as a metabolic reaction, since that's what poisons and stuff uses

**Comment by Bod9001** [comment]
BodyHealthEffect  SO should be the one you're looking for, note does require adding to the reaction set on the body parts is a little bit fiddly

File: UnityProject/Assets/Scripts/HealthV2/Living/Respiration/RespiratorySystemBase.cs (hunk 1 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/HealthV2/Living/Respiration/RespiratorySystemBase.cs]: > Metabolic

that's related to digestion, not respiratory.

File: UnityProject/Assets/Scripts/HealthV2/Living/Respiration/RespiratorySystemBase.cs [hunk 2]
```diff
@@ -32,6 +33,10 @@ public class RespiratorySystemBase : MonoBehaviour
 		public float pressure => healthStateController.Pressure;
 
 
+		private const float PLASMA_SAFE_MAX = 0.4F; //maximum amount of plasma in the air before it starts killing you
+		private const float CARBON_DIOXIDE_SAFE_MAX = 10; //maximum amount of CO2 in the air before it starts killing you
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/HealthV2/Living/Respiration/RespiratorySystemBase.cs]: this is the stuff I was saying in discord. These constants are only valid for Human biology, it makes no sense for it to be ``in RespiratorySystemBase``

File: UnityProject/Assets/Scripts/HealthV2/Living/Respiration/RespiratorySystemBase.cs [hunk 3]
```diff
@@ -158,6 +163,27 @@ public GasContainer GetInternalGasMix()
...
 
+		/// <summary>
+		/// Checks for toxic gases and if they excede their maximum range before they become deadly
+		/// </summary>
+		/// <param name="gasMix">the gases the character is breathing in</param>
+		/// <param name="gasType">what type of toxic gas we should check?</param>
+		public void ToxinBreathinCheck(GasMix gasMix, GasSO gasType)
+		{
+			if(CanBreathAnywhere || playerScript == null) return;
+			if(playerScript.Equipment.IsInternalsEnabled) return;
```
Comment (ThatDan123) [inline UnityProject/Assets/Scripts/HealthV2/Living/Respiration/RespiratorySystemBase.cs]: Are you sure breathGasMix cant be the internals tank gas mix as well as the environment? 

(i'm not sure how that works, so look for where BreatheIn() in lungs is called)

File: UnityProject/Assets/Scripts/HealthV2/Living/Respiration/RespiratorySystemBase.cs (hunk 2 above)
Comment (ThatDan123) [reply UnityProject/Assets/Scripts/HealthV2/Living/Respiration/RespiratorySystemBase.cs]: Yeah, think this would be better on lungs and then have serialised lists of bad gases and their safe levels.

File: UnityProject/Assets/Scripts/HealthV2/Living/Respiration/RespiratorySystemBase.cs (hunk 1 above)
Comment (Bod9001) [reply UnityProject/Assets/Scripts/HealthV2/Living/Respiration/RespiratorySystemBase.cs]: The idea would be that you take toxin damage on your organs versus your lungs,
so, you ingest it through the air and then it attacks your organs

Comment (PerfectTangent) [reply UnityProject/Assets/Scripts/HealthV2/Living/Respiration/RespiratorySystemBase.cs]: it seems just as plausible if not moreso that it would damage the lungs because it's an organically corrosive chemical

Comment (Bod9001) [reply UnityProject/Assets/Scripts/HealthV2/Living/Respiration/RespiratorySystemBase.cs]: it would add more gameplay depth If it was a toxin though,  since if you ate it it would also give you poisoning but it wouldn't with this solution

Comment (Bod9001) [reply UnityProject/Assets/Scripts/HealthV2/Living/Respiration/RespiratorySystemBase.cs]: like, with how the lungs work there is already plasma going round the blood there's just no reaction for it yet

Comment (corp-0) [reply UnityProject/Assets/Scripts/HealthV2/Living/Respiration/RespiratorySystemBase.cs]: I think it should apply an illness so it can do whatever the gas does on your body over time, including damaging organs and symptoms.

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/HealthV2/Living/Respiration/RespiratorySystemBase.cs]: Quick reminder I'm re-implementing old logic that was removed. I'm not trying to add something new or overhaul anything.

I'm not gonna add new behavior or functionality or anything like that because that's not what this PR is for.

Comment (corp-0) [reply UnityProject/Assets/Scripts/HealthV2/Living/Respiration/RespiratorySystemBase.cs]: Well this PR can't be merged as is because as I said on Discord, this implementation was always meant to be a temporary thing that would only work until the health rework

File: UnityProject/Assets/Scripts/HealthV2/Living/Respiration/RespiratorySystemBase.cs (hunk 2 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/HealthV2/Living/Respiration/RespiratorySystemBase.cs]: done

File: UnityProject/Assets/Scripts/HealthV2/Living/Respiration/RespiratorySystemBase.cs (hunk 3 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/HealthV2/Living/Respiration/RespiratorySystemBase.cs]: I'll be honest, I have no idea but `IsInternalsEnabled` get things working as intended.

File: UnityProject/Assets/Scripts/HealthV2/Living/Respiration/RespiratorySystemBase.cs (hunk 1 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/HealthV2/Living/Respiration/RespiratorySystemBase.cs]: Do I get to resolve this conversation or is there something else?

File: UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs [hunk 4]
```diff
@@ -293,4 +317,13 @@ private IEnumerator<WaitForSeconds> CooldownTick()
         yield return new WaitForSeconds(internalBleedingCooldown);
         onCooldown = false;
     }
+
+    [Serializable]
+    class ToxicGases
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs]:
```suggestion
    class ToxicGas
```
Each of these represent a single entry

File: UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs [hunk 5]
```diff
@@ -23,6 +23,8 @@ public class Lungs : Organ
 	[Tooltip("The minimum pressure needed to avoid suffocation")]
 	[SerializeField] private float pressureSafeMin = 16;
 
+	[SerializeField] private List<ToxicGases> toxicGasesToLung;
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs]: the ``ToLung`` part sounds weird. I think just ``toxicGases`` is good

File: UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs [hunk 6]
```diff
@@ -257,6 +261,26 @@ private bool BreatheIn(GasMix breathGasMix, ReagentMix blood, float efficiency)
 		return toInhale.Total > 0;
 	}
 
+	/// <summary>
+    /// Checks for toxic gases and if they excede their maximum range before they become deadly
+    /// </summary>
+    /// <param name="gasMix">the gases the character is breathing in</param>
+    /// <param name="gasType">what type of toxic gas we should check?</param>
+    public virtual void ToxinBreathinCheck(GasMix gasMix)
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs]: this method should receive a ``ToxicGas`` as parameter instead. Also remember to modify what calls this method to iterate the list of toxic gases,

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs]: why? we're checking what's in the gases we're breathing in inside this function.
you're asking me to hardcode gas checks by only supplying the parameter of what we want to check via code rather than the list we build in the inspector

**Comment by corp-0** [comment]
things that can improve this PR: 
- Maybe convert toxic gases to a scriptable object
- Include simple symptoms (coughing, smelling, sore throat)

For now, I think this is good enough to be merged.

**Review by corp-0 — DISMISSED** [review]

**Comment by MaxIsJoe** [comment]
Codacy is smoking something

**Comment by VernaSaurus** [comment]
codacy is always smoking something

**Comment by MaxIsJoe** [comment]
Someone approve this, Codacy is just dumb.

**Comment by NoooneyDude** [comment]
> Someone approve this, Codacy is just dumb.

You can assign `default` for serialized fields. Shuts up both compiler warnings and Codacy.

File: UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs [hunk 7]
```diff
@@ -257,6 +261,26 @@ private bool BreatheIn(GasMix breathGasMix, ReagentMix blood, float efficiency)
 		return toInhale.Total > 0;
 	}
 
+	/// <summary>
+    /// Checks for toxic gases and if they excede their maximum range before they become deadly
+    /// </summary>
+    /// <param name="gasMix">the gases the character is breathing in</param>
+    /// <param name="gasType">what type of toxic gas we should check?</param>
```
Comment (NoooneyDude) [inline UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs]:
```suggestion
```

File: UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs [hunk 8]
```diff
@@ -257,6 +261,26 @@ private bool BreatheIn(GasMix breathGasMix, ReagentMix blood, float efficiency)
...
+    public virtual void ToxinBreathinCheck(GasMix gasMix)
+    {
+    	if(RelatedPart.HealthMaster.RespiratorySystem.CanBreathAnywhere || RelatedPart.HealthMaster.playerScript == null) return;
+        if(RelatedPart.HealthMaster.playerScript.Equipment.IsInternalsEnabled) return;
+
+        foreach (ToxicGas gas in toxicGases)
+        {
+	        float pressure = gasMix.GetPressure(gas.GasType);
```
Comment (NoooneyDude) [inline UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs]: Tabs please ; (

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs]: no matter what software i use, i can't escape pressing tab somehow turns into just spaces

**Comment by MaxIsJoe** [comment]
I will beat codacy up

**Review by NoooneyDude — APPROVED** [review]

**Review by corp-0 — APPROVED** [review]
