### PR TITLE
Randomizing door hacking nodes both between rounds and between door types (Security vs Atmos, vs Command, etc.)

### LINKED ISSUE #4278: Hacking: connections don't get randomised until hard reset
If someone figures out how to open doors via hacking, they can keep doing it across rounds until hard reset

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Successfully hack a door once
2.  Wait for next round
3.  Try the same wire combo

### LINKED ISSUE #4595: Improving Door Hacking
## Description
Door Hacking is currently too OP
And there're some features that would help balance it

### Features
- [ ] proper door randomization (see issue #4278)
- [ ] maintenance interfaces differing across doors with different accesses (sec door having a different node setup than the chef's doors)*
*different node setup meaning that the same I/O wire that works to open the chef's door can't be used to open a sec door

### PR DESCRIPTION
**Pull request by coolcat1711**
### Purpose
Fixes #4278 
Fixes #4595 

Randomizes door hacking nodes between rounds and among door types.

### Notes:
Next steps to improve hacking would probably be to visually represent the base state for each panel so it can be repaired easily after someone messes with it.

### CODE REVIEW

**Comment by corp-0** [comment]
> Next steps to improve hacking would probably be to visually represent the base state for each panel so it can be repaired easily after someone messes with it.

for any improvements on door interactions, wait until #5030 is merged, please.

File: UnityProject/Assets/Scripts/Hacking/HackingProcesses/HackingProcessDoorSimple.cs [hunk 1]
```diff
@@ -109,9 +113,71 @@ public override void ServerPerformInteraction(HandApply interaction)
 		}
 	}
 
-	public void Shuffle(List<HackingNodeInfo> list)
+	private static bool serverEndRoundHackingResetSetup = false;
+	private static void ServerRegisterHackingReset()
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Hacking/HackingProcesses/HackingProcessDoorSimple.cs:117]: where is this called?

File: UnityProject/Assets/Scripts/Hacking/HackingProcesses/HackingProcessDoorSimple.cs [hunk 2]
```diff
@@ -125,8 +191,10 @@ public void Shuffle(List<HackingNodeInfo> list)
 
 	public override void ServerGenerateNodesFromNodeInfo()
 	{
+		if (serverEndRoundHackingResetSetup == false) ServerRegisterHackingReset();
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Hacking/HackingProcesses/HackingProcessDoorSimple.cs]: found it. Do it inside brackets and in a new line so it is easier to see at a glance.

**Comment by corp-0** [comment]
aight, let's give it a try in staging
