### PR TITLE
Fixes character customization screen being broken

### LINKED ISSUE #9440: [BUG] Character Selection and Creation Menus are Extremely Broken
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

22121218

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

Species selection in the character creation screen is fucked. Some sprites do not have most body parts drawn, only humans and felinids seem to work correctly. A number of species names in the selector appear to be "felinid" instead of what they should be as well.

Pre-existing characters with one of the broken species fail to load a preview image, show in the first 
attached image. Other attached images are from cycling through every species option.

Final image shows what happened after attempting to exit the menu by pressing "cancel", it failed.

Screenshot (1808)
Screenshot (1800)
Screenshot (1801)
Screenshot (1802)
Screenshot (1803)
Screenshot (1804)
Screenshot (1805)
Screenshot (1806)
Screenshot (1807)

### What should have happened instead?

Species selection should actually work. Ashwalker shouldn't be an option (that's also a long-standing issue, I think?). Menu should close when you click "cancel".

### Steps to reproduce the issue

1: Launch game.
2: Go to character selector.
2a: If you already have a non-human or non-felinid character made, select them an observe that it's broken.
3: Create a new character.
4: Cycle through the species options.
5: Attempt to close menu through "cancel" button.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MaxIsJoe**
closes  #9440

CL: [Fix] Fixes character customization/selection screen being broken due to alien organs and species that were not meant to appear there to begin with.

### CODE REVIEW

File: UnityProject/Assets/Scripts/UI/Systems/Lobby/CharacterCustomization.cs [hunk 1]
```diff
@@ -858,7 +892,7 @@ public void SetDropDownBody(ObjectList GameObjectBody)
 			}
 		}
 
-		public void SubSetBodyPart(BodyPart bodyPart, string path)
+		private void SubSetBodyPart([NotNull] BodyPart bodyPart, [NotNull] string path)
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/UI/Systems/Lobby/CharacterCustomization.cs]: the ``NotNull`` attribute means that this can't be null so there is no need to null check it inside the method body, isn't that the case? If so, you should remove the attribute.

File: UnityProject/Assets/Scripts/UI/Systems/Lobby/CharacterCustomization.cs [hunk 2]
```diff
@@ -1094,11 +1134,16 @@ public void SubSaveBodyPart(BodyPart bodyPart, string path)
 			}
 
 
-			if (bodyPart?.OrganStorage?.Populater?.DeprecatedContents != null)
+			if (bodyPart != null && bodyPart.OrganStorage?.Populater?.DeprecatedContents != null)
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/UI/Systems/Lobby/CharacterCustomization.cs]: the first ``!= null`` isn't needed. The Elvis operator did already what you are doing here.

File: UnityProject/Assets/Scripts/UI/Systems/Lobby/CharacterCustomization.cs [hunk 3]
```diff
@@ -879,11 +913,16 @@ public void SubSetBodyPart(BodyPart bodyPart, string path)
 				}
 			}
 
-			if (bodyPart?.OrganStorage?.Populater?.DeprecatedContents != null)
+			if (bodyPart != null && bodyPart.OrganStorage?.Populater?.DeprecatedContents != null)
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/UI/Systems/Lobby/CharacterCustomization.cs]: same here, why did you add the extra ``!= null`` ?

File: UnityProject/Assets/Scripts/UI/Systems/Lobby/CharacterCustomization.cs [hunk 4]
```diff
@@ -472,66 +491,81 @@ public void SetUpBodyPart(BodyPart bodyPart, bool InstantiateCustomisations = tr
...
-			if (Sprites != null)
+			try
 			{
-				if (Sprites?.Item1?.Orders == null || Sprites.Item1.Orders.Count == 0)
-				{
-					Logger.LogError("Rendering order not specified on " + bodyPart.name, Category.Character);
-				}
+				Sprites = bodyPart.GetBodyTypeSprites(ThisBodyType.bodyType); //Get the correct one
+			}
+			catch (Exception e)
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/UI/Systems/Lobby/CharacterCustomization.cs:529]: it is always best to catch the specific Exception you are expecting that could happen here.

File: UnityProject/Assets/Prefabs/Player/Resources/BodyParts/Lizard/Ashwalker.asset [hunk 5]
```diff
@@ -13,8 +13,6 @@ MonoBehaviour:
   m_Name: Ashwalker
   m_EditorClassIdentifier: 
   Base:
-    BrainPrefab: {fileID: 3442747058158572537, guid: 1e19c4562afbbd2479d14830399db738,
```
Comment (corp-0) [inline UnityProject/Assets/Prefabs/Player/Resources/BodyParts/Lizard/Ashwalker.asset]: do the 3 roles here still spawn with a brain after doing this?

File: UnityProject/Assets/Scripts/UI/Systems/Lobby/CharacterCustomization.cs (hunk 1 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/UI/Systems/Lobby/CharacterCustomization.cs]: Rider added this for me, going to change it

File: UnityProject/Assets/Scripts/UI/Systems/Lobby/CharacterCustomization.cs (hunk 2 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/UI/Systems/Lobby/CharacterCustomization.cs]: Rider complains about the ? operator on the body part because Unity doesn't like that on gameobjects

File: UnityProject/Assets/Scripts/UI/Systems/Lobby/CharacterCustomization.cs (hunk 4 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/UI/Systems/Lobby/CharacterCustomization.cs:529]: Shouldn't a log be enough?

File: UnityProject/Assets/Scripts/UI/Systems/Lobby/CharacterCustomization.cs (hunk 2 above)
Comment (corp-0) [reply UnityProject/Assets/Scripts/UI/Systems/Lobby/CharacterCustomization.cs]: For objects that extend UnityObject (Game object, components, etc), you use OrNull()  before the Elvis.

File: UnityProject/Assets/Prefabs/Player/Resources/BodyParts/Lizard/Ashwalker.asset (hunk 5 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Prefabs/Player/Resources/BodyParts/Lizard/Ashwalker.asset]: I didn't remove any brain prefabs wtf
going to see whats wrong with this

Comment (MaxIsJoe) [reply UnityProject/Assets/Prefabs/Player/Resources/BodyParts/Lizard/Ashwalker.asset]: still works just fine

**Comment by MaxIsJoe** [comment]
hewwo pls weview again pwease uwu

**Comment by corp-0** [comment]
I'd like Bod to give it a look

File: UnityProject/Assets/Scripts/Items/Implants/Organs/Eye.cs [hunk 6]
```diff
@@ -1,210 +1,208 @@
...
-	}
-
-
-	[NaughtyAttributes.Button()]
-	public void MakeBlind()
-	{
-		SyncBlindness(false, false);
-	}
+		[NaughtyAttributes.Button()]
+		public void GiveSite()
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Items/Implants/Organs/Eye.cs:72]:
```suggestion
		public void GiveSight()
```

File: UnityProject/Assets/Scripts/UI/Systems/Lobby/CharacterCustomization.cs [hunk 7]
```diff
@@ -381,36 +397,31 @@ private void LoadSettings(CharacterSheet inCharacterSettings)
...
 		}
 
-		public void InitiateFresh(PlayerHealthData SetRace)
+		private void InitiateFresh(PlayerHealthData setRace)
 		{
 			Cleanup();
 			//SelectedSpecies
 			SelectedSpecies = 0;
-			foreach (var Species in RaceSOSingleton.Instance.Races)
+			foreach (var species in allSpecies.TakeWhile(species => species != setRace))
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/UI/Systems/Lobby/CharacterCustomization.cs:412]: might be worth doing a get by name function on RaceSOSingleton.Instance

**Comment by Bod9001** [comment]
looks good

**Review by corp-0 — APPROVED** [review]
