### PR TITLE
Fixes blob not spawning #9884

### LINKED ISSUE #9884: [BUG] Blob doesn't spawn correctly
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

23053022

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

I spawned as CE and rolled a blob. When I was supposed to die and become a blob I died and become a ghost. My body was still alive but I was a ghost and there was no blob core. I tried to re-enter my body and suddenly I actually became a blob. There was still no core but I could move around the station (see screenshot). Jumping to core didn't do anything.
image

### What should have happened instead?

I should've died and become a blob with a core.

### Steps to reproduce the issue

1. Become blob antagonist 
2. Wait for you to die

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MaxIsJoe**
fixes #9884

CL: [Fix] Fixed an issue with blobs not spawning due to outdated information when moving the player's mind to the blob.

### CODE REVIEW

File: UnityProject/Assets/Scripts/Systems/Antagonists/Antags/Blob/BlobStarter.cs [hunk 1]
```diff
@@ -83,7 +83,12 @@ private void Start()
 
 		private void OnEnable()
 		{
+#if UNITY_EDITOR
+			UpdateManager.Add(PeriodicUpdate, 0.15f);
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/Systems/Antagonists/Antags/Blob/BlobStarter.cs]: might be better just to have a debug bool on it, that sskips the updateTime stuff?

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Systems/Antagonists/Antags/Blob/BlobStarter.cs]: no need

**Review by Bod9001 — APPROVED** [review]
