### PR TITLE
Techweb functionality

### LINKED ISSUE #8163: [Research Foundation] Techweb basic implementation
As part of the research foundation, building a basic functionality implementation of the techweb is critical. This issue provides core functionality that the rest of Science Division will build upon. Proper documentation of the core implementation is expected, as others may well build upon it.

The following features are essential:

1. Research Points (RP) - A basic passive trickle over time (Try 25RP/min) and a means of tying that points income to a particular research computer, separate from others that may exist (I.E. Not a global value)
2. A means of storing the contents of the tech tree for build-free modification by server owners (JSON is the preferred choice)
3. A rudimentary GUI that shows available, locked and completed techs, ideally being able to pull sprites and data from relevant object SOs.

Consider also in-game storage of research progress on a physical server.

### LINKED ISSUE #9461: Science Goggles not being produced in the science technofab.
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

22122405

### I was

Client

### OS

Mac

### What happened?

If you attempt to print science goggles in the technofab in research, the goggles will say they're printed, take the resources, and then nothing will be produced.

### What should have happened instead?

The goggles should have been produced.

### Steps to reproduce the issue

1.) Go to Technofab in research.
2.) Fill it with the required resources.
3.) Queue up "Science Goggles".
4.) Try to print them.

### Additional context

Screen Shot 2022-12-29 at 11 20 16 AM
Screen Shot 2022-12-29 at 11 20 21 AM
Screen Shot 2022-12-29 at 11 20 24 AM

### PR DESCRIPTION
**Pull request by AtnerNT**
This PR adds a GUI to the techweb and adds the ability for research tech.
The techweb has also been populated with ~10 nodes for now and more can be added as more science content is worked on.

Notes:
-This GUI doesn't meet the design goals as it is a list based design as opposed to a visual tree. This GUI is merely to complete the science gameplay loop and get the techweb up and running so that the visual tree UI can be developed down the line. This PR does alot of the ground work for the techweb, so this should also simplify the job of which ever dev decides to work on the tree GUI

This should close #8163 if Cross is happy with my implementation.
This also closes #9461 forgot to mention that, I forgor

### Changelog:
CL: [New] Added techweb functionality and GUI allowing scientists to conduct research
CL: [Improvement]Populates the techweb with 10ish nodes
CL: [Balance] Cybernetic organs have been moved to the techweb and are no longer available from the start.

### CODE REVIEW

File: UnityProject/Assets/Scripts/ScriptableObjects/Research/DefaultTechwebData.cs [hunk 1]
```diff
@@ -19,22 +19,26 @@ public void GenerateDefaultData()
...
 			Debug.Log(jsonData);
 
 			if (Directory.Exists($"{path}") == false)
 			{
 				Debug.Log($"{path} not found, making one..");
 				Directory.CreateDirectory(path);
 			}
-			if (File.Exists($"{path}{fileName}"))
+
+			path = Path.Combine(path, "TechwebData.json");
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/ScriptableObjects/Research/DefaultTechwebData.cs:31]: use constants for these strings

File: UnityProject/Assets/Scripts/Objects/Research/ResearchPointMachine.cs [hunk 2]
```diff
@@ -91,14 +91,9 @@ public void PowerNetworkUpdate(float voltage)
 
 		public virtual void StateUpdate(PowerState state)
 		{
-			if (state == PowerState.Off)
-			{
-				//Machine loses connection to server on power loss
-				UnSubscribeFromServerEvent();
```
Comment (MaxIsJoe) [inline UnityProject/Assets/Scripts/Objects/Research/ResearchPointMachine.cs:97]: Why is this removed?

File: UnityProject/Assets/Scripts/Systems/Research/Techweb.cs [hunk 3]
```diff
@@ -33,6 +48,56 @@ public List<TechWebNode> GetNodes()
...
+
+			ResearchedTech.Add(technologyToResearch);
+			researchedTechIDs.Add(technologyToResearch.ID);
+			researchPoints -= technologyToResearch.ResearchCosts;
+
+			UpdateTechnologyLists();
+			UpdateAvailableDesigns();
+			foreach(Technology tech in ResearchedTech)
+			{
+				Debug.Log(tech.DisplayName);
```
Comment (MaxIsJoe) [inline UnityProject/Assets/Scripts/Systems/Research/Techweb.cs]: Remove this log. If you need it inside a build use `Logger` instead.

File: UnityProject/Assets/Scripts/Systems/Research/Techweb.cs [hunk 4]
```diff
@@ -43,6 +108,27 @@ public List<Technology> GetTech()
...
 
+		public List<string> UpdateAvailableDesigns()
+		{
+			List<string> availableDesigns = AvailableDesigns;
+
+			foreach (Technology tech in ResearchedTech)
+			{
+				foreach (string str in tech.DesignIDs)
+				{
+					if (!availableDesigns.Contains(str))
```
Comment (MaxIsJoe) [inline UnityProject/Assets/Scripts/Systems/Research/Techweb.cs]: `if (availableDesigns.Contains(str) == false)` use `!` for inverting only

File: UnityProject/Assets/Scripts/UI/Objects/Research/ResearchServer/AvailableTechEntry.cs [hunk 5]
```diff
@@ -0,0 +1,59 @@
...
+			techPrice.MasterSetValue(technology.ResearchCosts.ToString());
+			SetSprites();
+		}
+
+		private void SetSprites()
+		{
+			int unlockCount = technologyToUnlock.DesignIDs.Count;
+			spriteList.SetItems(unlockCount);
+		
+			for(int i = 0; i < unlockCount; i++)
```
Comment (MaxIsJoe) [inline UnityProject/Assets/Scripts/UI/Objects/Research/ResearchServer/AvailableTechEntry.cs:39]: why a for loop isntead of a foreach loop?

File: UnityProject/Assets/Scripts/UI/Objects/Research/ResearchServer/GUI_ResearchServer.cs [hunk 6]
```diff
@@ -0,0 +1,122 @@
...
+
+			UpdateGUI();
+
+			OnTabOpened.AddListener(UpdateGUIForPeepers);
+
+		}
+
+		public void UpdateGUIForPeepers(PlayerInfo notUsed)
+		{
+			if (!isUpdating)
```
Comment (MaxIsJoe) [inline UnityProject/Assets/Scripts/UI/Objects/Research/ResearchServer/GUI_ResearchServer.cs]: `if (isUpdating == false)`

File: UnityProject/Assets/Scripts/UI/Objects/Research/ResearchServer/GUI_ResearchServer.cs [hunk 7]
```diff
@@ -0,0 +1,122 @@
...
+			{
+				isUpdating = true;
+				StartCoroutine(WaitForClient());
+			}
+		}
+
+		private IEnumerator WaitForClient()
+		{
+			yield return new WaitForSeconds(0.2f);
```
Comment (MaxIsJoe) [inline UnityProject/Assets/Scripts/UI/Objects/Research/ResearchServer/GUI_ResearchServer.cs]: use a constant for this time so codacy doesn't yell at us

File: UnityProject/Assets/Scripts/UI/Objects/Research/ResearchServer/GUI_ResearchServer.cs [hunk 8]
```diff
@@ -0,0 +1,122 @@
...
+			UpdateGUI();
+			isUpdating = false;
+		}
+
+		public void UpdateGUI()
+		{
+			UpdateResearchTechList();
+			UpdateFutureTechList();
+			UpdateAvailiableTechList();
+			PointLabel.MasterSetValue($"Available Points: {techWeb.researchPoints} (+1 / minute)");
```
Comment (MaxIsJoe) [inline UnityProject/Assets/Scripts/UI/Objects/Research/ResearchServer/GUI_ResearchServer.cs]: the (+1 / minute) is never going to change? is it hardcoded somewhere that the rate will always be 1+ per minute? its better to reference the value of how many points you'll receive in a given time incase it gets changed or becomes dynamic in the future.

File: UnityProject/Assets/Scripts/UI/Objects/Research/ResearchServer/GUI_ResearchServer.cs [hunk 9]
```diff
@@ -0,0 +1,122 @@
...
+		}
+
+		private void UpdateResearchTechList()
+		{
+			int researchedTechCount = techWeb.ResearchedTech.Count;
+
+			ResearchedTechList.SetItems(researchedTechCount);
+			for(int i = 0; i < researchedTechCount; i++)
```
Comment (MaxIsJoe) [inline UnityProject/Assets/Scripts/UI/Objects/Research/ResearchServer/GUI_ResearchServer.cs:88]: This as well, why is it not a foreach loop?

File: UnityProject/Assets/Scripts/UI/Objects/Research/ResearchServer/GUI_ResearchServer.cs [hunk 10]
```diff
@@ -0,0 +1,122 @@
...
+			{
+				Technology technology = techWeb.ResearchedTech[i];
+				ResearchedTechList.Entries[i].GetComponent<ResearchedTechEntry>().Initialise(technology.DisplayName,technology.Description);
```
Comment (MaxIsJoe) [inline UnityProject/Assets/Scripts/UI/Objects/Research/ResearchServer/GUI_ResearchServer.cs]: use `TryGetComponent<>()` and include error reporting.

File: UnityProject/Assets/Scripts/UI/Objects/Research/ResearchServer/GUI_ResearchServer.cs [hunk 11]
```diff
@@ -0,0 +1,122 @@
...
+
+		private void UpdateAvailiableTechList()
+		{
+			int availableTechCount = techWeb.AvailableTech.Count;
+
+			AvailableTechList.SetItems(availableTechCount);
+			for (int i = 0; i < availableTechCount; i++)
+			{
+				Technology technology = techWeb.AvailableTech[i];
+				AvailableTechList.Entries[i].GetComponent<AvailableTechEntry>().Initialise(technology, techWeb);
```
Comment (MaxIsJoe) [inline UnityProject/Assets/Scripts/UI/Objects/Research/ResearchServer/GUI_ResearchServer.cs]: same thing here. `TryGetComponent<>()`

File: UnityProject/Assets/StreamingAssets/TechWeb/TechwebData.json [hunk 12]
```diff
@@ -0,0 +1 @@
..."],"DesignIDs":[],"ResearchCosts":30,"ExportPrice":0,"PotentialUnlocks":["bluespacestorage"],"prefabID":"bluespace","techType":0,"Techweb":null},{"ID":"bluespacestorage","DisplayName":"Bluespace Storage","Description":"Unique methods of storing matter using bluespace.","StartingNode":false,"RequiredTechnologies":["bluespace"],"DesignIDs":["bluespace_matter_bin","bluespacebeaker"],"ResearchCosts":30,"ExportPrice":0,"PotentialUnlocks":["holding"],"prefabID":"bluespacestorage","techType":0,"Techweb":null},{"ID":"holding","DisplayName":"Bluespace Holding","Description":"New methods of storage allowing container contents to be sotred in large quantity in alternate dimensions","StartingNode":false,"RequiredTechnologies":["bluespacestorage"],"DesignIDs":["satchelholding","trashbagholding"],"ResearchCosts":50,"ExportPrice":0,"PotentialUnlocks":[],"prefabID":"bluespaceholding","techType":0,"Techweb":null},{"ID":"janitor","DisplayName":"Janitorial Science","Description":"New ways to keep the station clean.","StartingNode":false,"RequiredTechnologies":["advstock"],"DesignIDs":["advmop"],"ResearchCosts":15,"ExportPrice":0,"PotentialUnlocks":[],"prefabID":"janitor","techType":0,"Techweb":null}]
```
Comment (MaxIsJoe) [inline UnityProject/Assets/StreamingAssets/TechWeb/TechwebData.json]: can you pretify this so its more human-readable and people can edit it easily?

**Review by MaxIsJoe — CHANGES_REQUESTED** [review]

File: UnityProject/Assets/Scripts/UI/Core/Net/Elements/NetSpriteHandler.cs [hunk 13]
```diff
@@ -0,0 +1,44 @@
+using System;
+using UnityEngine;
+using UnityEngine.UI;
+
+namespace UI.Core.Net.Elements
+{
+	/// Sends client's touch coordinates (within element) over network
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/UI/Core/Net/Elements/NetSpriteHandler.cs]: probably forgot to remove this

File: UnityProject/Assets/StreamingAssets/TechWeb/TechwebData.json (hunk 12 above)
Comment (Bod9001) [reply UnityProject/Assets/StreamingAssets/TechWeb/TechwebData.json]: there's a plug-in you can use on notepad++ to auto form jstools

File: UnityProject/Assets/Scripts/UI/Objects/Research/ResearchServer/GUI_ResearchServer.cs (hunk 11 above)
Comment (AtnerNT) [reply UnityProject/Assets/Scripts/UI/Objects/Research/ResearchServer/GUI_ResearchServer.cs]: is try get component nessacary here? There is no scenario in with this component will not exist, as the list prefab contains it

File: UnityProject/Assets/Scripts/UI/Objects/Research/ResearchServer/GUI_ResearchServer.cs (hunk 9 above)
Comment (AtnerNT) [reply UnityProject/Assets/Scripts/UI/Objects/Research/ResearchServer/GUI_ResearchServer.cs:88]: This isnt a foreach because I use the index to access the same entry in ResearchedTech and the ResearchedTechList.Entries. I find this is far cleaner and easier to do in a for loop than a foreach

File: UnityProject/Assets/Scripts/UI/Objects/Research/ResearchServer/GUI_ResearchServer.cs (hunk 8 above)
Comment (AtnerNT) [reply UnityProject/Assets/Scripts/UI/Objects/Research/ResearchServer/GUI_ResearchServer.cs]: yeah fair enough

File: UnityProject/Assets/Scripts/UI/Objects/Research/ResearchServer/AvailableTechEntry.cs (hunk 5 above)
Comment (AtnerNT) [reply UnityProject/Assets/Scripts/UI/Objects/Research/ResearchServer/AvailableTechEntry.cs:39]: Responded to this comment elsewhere, its the same reason for all the for loops in this PR

File: UnityProject/Assets/Scripts/Systems/Research/Techweb.cs (hunk 3 above)
Comment (AtnerNT) [reply UnityProject/Assets/Scripts/Systems/Research/Techweb.cs]: Yup accidentally left that in there from when I was debugging errors

File: UnityProject/Assets/Scripts/Objects/Research/ResearchPointMachine.cs (hunk 2 above)
Comment (AtnerNT) [reply UnityProject/Assets/Scripts/Objects/Research/ResearchPointMachine.cs:97]: I personally think it does not add much and creates an issue.
Power on the station flickers off, even for a second quite frequently (often if engi turns off the plasma gen to run the stations reactor or similliar). Having the science department reconnect every machine in their department every time there is a power flicker seems awfully tedious and not adding much gameplay.
Also, this often triggers before power is fully initalised, meaning at round start, all resourcepoint machines disconnect from the server, meaning you have to go and reconnect them all everytime. For these reasons I just removed it

File: UnityProject/Assets/Scripts/UI/Objects/Research/ResearchServer/GUI_ResearchServer.cs (hunk 7 above)
Comment (AtnerNT) [reply UnityProject/Assets/Scripts/UI/Objects/Research/ResearchServer/GUI_ResearchServer.cs]: codacy poopoo but yes will do

File: UnityProject/Assets/Scripts/UI/Objects/Research/ResearchServer/GUI_ResearchServer.cs (hunk 10 above)
Comment (AtnerNT) [reply UnityProject/Assets/Scripts/UI/Objects/Research/ResearchServer/GUI_ResearchServer.cs]: same reason as below

File: UnityProject/Assets/StreamingAssets/TechWeb/TechwebData.json (hunk 12 above)
Comment (AtnerNT) [reply UnityProject/Assets/StreamingAssets/TechWeb/TechwebData.json]: Is there a way to autoformart Jsons using the json libary you used to add the techweb (this is generated using that)? Because having to open up this Json in something like notepad++ to reformat it everytime its changed seems like a hassle and so does manually added formatting logic to the serialiser.
@MaxIsJoe

File: UnityProject/Assets/Scripts/UI/Core/Net/Elements/NetSpriteHandler.cs (hunk 13 above)
Comment (AtnerNT) [reply UnityProject/Assets/Scripts/UI/Core/Net/Elements/NetSpriteHandler.cs]: ah yup

File: UnityProject/Assets/StreamingAssets/TechWeb/TechwebData.json (hunk 12 above)
Comment (corp-0) [reply UnityProject/Assets/StreamingAssets/TechWeb/TechwebData.json]: Any decent IDE can format JSON files

File: UnityProject/Assets/Scripts/UI/Objects/Research/ResearchServer/GUI_ResearchServer.cs (hunk 11 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/UI/Objects/Research/ResearchServer/GUI_ResearchServer.cs]: Better be safe than sorry. A component might not spawn properly or might get changed in the future, telling the developers a clear error helps us resolve things quickly rather than just receive a generic NRE message that often just breaks the entire game.

File: UnityProject/Assets/StreamingAssets/TechWeb/TechwebData.json (hunk 12 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/StreamingAssets/TechWeb/TechwebData.json]: `string json = JsonConvert.SerializeObject(yourData, Formatting.Indented);`

File: UnityProject/Assets/Scripts/UI/Objects/Research/ResearchServer/AvailableTechEntry.cs (hunk 5 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/UI/Objects/Research/ResearchServer/AvailableTechEntry.cs:39]: alright carry on

File: UnityProject/Assets/Scripts/ScriptableObjects/Research/DefaultTechwebData.cs (hunk 1 above)
Comment (AtnerNT) [reply UnityProject/Assets/Scripts/ScriptableObjects/Research/DefaultTechwebData.cs:31]: cant use constants for these strings as they aren't constant. Paths.Combine will produce a different string depending on the OS

**Comment by AtnerNT** [comment]
Tested with host and client and all working, unless codacy flags half my code this is ready to merge

File: UnityProject/Assets/Scripts/Objects/Research/ResearchPointMachine.cs (hunk 2 above)
Comment (Pockets-byte) [reply UnityProject/Assets/Scripts/Objects/Research/ResearchPointMachine.cs:97]: make it time dependent. a flicker won't hurt, but power goes out for 10 minutes and you have to set things up again

Comment (AtnerNT) [reply UnityProject/Assets/Scripts/Objects/Research/ResearchPointMachine.cs:97]: the APC powerable component doesnt have support for that right now, If we wanted to do that, that can be added at a later state. This just removes the logic from the APCpowerable component as the functionality that results in is not ideal

Comment (Bod9001) [reply UnityProject/Assets/Scripts/Objects/Research/ResearchPointMachine.cs:97]: okay that's fair enough

**Review by Bod9001 — APPROVED** [review]
