### PR TITLE
Variable Speed support for player

### LINKED ISSUE #1507: Player variable speed support + ability to toggle walk and run B: 90
# Description
Walk and run switch does not slow you down when you switch to walk
## Criteria

- [ ] Add variable speed support for PlayerSync
- [ ] Add support for walk/run switching
- [ ] Add ability to crawl in crit

## Detailed Bug Report
If you click on the walk/run button you don't slow down or speed up
## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Go into the game, spawn in
2.Click on the walk/run switch
3.See that it does nothing

### LINKED ISSUE #1572: Shuttle controls not working due to broken references
# Description
ShuttleInteract triggers are missing ShuttleMatrixMove reference

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Join as cargotech and try clicking escape shuttle console

### PR DESCRIPTION
**Pull request by fomalsd**
### Purpose
Fixes #1507, fixes #1572 
https://files.catbox.moe/14x0p0.gif
Adds soft crit (player is able to crawl and whisper)
Adds ability to come out of crit (i.e. from oxygen damage):
gif

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [x]  This PR has been tested in multiplayer

### Notes:
Player in softcrit still might be able to do something extra he's not supposed to...

### CODE REVIEW

File: UnityProject/Assets/Scripts/Health/Living/LivingHealthBehaviour.cs [hunk 1]
```diff
@@ -1,654 +1,666 @@
...
+
+	public virtual void UnCrit()
+	{
+		var proposedState = ConsciousState.CONSCIOUS;
+		if (ConsciousState == proposedState || IsDead)
+		{
+			return;
+		}
+		ConsciousState = proposedState;
+		OnConsciousStateChange( proposedState );
```
Comment (Jibbajabbafic) [inline UnityProject/Assets/Scripts/Health/Living/LivingHealthBehaviour.cs]: Could this be put in the ConsciousState set method? That way people won't forget to call OnConsciousStateChange (unless there are cases where you want to update ConsciousState without calling it).

File: UnityProject/Assets/Scripts/Objects/PushPull.cs [hunk 2]
```diff
@@ -187,6 +193,30 @@ private void TargetUpdatePullingUI(NetworkConnection target, bool pulling)
...
+	/// <summary>
+	/// Recursive method to get client speed of the train head
+	/// </summary>
+	public float GetHeadSpeedClient()
+	{
+		if ( IsBeingPulledClient )
+		{
+			return PulledByClient.GetHeadSpeedClient();
+		}
+		return Pushable.SpeedClient;
```
Comment (Jibbajabbafic) [inline UnityProject/Assets/Scripts/Objects/PushPull.cs:206]: Nice

File: UnityProject/Assets/Scripts/Player/PlayerMove.cs [hunk 3]
```diff
@@ -1,233 +1,169 @@
...
-		public float speed = 10;
+	private PlayerSprites playerSprites;
 
-		private RegisterTile registerTile;
-		private Matrix matrix => registerTile.Matrix;
+	[HideInInspector] public PlayerNetworkActions pna;
 
-		/// temp solution for use with the UI network prediction
-		public bool isMoving { get; } = false;
+	[FormerlySerializedAs( "speed" )]
```
Comment (Jibbajabbafic) [inline UnityProject/Assets/Scripts/Player/PlayerMove.cs:34]: That's really handy!

File: UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs [hunk 4]
```diff
@@ -637,29 +640,57 @@ private bool CanInteractWallmount(WallmountBehavior wallmount)
...
+				playerScript.PlayerSync.SpeedServer = playerMove.RunSpeed;
+				gameObject.GetComponent<ForceRotation>().Rotation = STRAIGHT;
+				break;
+			case ConsciousState.BARELY_CONSCIOUS:
+				//Drop items when unconscious
+				DropItem("rightHand");
+				DropItem("leftHand");
+				playerMove.allowInput = true;
+				playerScript.PlayerSync.SpeedServer =  playerMove.CrawlSpeed;
+				DropItem("rightHand");
```
Comment (Jibbajabbafic) [inline UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs]: How come DropItem is called twice?

File: UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs [hunk 5]
```diff
@@ -637,29 +640,57 @@ private bool CanInteractWallmount(WallmountBehavior wallmount)
...
 		}
 		playerScript.pushPull.CmdStopPulling();
 }
 
+	/// <summary>
+	/// Rotate player and play body fall sound
+	/// </summary>
+	private void Fall()
+	{
+		ForceRotation rotation = gameObject.GetComponent<ForceRotation>();
```
Comment (Jibbajabbafic) [inline UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs:676]: Could cache the rotation since it's being used elsewhere and I imagine falling will happen multiple times in a round

**Review by Jibbajabbafic — APPROVED** [review]
Very nice, I have some small nitpicks but I'll leave it to you if you want to change anything

I noticed some bugs but I think they might be unrelated

**Comment by Jibbajabbafic** [comment]
Btw, could we change it to run by default on spawn?

**Review by Jibbajabbafic — CHANGES_REQUESTED** [review]
Ok did some more testing and there are a few bugs with crawling and pulling. 
- ~~The crawling player's position doesn't get updated until they reach the tile which can have some strange effects, such as blood appearing on a tile before they reach it~~ Already noted in #1566
- Crawling player can push a standing one lol
- If another player pulls a crawling player, crawling doesn't break the pull properly. You can crawl really far away and position doesn't get updated for ages. Then if the pulling player does move, the crawling person slowly moves to where they should be. Example: https://imgur.com/a/pINpoq0 
- Guns stop working on host client
- Make run the default option on spawn

I think the lerp for viewers needs to be kept fast, and it should only appear slow for yourself.

File: UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs (hunk 4 above)
Comment (fomalsd) [reply UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs]: oops, looks like an overlooked merge

File: UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs (hunk 5 above)
Comment (fomalsd) [reply UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs:676]: I'll leave it as is so that @chairbender could swap it with his solution after it's merged

**Comment by fomalsd** [comment]
> Btw, could we change it to run by default on spawn?

will do, but I must admit that running feels way too fast after walking for some time

**Comment by fomalsd** [comment]
>     * If another player pulls a crawling player, crawling doesn't break the pull properly. You can crawl really far away and position doesn't get updated for ages. Then if the pulling player does move, the crawling person slowly moves to where they should be. Example: https://imgur.com/a/pINpoq0
Look at the wallmounts, you must have started editor with black fonts. no wonder game is messed up. 
I'll try to reproduce your issue anyway, but it might just be a messed up build on your side

File: UnityProject/Assets/Scripts/Health/Living/LivingHealthBehaviour.cs (hunk 1 above)
Comment (fomalsd) [reply UnityProject/Assets/Scripts/Health/Living/LivingHealthBehaviour.cs]: yep, good idea!

**Comment by fomalsd** [comment]
Reproduced crawling player not breaking pull, good catch!

**Comment by fomalsd** [comment]
Thanks for **proper** testing! it's all done now and ready for re-review

**Review by Jibbajabbafic — APPROVED** [review]

**Comment by Jibbajabbafic** [comment]
Not getting those bugs anymore, nice work 👍
