### PR TITLE
Emotes now exhale (and inhale) air from lungs

### LINKED ISSUE #9959: No spam prevention on emotes.
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

23070821

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

You can spam any emote by either rapidly pasting *emote into chat or quickly pressing \ and clicking the button for it. This allows players to spam sounds such as sneezing, laughing, screaming, etc. which is very loud and disruptive.

### What should have happened instead?

There should be some way to prevent players from spamming obnoxious sounds.

### Steps to reproduce the issue

1. Copy a emote and rapidly paste it into the chat
2. OR quickly press \ and click on the emote's button in rapid succession

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MaxIsJoe**
closes #9959

# Changelog:

CL: [New] Added sounds for gasping.
CL: [New] Gasping is no longer a cosmetic emote. When gasping, you will inhale air in sharply to increase required gases in your blood stream.
CL: [Improvement] Lungs use the "gasp-air" emote now to invoke the gasping sounds.
CL: [Improvement] Screaming, Sighing, Laughing and Dry-heaving will all now force you to exhale a small amount of air from your lungs. Spamming these emotes now will cause you to go out of breath after some time.

### CODE REVIEW

**Comment by corp-0** [comment]
Can we force everyone into manual breathing mode with this?

**Comment by MaxIsJoe** [comment]
> Can we force everyone into manual breathing mode with this?

You'd need to kill the respiratory system first, but yeah, you can.

**Comment by MaxIsJoe** [comment]
appproovallls

File: UnityProject/Assets/Scripts/HealthV2/Living/PolymorphicSystems/ReagentPoolSystem.cs [hunk 1]
```diff
@@ -25,8 +25,17 @@ public class ReagentPoolSystem : HealthSystemBase
 
 		[HideInInspector] public List<Heart> PumpingDevices = new List<Heart>();
 
+		public ReagentMix RegenBloodPool = new ReagentMix();
+		public float RegenEfficeny = 0.15f;
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/HealthV2/Living/PolymorphicSystems/ReagentPoolSystem.cs]: typo

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/HealthV2/Living/PolymorphicSystems/ReagentPoolSystem.cs]: fixed

File: UnityProject/Assets/Scripts/ScriptableObjects/RP/EmoteBehaviors/InhaleOnEmote.cs [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+
+		public void Behave(GameObject actor)
+		{
+			if (actor == null || actor.TryGetComponent<LivingHealthMasterBase>(out var health) == false) return;
+			var gas = GasMix.GetEnvironmentalGasMixForObject(actor.GetUniversalObjectPhysics());
+			var lungs = GetLungs(health);
+			if (lungs == null || gas == null) return;
+			foreach (var lung in lungs)
+			{
+				lung.BreatheIn(gas, health.reagentPoolSystem.BloodPool, Efficiency);
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/ScriptableObjects/RP/EmoteBehaviors/InhaleOnEmote.cs]: You need to pull out the calculation for how much blood it's processing from the lungs, since this bypasses it

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/ScriptableObjects/RP/EmoteBehaviors/InhaleOnEmote.cs]: wdym?

Comment (Bod9001) [reply UnityProject/Assets/Scripts/ScriptableObjects/RP/EmoteBehaviors/InhaleOnEmote.cs]: ReagentMix availableBlood =
                ReagentCirculatedComponent.AssociatedSystem.BloodPool.Take(
                    (ReagentCirculatedComponent.AssociatedSystem.BloodPool.Total * efficiency) / 2f);

Comment (Bod9001) [reply UnityProject/Assets/Scripts/ScriptableObjects/RP/EmoteBehaviors/InhaleOnEmote.cs]: that's inside of the lungs

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/ScriptableObjects/RP/EmoteBehaviors/InhaleOnEmote.cs]: this wont work because both the inhale and exhale use entirely different values.

Comment (Bod9001) [reply UnityProject/Assets/Scripts/ScriptableObjects/RP/EmoteBehaviors/InhaleOnEmote.cs]: nah tthey share the same pool

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/ScriptableObjects/RP/EmoteBehaviors/InhaleOnEmote.cs]: it literally doesn't work, i just tested it
