### PR TITLE
Fixing issue #7874

### LINKED ISSUE #7874: Countdown require ready player
Make the countdown require at least one ready player.

(Need message saying more ready players needed for countdown if not enough)

-Bonus if its a server config option e.g `RequiredPlayersForCountdown : 0` this allows for server to set what player number they want

### PR DESCRIPTION
**Pull request by 404-P4rziv4L**
### Purpose

Fixing #7874

CL: [Improvement] the round start countdown won't start until at least 1 player has readied.

### CODE REVIEW

**Comment by Bod9001** [comment]
You need to add the references in LoadConfig and 
GameConfig class

**Comment by Bod9001** [comment]
that's easy enough to do

**Comment by Bod9001** [comment]
humm, this might be worth adding the entry to the config so the one that ships with the game has the entry in, but otherwise all good

**Comment by 404-P4rziv4L** [comment]
> humm, this might be worth adding the entry to the config so the one that ships with the game has the entry in, but otherwise all good

Which config again? @Bod9001

**Comment by Bod9001** [comment]
gameConfig.json in UnityProject\Assets\StreamingAssets\config

**Review by Bod9001 — DISMISSED** [review]

**Comment by NoooneyDude** [comment]
~~What triggers the round to start once enough players have joined?~~

It's in an UpdateMe : )

**Review by NoooneyDude — DISMISSED** [review]

**Comment by 404-P4rziv4L** [comment]
@NoooneyDude I think unless the game starts, it would keep checking for the number of ready players present.

**Comment by NoooneyDude** [comment]
Oh, just noticed tests failing. Could you take a look?

There's also a UX issue where a server has set this new option greater than 1 and there's not enough players, they'll wonder why the round isn't starting once the timer ends, but it's probably not too big of a deal for now.

File: UnityProject/Assets/Scripts/Managers/GameManager.cs [hunk 1]
```diff
@@ -370,7 +376,13 @@ private void UpdateMe()
...
 			if (NetworkTime.time >= CountdownEndTime)
 			{
-				StartRound();
+				if (PlayerList.Instance.ReadyPlayers.Count >= MinReadyPlayersForCountdown)
+				{
+					StartRound();
+				}
+				else {
+					Logger.Log("More ready players needed for countdown!")
+				}
```
Comment (NoooneyDude) [inline UnityProject/Assets/Scripts/Managers/GameManager.cs]: Found the tests failing issue : )
Missing semicolon.

```suggestion
```

I've suggested to just remove the log instead of fixing it as it is somewhat expected behaviour and could add quite a few entries to the log.

**Comment by 404-P4rziv4L** [comment]
> Oh, just noticed tests failing. Could you take a look?
> 
> There's also a UX issue where a server has set this new option greater than 1 and there's not enough players, they'll wonder why the round isn't starting once the timer ends, but it's probably not too big of a deal for now.

What could we do for the UX issue? Or is that a separate issue in itself?

**Comment by NoooneyDude** [comment]
> What could we do for the UX issue? Or is that a separate issue in itself?

I think showing a fraction `Players: 2 / 3` (two online out of three required) somewhere on that lobby window would be sufficient. I would personally only show it if the requirement isn't yet met as seeing, as an example, `Players: 84 / 1` isn't particularly useful.

Edit: if you don't feel like implementing this for this PR, could you make an issue for it once this is merged?

**Review by Bod9001 — APPROVED** [review]

**Review by NoooneyDude — APPROVED** [review]

**Comment by NoooneyDude** [comment]
Let us know in Discord if you want the Engineer role.

**Comment by 404-P4rziv4L** [comment]
Sure, I'd like working on the UX issue as well

**Comment by mmails** [comment]
> Sure, but I don't have access to the Discord server yet...

Here's the [discord server](https://discord.com/invite/tFcTpBp), if you're interested

**Comment by 404-P4rziv4L** [comment]
Thanks, I'm in.

**Comment by mmails** [comment]
> Thanks, I'm in.

My pleasure
