### PR TITLE
Fixes infinite firelocks / doors

### LINKED ISSUE #8432: Seems to be infinite firelocks
### Environment
- Game Version: 22022318
- OS Version: Catalina

When North to South facing airlock is broken it leaves behind what seems to be an infinite amount of airlocks. Oh and it doesn't really break either.

### Steps to reproduce

1. Robust a North to South facing airlock until it "breaks"
2. Observe the leftover airlocks. 
Observe the non-broken airlock. 
image

### PR DESCRIPTION
**Pull request by MaxIsJoe**
fixes #8432 

CL: [Fix] fixed duplicating firelocks and airlocks

### CODE REVIEW

**Review by Bod9001 — DISMISSED** [review]

File: UnityProject/Assets/Scripts/Health/Objects/Integrity.cs [hunk 1]
```diff
@@ -125,6 +126,7 @@ public class Integrity : NetworkBehaviour, IHealth, IFireExposable, IRightClicka
 	private RegisterTile registerTile;
 	public RegisterTile RegisterTile => registerTile;
 	private IPushable pushable;
+	public Meleeable Meleeable => GetComponent<Meleeable>();
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Health/Objects/Integrity.cs]: it is better to cache this reference. Like it is right now it will call GetComponent every time the ``Meleeable`` property is used anywhere in the consumer code. Yeah, currently it is only used in ``WhenDestroyed`` from ``ConstructibleDoor`` component, so we won't notice it until it becomes a problem later in the future.

**Review by corp-0 — CHANGES_REQUESTED** [review]

**Comment by MaxIsJoe** [comment]
review pls

**Review by Bod9001 — APPROVED** [review]

**Review by corp-0 — APPROVED** [review]
