### PR TITLE
Fixes explosion sound spam on pot+water inside body mix

### LINKED ISSUE #7626: water + pot pills infitinite loud explosion sounds
### Environment
- Game Version: Staging 21101813
- OS Version: Arch Linux

### Detailed description of bug

WARNING: loud sounds dont use headphones at max volume when testing

right now taking both water and potassium pills makes your body to explode it in really fast intervals making a really loud and annoying explotion sound that can be heard on the whole station 

### Steps to reproduce

1. make 10u water pill on chemmaster
2. make 10u potassium pill on chemmaster
3. eat both and lower your volume if you dont want to end up deaf

### PR DESCRIPTION
**Pull request by Aranclanos**
### Purpose
CL: [Fix] Fixed chem explosions from triggering with really low units.
Fixes #7626

### CODE REVIEW

**Review by NoooneyDude — APPROVED** [review]

File: UnityProject/Assets/Scripts/Systems/Chemistry/Effects/ChemExplosion.cs [hunk 1]
```diff
@@ -39,7 +39,7 @@ public override void Apply(MonoBehaviour sender, float amount)
 			var strength = (float)(-463+205*Mathf.Log(amount)+75*Math.PI)*potency;
 
 
-			if (insideBody)
+			if (insideBody && strength > 0)
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/Systems/Chemistry/Effects/ChemExplosion.cs:42]: surely this would trigger still, since it would be something like 0.001

Comment (Aranclanos) [reply UnityProject/Assets/Scripts/Systems/Chemistry/Effects/ChemExplosion.cs:42]: it was negative, like -1600

Comment (Bod9001) [reply UnityProject/Assets/Scripts/Systems/Chemistry/Effects/ChemExplosion.cs:42]: oh ok

**Review by Bod9001 — APPROVED** [review]
