### PR TITLE
Porting some of Addressables PR changes

### LINKED ISSUE #9514: [Rework Needed] Subsystems should be initialized as part of the server loading process, not outside of it.
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

14/1/2023

### I was

Server

### OS

Windows 8, 10, 11

### What happened?

Subsystems are initialized after all scenes are loaded from an event that developers may or may not forget to subscribe to manually and can be initialized more than once accidentally.

### What should have happened instead?

There should be a high level manager that handles all the initialization processes of our subsystems that also handles adding all behaviors automatically on Awake to the manager.

### Steps to reproduce the issue

Just open an IDE and try adding any new behaviors to loading scenes.

The easiest way to cause issues with this is to set a scene as inactive via code when it gets spawned, then enable it. This will cause all subsystems on every map to get confused and break itself, including the newly activated scene.

### Additional context

This is bad design and does not allow for easy modability for scenes.

### PR DESCRIPTION
**Pull request by MaxIsJoe**
fixes #9514

This PR ports some of the cleaning I've done in #9459 since that PR is a bit stuck in rebase/conflict merges hell. All addressable stuff is not enabled, but some of the settings are there.

The reasoning behind this is:
1) In case I get stuck again for long periods of time and someone decides to touch these files again or any scene assets, they don't get in my way again and force me to re-do everything from scratch like now.
2) to close #9514
3) to reduce the gigantic size of the addressables PR changes, and split into chunks to detect any funny mistakes that may or may not lurk in the sea of changes that I've made.
4) To keep the important settings that are hard to configure on upstream/develop in-case I go on a two-month hiatus (again) away from addressables.

In the following PR after this is merged I'll work again on converting scene code to use `AssetReference` and load scenes from bundles... then its off to "game-breaking bug fixing land"

### CODE REVIEW

File: UnityProject/Assets/Scripts/Managers/SubSceneManager/SubSceneManager.cs [hunk 1]
```diff
@@ -112,6 +112,12 @@ IEnumerator LoadSubScene(string sceneName, SubsceneLoadTimer loadTimer = null, b
 				RequestObserverRefresh.Send(sceneName);
 			}
 		}
+
+		loadedScenesList.Add(new SceneInfo
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/Managers/SubSceneManager/SubSceneManager.cs:116]: Make sure to set is dirty,  if it's a Synch  list

File: UnityProject/Assets/Scripts/Managers/SubSceneManager/SubSceneManager.SceneList.cs [hunk 2]
```diff
@@ -172,7 +148,7 @@ IEnumerator ServerLoadAdditionalScenes(SubsceneLoadTimer loadTimer)
 	{
 		if (GameManager.Instance.QuickLoad)
 		{
-			yield return null;
+			yield break;
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/Managers/SubSceneManager/SubSceneManager.SceneList.cs:146]: doesn't this just cause it to  get stuck?

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Managers/SubSceneManager/SubSceneManager.SceneList.cs:146]: wdym? `break` should exit the function, not make get stuck?

File: UnityProject/Assets/Scripts/Managers/SubSceneManager/SubSceneManager.cs (hunk 1 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Managers/SubSceneManager/SubSceneManager.cs:116]: it already does in the function thats calling it... which good thing you reminded me; this can be further cleaned by moving that over to the load function

File: UnityProject/Assets/Scripts/Managers/SubSceneManager/SubSceneManager.SceneList.cs (hunk 2 above)
Comment (Bod9001) [reply UnityProject/Assets/Scripts/Managers/SubSceneManager/SubSceneManager.SceneList.cs:146]: but the UI gets stuck thinking it's loading, if I'm reading it right?

File: UnityProject/Assets/Scripts/Managers/SubSceneManager/SubSceneManager.cs (hunk 1 above)
Comment (Bod9001) [reply UnityProject/Assets/Scripts/Managers/SubSceneManager/SubSceneManager.cs:116]: I think the load function gets called on client?

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Managers/SubSceneManager/SubSceneManager.cs:116]: ?

File: UnityProject/Assets/Scripts/Managers/SubSceneManager/SubSceneManager.SceneList.cs [hunk 3]
```diff
@@ -246,13 +231,6 @@ public IEnumerator LoadWizard()
 
 		yield return StartCoroutine(LoadSubScene(pickedScene));
 
-		loadedScenesList.Add(new SceneInfo
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/Managers/SubSceneManager/SubSceneManager.SceneList.cs:289]: does this get added automatically?

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Managers/SubSceneManager/SubSceneManager.SceneList.cs:289]: yes

**Review by Bod9001 — APPROVED** [review]
