### PR TITLE
Few small fixes

### LINKED ISSUE #5195: Add generators fueled by uranium and diamonds instead of plasma.
## Description
In /tg/, there aren't just portable generators that run off plasma. There are also portable generators that run off uranium and diamond. The plasma generator is called the P.A.C.M.A.N., the uranium generator is called the S.U.P.E.R.P.A.C.M.A.N., and the diamond generator is called the M.R.S.P.A.C.M.A.N.. 

The uranium generator in /tg/ produces 15,000 power by default to the plasma generator's 5000. Meanwhile, the diamond generator in /tg/ produces 40,000 power to the uranium generator's 15,000 and the plasma generator's 5000. However, the uranium and diamond generators appear to consume their fuel at a faster rate. While plasma generators in /tg/ allow for 260 time per sheet (unit of measurement unknown) uranium and diamond generators only allow for 85 and 80 time per sheet respectively.

### Note
At time of writing, diamond generators have been removed from /tg/, for reasons. However, it is still possible to view their code.
[This link leads to the .dm file for plasma, uranium, and diamond generators before the removal of the latter.](https://github.com/tgstation/tgstation/blob/4b6500fb67a4c119d9d6e56bdaf2994bf1b04946/code/modules/power/port_gen.dm)

### LINKED ISSUE #7758: Box station kitchen starts upowered due to hungry and angry mice
### Environment
- Game Version: Staging 21110423
- OS Version: Arch Linux

### Detailed description of bug

At round start a mice will eat all the low voltage cables in the kitchen maint leaving it completely unpowered.

https://user-images.githubusercontent.com/80334192/140615922-f3261b44-0ad0-4870-b79a-f9598b7892c1.mp4

this happens because the mouse initial mood level is set to 0

### Steps to reproduce

1. start round in box station
2. check wires in kitchen maint
3. check mouse MobMood levels with VV

### LINKED ISSUE #7782: Make Quantum Keys Available in Autolathe
Allow creation of quantum keys in autolathes.

Make them expensive though, diamonds and blue space crystals?

### PR DESCRIPTION
**Pull request by ilinm1**
### Purpose
Fixes #7758, fixes #7782, fixes #5195

### Notes:
-

### Changelog:
CL: [Fix] Fixes mice eating all the wires because of low initial mood
CL: [New] Adds ability to produce quantum keys on autolathe
CL: [New] Adds S.U.P.E.R.P.A.C.M.A.N. generator

### CODE REVIEW

File: UnityProject/Assets/Scripts/Objects/Engineering/PowerGenerator.cs [hunk 1]
```diff
@@ -138,55 +142,59 @@ public bool WillInteract(HandApply interaction, NetworkSide side)
 		{
 			if (!DefaultWillInteract.Default(interaction, side)) return false;
 			if (interaction.TargetObject != gameObject) return false;
-			if (interaction.HandObject != null && !Validations.HasItemTrait(interaction.HandObject, CommonTraits.Instance.SolidPlasma)) return false;
-
-			return true;
+			if (interaction.HandObject == null) return true;
+			foreach (ItemTrait fuelType in fuelTypes) { if (Validations.HasItemTrait(interaction.HandObject, fuelType)) return true; }
```
Comment (NoooneyDude) [inline UnityProject/Assets/Scripts/Objects/Engineering/PowerGenerator.cs]: Braces should usually be on their own, and on their own line.

You might want to check out our [development standards guide](https://unitystation.github.io/unitystation/contribution-guides/Development-Standards-Guide/).

File: UnityProject/Assets/Scripts/Objects/Engineering/PowerGenerator.cs [hunk 2]
```diff
@@ -138,55 +142,59 @@ public bool WillInteract(HandApply interaction, NetworkSide side)
...
 		public void ServerPerformInteraction(HandApply interaction)
 		{
-			if (Validations.HasItemTrait(interaction.HandObject, CommonTraits.Instance.SolidPlasma))
-			{
-				int amountTransfered;
-				var handStackable = interaction.HandObject.GetComponent<Stackable>();
-				if (itemSlot.Item)
+			foreach(ItemTrait fuelType in fuelTypes)
+            {
+				if (Validations.HasItemTrait(interaction.HandObject, fuelType))
```
Comment (NoooneyDude) [inline UnityProject/Assets/Scripts/Objects/Engineering/PowerGenerator.cs]: Please use tabs for indentation. You might need to configure your IDE to use tabs (width 4).

File: UnityProject/Assets/Scripts/Objects/Engineering/PowerGenerator.cs [hunk 3]
```diff
@@ -138,55 +142,59 @@ public bool WillInteract(HandApply interaction, NetworkSide side)
...
-					amountTransfered = handStackable.Amount;
-					Inventory.ServerTransfer(interaction.HandSlot, itemSlot);
+					Chat.AddExamineMsgFromServer(interaction.Performer, $"You fill the generator sheet storage with {amountTransfered.ToString()} more.");
 				}
-				Chat.AddExamineMsgFromServer(interaction.Performer, $"You fill the generator sheet storage with {amountTransfered.ToString()} more.");
-			}
-			else if (securable.IsAnchored)
-			{
-				if (!isOn)
+				else if (securable.IsAnchored)
```
Comment (NoooneyDude) [inline UnityProject/Assets/Scripts/Objects/Engineering/PowerGenerator.cs]: I see you're allowing for the possibility of generators to have multiple acceptable fuels. This is good, but it looks like if the generator can accept an even-number of fuels, and your hand is empty, the generator will be toggled and then toggled again, back to its original state, because it is in the loop of the possible fuels.

I suggest checking for an empty hand first to toggle the generator, else try refueling.

Returning early can also reduce the needed indentation.

File: UnityProject/Assets/Prefabs/Objects/Electricity/PowerGeneratorPlasma.prefab [hunk 4]
```diff
@@ -5332,9 +5332,9 @@ MonoBehaviour:
   Previouscurrent: 0
   current: 0
   PreviousSupplyingVoltage: 760000
-  SupplyingVoltage: 760000
+  SupplyingVoltage: 500000
   PreviousInternalResistance: 76000
-  InternalResistance: 76000
+  InternalResistance: 50000
```
Comment (NoooneyDude) [inline UnityProject/Assets/Prefabs/Objects/Electricity/PowerGeneratorPlasma.prefab]: What are the implications of reducing this to 500 kV? Does the PACMAN still power the stations?

Also, reducing the internal resistance I imagine would buff the current supply of the PACMAN. Is that intended?

**Review by NoooneyDude — COMMENTED** [review]
Hi @IlinMihail, thanks for your contribution!

File: UnityProject/Assets/Scripts/Objects/Engineering/PowerGenerator.cs [hunk 5]
```diff
@@ -138,55 +142,59 @@ public bool WillInteract(HandApply interaction, NetworkSide side)
 		{
 			if (!DefaultWillInteract.Default(interaction, side)) return false;
 			if (interaction.TargetObject != gameObject) return false;
-			if (interaction.HandObject != null && !Validations.HasItemTrait(interaction.HandObject, CommonTraits.Instance.SolidPlasma)) return false;
-
-			return true;
+			if (interaction.HandObject == null) return true;
```
Comment (ThatDan123) [inline UnityProject/Assets/Scripts/Objects/Engineering/PowerGenerator.cs:145]: Are you sure you want to be checking for null here? As the server interaction is checking the contents of the hand.

Comment (ThatDan123) [reply UnityProject/Assets/Scripts/Objects/Engineering/PowerGenerator.cs:145]: oh wait sorry didnt check the line below :p

File: UnityProject/Assets/Scripts/Objects/Engineering/PowerGenerator.cs (hunk 1 above)
Comment (ThatDan123) [reply UnityProject/Assets/Scripts/Objects/Engineering/PowerGenerator.cs]: There might also be a `Validations.HasItemTraits(interaction.HandObject, fuelTypes)` so you can just send the whole list

Might also be called `HasAnyItemTrait` or something like that

File: UnityProject/Assets/Scripts/Objects/Engineering/PowerGenerator.cs (hunk 3 above)
Comment (ilinm1) [reply UnityProject/Assets/Scripts/Objects/Engineering/PowerGenerator.cs]: Fixed in new commit

File: UnityProject/Assets/Prefabs/Objects/Electricity/PowerGeneratorPlasma.prefab (hunk 4 above)
Comment (ilinm1) [reply UnityProject/Assets/Prefabs/Objects/Electricity/PowerGeneratorPlasma.prefab]: Lowered values just for testing, forgot to set em back. Fixed in new commit

File: UnityProject/Assets/Scripts/Objects/Engineering/PowerGenerator.cs (hunk 2 above)
Comment (ilinm1) [reply UnityProject/Assets/Scripts/Objects/Engineering/PowerGenerator.cs]: Fixed in new commit

File: UnityProject/Assets/Scripts/Objects/Engineering/PowerGenerator.cs (hunk 1 above)
Comment (ilinm1) [reply UnityProject/Assets/Scripts/Objects/Engineering/PowerGenerator.cs]: Fixed in new commit

File: UnityProject/Assets/Scripts/Objects/Engineering/PowerGenerator.cs (hunk 5 above)
Comment (ilinm1) [reply UnityProject/Assets/Scripts/Objects/Engineering/PowerGenerator.cs:145]: So, do I need to change this check?

File: UnityProject/Assets/Scripts/Objects/Engineering/PowerGenerator.cs (hunk 2 above)
Comment (ilinm1) [reply UnityProject/Assets/Scripts/Objects/Engineering/PowerGenerator.cs]: Okay, now fully fixed

**Review by NoooneyDude — DISMISSED** [review]

File: UnityProject/Assets/Scripts/Objects/Engineering/PowerGenerator.cs [hunk 6]
```diff
@@ -138,55 +142,65 @@ public bool WillInteract(HandApply interaction, NetworkSide side)
...
+			foreach (ItemTrait fuelType in fuelTypes)
+			{
+				if (Validations.HasItemTrait(interaction.HandObject, fuelType)) return true;
+			}
```
Comment (NoooneyDude) [inline UnityProject/Assets/Scripts/Objects/Engineering/PowerGenerator.cs]: ThatDan's suggestion

```suggestion
			if (Validations.HasAnyTrait(interaction.HandObject, fuelTypes)) return true;
			
```

Comment (ilinm1) [reply UnityProject/Assets/Scripts/Objects/Engineering/PowerGenerator.cs]: commited

**Review by NoooneyDude — DISMISSED** [review]

**Review by Bod9001 — DISMISSED** [review]

**Comment by Bod9001** [comment]
gotta fix tests

**Comment by Bod9001** [comment]
would you like help fixing tests

**Comment by ilinm1** [comment]
fix soon

**Comment by ilinm1** [comment]
god, I disabled scene files, why commit included them

**Review by Bod9001 — APPROVED** [review]

**Review by corp-0 — APPROVED** [review]
