### PR TITLE
Some cargo improvements and fixes

### LINKED ISSUE #8280: Cargo system counts "selling" the gas loose inside the cargo shuttle
### Environment
- Game Version: 22012917
- OS Version: Windows 10

### Detailed description of bug

When you send the cargo shuttle to CentCom, the sales log shows the atmosphere inside the shuttle as being sold for 0 credits. In the console's log, this gets broken down per gas per tile, so it massively clutters the UI.

### PR DESCRIPTION
**Pull request by MaxIsJoe**
Fixes #8280

# Changelog:
CL: [Improvement] - Players will now receive text explaining why they died when getting transported on the cargo shuttle.
CL: [Improvement] - Cargo will now recycle worthless items and award 5, 10 or 15 credits per item. (value is random)
CL: [Improvement] - Centeral Communications will now charge 5, 10 or 15 credits per item that contains the trash trait that is thrown in cargo shuttle. (value is random)
CL: [Improvement] - Cargo will now only sell gases in containers that are cargo approved (Like gas canisters).
CL: [Fix] - Fixed cargo randomly refusing to sell some items for no reason.
CL: [Fix] - Fixed cargo refusing to sell bounty items if they were considered worthless.
CL: [Fix] - Fixed cargo selling gas outside containers.

### CODE REVIEW

**Comment by corp-0** [comment]
> layers will now receive text explaining why they died when getting transported on the cargo shuttle.

I thought the cargo shuttle wouldn't leave while players are inside

File: UnityProject/Assets/Scripts/Managers/CargoManager.cs [hunk 1]
```diff
@@ -328,6 +343,13 @@ public void ProcessCargo(GameObject obj, HashSet<GameObject> alreadySold)
 
 			if (obj.TryGetComponent<ItemAttributesV2>(out var itemAttributes))
 			{
+				//charge cargo for getting rid of trash through centeral commmunications.
+				if (itemAttributes.HasTrait(CommonTraits.Instance.Trash))
+				{
+					var chargedPrice = randomJunkPrices.PickRandom();
+					Credits -= chargedPrice;
+					export.ExportMessage += "\n" + $"{chargedPrice} Charged for junk removal for item : {itemAttributes.ArticleName}.";
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Managers/CargoManager.cs:347]: cursed

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Managers/CargoManager.cs:347]: no `AppendLine()` sadly

**Comment by MaxIsJoe** [comment]
> > layers will now receive text explaining why they died when getting transported on the cargo shuttle.
> 
> I thought the cargo shuttle wouldn't leave while players are inside

no it can leave while players on it and you can get yourself killed if it leaves and the cargo gets processed.

**Review by Bod9001 — DISMISSED** [review]

File: UnityProject/Assets/Scripts/Items/Attributes.cs [hunk 2]
```diff
@@ -50,10 +50,9 @@ public int ExportCost
 		}
 	}
 
-	[SerializeField, BoxGroup("Cargo"), PrefabModeOnly]
+	[SerializeField, BoxGroup("Cargo")]
 	[Tooltip("If default, will only be considered exportable if the value is not zero and the object is movable.")]
```
Comment (Alainx277) [inline UnityProject/Assets/Scripts/Items/Attributes.cs]: This tooltip needs to be updated.

File: UnityProject/Assets/Scripts/Managers/CargoManager.cs [hunk 3]
```diff
@@ -49,13 +49,15 @@ public class CargoManager : MonoBehaviour
...
 		public bool RandomBountiesActive = true;
-    private int lastTimeRecorded = 0;
+		private int lastTimeRecorded = 0;
 		private int randomBountyTimeCheck = 0;
 
 		[SerializeField, BoxGroup("Random Bounties")] private float checkForTimeCooldown = 50f;
 		[SerializeField, BoxGroup("Random Bounties")] private Vector2 randomTimeRangeForRandomBounty = new Vector2(320, 690);
 		[SerializeField, BoxGroup("Random Bounties")] private List<CargoBounty> randomBountiesList = new List<CargoBounty>();
 
+		private List<int> randomJunkPrices = new List<int>();
```
Comment (Alainx277) [inline UnityProject/Assets/Scripts/Managers/CargoManager.cs]: You can initialize the list once like this:
```suggestion
		private static readonly List<int> randomJunkPrices = new List<int> { 5, 10, 15 };
```

File: UnityProject/Assets/Scripts/Shuttles/CargoShuttle.cs [hunk 4]
```diff
@@ -169,10 +184,11 @@ private void UnloadCargo()
 				{
 					if (item.TryGetComponent<Attributes>(out var attributes))
 					{
-						if (attributes.ExportType == Attributes.CargoExportType.Never) continue;
+						// Items that cannot be sold in cargo will be ignored unless they have a trait that is assoicated with a bounty
+						if (attributes.CanBeSoldInCargo == false && hasBountyTrait(attributes) == false) continue;
 
 						// Don't sell secured objects e.g. conveyors.
-						if (attributes.ExportType != Attributes.CargoExportType.Always && behaviour.IsNotPushable) continue;
+						if (attributes.CanBeSoldInCargo && behaviour.IsNotPushable) continue;
```
Comment (Alainx277) [inline UnityProject/Assets/Scripts/Shuttles/CargoShuttle.cs:191]: I think this should only be the pushable check?

**Review by Alainx277 — CHANGES_REQUESTED** [review]

File: UnityProject/Assets/Scripts/Shuttles/CargoShuttle.cs (hunk 4 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Shuttles/CargoShuttle.cs:191]: No because sometimes you can have something that can be sold but has been screwed which in that case it shouldn't be sold until it is unscrewed.

**Comment by MaxIsJoe** [comment]
review again pls

File: UnityProject/Assets/Scripts/Shuttles/CargoShuttle.cs (hunk 4 above)
Comment (Alainx277) [reply UnityProject/Assets/Scripts/Shuttles/CargoShuttle.cs:191]: If I'm reading correctly: If I have something that can't be sold normally but has a bounty and it's wrenched to the shuttle, it will still be sold.

You just want to prevent anything that's wrenched being sold, right?

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Shuttles/CargoShuttle.cs:191]: >You just want to prevent anything that's wrenched being sold, right?

Yes

Comment (Alainx277) [reply UnityProject/Assets/Scripts/Shuttles/CargoShuttle.cs:191]: So you can just check `behaviour.IsNotPushable` and `continue` if it is. Maybe I'm misunderstanding?

**Review by Bod9001 — APPROVED** [review]
