### PR TITLE
When calculating if something is "in reach", often checks if something is blocking the way.

### LINKED ISSUE #4282: Fix ability to interact with inaccessible diagonal tile
gif says it all:
diagabuse

### LINKED ISSUE #4896: Directional windows and closed windoors should block interactions.
## Description
Right now, you can interact with anything even if that thing would logically be blocked by a directional window or a closed windoor. This results in such oddities as being able to climb onto tables through windows and snatching items through windows as well. 

It's also possible to swap places with people through windows if both of you are on help intent. This is especially problematic with cells in Pogstation and any other station that uses windoors for cells. An unaware officer might accidentally let a prisoner escape due to swapping places with them through the cell's windoor.

### Steps to Reproduce
1.  On Outpost Station, go to the front of head of personnel's office, preferably without access to said office.  
2.  Drag yourself onto the front table through the windoor. As you can see, you can pass through windoors no problem while climbing.
3.  Drag yourself to the other table to your upper-left. You will diagonally pass through another windoor Notably, this windoor is access restricted and climbing the inner table from the front desk allows you to break into HoP's office as any job.

image
HoP's office in question. You can climb from the bottom table to the table up and to the left even though there's a windoor in the way.

### PR DESCRIPTION
**Pull request by Ruzihm**
Fixes #4896
Fixes #4282 - Edit: It's possible that diagonal tilemap walls/windows/grates might not block. needs testing. This does work with walls spawned in using the admin spawner.

Also makes some additional code style compliant.

### CODE REVIEW

File: UnityProject/Assets/Scripts/Core/Input System/InteractionV2/Validations.cs [hunk 1]
```diff
@@ -221,7 +221,7 @@ private static bool CanInteractByConsciousState(PlayerHealth playerHealth, bool
 
 		var playerObjBehavior = playerScript.pushPull;
 
-		if (!CanInteract(playerScript, side, allowSoftCrit, isPlayerClick: isPlayerClick))
+		if (false == CanInteract(playerScript, side, allowSoftCrit, isPlayerClick: isPlayerClick))
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Core/Input System/InteractionV2/Validations.cs]:
```suggestion
		if (CanInteract(playerScript, side, allowSoftCrit, isPlayerClick: isPlayerClick == false))
```
it may work either way, but I think this is less of a sin (although still sinful, I really hate this part of the guidelines, lol)

File: UnityProject/Assets/Scripts/Objects/Directionals/DirectionalPassable.cs [hunk 2]
```diff
@@ -51,33 +51,32 @@ private void EnsureInit()
...
-			if (context == gameObject || context == null) return true;
+			if (context == gameObject) return true;
 
 			return Passable;
 		}
 
 		public override bool IsPassable(Vector3Int enteringFrom, bool isServer, GameObject context = null)
 		{
-			if (!Passable) return false;
+			if (false == Passable) return false;
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Objects/Directionals/DirectionalPassable.cs]:
```suggestion
			if (Passable == false) return false;
```

File: UnityProject/Assets/Scripts/Objects/Directionals/DirectionalPassable.cs [hunk 3]
```diff
@@ -51,33 +51,32 @@ private void EnsureInit()
...
-			if (context == gameObject || context == null) return true;
+			if (context == gameObject) return true;
 
 			return IsPassableAtSide(GetSideFromVector(enteringFrom), enterableSides);
 		}
 
 		public override bool IsPassableTo(Vector3Int leavingTo, bool isServer, GameObject context = null)
 		{
-			if (!Passable) return false;
+			if (false == Passable) return false;
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Objects/Directionals/DirectionalPassable.cs]:
```suggestion
			if (Passable == false) return false;
```

File: UnityProject/Assets/Scripts/Objects/Directionals/DirectionalPassable.cs [hunk 4]
```diff
@@ -51,33 +51,32 @@ private void EnsureInit()
...
-			if (context == gameObject || context == null) return true;
+			if (context == gameObject) return true;
 
 			return IsPassableAtSide(GetSideFromVector(leavingTo), leavableSides);
 		}
 
 		public override bool IsAtmosPassable(Vector3Int enteringFrom, bool isServer)
 		{
-			if (!AtmosPassable) return false;
+			if (false == AtmosPassable) return false;
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Objects/Directionals/DirectionalPassable.cs]:
```suggestion
			if (AtmosPassable == false) return false;
```

**Comment by corp-0** [comment]
Code looks good. I don't have enough free time to test it on editor.

File: UnityProject/Assets/Scripts/Core/Input System/InteractionV2/Validations.cs [hunk 5]
```diff
@@ -352,28 +352,71 @@ private static bool CanInteractByConsciousState(PlayerHealth playerHealth, bool
...
+
+
+	/// <summary>
+	/// Checks if two position vectors are is within interaction distance AND also there is no blocking element between them
+	/// </summary>
+	/// <param name="fromWorldPos">One position of the interaction</param>
+	/// <param name="interactDist">The Other position of the interaction</param>
+	/// <param name="isServer">Whether or not this call is occurring on the server</param>
+	/// <returns>true if the x and y distance of interaction are less than interactDist and there is no blockage. False otherwise.</returns>
+	public static bool IsInReach(Vector3 fromWorldPos, Vector3 toWorldPos, bool isServer, float interactDist = PlayerScript.interactionDistance, GameObject context = null)
```
Comment (fomalsd) [inline UnityProject/Assets/Scripts/Core/Input System/InteractionV2/Validations.cs:401]: please add to the doc above what `context` is

File: UnityProject/Assets/Scripts/Core/Input System/InteractionV2/Validations.cs [hunk 6]
```diff
@@ -385,17 +428,15 @@ public static bool IsInReach(Vector3 fromWorldPos, Vector3 toWorldPos, float int
 	/// <param name="isServer"></param>
 	/// <param name="interactDist"></param>
 	/// <returns></returns>
-	public static bool IsInReach(RegisterTile from, RegisterTile to, bool isServer, float interactDist = PlayerScript.interactionDistance)
+	public static bool IsInReach(RegisterTile from, RegisterTile to, bool isServer, float interactDist = PlayerScript.interactionDistance, GameObject context = null)
```
Comment (fomalsd) [inline UnityProject/Assets/Scripts/Core/Input System/InteractionV2/Validations.cs:434]: same here

**Comment by NoooneyDude** [comment]
Hmm. This breaks pushing around unsecured disposal intakes (and perhaps unsecured directional windows).

I also can't seem to be able to pick anything up or drag things, including my character.

**Comment by corp-0** [comment]
adding a DNM until we figure out the problem with pushing stuff

**Comment by Ruzihm** [comment]
I just noticed one of corp-0's suggestions put the one of the `== false`
inside of some parenthesis it shouldn't be in. Does that help fix the
problem? Can't login to github atm.

**Comment by Ruzihm** [comment]
Does fixing that typo fix the problem* I mean

**Comment by corp-0** [comment]
oops sorry. I did suggestions from my phone.

**Comment by Ruzihm** [comment]
No worries! I was just confused because I had no problems picking things up
like pdas, ID cards, or the chain of command.

I didn't try pushing things like unsecured disposal intakes or directional
windows. I would not be surprised if being unable to push those is
something I need to make a small fix for

**Comment by Ruzihm** [comment]
@NoooneyDude Can you confirm that the bugs you found are now fixed? 

I added a **Reachable Through** property to RegisterObject but I'm not sure what objects it should be enabled on. I went ahead and enabled it on disposals because I know you need to be able to grab things that it expels. 

Edit: just to clarify, **Reachable Through** does not need to be enabled to allow pushing an object.

**Comment by NoooneyDude** [comment]
Can now pick things up, but still can't push unsecured disposal intakes. I also can't leave the disposal intake tile if I'm standing on top of one, too.

**Comment by Ruzihm** [comment]
@NoooneyDude Disposalintake to be have Passable enabled and setting leavable directional down as enabled fixed the leaving problem. Can you confirm? 

 I think I know how to fix the pushing problem. Will work on that next.

**Comment by Ruzihm** [comment]
Please test when able.

**Comment by NoooneyDude** [comment]
Directional windows and disposal intakes now work flawlessly. Thank you!
