### PR TITLE
Object shatter on thrown

### LINKED ISSUE #5744: things like bottles should break when thrown
### Description

This is a very simple request. When a fragile item, such as an egg or a bottle is thrown, they should shatter/break, leaving behind broken parts, such as glass shards. It would be useful if this was added to the throwing component and also it should be configurable to spawn whatever broken item that is needed.

### PR DESCRIPTION
**Pull request by Emma3DSS**
### Purpose
fixes #5744 throw them bottles

### Notes:
needs testing

### CODE REVIEW

File: UnityProject/Assets/Scripts/Items/ThrowableBreakable.cs [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+	public class ThrowableBreakable : MonoBehaviour
+	{
+		[SerializeField]
+		private GameObject brokenItem = default;
+
+		[SerializeField, Range(0, 100)]
+		private int chanceToBreak = 100;
+
+		[SerializeField]
+		private AddressableAudioSource soundToPlay = SingletonSOSounds.Instance.GlassBreak01;
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/Items/ThrowableBreakable.cs]: can you check quickly that if you change it on the prefab it doesn't change it for the Bass sound

Comment (Emma3DSS) [reply UnityProject/Assets/Scripts/Items/ThrowableBreakable.cs]: sorry what do you mean by this?

Comment (Bod9001) [reply UnityProject/Assets/Scripts/Items/ThrowableBreakable.cs]: so, if you change the prefab, does it change the SO?

Comment (corp-0) [reply UnityProject/Assets/Scripts/Items/ThrowableBreakable.cs]: it is changing the prefab. If it was changing a value on the SO it would be persistent.

File: UnityProject/Assets/Scripts/Items/ThrowableBreakable.cs [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+			customNetTransform = GetComponent<CustomNetTransform>();
+			customNetTransform.OnThrowEnd.AddListener(MyListener);
+		}
+
+		private void OnDisable()
+		{
+			customNetTransform.OnThrowEnd.RemoveListener(MyListener);
+		}
+
+		private void MyListener(ThrowInfo info)
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Items/ThrowableBreakable.cs]:
```suggestion
		private void OnThrown(ThrowInfo info)
```

**Comment by corp-0** [comment]
tests are failing for the same reason they failed for Pet. I have no idea what's up with that, someone who has worked on addressables needs to check it out. @JesterX666

File: UnityProject/Assets/Scripts/Items/ThrowableBreakable.cs [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+			customNetTransform = GetComponent<CustomNetTransform>();
+			customNetTransform.OnThrowEnd.AddListener(MyListener);
+		}
+
+		private void OnDisable()
+		{
+			customNetTransform.OnThrowEnd.RemoveListener(MyListener);
+		}
+
+		private void OnThrown(ThrowInfo info)
```
Comment (NoooneyDude) [inline UnityProject/Assets/Scripts/Items/ThrowableBreakable.cs:37]: Method was renamed to `OnThrown` but lines 25, 30 weren't updated to reflect the changes.

File: UnityProject/Assets/Scripts/Items/ThrowableBreakable.cs [hunk 4]
```diff
@@ -0,0 +1,44 @@
...
+
+		[SerializeField]
+		private AddressableAudioSource soundToPlay = SingletonSOSounds.Instance.GlassBreak01;
+
+		private CustomNetTransform customNetTransform;
+
+		private void Start()
+		{
+			customNetTransform = GetComponent<CustomNetTransform>();
+			customNetTransform.OnThrowEnd.AddListener(MyListener);
```
Comment (NoooneyDude) [inline UnityProject/Assets/Scripts/Items/ThrowableBreakable.cs]:
```suggestion
			customNetTransform.OnThrowEnd.AddListener(OnThrown);
```

File: UnityProject/Assets/Scripts/Items/ThrowableBreakable.cs [hunk 5]
```diff
@@ -0,0 +1,44 @@
...
+		}
+
+		private void OnDisable()
+		{
+			customNetTransform.OnThrowEnd.RemoveListener(MyListener);
```
Comment (NoooneyDude) [inline UnityProject/Assets/Scripts/Items/ThrowableBreakable.cs]:
```suggestion
			customNetTransform.OnThrowEnd.RemoveListener(OnThrown);
```

**Comment by NoooneyDude** [comment]
Tests are failing because it turns out you cannot currently assign a value from a `SingletonScriptableObject` to a serialized field, as is done for `soundToPlay`. See https://discord.com/channels/273774715741667329/312454684021620736/790095513412304896.

Going back to the old way of having a serialized bool for using custom sound which will show a second field for the sound is one solution to this problem.
