### PR TITLE
Fixes plant stats from going over 100

### LINKED ISSUE #5602: Stats for plants can still go over 100.
### Environment
- Game Version: Staging 5538
- OS Version: Windows 10

### Detailed description of bug
Plant potency can still go over 100 even after #4520, which supposedly capped potency to 100. This is quite bad in regards to combustible lemons, due to how destructive they can get. How to get plants to go over potency cap is unknown.
overcap

### PR DESCRIPTION
**Pull request by Aranclanos**
### Purpose
Fixes plant stats from going over 100.
Fixes #5602

### CODE REVIEW

File: UnityProject/Assets/Scripts/Systems/Botany/PlantData.cs [hunk 1]
```diff
@@ -205,87 +206,76 @@ public void Mutation()
...
+					Lifespan = StatMutation(Lifespan, StatMutationType.Special);
 					break;
 			}
 
-			CheckMutation(WeedResistance, 0, 100);
-			CheckMutation(WeedGrowthRate, 0, 100);
-			CheckMutation(GrowthSpeed, 0, 100);
-			CheckMutation(Potency, 0, 100);
-			CheckMutation(Endurance, 0, 100);
-			CheckMutation(Yield, 0, 100);
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/Systems/Botany/PlantData.cs:251]: the problem is with some of these that they're not supposed to go to hundred but look like someone accidentally set them to go to hundred, should this be included as part of PR?
image

Comment (Bod9001) [reply UnityProject/Assets/Scripts/Systems/Botany/PlantData.cs:251]: tho idk if they changed the corresponding code to match the new scheme
