### PR TITLE
Bike horn (and some refactoring)

### LINKED ISSUE #2069: Some objects on walls aren't visible
# Description
When the player spawns in, there are some objects like medbay signs or fire extinguisher cabinets that aren't visible, even if the player is in the right range. However when a player closes himself in a locker and is in the right range, these objects will appear and work perfectly fine from that point on.

## Category
BUG

### LINKED ISSUE #2072: You can shoot guns inside lockers
# Description
You can shoot inside lockers.

And it doesn't look too good, you actually just get recoil effect and literally nothing else happens, not even bullets appear.

## Category
BUG

## Detailed Bug Report
TODO: Remove shooting insided locker.

## Steps to Reproduce
Get in the locker with a machine gun and ratatatatatata

### LINKED ISSUE #2073: Spacewalking doesn't cause damage or Alerts
# Description
You no longer take damage from spacewalking

## Category
BUG or TODO?

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Develop
2. Run out in space
3. Observe no damage taken

### LINKED ISSUE #2090: Opened lockers are considered solid for late joiners
# Description
GIF

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Host server in build, open one locker
2. Join server from editor, approach opened locker
(you'll predictive push it once and then it'll get stuck)

### PR DESCRIPTION
**Pull request by fomalsd**
### Purpose
Fixes #2069 
Fixes #2073
Fixes #2090 
Gives clown something to do (has a chance to harm eardrums when honked in close proximity)
GIF

Synchronizes player (dis)appearance with closet door
Adds "polyphonic sound" option, so that more than one instance of sound could be played
Removes VisibleBehaviour and ClosetPlayerHandler
Makes ObjectBehaviour kinda redundant (as it's identical to PushPull)
If you need to make something (dis)appear you can just set its VisibleState boolean

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [x]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### Notes:
You'll need to spawn it manually as there's no way to spawn prefabs as part of job outfits yet (see #2091)
This needs to be tested on live server to see if WaitForCameraToReachCloset stuff is still relevant

### CODE REVIEW

**Comment by fomalsd** [comment]
Also looks like this PR introduces a reproduction case for #1699.
Try getting an Extinguisher out of Fire Cabinet and you'll experience it

File: UnityProject/Assets/Scripts/Closets/ClosetControl.cs [hunk 1]
```diff
@@ -131,6 +131,12 @@ private void SetIsLocked(bool value)
 		}
 	}
 
+	public IEnumerator ChangeSpriteDelayed()
+	{
+		yield return WaitFor.EndOfFrame;
```
Comment (Aranclanos) [inline UnityProject/Assets/Scripts/Closets/ClosetControl.cs:136]: why it needs a delay? In byond the spawn(0) caused a lot of problems which is basically a small wait and Id prefer to avoid them

File: UnityProject/Assets/Scripts/Items/Others/Horn.cs [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+		SoundManager.PlayNetworkedAtPos( Sound, gameObject.AssumedWorldPosServer(), -1f, true, true, 20, 5 );
+		targetHealth.ApplyDamage( clickData.Performer, CritDamage, AttackType.Energy, DamageType.Brute, BodyPartType.Head );
+	}
+
+	/// <summary>
+	///	honk on activate
+	/// </summary>
+	protected override void ServerPerformInteraction( HandActivate interaction )
+	{
+		TryHonk();
```
Comment (Aranclanos) [inline UnityProject/Assets/Scripts/Items/Others/Horn.cs]: why not just call classichonk()

File: UnityProject/Assets/Scripts/Items/Others/Horn.cs [hunk 3]
```diff
@@ -0,0 +1,118 @@
...
+
+	private bool allowUse = true;
+	private float randomPitch => Random.Range( 0.7f, 1.2f );
+
+	private IEnumerator CoolDown()
+	{
+		allowUse = false;
+		yield return WaitFor.Seconds(Cooldown);
+		allowUse = true;
+	}
```
Comment (Aranclanos) [inline UnityProject/Assets/Scripts/Items/Others/Horn.cs:32]: the cooldown usage is a bit weird, honking with my hand will make me unable to use it on another player until the cd ends, even if WillInteract() is accepted
names like CoolDown() and Cooldown are also a bit confusing

File: UnityProject/Assets/Scripts/Items/Others/Horn.cs [hunk 4]
```diff
@@ -0,0 +1,118 @@
...
+
+		// simple honk on activate
+		if ( clickData == null )
+		{
+			ClassicHonk();
+		}
+		else
+		{
+			bool inCritRange = PlayerScript.IsInReach( clickData.TargetVector );
+			var targetHealth = clickData.TargetObject.GetComponent<LivingHealthBehaviour>();
```
Comment (Aranclanos) [inline UnityProject/Assets/Scripts/Items/Others/Horn.cs]: it would be better to calculate isCrit first before these two lines

File: UnityProject/Assets/Scripts/Player/PlayerSync.cs [hunk 5]
```diff
@@ -396,19 +396,36 @@ public void setLocalPlayer()
 		predictedSpeedClient = UIManager.WalkRun.running ? playerMove.RunSpeed : playerMove.WalkSpeed;
 	}
 
+	private bool didWiggle = false;
```
Comment (Aranclanos) [inline UnityProject/Assets/Scripts/Player/PlayerSync.cs:403]: this might need a summary or small comment

**Comment by Aranclanos** [comment]
if possible for next stuff try to separate the changes on different prs

File: UnityProject/Assets/Scripts/Closets/ClosetControl.cs (hunk 1 above)
Comment (fomalsd) [reply UnityProject/Assets/Scripts/Closets/ClosetControl.cs:136]: otherwise player disappearance/appearance is always one frame late, didn’t dig too deep to learn why in order to keep sanity

File: UnityProject/Assets/Scripts/Items/Others/Horn.cs (hunk 2 above)
Comment (fomalsd) [reply UnityProject/Assets/Scripts/Items/Others/Horn.cs]: because of cooldown check inside that method

File: UnityProject/Assets/Scripts/Items/Others/Horn.cs (hunk 3 above)
Comment (fomalsd) [reply UnityProject/Assets/Scripts/Items/Others/Horn.cs:32]: are you planning to honk faster than 5 HPS (honks per second)? don’t know of any clowns that can honk this fast
it’s more of a precaution against script abuse

File: UnityProject/Assets/Scripts/Items/Others/Horn.cs (hunk 4 above)
Comment (fomalsd) [reply UnityProject/Assets/Scripts/Items/Others/Horn.cs]: it’s not used outside, but I’ll try to make this part easier to understand

File: UnityProject/Assets/Scripts/Player/PlayerSync.cs (hunk 5 above)
Comment (fomalsd) [reply UnityProject/Assets/Scripts/Player/PlayerSync.cs:403]: yeah

File: UnityProject/Assets/Scripts/Items/Others/Horn.cs (hunk 3 above)
Comment (fomalsd) [reply UnityProject/Assets/Scripts/Items/Others/Horn.cs:32]: oh, I get what you mean. added cooldown check to WillInteract instead
