### PR TITLE
Fixes the defribillator not returning ghosts to their bodies

### LINKED ISSUE #6303: Alternative forms of resuscitation dont put players in their body
### Environment 
- Game Version: Staging 21032700
- OS Version: Windows 10

### Detailed description of bug

Currently, all other forms of resuscitation (CPR/Defibrillation) do not put players back in their body, and do not provide a warning that they are being revived.

### Steps to reproduce

1. Restart someone's heart with a defibrillator (or cpr to restart heart)
2. Wait for them to stand up
3. They wont stand up.. the ghost player isn't aware that they just got "revived"

### PR DESCRIPTION
**Pull request by Aranclanos**
### Purpose
CL: [Fix] Players revived by the defibrillator will now return to their bodies if they're a ghost
Fixes #6303

### CODE REVIEW

**Review by MaxIsJoe — APPROVED** [review]

File: UnityProject/Assets/Scripts/Items/Medical/DefibrillatorPaddles.cs [hunk 1]
```diff
@@ -17,7 +17,8 @@ public bool WillInteract(HandApply interaction, NetworkSide side)
 	{
 		if (DefaultWillInteract.Default(interaction,side) == false)
 			return false;
-		if (interaction.TargetObject.GetComponent<LivingHealthMasterBase>() == null)
+		var livingHealthMaster = interaction.TargetObject.GetComponent<LivingHealthMasterBase>();
+		if (livingHealthMaster == null)
 			return false;
 		var equipment = interaction.Performer.GetComponent<Equipment>();
 		var ObjectInSlot = equipment.GetClothingItem(NamedSlot.back).GameObjectReference;
```
Comment (NoooneyDude) [inline UnityProject/Assets/Scripts/Items/Medical/DefibrillatorPaddles.cs:24]: Possible runtime if a mob is the target? Or do they have Equipment component too?

Comment (Aranclanos) [reply UnityProject/Assets/Scripts/Items/Medical/DefibrillatorPaddles.cs:24]: the equipment check is for the player using the defibrillator, not the target. It's to check if they have it equipped and aren't running around with only the paddles

Comment (NoooneyDude) [reply UnityProject/Assets/Scripts/Items/Medical/DefibrillatorPaddles.cs:24]: D'oh. Of course.

**Review by NoooneyDude — APPROVED** [review]

**Review by ThatDan123 — APPROVED** [review]
