### PR TITLE
Continues improvements for laying down behavior

### LINKED ISSUE #9753: [BUG] People randomly being sideways.
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

23032711

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

Sometimes people will randomly appear sideways but otherwise walk, talk, interact, etc. the same. Throwing them typically fixes the issue. It's just a very annoying visual bug.

### What should have happened instead?

People should only be sideways if they are lying down.

### Steps to reproduce the issue

1. Don't know it seems to be random when playing.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MaxIsJoe**
cleaned up some of the movement code while I'm at it
fixes #9753

CL: [Improvement] Flying and sliding animations now target the sprites instead of the Mob's root gameobject. Making the behavior much more consistent. 
CL: [Improvement] Burning animations and body overlays will now correctly follow the body sprites's rotation.
CL: [Fix] Whenever the server asks to ensure mob's laying down state, it will notify all clients respectively as well.

### CODE REVIEW

File: UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs [hunk 1]
```diff
@@ -310,6 +274,24 @@ public virtual void Awake()
 		registerTile = GetComponent<RegisterTile>();
 		rotatable = GetComponent<Rotatable>();
 		pickupable.DirectSetComponent(GetComponent<Pickupable>());
+		SetRotationTarget();
+	}
+
+	private void SetRotationTarget()
+	{
+		if (rotationTarget != null) return;
+		if (this is MovementSynchronisation c && c.playerScript.RegisterPlayer.LayDownBehavior != null)
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs:283]: base class shouldn't handle cases for a child class. Can you make this method protected virtual and do the second part of the if on the subclass?

Comment (corp-0) [reply UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs:283]: nevermind, I just took a look at this class and the subclass. I wouldn't want to touch any of that either.

**Review by corp-0 — APPROVED** [review]
