### PR TITLE
Drunk effect

### LINKED ISSUE #7925: Drunk effect flicks on and off
When drinking, the camera effect turns on and off, it looks to an issue where you are on the verge of being drunk but your blood alcohol is not stable above the threadhold. Could be related too #7142

### LINKED ISSUE #9488: Drunk effect no longer works
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

23010820

### I was

Client

### OS

Mac

### What happened?

Drunkenness exists in that your liver will explode from toxin damage, but the effect no longer shows up.

### What should have happened instead?

The drunk effect should've been overlayed.

### Steps to reproduce the issue

1.) Go to the bar.
2.) Drink.
3.) Repeat step 2 and 3.

### Additional context

Screen Shot 2023-01-09 at 5 19 38 PM

### PR DESCRIPTION
**Pull request by Bod9001**
fixes: #9488
fixes: #7925

### Changelog:

CL: [New] Mutations for alcohol resistance and susceptibility
CL: [New] kidneys actually do something now ( clearing ethanol out of the blood )
CL: [Improvement] Drug effect now has a range depending on how much you drink
CL: [Fix] fixes Drunk effect

### CODE REVIEW

**Comment by Fr-Dae** [comment]
https://github.com/unitystation/unitystation/issues/9488
https://github.com/unitystation/unitystation/issues/7925
https://github.com/unitystation/unitystation/issues/7415

File: UnityProject/Assets/Scripts/HealthV2/Living/Mutations/Brain/AlcoholEffectMutation.cs [hunk 1]
```diff
@@ -0,0 +1,40 @@
+using UnityEngine;
+
+namespace HealthV2.Living.Mutations.Brain
+{
+	[CreateAssetMenu(fileName = "AlcoholEffectMutation", menuName = "ScriptableObjects/Mutations/AlcoholEffectMutation")]
+	public class AlcoholEffectMutation  : MutationSO
```
Comment (MaxIsJoe) [inline UnityProject/Assets/Scripts/HealthV2/Living/Mutations/Brain/AlcoholEffectMutation.cs:6]: why is drunkness a mutation now?

File: UnityProject/Assets/Scripts/HealthV2/Living/Mutations/Brain/AlcoholEffectMutation.cs [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+
+			public InAlcoholEffectMutations(BodyPart BodyPart,MutationSO _RelatedMutationSO, float NewDrugResistanceAddFraction) : base(BodyPart,_RelatedMutationSO)
+			{
+				DrugResistanceAddFraction = NewDrugResistanceAddFraction;
+			}
+
+			public override void SetUp()
+			{
+				RelatedBrain = BodyPart.GetComponent<Items.Implants.Organs.Brain>();
+				RelatedBrain.MaxDrunkAtPercentage += DrugResistanceAddFraction;
```
Comment (MaxIsJoe) [inline UnityProject/Assets/Scripts/HealthV2/Living/Mutations/Brain/AlcoholEffectMutation.cs:30]: `RelatedBrain?.MaxDrunkAtPercentage += DrugResistanceAddFraction;`

File: UnityProject/Assets/Scripts/HealthV2/Living/Mutations/Brain/AlcoholEffectMutation.cs [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+			}
+
+			public override void Remove()
+			{
+				RelatedBrain.MaxDrunkAtPercentage -= DrugResistanceAddFraction;
```
Comment (MaxIsJoe) [inline UnityProject/Assets/Scripts/HealthV2/Living/Mutations/Brain/AlcoholEffectMutation.cs:35]: `RelatedBrain?.MaxDrunkAtPercentage -= DrugResistanceAddFraction;`

File: UnityProject/Assets/Scripts/Systems/Chemistry/ReagentMix.cs [hunk 4]
```diff
@@ -339,6 +339,11 @@ public float Remove(Reagent reagent, float amount)
 				return 0;
 			}
 
+			if (amount == 0f)
```
Comment (MaxIsJoe) [inline UnityProject/Assets/Scripts/Systems/Chemistry/ReagentMix.cs]: use Mathf.Approximately

File: UnityProject/Assets/Scripts/UI/Systems/Lobby/CharacterCustomization.cs [hunk 5]
```diff
@@ -510,6 +510,25 @@ public void SetUpBodyPart(BodyPart bodyPart, bool instantiateCustomisations = tr
 						SetUpBodyPart(subBodyPart);
 					}
 				}
+
+				if (bodyPart.OrNull()?.OrganStorage.OrNull()?.Populater?.SlotContents != null)
+				{
+					foreach (var organ in bodyPart.OrganStorage.Populater.SlotContents)
+					{
+						if (organ == null || organ.Prefab) continue;
```
Comment (MaxIsJoe) [inline UnityProject/Assets/Scripts/UI/Systems/Lobby/CharacterCustomization.cs]: why are we continuning if `organ.Prefab` is true?

**Review by MaxIsJoe — CHANGES_REQUESTED** [review]

File: UnityProject/Assets/Scripts/HealthV2/Living/Mutations/Brain/AlcoholEffectMutation.cs [hunk 6]
```diff
@@ -0,0 +1,40 @@
...
+			public float DrugResistanceAddFraction = 0;
+
+			public InAlcoholEffectMutations(BodyPart BodyPart,MutationSO _RelatedMutationSO, float NewDrugResistanceAddFraction) : base(BodyPart,_RelatedMutationSO)
+			{
+				DrugResistanceAddFraction = NewDrugResistanceAddFraction;
+			}
+
+			public override void SetUp()
+			{
+				RelatedBrain = BodyPart.GetComponent<Items.Implants.Organs.Brain>();
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/HealthV2/Living/Mutations/Brain/AlcoholEffectMutation.cs:29]: just add the using statement. It looks very ugly like that

File: UnityProject/Assets/Scripts/HealthV2/Living/Mutations/Brain/AlcoholEffectMutation.cs (hunk 2 above)
Comment (corp-0) [reply UnityProject/Assets/Scripts/HealthV2/Living/Mutations/Brain/AlcoholEffectMutation.cs:30]: ``RelatedBrain`` is likely a unity object, so it would be ``OrNull()?``

File: UnityProject/Assets/Scripts/HealthV2/Living/Mutations/Brain/AlcoholEffectMutation.cs (hunk 1 above)
Comment (corp-0) [reply UnityProject/Assets/Scripts/HealthV2/Living/Mutations/Brain/AlcoholEffectMutation.cs:6]: I agree ethimologically it doesn't make sense, but the player effect system didn't take off. Seems like we are making everything a mutation now, which isn't really that bad.

File: UnityProject/Assets/Scripts/Systems/Inventory/Inventory.cs [hunk 7]
```diff
@@ -656,15 +656,25 @@ public static void PopulateSubInventory(ItemStorage itemStorage, List<SlotPopula
...
-			if (namedSlotPopulatorEntry.UesIndex)
+			if (namedSlotPopulatorEntry.DoNotGetFirstEmptySlot == false)
 			{
-				ItemSlot = itemStorage.GetIndexedItemSlot(namedSlotPopulatorEntry.IndexSlot);
+				ItemSlot =  itemStorage.GetNextEmptySlot();
 			}
 			else
 			{
-				ItemSlot = itemStorage.GetNamedItemSlot(namedSlotPopulatorEntry.NamedSlot);
+				if (namedSlotPopulatorEntry.UesIndex)
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Systems/Inventory/Inventory.cs]: what the hell is a ``UesIndex``

File: UnityProject/Assets/Scripts/HealthV2/Living/Mutations/Brain/AlcoholEffectMutation.cs (hunk 1 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/HealthV2/Living/Mutations/Brain/AlcoholEffectMutation.cs:6]: Wouldn't it be better to make it a status effect then, rather than a mutation? Because drunkness isn't a mutation, it's an effect caused by something you can find in multiple factors that also isn't just alcohol.

File: UnityProject/Assets/Scripts/UI/Systems/Lobby/CharacterCustomization.cs (hunk 5 above)
Comment (corp-0) [reply UnityProject/Assets/Scripts/UI/Systems/Lobby/CharacterCustomization.cs]: likely, it is missing another comparison with null.

``organ.OrNull()?.Prefab == null`` would make it better.

File: UnityProject/Assets/Scripts/Systems/Inventory/Inventory.cs (hunk 7 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Systems/Inventory/Inventory.cs]: no comments? no explanations for the why?

image

File: UnityProject/Assets/Scripts/HealthV2/Living/Mutations/Brain/AlcoholEffectMutation.cs (hunk 1 above)
Comment (Bod9001) [reply UnityProject/Assets/Scripts/HealthV2/Living/Mutations/Brain/AlcoholEffectMutation.cs:6]: this is not the drunkenness itself, It's just modifying Susceptibility to drunkenness

File: UnityProject/Assets/Scripts/HealthV2/Living/Mutations/Brain/AlcoholEffectMutation.cs (hunk 2 above)
Comment (Bod9001) [reply UnityProject/Assets/Scripts/HealthV2/Living/Mutations/Brain/AlcoholEffectMutation.cs:30]: Theoretically it shouldn't be null, since you have to manually place it on brings

File: UnityProject/Assets/Scripts/HealthV2/Living/Mutations/Brain/AlcoholEffectMutation.cs (hunk 6 above)
Comment (Bod9001) [reply UnityProject/Assets/Scripts/HealthV2/Living/Mutations/Brain/AlcoholEffectMutation.cs:29]: using?

Comment (corp-0) [reply UnityProject/Assets/Scripts/HealthV2/Living/Mutations/Brain/AlcoholEffectMutation.cs:29]:
```cs
using Items.Implants.Organs;

...
RelatedBrain = BodyPart.GetComponent<Brain>();
```

File: UnityProject/Assets/Scripts/HealthV2/Living/Mutations/Brain/AlcoholEffectMutation.cs (hunk 2 above)
Comment (corp-0) [reply UnityProject/Assets/Scripts/HealthV2/Living/Mutations/Brain/AlcoholEffectMutation.cs:30]: sorry, I replied to the wrong comment by Max

File: UnityProject/Assets/Scripts/Systems/Inventory/Populators/Storage/PlayerSlotStoragePopulator.cs [hunk 8]
```diff
@@ -167,15 +163,18 @@ public class SlotPopulatorEntry
...
+
+		[Tooltip("  The Index lot that the prefab will be spawned into " )]
 		public int IndexSlot = 0;
 
-		public bool IfOccupiedFindEmptyIndexSlot = true;
+		public bool IfOccupiedFindEmptySlot = true;
 
-		public bool UseIndex = false;
+		[Tooltip(" Place object in Specified indexed slot or Use named slot Identifer ")]
+		public bool UesIndex = false;
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Systems/Inventory/Populators/Storage/PlayerSlotStoragePopulator.cs]:
```suggestion
		public bool UseIndex = false;
```

or perhaps
```suggestion
		public bool ForceIndex = false;
```

**Comment by corp-0** [comment]
```
The script for a component on AlienDrone could not be loaded.
The script for a component on AlienHunter could not be loaded.
The script for a component on AlienMatureLarva could not be loaded.
The script for a component on AlienNewbornLarva could not be loaded.
The script for a component on AlienPraetorian could not be loaded.
The script for a component on AlienQueen could not be loaded.
The script for a component on AlienSentinel could not be loaded.
The script for a component on AlienYoungLarva could not be loaded.
The script for a component on TheWelder could not be loaded.
The script for a component on Player_V4(uNet) could not be loaded.
```

did you delete a script or something?
