### PR TITLE
Fixed #829, removed an old Debug.Log, added suicide PNA-hook.

### LINKED ISSUE #829: Dying inside closet doesn't spawn ghost sprite and opens closet on moving
# Preliminary information

## Category
BUG

## Bug: Release or Development?
Develop

# Report
## Current Behavior
When you die while being in a closet, you don't spawn a ghost sprite, but you do open up the closet when moving after dying. tested with High ping, should be there without it too.

## Expected/Wanted/Requested Behavior
You should just ghost, leaving the closet how it is.

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Die in closet
2. Move as after death
3.

## OS used:
OSX

## System specifications
MBP-r 2012

## Network
High ping, headless

### PR DESCRIPTION
**Pull request by JacobSweeten**
### Purpose
Fixed #829, removed an old Debug.Log, added suicide.

### Approach
Made player closet behaviour stop updating the player when ghosted. Made ghost impossible to make invisible. Removed player closet behaviour when respawning.

### Open Questions and Pre-Merge TODOs

- [X]  I read the contribution guidelines and the wiki.
- [X]  This fix is tested on the same branch it is PR'ed to.
- [X]  I correctly commented my code
- [X]  This PR does not include files without specific need to do so.
- [X]  This PR does not bring up any new compile errors
- [X]  This PR has been tested in editor
- [X]  This PR has been tested in multiplayer

### Notes:
Suicide is backspace, Must be un-commented in InputController.cs first. Fixed improper naming on a function.

### CODE REVIEW

**Comment by JacobSweeten** [comment]
Can do. I'm at work right now though.

File: UnityProject/Assets/Scripts/Closets/ClosetPlayerHandler.cs [hunk 1]
```diff
@@ -38,6 +39,17 @@ public void Init(ClosetControl closetCtrl)
...
+			{
+				Camera2DFollow.followControl.damping = 0.0f;
+				return;
+			}
+			else
+			{
+				// In case we re-enter corpse
+				Camera2DFollow.followControl.damping = 0.2f;
+			}
+
```
Comment (DooblyNoobly) [inline UnityProject/Assets/Scripts/Closets/ClosetPlayerHandler.cs]: What happens if LocalPlayerScript is null (When there is a few frames of spawning new player) and what happens if Camera2DFollow.followControl.damping needs to be set to something different from another object in a different scenario? This condition in all of the closets Update loops will override that. I would like you to come up with a better solution to changing the damping if a player turns into a ghost. You could just always set the damping property once whenever a player turns into a ghost no matter if they are in a closet or not (maybe in the local client of HealthBehaviour) then you can get rid of this condition.

File: UnityProject/Assets/Scripts/Objects/VisibleBehaviour.cs [hunk 2]
```diff
@@ -36,6 +36,9 @@ public class VisibleBehaviour : NetworkBehaviour
 		closetHandler
 	};
 
+	public GameObject[] ignoreSpriteUpdates;
+	private SpriteRenderer[] ignoredSpriteRenderers;
```
Comment (DooblyNoobly) [inline UnityProject/Assets/Scripts/Objects/VisibleBehaviour.cs]: Why not just make this public and drag the spriterenderers into the inspector? You just need to drag the whole game object and it will take the sprite renderer from it

File: UnityProject/Assets/Scripts/Objects/VisibleBehaviour.cs [hunk 3]
```diff
@@ -57,6 +60,16 @@ public override void OnStartClient()
...
+
+		ignoredSpriteRenderers = new SpriteRenderer[ignoreSpriteUpdates.Length];
+		for (int i = 0; i < ignoreSpriteUpdates.Length; i++)
+		{
+			SpriteRenderer sr = ignoreSpriteUpdates[i].GetComponent<SpriteRenderer>();
+			if (sr != null)
+			{
+				ignoredSpriteRenderers[i] = sr;
+			}
+		}
```
Comment (DooblyNoobly) [inline UnityProject/Assets/Scripts/Objects/VisibleBehaviour.cs]: You wouldn't need this loop if you make ignoredSpriteRenders public and just drag them in

File: UnityProject/Assets/Scripts/Objects/VisibleBehaviour.cs [hunk 4]
```diff
@@ -109,7 +134,12 @@ private void UpdateState(bool _aliveState)
 		}
 	}
 
-	private bool canBeDisabled(MonoBehaviour script)
+	private bool CanBeDisabled(SpriteRenderer script)
+	{
```
Comment (DooblyNoobly) [inline UnityProject/Assets/Scripts/Objects/VisibleBehaviour.cs]: I know its a small thing but the parameter here should not be called script. Call it something related to a renderer

File: UnityProject/Assets/Scripts/Objects/VisibleBehaviour.cs [hunk 5]
```diff
@@ -93,7 +106,19 @@ private void UpdateState(bool _aliveState)
 
 		for (int i = 0; i < renderers.Length; i++)
 		{
-			renderers[i].enabled = _aliveState;
+			// Cast and check cast
+			SpriteRenderer sr = renderers[i] as SpriteRenderer;
+			if (sr != null)
+			{
```
Comment (DooblyNoobly) [inline UnityProject/Assets/Scripts/Objects/VisibleBehaviour.cs]: Is this needed? renderers should only have SpriteRenderers in them anyway

File: UnityProject/Assets/Scripts/Objects/VisibleBehaviour.cs [hunk 6]
```diff
@@ -93,7 +106,19 @@ private void UpdateState(bool _aliveState)
...
+			if (sr != null)
+			{
+				if (CanBeDisabled(sr))
+				{
+					sr.enabled = _aliveState;
+				}
+			}
+			else
+			{
+				renderers[i].enabled = _aliveState;
```
Comment (DooblyNoobly) [inline UnityProject/Assets/Scripts/Objects/VisibleBehaviour.cs]: This is weird because you are saying that if renderers does not contain a renderer then disable the renderer that according to this condition should not contain a renderer. Very confusing. You don't need this at all. Just remove the whole condition and check if:
```
if(CanBeDisabled(renderers[i]){
renderers[i].enabled = _aliveState;
}
```

File: UnityProject/Assets/Scripts/PlayGroups/Input/InputController.cs [hunk 7]
```diff
@@ -97,6 +98,14 @@ private void CheckAltClick()
 			}
 		}
 
+		private void CheckSuicide()
+		{
+			if (UnityEngine.Input.GetKeyDown(KeyCode.Backspace))
+			{
+				PlayerManager.LocalPlayerScript.playerNetworkActions.CmdCommitSuicide();
+			}
+		}
```
Comment (DooblyNoobly) [inline UnityProject/Assets/Scripts/PlayGroups/Input/InputController.cs]: Wouldn't this kill the player if they use backspace in chat? I don't think this should be a feature here anyway. if you want to commit suicide make it a chat command i.e "/suicide or .suicide" something like that

File: UnityProject/Assets/Scripts/PlayGroups/PlayerNetworkActions.cs [hunk 8]
```diff
@@ -448,8 +458,7 @@ public void RpcSpawnGhost()
 			Camera.main.cullingMask &= ~(1 << LayerMask.NameToLayer("FieldOfView"));
```
Comment (DooblyNoobly) [inline UnityProject/Assets/Scripts/PlayGroups/PlayerNetworkActions.cs:459]: This is where you should set the Camera2D followcontrol dampening property, not from the closet update loop

**Review by DooblyNoobly — CHANGES_REQUESTED** [review]

File: UnityProject/Assets/Scripts/Objects/VisibleBehaviour.cs (hunk 5 above)
Comment (JacobSweeten) [reply UnityProject/Assets/Scripts/Objects/VisibleBehaviour.cs]: I have to type cast to pass it to CanBeDisabled, and a few fail cast. So i'm keeping this bit unless you have another solution.

**Comment by JacobSweeten** [comment]
Ready for another review.

File: UnityProject/Assets/Scripts/PlayGroups/Input/InputController.cs [hunk 9]
```diff
@@ -54,6 +54,11 @@ private void Update()
 			CheckHandSwitch();
 			CheckClick();
 			CheckAltClick();
+			// Useful for debugging death and ghost related issues
+			//if(Debug.isDebugBuild)
```
[the remark this answers is not in the document]
Comment (JacobSweeten) [reply UnityProject/Assets/Scripts/PlayGroups/Input/InputController.cs]: In case someone is debugging the chat. This gets uncommented if you are specifically debugging death related stuff.

File: UnityProject/Assets/Scripts/Objects/VisibleBehaviour.cs [hunk 10]
```diff
@@ -93,7 +95,20 @@ private void UpdateState(bool _aliveState)
...
+			if (sr != null)
+			{
+				if (CanBeDisabled(sr))
+				{
+					renderers[i].enabled = _aliveState;
+				}
+			}
+			else
+			{
+				renderers[i].enabled = _aliveState;
```
[the remark this answers is not in the document]
Comment (JacobSweeten) [reply UnityProject/Assets/Scripts/Objects/VisibleBehaviour.cs]: I needed to get just the sprite renderers to test them for eligibility. The other renderers need no filtering.

File: UnityProject/Assets/Scripts/PlayGroups/Input/InputController.cs (hunk 9 above)
[the remark this answers is not in the document]
Comment (JacobSweeten) [reply UnityProject/Assets/Scripts/PlayGroups/Input/InputController.cs]: Should I leave the PNA commands in, and just remove the input check?

File: UnityProject/Assets/Scripts/Objects/VisibleBehaviour.cs (hunk 10 above)
[the remark this answers is not in the document]
Comment (JacobSweeten) [reply UnityProject/Assets/Scripts/Objects/VisibleBehaviour.cs]: Oh ok I see

**Comment by JacobSweeten** [comment]
I added ghost and chaticon to the ignoredspriterenderers array

File: UnityProject/Assets/Scripts/PlayGroups/Input/InputController.cs (hunk 7 above)
Comment (JacobSweeten) [reply UnityProject/Assets/Scripts/PlayGroups/Input/InputController.cs]: I can do that.

**Comment by JacobSweeten** [comment]
How do I go about making a headless server?

**Comment by JacobSweeten** [comment]
Oh that's what you meant ok.

**Comment by JacobSweeten** [comment]
Tested on 200 ping headless with two clients. Had a camera follow issue, but I fixed and tested it. Should be OK for pull.
