### PR TITLE
Fixes uplink entries being mixed up

### LINKED ISSUE #6752: PDA uplink has some weirdness with certain tabs
Linux Staging
the Trator PDA's misc tab acts funky when repeatedly hopped into and out 

1. open pda
2. switch through the various store pages
3. start swapping between misc and other pages

https://user-images.githubusercontent.com/55299415/120908373-a6de0080-c637-11eb-9d71-44c26cfb42b1.mov

### PR DESCRIPTION
**Pull request by Aranclanos**
Fixes cargo and antag uplink lists having the chance of having its entries mixed up.
Changed chem entry addition to use this same method, while also fixing a possible runtime based on how it was written originally.
Fixes #6752

Entries[Entries.Length-1] would not return the last added entry since Entries is not a list
 `public DynamicEntry[] Entries => GetComponentsInChildren<DynamicEntry>(false);`
you'd get the last enabled object based on the ingame heriarchy

### CODE REVIEW

File: UnityProject/Assets/Scripts/UI/Items/PDA/GUI_PDAUplinkItem.cs [hunk 1]
```diff
@@ -29,8 +29,7 @@ public void GenerateEntries(UplinkCategory category)
 			{
 				if (isNukie || uplinkItem.IsNukeOps == false)
 				{
-					dynamicList.AddItem();
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/UI/Items/PDA/GUI_PDAUplinkItem.cs:32]: Easy enough to fix

**Comment by Aranclanos** [comment]
yoooooooo #7000
