### PR TITLE
Fixes Emag NRE + Simple logic for emmaging

### LINKED ISSUE #7609: Cargo Console Emagging does not work
### Environment
- Game Version: latest develop (10-18-21)

### Detailed description of bug

Cargo Console Emagging, introduced in #6330, does not work properly. Using an Emag on the console does nothing and drains no charges.

### Steps to reproduce

1. attempt to emag the cargo console
2. nothing happens.
3. an NRE is produced in the console every time you use the emag on the console

### PR DESCRIPTION
**Pull request by MaxIsJoe**
fixes #7609

There was no emag logic to start with when that PR got introduced, emagging served no purpose as well except changing a bool and that's it.
This PR fixes the NRE and lets emags bypass ID access requirements 

CL: [Fix] fixed console emagging

### CODE REVIEW

File: UnityProject/Assets/Scripts/Objects/Consoles/CargoConsole.cs [hunk 1]
```diff
@@ -40,18 +41,18 @@ public void ResetID()
 
 		public void ServerPerformInteraction(HandApply interaction)
 		{
-			if (Validations.HasItemTrait(interaction.HandObject, CommonTraits.Instance.Id))
+			IDCard id = interaction.HandSlot.Item.GetComponent<IDCard>();
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Objects/Consoles/CargoConsole.cs]: I think you could do a mini optimization using ``TryGetComponent`` and try to get IDCard first and only try to get Emag if the first try returned false.

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Objects/Consoles/CargoConsole.cs]: Done 👍

**Review by corp-0 — APPROVED** [review]

**Review by Bod9001 — APPROVED** [review]
