### PR TITLE
Fixes some PDA issues, improve player identity behaviour

### LINKED ISSUE #5239: Spawning uplink on unrelated PDAs exploit
## Description
If a traitor picks up a freshly spawned PDA and holds it before 10 seconds pass by, this PDA will become an antag PDA, with a new code-phrase transmitied to the antag and 20 fresh points to use
This happens because the PDA code itself is handling this antag activation, instead of the spawn system

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1. Be antag  
2. Spawn with a non-antag second player and instantly drop the PDA on the floor
3. Pick up the PDA with the antag player
3. If the antag is holding the PDA after 10 seconds of spawning, it'll become an antag PDA

### LINKED ISSUE #5689: PDA names should update based on their owner's name and job.
### Description
In /tg/, the name of the PDA characters usually start with is altered according to their given name and job.
Below, is a PDA that Norah Coldsmith the captain started the round with. As you can see, it has her name and job on it.
image

In addition, if PDAs are ownerless (and therefore aren't already labeled with owner name and jobs), they will be renamed when an ID card is used on them for the first time. 
Below, a security PDA
image
Message made when using the ID card of Jeff Summers, Botanist, on the security PDA.
image
Below, security PDA with Jeff Summers's name and job (Botanist) after using his ID card on it.
image

Somewhat similar to #5584, in that it deals with owner's name and job on items, though for PDAs and not IDs.
New name formula: PDA-[Name] ([Job])

### LINKED ISSUE #5723: Crew manifest in PDA is currently blank and devoid of content.
### Environment
- Game Version: 5608
- OS Version: Windows 10

### Detailed description of bug
Title. When you click on the crew manifest button in the PDA, you don't see anything. You did see something in there before, once.
blank

### Steps to reproduce
1. Use PDA.
2. Click crew manifest button.
3. See nothing in the window.

### PR DESCRIPTION
**Pull request by NoooneyDude**
- Fixes coughing, sneezing revealing the player's true identity.
- Fixes a couple issues with PDAs.
    - Syndicate uplink activation is now handled through `AntagManager`. Fixes #5239.
    - PDA object name is now generated similar to that of ID cards. Closes #5689.
    - Removes unused, commented out messenger code. Probably best to start anew.
- `Antagonist` now returns `ConnectedPlayer` (which is great; I'd like to see it used more elsewhere) as `AntagManager`.
### Update
- Crew manifest list is now populating. Fixes #5723.
- Adds new serialized boolean for determining whether an article of clothing (for masks, headwear) obscures the identity of the wearer. Updates most relevant prefabs to reflect the changes. Partially implements #5711.
- Player identity is now derived from whether their face is obscured or not, falling back to what equipment (ID card, PDA) they have in their ID slot. Partially implements #5711.

### CODE REVIEW

File: UnityProject/Assets/Scripts/Items/PDA/PDALogic.cs [hunk 1]
```diff
@@ -12,11 +12,12 @@ namespace Items.PDA
...
 	[RequireComponent(typeof(PDANotesNetworkHandler))]
-	public class PDALogic : NetworkBehaviour, ICheckedInteractable<HandApply>, ICheckedInteractable<InventoryApply>
+	public class PDALogic : NetworkBehaviour, ICheckedInteractable<HandApply>, ICheckedInteractable<InventoryApply>, IServerInventoryMove
 	{
-		private const bool DEBUG_UPLINK = false;
-		private const string DEBUG_UPLINK_CODE = "Whiskey Tango Foxtrot-1337";
-		private const int TIME_BEFORE_UPLINK_ACTIVATION = 10;
+		// TODO: consider moving uplink code into its own class (perhaps compatible with pen, headset uplinks)
+
+		private readonly bool DEBUG_UPLINK = false;
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Items/PDA/PDALogic.cs]: I feel like these variables would work better as a serializable field. Any reason to have the only be changed in the code itself?

Comment (NoooneyDude) [reply UnityProject/Assets/Scripts/Items/PDA/PDALogic.cs]: Done.

**Comment by NoooneyDude** [comment]
New changes added. Ready for review.

File: UnityProject/Assets/Scripts/Items/PDA/PDALogic.cs [hunk 2]
```diff
@@ -111,48 +109,46 @@ private void Start()
...
-			var owner = GetPlayerByParentInventory();
-			if (owner == null) return;
+		public void OnInventoryMoveServer(InventoryMove info)
+		{
+			// This is also triggered when the PDA spawns as part of the player's inventory populator
+			// and added to their inventory, when they spawn.
 
-			RegisteredPlayerName = owner.ExpensiveName();
-			TryInstallUplink(owner);
+			if (RegisteredPlayerName != default) return; // PDA already registered to someone
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Items/PDA/PDALogic.cs:127]: I might be nitpicking, but instead of using ``default`` you could use ``string.IsNullOrEmpty()``

Comment (NoooneyDude) [reply UnityProject/Assets/Scripts/Items/PDA/PDALogic.cs:127]: I'm assigning the default value when resetting the string, so it made sense for me to check if it is still the default later.

Comment (corp-0) [reply UnityProject/Assets/Scripts/Items/PDA/PDALogic.cs:127]: Yeah, and I think that works just fine. I suggested the other option because it is more obvious what you're asking. I will nonetheless merge now.
