### PR TITLE
Gib players with destroy tool instead

### LINKED ISSUE #8998: Deleting a Player breaks the Server
Dev destroying a player breaks spawning for other players

System.NullReferenceException
  at (wrapper managed-to-native) UnityEngine.Object.GetName(UnityEngine.Object)
  at UnityEngine.Object.get_name () [0x00001] in /home/bokken/buildslave/unity/build/Runtime/Export/Scripting/UnityEngineObject.bindings.cs:194 
  at PlayerInfo.get_Name () [0x00011] in /root/UnityProject/Assets/Scripts/Managers/PlayerInfo.cs:91 
  at PlayerList+<>c__DisplayClass127_0.<GetByCharacter>b__0 (PlayerInfo player) [0x00000] in /root/UnityProject/Assets/Scripts/Managers/PlayerList.cs:330 
  at PlayerList.GetInternalLoggedOn (System.Func`2[T,TResult] condition) [0x00006] in /root/UnityProject/Assets/Scripts/Managers/PlayerList.cs:386 
  at PlayerList.GetInternalAll (System.Func`2[T,TResult] condition) [0x00001] in /root/UnityProject/Assets/Scripts/Managers/PlayerList.cs:367 
  at PlayerList.GetByCharacter (System.String characterName) [0x0002f] in /root/UnityProject/Assets/Scripts/Managers/PlayerList.cs:330 
  at PlayerList.Has (System.String characterName, System.String userId) [0x00022] in /root/UnityProject/Assets/Scripts/Managers/PlayerList.cs:262 
  at PlayerInfo.GetUniqueName (System.String name, System.String _UserId, System.Int32 sameNames) [0x00036] in /root/UnityProject/Assets/Scripts/Managers/PlayerInfo.cs:161 
  at PlayerInfo.TryChangeName (System.String playerName) [0x0005e] in /root/UnityProject/Assets/Scripts/Managers/PlayerInfo.cs:140 
  at PlayerInfo.set_Name (System.String value) [0x00001] in /root/UnityProject/Assets/Scripts/Managers/PlayerInfo.cs:97 
  at PlayerSpawn.ServerSpawnInternal (Mirror.NetworkConnectionToClient connection, Occupation occupation, CharacterSheet characterSettings, Mind existingMind, System.Nullable`1[T] spawnPos, System.Boolean spawnItems, System.Boolean willDestroyOldBody, System.Boolean showBanner) [0x0013d] in /root/UnityProject/Assets/Scripts/Core/Lifecycle/PlayerSpawn.cs:244 
  at PlayerSpawn.ServerRespawnPlayer (Mind forMind, System.Nullable`1[T] spaw

Anything asking for the playerscript list breaks

### PR DESCRIPTION
**Pull request by MaxIsJoe**
Fixes #8998

## Changelog: 

CL: [Fix] - Admins deleting a player now won't cause the server to break, as they will directly gib the player instead.

### CODE REVIEW

File: UnityProject/Assets/Scripts/Messages/Client/DevSpawner/DevDestroyMessage.cs [hunk 1]
```diff
@@ -40,6 +40,13 @@ private void ValidateAdmin(NetMessage msg)
 				if (NetworkObject == null) return;
 
 				Vector2Int worldPos = NetworkObject.transform.position.RoundTo2Int();
+				if (NetworkObject.TryGetComponent<PlayerScript>(out var victim))
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Messages/Client/DevSpawner/DevDestroyMessage.cs:43]: I think we have an smite action, is that not working anymore? If it is, maybe this message should call that action and return, so we only have one way to destroy players.

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Messages/Client/DevSpawner/DevDestroyMessage.cs:43]: it's not a message it's a CMD request

image

This message im editing is already being processed on the server so we don't need to do extra stuff

**Review by corp-0 — APPROVED** [review]
