### PR TITLE
Issue 1824 Girder deconstruction doesn't make tile passable on serverside

### LINKED ISSUE #1824: Girder deconstruction doesn't make tile passable on serverside B: 40
## Detailed Bug Report
https://cdn.discordapp.com/attachments/443317202179981322/574252147642728478/Scr_2019-05-04_18.09.25.mov

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Host as build, join from editor as engineer
2. Weld a wall, wrench off girder
3. Try walking onto that tile

### PR DESCRIPTION
**Pull request by JaytleBee**
### Purpose
Fixes #1824 

### Open Questions and Pre-Merge TODOs

- [X]  This fix is tested on the same branch it is PR'ed to.
- [X]  I correctly commented my code (Not much to comment)
- [X]  My code is indented with tabs and not spaces
- [X]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [X]  This PR does not bring up any new compile errors
- [X]  This PR has been tested in editor
- [X]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### Notes:
Turns out to be a pretty simple fix: The girder doesn't actually get destroyed (because pooling) so we need to make it passable when it disappears.

I also fixed a typo in a related file

### CODE REVIEW

**Comment by Aranclanos** [comment]
Hacky fix, the girder should not be in the tile at all, will bring issues later on. Fix it properly.

**Review by Aranclanos — CHANGES_REQUESTED** [review]
Hacky fix, the girder should not be in the tile at all, will bring issues later on. Fix it properly.

**Comment by JaytleBee** [comment]
Alright, working on that

**Comment by JaytleBee** [comment]
Alright, it should be fixed properly now.

File: UnityProject/Assets/Scripts/Items/MetalTrigger.cs [hunk 1]
```diff
@@ -9,7 +9,7 @@
 public class MetalTrigger : PickUpTrigger
 {
 	private bool isBuilding;
-	public GameObject griderPrefab;
+	public GameObject girderPrefab;
```
Comment (fomalsd) [inline UnityProject/Assets/Scripts/Items/MetalTrigger.cs:12]: are you sure prefab didn't lose reference because of that change?
use [FormerlySerializedAs("griderPrefab")] above it to keep the references

**Review by fomalsd — CHANGES_REQUESTED** [review]
Yeah, it was a typo. But please add FormerlySerializedAs attribute to girderPrefab to keep the existing references after rename

File: UnityProject/Assets/Scripts/Items/MetalTrigger.cs (hunk 1 above)
Comment (JaytleBee) [reply UnityProject/Assets/Scripts/Items/MetalTrigger.cs:12]: Well, MetalTrigger is only used for the metal prefab and I updated the reference there, so should I still add the FormerlySerializedAs (and should I remove the .prefab from the commit)

Comment (Aranclanos) [reply UnityProject/Assets/Scripts/Items/MetalTrigger.cs:12]: just grab a piece of metal ingame and see if it works

Comment (JaytleBee) [reply UnityProject/Assets/Scripts/Items/MetalTrigger.cs:12]: It does, I tested my commit

**Review by fomalsd — APPROVED** [review]
