### PR TITLE
Fix chest damage suffication

### LINKED ISSUE #7576: Taking at least 40 dmg to the chest makes you start suffocating
### Environment
- Game Version: Win10
- OS Version: 21101020 (latest at the moment of writing)

### Detailed description of bug

As stated in the title, whenever you take at least 40  brute damage to the chest you start suffocating and there is nothing you can do about it. I also had an instance where my *torso dislocated*

### Steps to reproduce
1. Login to staging
2. Hit yourself a couple times in the chest
3. Use health scanner and stop when you have at leat 40 damage
3. start suffocating

### PR DESCRIPTION
**Pull request by JustinTrotter**
### Purpose
 <br>

Whenever you take at least 30 damage to the chest you start suffocating. Caused by the heart and lungs using the torso health for efficiency modification. Also it was possible to dislocate the torso.
Fixes #7576

### Notes:

Made lungs and heart use its own bodypart for tracking its health rather than use its parent bodypart.
Added a check during dislocation to not dislocate when its the torso specifically.

### Changelog:

CL: [Fix] Lungs and heart no long use torso for health modified efficiency tracking

### CODE REVIEW

File: UnityProject/Assets/Scripts/HealthV2/Living/Damage/BodyPartTraumaDamage.cs [hunk 1]
```diff
@@ -90,7 +90,10 @@ public void ApplyTraumaDamage(TraumaticDamageTypes damageType = TraumaticDamageT
 				TakeBurnDamage();
 			}
 
-			if (damageType == TraumaticDamageTypes.BLUNT && DMMath.Prob(SelfArmor.Melee * 100) == false)
+			if (damageType == TraumaticDamageTypes.BLUNT 
+				&& DMMath.Prob(SelfArmor.Melee * 100) == false
+				&& BodyPartReadableName != "Torso"
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/HealthV2/Living/Damage/BodyPartTraumaDamage.cs]: Not a fan of this check, maybe you could try to get ``RootBodyPartController``

Comment (NoooneyDude) [reply UnityProject/Assets/Scripts/HealthV2/Living/Damage/BodyPartTraumaDamage.cs]: Not too familiar with trauma code but it does look like this would prevent blunt traumas on the torso?

Comment (JustinTrotter) [reply UnityProject/Assets/Scripts/HealthV2/Living/Damage/BodyPartTraumaDamage.cs]: > Not too familiar with trauma code but it does look like this would prevent blunt traumas on the torso?

You're right, I've made adjustments.

File: UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs [hunk 2]
```diff
@@ -54,22 +54,29 @@ public class Lungs : Organ
...
+	}
+
 	public override void ImplantPeriodicUpdate()
 	{
 		base.ImplantPeriodicUpdate();
 		Vector3Int position = RelatedPart.HealthMaster.ObjectBehaviour.AssumedWorldPositionServer();
 		MetaDataNode node = MatrixManager.GetMetaDataAt(position);
 		var TotalModified = 1f;
-		foreach (var Modifier in RelatedPart.AppliedModifiers)
+		foreach (var Modifier in bodyPart.AppliedModifiers)
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs]: since you're here, would you mind making this comply with naming convention?
```suggestion
		foreach (var modifier in bodyPart.AppliedModifiers)
```

File: UnityProject/Assets/Scripts/Items/Implants/Organs/Heart.cs [hunk 3]
```diff
@@ -109,14 +116,14 @@ public void DoHeartBeat()
...
 		var TotalModified = 1f;
-		foreach (var Modifier in RelatedPart.AppliedModifiers)
+		foreach (var Modifier in bodyPart.AppliedModifiers)
 		{
 			var toMultiply = 1f;
-			if (Modifier == RelatedPart.DamageModifier)
+			if (Modifier == bodyPart.DamageModifier)
 			{
-				toMultiply = Mathf.Max(0f,Mathf.Max(RelatedPart.MaxHealth - RelatedPart.TotalDamageWithoutOxyCloneRadStam, 0) / RelatedPart.MaxHealth);
+				toMultiply = Mathf.Max(0f,Mathf.Max(bodyPart.MaxHealth - bodyPart.TotalDamageWithoutOxyCloneRadStam, 0) / bodyPart.MaxHealth);
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Items/Implants/Organs/Heart.cs:117]: could this be replaced with a simpler ``Mathf.Clamp`` or am I dum dum?

File: UnityProject/Assets/Scripts/HealthV2/Living/Damage/BodyPartTraumaDamage.cs [hunk 4]
```diff
@@ -107,7 +107,10 @@ void TakeBluntLogic(BodyPart bodyPart)
 					return;
 				}
 				bodyPart.currentBluntDamageLevel += 1;
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/HealthV2/Living/Damage/BodyPartTraumaDamage.cs]: is this for stuff like ribs and stuff?

File: UnityProject/Assets/Scripts/Items/Implants/Organs/Heart.cs [hunk 5]
```diff
@@ -44,6 +44,13 @@ public class Heart : Organ
 
 	private bool alarmedForInternalBleeding = false;
 
+	private BodyPart bodyPart;
+
+	private void Awake()
+	{
+		bodyPart = GetComponent<BodyPart>();
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/Items/Implants/Organs/Heart.cs]: you might as well move this to the base organ script

File: UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs [hunk 6]
```diff
@@ -54,22 +54,29 @@ public class Lungs : Organ
...
 		{
 			var toMultiply = 1f;
-			if (Modifier == RelatedPart.DamageModifier)
+			if (Modifier == bodyPart.DamageModifier)
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs]: one thing to note damage may not propagate to the organs properly that needs to be checked, 
imo it should propagate to organs

File: UnityProject/Assets/Scripts/HealthV2/Living/Damage/BodyPartTraumaDamage.cs (hunk 4 above)
Comment (JustinTrotter) [reply UnityProject/Assets/Scripts/HealthV2/Living/Damage/BodyPartTraumaDamage.cs]: I'm not sure. I think so, it could also possibly be for bruising.

File: UnityProject/Assets/Scripts/Items/Implants/Organs/Heart.cs (hunk 3 above)
Comment (JustinTrotter) [reply UnityProject/Assets/Scripts/Items/Implants/Organs/Heart.cs:117]: This could possibly be refactored to be more readable. But we're shifting a bit out of scope. Why don't we address this in a separate PR?

File: UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs (hunk 6 above)
Comment (JustinTrotter) [reply UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs]: I just ran some tests. I temporarily lowered the torso's `SubOrganBodyPartArmour` for melee from 100 to 0 and started whaling on myself with a toolbox. The heart, lungs, stomach, etc do get damaged as expected.

I healed the torso and repeated the beatings. As expected, eventually the organs become less and less efficient and I start to take oxy damage.

Organs seem to either take a very very long time to heal or require surgery when damaged.

File: UnityProject/Assets/Scripts/Items/Implants/Organs/Heart.cs (hunk 3 above)
Comment (corp-0) [reply UnityProject/Assets/Scripts/Items/Implants/Organs/Heart.cs:117]: fair enough

File: UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs (hunk 6 above)
Comment (Bod9001) [reply UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs]: ok cool

File: UnityProject/Assets/Scripts/HealthV2/Living/Damage/BodyPartTraumaDamage.cs (hunk 4 above)
Comment (Bod9001) [reply UnityProject/Assets/Scripts/HealthV2/Living/Damage/BodyPartTraumaDamage.cs]: I'm going to ping Max

**Review by Bod9001 — DISMISSED** [review]

File: UnityProject/Assets/Scripts/HealthV2/Living/Damage/BodyPartTraumaDamage.cs (hunk 4 above)
Comment (Bod9001) [reply UnityProject/Assets/Scripts/HealthV2/Living/Damage/BodyPartTraumaDamage.cs]: it's the same issue where, the bone thinks it's the chest and not using the correct body part

Comment (JustinTrotter) [reply UnityProject/Assets/Scripts/HealthV2/Living/Damage/BodyPartTraumaDamage.cs]: I see, what I can do is instead of canceling the dislocation announcement, have the bone organ make the TakeBluntLogic() call. I would have to pull it outside of the TakeBluntDamage() scope and make it public, then I can have the torso tell the bone to call TakeBluntLogic().

Comment (Bod9001) [reply UnityProject/Assets/Scripts/HealthV2/Living/Damage/BodyPartTraumaDamage.cs]: humm, I'm not sure actually max is supposed to be checking it out

Comment (JustinTrotter) [reply UnityProject/Assets/Scripts/HealthV2/Living/Damage/BodyPartTraumaDamage.cs]: Screen Shot 2021-10-19 at 7 49 24 PM
Updated.

Comment (JustinTrotter) [reply UnityProject/Assets/Scripts/HealthV2/Living/Damage/BodyPartTraumaDamage.cs]: If necessary we can always just revert my latest commit.

Comment (Bod9001) [reply UnityProject/Assets/Scripts/HealthV2/Living/Damage/BodyPartTraumaDamage.cs]: "This looks good, just remove the debug.log
" max

Comment (JustinTrotter) [reply UnityProject/Assets/Scripts/HealthV2/Living/Damage/BodyPartTraumaDamage.cs]: Fixed

**Review by Bod9001 — APPROVED** [review]

**Review by corp-0 — APPROVED** [review]
