### PR TITLE
Fixes assassination objective and black gloves not protecting hands

### LINKED ISSUE #7127: Assassinate objective succeeds as long as the target dies once, even if they're still alive at round end.
### Environment
- Game Version: Production 4120
- OS Version: Windows 10

### Detailed description of bug
The assassinate objective will succeed when the target dies. Not when the target is dead at round start, just if they die. This means that even if the target is alive and in completely good condition at round end, the assassinate objective will still be completed as long as they died at least once prior. 
It doesn't even have to be by the assassin's hands, since the target dying of anything will complete the objective.

### Steps to reproduce
1. Have a traitor with assassinate objectives, have their targets die.
2. The targets must come back to life, such as by cloning.
3. Have the round end with the target alive. The assassinate objective will show up as complete even if the target is still quite alive.

### LINKED ISSUE #7688: Wearing black gloves no longer protects you from being burnt by light bulbs.
### Environment
- Game Version: Staging 21102918
- OS Version: Windows 10

### Detailed description of bug
Title. Black gloves no longer protect you from being burned by light bulbs.

### Steps to reproduce

1. Wear black gloves.
2. Click on an active light bulb.
3. Get burned.

### PR DESCRIPTION
**Pull request by MaxIsJoe**
fixes #7688
fixes #7127

CL: [Fix] fixed assassination objective
CL: [Fix] fixed black gloves not protecting hands from heat

### CODE REVIEW

File: UnityProject/Assets/Scripts/Core/Lighting/LightSource.cs [hunk 1]
```diff
@@ -306,11 +307,20 @@ private void TryRemoveBulb(HandApply interaction)
 		{
 			try
 			{
-				var handSlot = interaction.PerformerPlayerScript.DynamicItemStorage.GetActiveHandSlot();
+				var handSlots = interaction.PerformerPlayerScript.DynamicItemStorage.GetNamedItemSlots(NamedSlot.hands);
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Core/Lighting/LightSource.cs:312]: I feel like getting the active hand slot was the way to go, what isn't working there? It isn't returning the gloves in the slot?

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Core/Lighting/LightSource.cs:312]: active hand slot is the slot that you hold stuff in
not the slot that you use to wear gloves

Comment (corp-0) [reply UnityProject/Assets/Scripts/Core/Lighting/LightSource.cs:312]: ok so that is what isn't working, they should be the same hand (the one that holds stuff and interacts and the one that wears gloves)

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Core/Lighting/LightSource.cs:312]: active hands are `leftHand` and `rightHand` slots which don't house the item we want to check
`hands` is one that is used for customizations like `eyes`, `feet`, etc.

**Review by Bod9001 — DISMISSED** [review]

File: UnityProject/Assets/Scripts/Core/Lighting/LightSource.cs [hunk 2]
```diff
@@ -306,11 +307,20 @@ private void TryRemoveBulb(HandApply interaction)
...
 
-				if (mState == LightMountState.On && (handSlot.IsOccupied == false ||
-				                                     !Validations.HasItemTrait(handSlot.ItemObject,
-					                                     CommonTraits.Instance.BlackGloves)))
+				bool HasGlove()
+				{
+					foreach (var slot in handSlots)
+					{
+						if(slot.IsEmpty) continue;
+						if (Validations.HasItemTrait(slot.ItemObject, gloveTrait)) return true;
```
Comment (ThatDan123) [inline UnityProject/Assets/Scripts/Core/Lighting/LightSource.cs]: Why did you stop using the common trait?

File: UnityProject/Assets/Scripts/Systems/Antagonists/Objectives/Assassinate.cs [hunk 3]
```diff
@@ -46,17 +46,17 @@ protected override void Setup()
 			}
 
 			// Pick a random target and add them to the targeted list
-			Target = playerPool.PickRandom().Script;
+			Target = playerPool.PickRandom().Script.connectedPlayer;
```
Comment (ThatDan123) [inline UnityProject/Assets/Scripts/Systems/Antagonists/Objectives/Assassinate.cs:49]: Worth saying this will mean if someone respawns as a ghost role or is admin respawned then this will fail the objective.

Not much can be done about that without a big change

File: UnityProject/Assets/Scripts/Core/Lighting/LightSource.cs (hunk 1 above)
Comment (corp-0) [reply UnityProject/Assets/Scripts/Core/Lighting/LightSource.cs:312]: Please don't resolve conversations like that, at least wait until the reviewer gives back a positive answer. If you're not willing to make the hands be hands both in interaction and in clothing slot, which is fair because it is a bit change, at least add a TODO comment stating it has to be done.

Comment (Bod9001) [reply UnityProject/Assets/Scripts/Core/Lighting/LightSource.cs:312]: but you wouldn't be able to interact with anything because your hands are taken up with gloves

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Core/Lighting/LightSource.cs:312]: I mean, Bod is just repeating what I said now.

File: UnityProject/Assets/Scripts/Systems/Antagonists/Objectives/Assassinate.cs (hunk 3 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Systems/Antagonists/Objectives/Assassinate.cs:49]: Can't we just make a bool that is like `ObserverOrGhostRole`?
I don't think that's a big change, we just need to tell the connectedPlayer when we have rejoined as a ghost role after death.

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Systems/Antagonists/Objectives/Assassinate.cs:49]: I think SS13 already does that as well because i don't think you can respawn as a normal character after you've chosen to play as a ghost role.

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Systems/Antagonists/Objectives/Assassinate.cs:49]: hey, no need to even do a Boolean and keep updating/tracking it, I made a function that checks if the player is a ghost role.

File: UnityProject/Assets/Scripts/Core/Lighting/LightSource.cs (hunk 2 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Core/Lighting/LightSource.cs]: something was wrong with unity on my end, it fixed itself so no need for this change.

File: UnityProject/Assets/Scripts/Systems/Antagonists/Objectives/Assassinate.cs (hunk 3 above)
Comment (Bod9001) [reply UnityProject/Assets/Scripts/Systems/Antagonists/Objectives/Assassinate.cs:49]: remember it has to be thread safe

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Systems/Antagonists/Objectives/Assassinate.cs:49]: what?

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Systems/Antagonists/Objectives/Assassinate.cs:49]: image

File: UnityProject/Assets/Scripts/Core/Lighting/LightSource.cs (hunk 1 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Core/Lighting/LightSource.cs:312]: Added the TODO and I've added a little note explaining the difference between the two currently.

**Review by corp-0 — APPROVED** [review]

**Review by Bod9001 — APPROVED** [review]
