### PR TITLE
Fixes: helmet, voting, chat, admin

### LINKED ISSUE #3052: The Vote system can be manipulated
How it happens Votes all count up instantaneously, 
TODO
Examine what could be the issue with The not  messages

### LINKED ISSUE #3071: Suggestion: Nuke location finder
It's becoming more popular for security to discard the nuke out an airlock into space

Could it be possible to add a terminal to the nukie ship which shows the gps location of the nuke?

### PR DESCRIPTION
**Pull request by fomalsd**
Fixed missing helmet from mining lockers
Fixes #3071 – adds nuke location to emagged shuttle console
Changed chat bubble font to Ubuntu with cp1251+1252 support
Hopefully fixes nukies always getting redtext (#2863)
Hopefully fixes everyone hearing everything (#2915)
Fixes #3052 voting exploit

### CODE REVIEW

File: UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs [hunk 1]
```diff
@@ -236,10 +236,12 @@ public void CmdInitiateRestartVote()
 	}
 
 	[Command]
-	public void CmdRegisterVote(string userId, bool isFor)
+	public void CmdRegisterVote(bool isFor)
 	{
 		if (VotingManager.Instance == null) return;
-		VotingManager.Instance.RegisterVote(userId, isFor);
```
Comment (steamp0rt) [inline UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs:242]: $1,000 a month and it took rshoe to make everyone realize this was a bad idea
