### PR TITLE
Disconnect Logging & Leave Messages

### LINKED ISSUE #1278: "AuthTicketCanceled" messages when somebody closes the game B: 15
# Description

## Category
BUG

## Detailed Bug Report
When another player leaves the game, a Steam error appears in chat "AuthTicketCanceled".
This should be replaced by a more friendlier message, like "X left the game."

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Two player join the game via steam 
2. One leaves
3. The other sees the message

### PR DESCRIPTION
**Pull request by ghost**
### Purpose
Adds logging for disconnects, returns a friendlier disconnect message in chat (hopefully).
Fixes #1278 

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [ ]  This PR has been tested in editor
- [ ]  This PR has been tested in multiplayer

### Notes:
Hasn't been tested, no time. Told to PR for a test.

### CODE REVIEW

File: UnityProject/Assets/Scripts/Managers/NetworkManagement/CustomNetworkManager.cs [hunk 1]
```diff
@@ -176,12 +176,20 @@ public void AuthChange(ulong steamid, ulong ownerid, ServerAuth.Status status)
 			return;
 		}
 
+		//god please work, should be the leave message and associated logging.
```
Comment (DooblyNoobly) [inline UnityProject/Assets/Scripts/Managers/NetworkManagement/CustomNetworkManager.cs]: Please make your comments straight and to the point

File: UnityProject/Assets/Scripts/Managers/NetworkManagement/CustomNetworkManager.cs [hunk 2]
```diff
@@ -176,12 +176,20 @@ public void AuthChange(ulong steamid, ulong ownerid, ServerAuth.Status status)
...
+			return;
+	}
+
 		if (status == ServerAuth.Status.VACCheckTimedOut)
 		{
 			return;
 		}
 
-		Kick(player, $"Steam: {status}");
+		Kick(player, $"{player} has departed from the station.");
```
Comment (DooblyNoobly) [inline UnityProject/Assets/Scripts/Managers/NetworkManagement/CustomNetworkManager.cs]: I don't think we should be broadcasting over chat if someone has left. Chat is meant to resemble radio chatter or local room chatter, saying that someone has left or logged out will break immersions unless it's broadcast over OOC but I still think we should not notify others of joining or leaving. Just remove the whole kick line, it's not needed.

File: UnityProject/Assets/Scripts/Managers/NetworkManagement/CustomNetworkManager.cs [hunk 3]
```diff
@@ -176,12 +176,20 @@ public void AuthChange(ulong steamid, ulong ownerid, ServerAuth.Status status)
 			return;
 		}
 
+		//god please work, should be the leave message and associated logging.
+		if (status == ServerAuth.Status.VACCheckTimedOut)
+		{
+
+			Logger.LogWarning($"The SteamID '{SteamID}' left the server. ({status})");
```
Comment (DooblyNoobly) [inline UnityProject/Assets/Scripts/Managers/NetworkManagement/CustomNetworkManager.cs]: Use of Logger requires a Category, otherwise it gets dumped into the Category.None pile and probably is never seen

**Review by DooblyNoobly — CHANGES_REQUESTED** [review]

File: UnityProject/Assets/Scripts/Managers/NetworkManagement/CustomNetworkManager.cs (hunk 1 above)
Comment (ghost) [reply UnityProject/Assets/Scripts/Managers/NetworkManagement/CustomNetworkManager.cs]: Fixed. My bad.

File: UnityProject/Assets/Scripts/Managers/NetworkManagement/CustomNetworkManager.cs (hunk 2 above)
Comment (ghost) [reply UnityProject/Assets/Scripts/Managers/NetworkManagement/CustomNetworkManager.cs]: Done.

File: UnityProject/Assets/Scripts/Managers/NetworkManagement/CustomNetworkManager.cs (hunk 3 above)
Comment (ghost) [reply UnityProject/Assets/Scripts/Managers/NetworkManagement/CustomNetworkManager.cs]: Added a reference to Category.Steam, please review.
