### PR TITLE
handles conditional slots better dynamic UI

### LINKED ISSUE #8105: Inventory slots duplicated on spawn.
### Environment
- Game Version: 22010322

### Detailed description of bug

Screenshot 2022-01-05 032400

```
Caught NRE in ItemStorage:  
  at (wrapper managed-to-native) UnityEngine.Component.GetComponentFastPath(UnityEngine.Component,System.Type,intptr)
  at UnityEngine.Component.GetComponent[T] () [0x00021] in <6e7a9b489b134053bc0600a292ec678e>:0 
  at ItemStorage.GetRootStorageOrPlayer () [0x00002] in <a1809b9fd09244a79ad6f12e344d5321>:0 ```
  
 NullReferenceException: Object reference not set to an instance of an object
ItemSlot.CanFit (Pickupable toStore, System.Boolean ignoreOccupied, UnityEngine.GameObject examineRecipient) (at <a1809b9fd09244a79ad6f12e344d5321>:0)
Validations.CanFit (ItemSlot itemSlot, Pickupable toCheck, NetworkSide side, System.Boolean ignoreOccupied, UnityEngine.GameObject examineRecipient) (at <a1809b9fd09244a79ad6f12e344d5321>:0)
Validations.CanPutItemToSlot (PlayerScript playerScript, ItemSlot itemSlot, Pickupable toCheck, NetworkSide side, System.Boolean ignoreOccupied, UnityEngine.GameObject examineRecipient) (at <a1809b9fd09244a79ad6f12e344d5321>:0)
Inventory.ClientRequestTransfer (ItemSlot from, ItemSlot to) (at <a1809b9fd09244a79ad6f12e344d5321>:0)
UI_ItemSlot.SwapItem (UI_ItemSlot itemSlot) (at <a1809b9fd09244a79ad6f12e344d5321>:0)
UI_ItemSlot.TryItemInteract (System.Boolean swapIfEmpty) (at <a1809b9fd09244a79ad6f12e344d5321>:0)
UI.UI_ItemSwap.OnClick () (at <a1809b9fd09244a79ad6f12e344d5321>:0)
UI.UI_ItemSwap.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <a1809b9fd09244a79ad6f12e344d5321>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <10f02e380b7f44a2ba6b1bc238f0b3cc>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <10f02e380b7f44a2ba6b1bc238f0b3cc>:0)
UnityEngine.EventSystems.EventSystem:Update()```

NullReferenceException
UnityEngine.Component.GetComponent[T] () (at <6e7a9b489b134053bc0600a292ec678e>:0)
ItemSlot.get_ItemStorageNetID () (at <a1809b9fd09244a79ad6f12e344d5321>:0)
Messages.Client.RequestInventoryTransferMessage.Send (ItemSlot fromSlot, ItemSlot toSlot) (at <a1809b9fd09244a79ad6f12e344d5321>:0)
Inventory.ClientRequestTransfer (ItemSlot from, ItemSlot to) (at <a1809b9fd09244a79ad6f12e344d5321>:0)
UI.UI_ItemSwap.OnDrop (UnityEngine.EventSystems.PointerEventData data) (at <a1809b9fd09244a79ad6f12e344d5321>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IDropHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <10f02e380b7f44a2ba6b1bc238f0b3cc>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <10f02e380b7f44a2ba6b1bc238f0b3cc>:0)
UnityEngine.EventSystems.EventSystem:Update()```

### PR DESCRIPTION
**Pull request by Bod9001**
should hopefully fix issues with conditional slots, 
also made it so when removing network identity doesn't have to be present, it can be destroyed

Need to test on build

fixes #8105 

CL: [Fix] fixed a bug causing inventory slots to duplicate when first spawning.

tested in headless build

### CODE REVIEW

File: UnityProject/Assets/Scripts/Systems/Inventory/DynamicItemStorage.cs [hunk 1]
```diff
@@ -583,6 +619,13 @@ public void Add(IDynamicItemSlotS bodyPartUISlots)
 			ServerObjectToSlots[bodyPartUISlots.GameObject].Add(Slot);
 
 			ServerTotal.Add(Slot);
+			var InternalData = new InternalData();
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Systems/Inventory/DynamicItemStorage.cs]: if you make those properties instead of public fields you can do this
```cs
var internalData = new InternalData() 
{
    Id = id,
    IndexEnabled = i
}
```

Comment (corp-0) [reply UnityProject/Assets/Scripts/Systems/Inventory/DynamicItemStorage.cs]: also notice I used camelCase for the privates and iterator of the loop

Comment (Bod9001) [reply UnityProject/Assets/Scripts/Systems/Inventory/DynamicItemStorage.cs]: ok cool will do

**Comment by corp-0** [comment]
this PR has been waiting for reviews for a while. To be quite honest I don't understand the changes or the reasoning behind them. What was the issue? How does this solve it?

**Comment by Bod9001** [comment]
ok, the basically the changes are that it caches the interface for dynamic inventory slots that has been added to the inventory, So if they've been destroyed it can remove them seamlessly, 

also moves the logic for conditional slots to server side, and sends the client what slots they should see

**Comment by corp-0** [comment]
I see, I see. Well, in that case the only thing missing for me to give you a green tick is solving the codacy complains

**Comment by Bod9001** [comment]
ok

**Comment by Bod9001** [comment]
done

**Review by corp-0 — APPROVED** [review]

**Review by ThatDan123 — APPROVED** [review]
