### PR TITLE
Fixes Controls Internal Error

### LINKED ISSUE #5734: Oxygen tank icon with new UI doesn't change when you equip an oxygen tank.
### Environment
- Game Version: Develop, as of #5732
- OS Version: Windows 10

### Detailed description of bug
For some reason, the sprite for the oxygen tank on the new UI doesn't change if you actually equip an oxygen tank. It did before. Notably, putting on breathing mask does add a mask icon on top of the oxygen tank.

### Steps to reproduce

1. Wear the breathing mask from your survival box. See mask icon appear over "blank" oxygen tank icon.
2. Wear the oxygen tank from your survival box. Notice that "blank" oxygen tank icon stays the same.

### LINKED ISSUE #6069: Internals tank icon in new UI doesn't update when a usable tank is equipped.
### Environment
- Game Version: 21021823
- OS Version: Windows 10

### Detailed description of bug
For some reason, the O2 tank icon in the new UI doesn't change if you have a usable internals tank in your external slots. This is especially odd because it changed before. This makes it impossible to properly tell if internals is turned on or not.
image

### Steps to reproduce
1. Put oxygen tank in hands, pockets, or suit storage slot.
2. Notice that the internals tank icon doesn't change.

### LINKED ISSUE #6139: Control Internals Update NRE
### Environment
- Game Version: 21022501
- OS Version: Windows 10

### Detailed description of bug
image
Control internals NRE pictured above can occur when station room becomes breached and you walk into it without any internals on. The error spam can be halted if you die and are recloned, upon entering the atmos effected area it will begin again. Turning on your internals after this error doesn't stop the spam either.

### Steps to reproduce
1.  Cause hull and floor breaches through Meteor Event (Catastrophic) through Admin Panel
2.  Enter breached place without oxygen mask, tank or hardsuit in any slots
3.  Check NREs and receive the Control Internals Update Errors

### PR DESCRIPTION
**Pull request by ThatDan123**
CL: [Improvement] Oxygen tank in UI will now show oxygen amount

-Fixes control internal error when you have internals on

Fixes #6139
Fixes #6069
Fixes #5734

### CODE REVIEW

File: UnityProject/Assets/Scripts/Objects/GasContainer.cs [hunk 1]
```diff
@@ -38,10 +38,18 @@ public class GasContainer : NetworkBehaviour, IGasMixContainer, IServerSpawn
 
 		private bool gasIsInitialised = false;
 
+		private Pickupable pickupable;
+
+		[SyncVar]
+		//Only updated and valid for canisters inside the players inventory!!!
+		private float oxygenRatio = 0;
+		public float OxygenRatio => oxygenRatio;
```
Comment (Aranclanos) [inline UnityProject/Assets/Scripts/Objects/GasContainer.cs]: feels hacky, shouldnt this be on the players UI instead of each gascontainer? 
Small note, its name is oxygenratio while in reality it's just the relation of the max capacity and current moles

**Comment by ThatDan123** [comment]
renamed to be more accurate

File: UnityProject/Assets/Scripts/Objects/GasContainer.cs (hunk 1 above)
Comment (ThatDan123) [reply UnityProject/Assets/Scripts/Objects/GasContainer.cs]: cant put a syncvar on UI, would have to do two netmessages instead. If you think thats better?
