### PR TITLE
Fixes players being unable to escape lockers and expanding Escapable Containers and Cremator logic

### LINKED ISSUE #7705: Players inside morgues appear on the morgue itself and not its tray when they are opened.
### Environment
- Game Version: Staging 21102918
- OS Version: Windows 10

### Detailed description of bug

Title. When morgues are opened, players appear on the same tile as the morgue and not on the tray. Notably this does not affect items nor dead mobs, who will appear on the tray as they should.

morgue

### Steps to reproduce
1. Enter a morgue.
2. Exit the morgue.
3. See that you appear on the morgue itself and not the tray.

### PR DESCRIPTION
**Pull request by MaxIsJoe**
CL: [Fix] - Fixed an issue where players were unable to escape lockers
CL: [Fix] - Fixed  #7705
CL: [New] - You can no longer open a cremator or morgue from the inside and can attempt an escape by moving.
CL: [New] - Cremators now have proper burning logic, all items and mobs caught inside will be burnt for a period of time until they turn to ash.

### CODE REVIEW

**Comment by MaxIsJoe** [comment]
I was planning on adding animations and maybe improving the sounds a little bit for all objects so it can match the same quality as /tg/ but I've a headache now because of the progress bar fix.

Guess I'll leave that for another PR oh well
Also why the heck is tests failing 2 seconds in

File: UnityProject/Assets/Scripts/Objects/Drawers/Cremator.cs [hunk 1]
```diff
@@ -107,55 +121,65 @@ public override void CloseDrawer()
...
+				if(obj.TryGetComponent<Integrity>(out var integrity)) //For items
+					integrity.ApplyDamage(burningDamage, AttackType.Fire, DamageType.Burn, true);
+				if (obj.TryGetComponent<LivingHealthBehaviour>(out var healthBehaviour)) //For NPCs
+					healthBehaviour.ApplyDamage(gameObject, burningDamage, AttackType.Fire, DamageType.Burn);
+				if (obj.TryGetComponent<PlayerHealthV2>(out var playerHealthV2)) //For Players
+					playerHealthV2.ApplyDamageAll(gameObject, burningDamage, AttackType.Fire, DamageType.Burn);
 			}
+
+			yield return WaitFor.Seconds(BURNING_DURATION);
+			StartCoroutine(nameof(BurnContent));
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/Objects/Drawers/Cremator.cs:164]: not really about code but, should we have these things that can remove a player from a round Permanently?

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Objects/Drawers/Cremator.cs:164]: I removed the insta player removal because thats not how /tg/ handles it, the player's body needs to burn for a while until it ashes so they can be removed from the game entirely. Doing it this way allows players to have time to rescue antag victims who were attempting to destroy evidence.

File: UnityProject/Assets/Scripts/Objects/ObjectContainer.cs [hunk 2]
```diff
@@ -197,7 +197,14 @@ public void RetrieveObject(GameObject obj, Vector3? worldPosition = null)
...
 				{
-					playerScript.PlayerSync.AppearAtPositionServer(registerTile.WorldPositionServer);
+					if (worldPosition != null)
+					{
+						playerScript.PlayerSync.AppearAtPositionServer(worldPosition.Value);
+					}
+					else
+					{
+						playerScript.PlayerSync.AppearAtPositionServer(registerTile.WorldPositionServer);
+					}
```
Comment (NoooneyDude) [inline UnityProject/Assets/Scripts/Objects/ObjectContainer.cs]:
```suggestion
					playerScript.PlayerSync.AppearAtPositionServer(worldPosition.GetValueOrDefault(registerTile.WorldPositionServer);
```

**Comment by NoooneyDude** [comment]
So, movement is cancelling the escape? But why is the player moving? This was not occurring earlier.

**Comment by MaxIsJoe** [comment]
> So, movement is cancelling the escape? But why is the player moving? This was not occurring earlier.

Something probably broke it at some point and players are now drifting away from 0,0 when they move
but we also kinda needed progress bars to have the option to be used while moving sooo, I guess we should create a new issue talking about this? Either way it's fixed for now.

File: UnityProject/Assets/Scripts/Objects/ObjectContainer.cs (hunk 2 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Objects/ObjectContainer.cs]: Done

File: UnityProject/Assets/Scripts/Objects/Drawers/Cremator.cs [hunk 3]
```diff
@@ -107,55 +121,65 @@ public override void CloseDrawer()
...
 
 		private void Cremate()
 		{
-			OnStartPlayerCremation();
-			StartCoroutine(PlayIncineratingAnim());
 			SoundManager.PlayNetworkedAtPos(CremationSound, DrawerWorldPosition, sourceObj: gameObject);
+			SetDrawerState((DrawerState)CrematorState.ShutAndActive);
+			UpdateCloseState();
+			OnStartPlayerCremation();
+			StartCoroutine(nameof(BurnContent));
```
Comment (NoooneyDude) [inline UnityProject/Assets/Scripts/Objects/Drawers/Cremator.cs:146]: There isn't anything to stop the burning once complete as it is recursive. Store a reference to this coroutine and stop it on some condition, like timer ending or OnDisable.

Though, does it need to be recursive? I think a loop would be fine here, and don't need to worry about stopping it.

25 damage per five seconds also sounds pretty low.

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Objects/Drawers/Cremator.cs:146]: Added an extra check to stop it.

Also 25 per five seconds is not low at all.

**Review by Bod9001 — APPROVED** [review]

**Review by NoooneyDude — APPROVED** [review]
