### PR TITLE
Tried to make log messages more useful.

### LINKED ISSUE #1801: There are many Debug.Log() messages outside of Logger.cs
# Description
image
Some examples of them, personally I'd like them gone

## Category
TODO

### LINKED ISSUE #1820: Large amount of unhelpful log messages
# Description
There are a number of unhelpful log messages added in https://github.com/unitystation/unitystation/commit/07e8dde0477154b704add1a71f1c0ed9e12e92a0. I'd love to correct this, but I have no clue what they are supposed to be doing.

## Category
TODO

## Detailed Bug Report
The ones that are the least useful:
https://github.com/unitystation/unitystation/commit/07e8dde0477154b704add1a71f1c0ed9e12e92a0#diff-303b2589ad5f32ef1db03fec8f40c87dR157
https://github.com/unitystation/unitystation/commit/07e8dde0477154b704add1a71f1c0ed9e12e92a0#diff-b3058f4d18503993b127a5e3c5c5aaa4R18
https://github.com/unitystation/unitystation/commit/07e8dde0477154b704add1a71f1c0ed9e12e92a0#diff-eeca8484590f41aaae78cf1cf6aced79R8
https://github.com/unitystation/unitystation/commit/07e8dde0477154b704add1a71f1c0ed9e12e92a0#diff-0b2a13cafa0dd324db2c0361bb1ab848R8
https://github.com/unitystation/unitystation/commit/07e8dde0477154b704add1a71f1c0ed9e12e92a0#diff-ecc26f825674ed675ab4daf65b5a7f4fR109

There are various slightly more useful ones as well, but these are really not helpful.

Example of one of the Log messages: HEYEYEYYEYEYE

### PR DESCRIPTION
**Pull request by ghost**
### Purpose
Fixes #1820 
Makes significant progress towards #1801 

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [ ]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### Notes:
While this PR also improves several log statements, it does not make every log message perfect yet. Its main purpose is to make sure there are no unneeded Debug.Log()'s and to make sure that every Logger.Log() call has a category (where possible).

### CODE REVIEW

**Comment by ghost** [comment]
Feel free to comment with improvements for my current changes.

File: UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs [hunk 1]
```diff
@@ -601,8 +601,9 @@ public void CmdToggleShutters(GameObject switchObj)
 		}
 		else
 		{
-			Logger.LogWarning("player attempted to interact with shutter switch through wall," +
-				" this could indicate a hacked client.");
+			//TODO: Output name of player attempting to interact with shutter switch.
+			Logger.LogWarning("Player attempted to interact with shutter switch through wall," +
```
Comment (RedlineTriad) [inline UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs]: This log message doesn't have a category.

File: UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs [hunk 2]
```diff
@@ -623,6 +624,7 @@ public void CmdToggleLightSwitch(GameObject switchObj)
 		}
 		else
 		{
+			//TODO: Output name of player attempting to interact with light switch.
 			Logger.LogWarning("player attempted to interact with light switch through wall," +
```
Comment (RedlineTriad) [inline UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs]: This log message doesn't have a category

File: UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs [hunk 3]
```diff
@@ -668,6 +670,7 @@ public void CmdToggleFireCabinet(GameObject cabObj, bool forItemInteract, string
 		}
 		else
 		{
+			//TODO: Output name of player attempting to interact with fire cabinet.
 			Logger.LogWarning("player attempted to interact with fire cabinet through wall," +
```
Comment (RedlineTriad) [inline UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs]: This log message doesn't have a category.

**Review by RedlineTriad — COMMENTED** [review]
There seem to be multiple log messages where you didn't assign a category.

File: UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs (hunk 1 above)
Comment (ghost) [reply UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs]: > There seem to be multiple log messages where you didn't assign a category.

You're right, silly me. Thanks for letting me know!

File: UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs (hunk 2 above)
Comment (ghost) [reply UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs]: Do you think Category.NetMessage would be right for this?

Comment (RedlineTriad) [reply UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs]: I think, for questions like these, the discord server can give you answers better and faster.

**Comment by ghost** [comment]
> There seem to be multiple log messages where you didn't assign a category.

I have fixed the instances you've referenced. I'll be sure to check any other files for log messages without a category as well.

**Comment by ghost** [comment]
c936817 added, feedback welcome 😄.

**Comment by ghost** [comment]
I made a big mistake somewhere. Debugging it now o-o
Resolved

File: UnityProject/Assets/Scripts/Debug/Logger.cs [hunk 4]
```diff
@@ -130,6 +130,8 @@ private static void TryLog(string message, LogLevel messageLevel, Category categ
 			return;
 		}
 
+		LogTraceFormat("Message {messageLevel} {0} did not specify a category!", Category.CodeQuality);
```
Comment (fomalsd) [inline UnityProject/Assets/Scripts/Debug/Logger.cs]: it's not a $ string so {messageLevel} wouldn't work
and you didn't pass any arguments for {0} to work either

Comment (ghost) [reply UnityProject/Assets/Scripts/Debug/Logger.cs]: You're right. When I fixed that more stuff went wrong, so I decided against doing it.

**Comment by fomalsd** [comment]
is this ready for review?

**Comment by ghost** [comment]
Planning to go and check for missing categories in Logger.Log calls but other than that current code could be reviewed.

File: UnityProject/Assets/Scripts/Lighting System/Light2D/Util.cs [hunk 5]
```diff
@@ -362,7 +362,7 @@ public static T Deserialize<T>(byte[] data)
             }
             catch (Exception ex)
             {
-                Debug.LogError(ex);
+                Logger.LogErrorFormat("Deserialize: {0}", Category.Light2D);
```
Comment (ghost) [inline UnityProject/Assets/Scripts/Lighting System/Light2D/Util.cs]: Note to self: Change to use tabs instead of space.

File: UnityProject/Assets/Scripts/Lighting System/LightingSystem.cs [hunk 6]
```diff
@@ -271,8 +274,8 @@ private void OnEnable()
 
 		if (!SystemInfo.supportsAsyncGPUReadback)
 		{
-			UnityEngine.Debug.LogWarning("LightingSystem: Async GPU Readback not supported on this machine, slower synchronous readback will" +
-			                             " be used instead.");
+			Logger.LogWarning("LightingSystem: Async GPU Readback not supported on this machine, slower synchronous readback will" +
+			                             " be used instead.", Category.Lighting);
```
Comment (ghost) [inline UnityProject/Assets/Scripts/Lighting System/LightingSystem.cs]: Note to self: Check if spaces should be replaced with tabs.

File: UnityProject/Assets/UI/ColorPicker/UI/HexColorField.cs [hunk 7]
```diff
@@ -41,7 +41,7 @@ private void UpdateColor(string newHex)
         if (HexToColor(newHex, out color))
             hsvpicker.CurrentColor = color;
         else
-            Debug.Log("hex value is in the wrong format, valid formats are: #RGB, #RGBA, #RRGGBB and #RRGGBBAA (# is optional)");
+            Logger.Log("hex value is in the wrong format, valid formats are: #RGB, #RGBA, #RRGGBB and #RRGGBBAA (# is optional)", Category.UI);
```
Comment (ghost) [inline UnityProject/Assets/UI/ColorPicker/UI/HexColorField.cs]: Note to self: Replace spaces with tabs.

**Comment by ghost** [comment]
Ready to be ~~purged~~ reviewed.

**Comment by ghost** [comment]
Merged new changes in order to prevent conflict.

**Comment by Jibbajabbafic** [comment]
Leaving this to you guys since you had a look before.

**Comment by RedlineTriad** [comment]
This branch has conflicting files, could you update it to the latest develop?

**Comment by ghost** [comment]
@RedlineTriad Done.

**Comment by RedlineTriad** [comment]
Currently looking at it...

**Review by RedlineTriad — CHANGES_REQUESTED** [review]
There are still log messages that do not specify a category.
Some of these can be found with the following regex:
`^[^(?:\/\/)]*Logger\.Log(?:Warning|Error|Trace)?(?:Format)?\([^,\r\n]*\);`

**Comment by ghost** [comment]
> There are still log messages that do not specify a category.
> Some of these can be found with the following regex:
> `^[^(?:\/\/)]*Logger\.Log(?:Warning|Error|Trace)?(?:Format)?\([^,\r\n]*\);`

I've made the requested changes.

File: UnityProject/Assets/Scripts/Util/SweetExtensions.cs [hunk 8]
```diff
@@ -128,7 +128,8 @@ public static BodyPartType Randomize( this BodyPartType aim, float hitProbabilit
 			if ( posData.Length > 1 && int.TryParse(posData[0], out x) && int.TryParse(posData[1], out y) ) {
 				return new Vector2(x, y);
 			}
-			Logger.LogWarning( $"Vector parse failed: what the hell is '{stringifiedVector}'?" );
+		//Would normally not use Category.Server for this, but I really don't see this fitting anywhere else unless I made a Misc or Utils category which could easily become a catch-all for people. -Alice
+		Logger.LogWarning( $"Vector parse failed: what the hell is '{stringifiedVector}'?", Category.Server);
```
Comment (fomalsd) [inline UnityProject/Assets/Scripts/Util/SweetExtensions.cs]: Category.NetUI

File: UnityProject/Assets/Scripts/Items/ItemAttributes.cs [hunk 9]
```diff
@@ -245,9 +245,9 @@ private void CheckEvaCapatibility()
 	private void DebugInfo()
 	{
 		//Logger.Log(GetItemDebugInfo());
-		Logger.Log("hier: " + hier);
-		Logger.Log("is server: " + isServer);
-		Logger.Log("is eva capable: " + IsEVACapable);
+		Logger.Log("hier: " + hier, Category.Editor);
+		Logger.Log("is server: " + isServer, Category.Editor);
+		Logger.Log("is eva capable: " + IsEVACapable, Category.Editor);
```
Comment (fomalsd) [inline UnityProject/Assets/Scripts/Items/ItemAttributes.cs]: These three are Category.DmMetadata

**Comment by fomalsd** [comment]
@RedlineTriad not like it's criminal to have no category, it's acceptable for some rare cases like editor scripts
@HiddenKn good job! just a couple of mismatches I could spot so far. I think Editor category should be ditched though

**Review by fomalsd — APPROVED** [review]
thanks! looks fine!
