### PR TITLE
Copies log entry text when clicked.

### LINKED ISSUE #6194: It would be extremely handy if errors in the game console could be copied.
### Description

Currently, it's a bit of a hassle getting errors from the in game console. Most people have to screenshot to share them because they are quite long and the text cannot be copied. It would be extremely helpful if we could get a command to copy the errors in the console for improved bug reports. Something simple like the copyid command used to get the player ID. Simply allowing the text to be highlighted and copied is acceptable also.

### PR DESCRIPTION
**Pull request by MaxIsJoe**
### Purpose
closes #6194 
Allows players and devs to copy log entry text from the in-game console.

### Changelog:
CL: Logs can now be copied from the in-game console by just left clicking on them.

### CODE REVIEW

File: UnityProject/Assets/IngameDebugConsole/Scripts/DebugLogItem.cs [hunk 1]
```diff
@@ -148,5 +152,10 @@ public override string ToString()
 		{
 			return logEntry.ToString();
 		}
+
+		private void CopyLogText()
+		{
+			GUIUtility.systemCopyBuffer = logEntry.ToString();
```
Comment (corp-0) [inline UnityProject/Assets/IngameDebugConsole/Scripts/DebugLogItem.cs:158]: is this tested? we use ``TextUtils.CopyTextToClipboard(stringHere)`` to copy to clipboard when doing the ``copyid`` command. I think we had troubles with other methods of copying to clipboard.

Comment (MaxIsJoe) [reply UnityProject/Assets/IngameDebugConsole/Scripts/DebugLogItem.cs:158]: I tested it and it works for me.

Comment (corp-0) [reply UnityProject/Assets/IngameDebugConsole/Scripts/DebugLogItem.cs:158]: tested on a build? I can build it tomorrow and see myself, kinda late for me now.

Comment (MaxIsJoe) [reply UnityProject/Assets/IngameDebugConsole/Scripts/DebugLogItem.cs:158]: > tested on a build? I can build it tomorrow and see myself, kinda late for me now.

Will build the game in a few minutes and test it.

Comment (MaxIsJoe) [reply UnityProject/Assets/IngameDebugConsole/Scripts/DebugLogItem.cs:158]: tested. works fine.
