### PR TITLE
Fix Conveyor belts having animated sprites at round start

### LINKED ISSUE #7444: Conveyor belts have animated sprite at round start
### Environment
- Game Version: UnityStationDevelop-21091918

### Detailed description of bug

All conveyors have moving sprite at round start. Toggling them on/off fixes this.

### Steps to reproduce

1. Start new round
2. Observe

### PR DESCRIPTION
**Pull request by MaxIsJoe**
fixes #7444 

apparently the fix is this easy, just need to refresh the sprites on start up.

CL: [Fix] Fixed Conveyor belts having animated sprites at round start

### CODE REVIEW

**Comment by ThatDan123** [comment]
This will call it for client too which might break things. Adding the ServerSpawn interface and calling it there might be better than awake

**Comment by Aranclanos** [comment]
try to not use awake for this, IServerSpawn should be fine as dan said

**Comment by MaxIsJoe** [comment]
done

File: UnityProject/Assets/Scripts/Objects/Cargo/ConveyorBelts/ConveyorBelt.cs [hunk 1]
```diff
@@ -42,6 +42,12 @@ public class ConveyorBelt : NetworkBehaviour, ICheckedInteractable<HandApply>, I
 		private void Awake()
 		{
 			registerTile = GetComponent<RegisterTile>();
+			if(netIdentity.isServer) RefreshSprites(); //So the host can see the sprites animated correctly on start.
```
Comment (ThatDan123) [inline UnityProject/Assets/Scripts/Objects/Cargo/ConveyorBelts/ConveyorBelt.cs]: `netIdentity.isServer` pretty sure isnt a way to check if its a server doing the action. 

You shouldnt need to do the awake check now that OnSpawnServer is used, the host will call that too since it is also a server.

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Objects/Cargo/ConveyorBelts/ConveyorBelt.cs]: OnSeverSpawn() doesn't work on the host

**Comment by MaxIsJoe** [comment]
Finally fixed and done.

**Review by ThatDan123 — APPROVED** [review]

**Review by NoooneyDude — APPROVED** [review]
