### PR TITLE
Fixes defib sound thread error

### LINKED ISSUE #8155: Defib Bug
```
UnityException: get_gameObject can only be called from the main thread.
Constructors and field initializers will be executed from the loading thread when loading a scene.
Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.

Items.Medical.DefibrillatorPaddles+<Cooldown>d__14.MoveNext () (at/root/UnityProject/Assets/Scripts/Items/Medical/DefibrillatorPaddles.cs:106)
```

Seems like we're gonna need to remove the async (I havent looked at the code might be an easy fix)

### PR DESCRIPTION
**Pull request by MaxIsJoe**
functions run on other threads can't fetch gameobjects correctly
this fix changes the cooldown function to stop the sound manager from fetching the game object's position and instead the server will provide the position from the main thread to the function.

Fixes #8155

CL: [Fix] fix an error when defibrillators played their sfx.

### CODE REVIEW

**Review by tomasalves8 — DISMISSED** [review]

File: UnityProject/Assets/Scripts/Items/Medical/DefibrillatorPaddles.cs [hunk 1]
```diff
@@ -98,12 +99,12 @@ void Perform()
...
 	}
 
-	private async void Cooldown()
+	private async void Cooldown(Vector3 soundPos)
 	{
 		onCooldown = true;
 		await Task.Delay(cooldownMs).ConfigureAwait(false);
 		onCooldown = false;
-		SoundManager.PlayNetworkedAtPos(soundCharged, gameObject.AssumedWorldPosServer());
+		SoundManager.PlayNetworkedAtPos(soundCharged, soundPos);
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/Items/Medical/DefibrillatorPaddles.cs]: wouldn't this be weird on a moving shuttle?

**Comment by ThatDan123** [comment]
This might have the issue of the sound playing in the wrong place if the person moves before the 5 second cooldown is done?

Not sure whats the best way of fixing that, other than switching to a coroutine. 

I guess if the SoundManager has a method which only takes the object source would also fix it. Could be useful to add and would fix this issue.

File: UnityProject/Assets/Scripts/Items/Medical/DefibrillatorPaddles.cs (hunk 1 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Items/Medical/DefibrillatorPaddles.cs]: You're right so i fixed this

**Comment by MaxIsJoe** [comment]
> I guess if the SoundManager has a method which only takes the object source would also fix it. Could be useful to add and would fix this issue.

There is actually a method like this already but the issue was that threads didn't play nicely when just using `gameObject` because it would try fetching it off the wrong thread
I fixed it this time after what Bod pointed out by just giving the gameObject to the function as an argument

**Comment by MaxIsJoe** [comment]
review again pls

**Review by ThatDan123 — DISMISSED** [review]
Ah yeah, that also works

**Review by Bod9001 — APPROVED** [review]

**Review by Bod9001 — CHANGES_REQUESTED** [review]
it's the users get component in AssumedWorldPos  as ThatDaniel has highlighted

**Comment by MaxIsJoe** [comment]
> it's the users get component in AssumedWorldPos as ThatDaniel has highlighted

I changed that

**Review by Bod9001 — DISMISSED** [review]

**Comment by ThatDan123** [comment]
You don't need to send the gameObject as a parameter now

**Comment by MaxIsJoe** [comment]
> You don't need to send the gameObject as a parameter now

done

**Review by Bod9001 — APPROVED** [review]

**Review by ThatDan123 — APPROVED** [review]
