### PR TITLE
Fixes disposal pipes construction and deconstruction

### LINKED ISSUE #7482: Disposal pipes duplicate when deconstructed and cannot interact with new ones
### Environment
- Game Version: Staging 21092802
- OS Version: Arch Linux

### Detailed description of bug

Disposal pipes get duplicated when deconstructed and also you cannot interact with them to place new ones.
example:

https://user-images.githubusercontent.com/80334192/135126344-0538a79a-ab11-4120-8044-af2e2141ec2b.mp4

### Steps to reproduce

1. try making new pipes and placing them on the floor
2. or try to deconstruct old ones that are already on use

### PR DESCRIPTION
**Pull request by Ahion**
### Purpose
Fix #7482

### Notes:
In general, it is a big problem that underfloor objects use one layer. In order to distinguish these objects, z-coordinate is used. We have a method that, when loading a map, goes through each cell of all matrices and if there are several objects on the underfloor layer, it assigns them a unique z coordinate. But this method did not count the disposal pipes. So, i fixed it.

### Changelog:
CL: [Fix] Disposal pipes construction and deconstruction has been fixed.

### CODE REVIEW

File: UnityProject/Assets/Scripts/Objects/Disposals/DisposalPipe.cs.meta [hunk 1]
```diff
@@ -5,7 +5,7 @@ MonoImporter:
   serializedVersion: 2
   defaultReferences: []
   executionOrder: 0
-  icon: {fileID: 2800000, guid: da9a6cbf0b6d881488fe2e0cbe135069, type: 3}
```
Comment (Ahion) [inline UnityProject/Assets/Scripts/Objects/Disposals/DisposalPipe.cs.meta]: I broke something, right? ))

Comment (corp-0) [reply UnityProject/Assets/Scripts/Objects/Disposals/DisposalPipe.cs.meta]: looks like you unassigned the icon

Comment (Ahion) [reply UnityProject/Assets/Scripts/Objects/Disposals/DisposalPipe.cs.meta]: I'll try to find what sprite was

Comment (Ahion) [reply UnityProject/Assets/Scripts/Objects/Disposals/DisposalPipe.cs.meta]: done

**Review by Bod9001 — APPROVED** [review]

**Review by NoooneyDude — APPROVED** [review]
Yes, I would like to eventually see the underfloor types use their own layer, even if just as a fix for the sprite render overlapping. It is disappointing we need to add all this code to remove a tile. I think there could be large improvements to be had with tilecode.

Thank you!

File: UnityProject/Assets/Scripts/Objects/Disposals/DisposalPipe.cs.meta (hunk 1 above)
Comment (NoooneyDude) [reply UnityProject/Assets/Scripts/Objects/Disposals/DisposalPipe.cs.meta]: Yeah, around this time I was assigning icons to scripts, objects, though I've since stopped doing that as I've discovered it adds a new unnecessary gizmo entry.
