### PR TITLE
Fixed NRE when touching electric devices as client

### LINKED ISSUE #1823: Clientside NRE when touching electric devices B: 40
# Description

## Category
BUG

## Detailed Bug Report
```
NullReferenceException: Object reference not set to an instance of an object
PowerSupplyControlInheritance.ConstructionInteraction (UnityEngine.GameObject originator, UnityEngine.Vector3 position, System.String hand) (at Assets/Scripts/Electricity/Inheritance/PowerSupplyControlInheritance.cs:137)
PowerSupplyControlInheritance.Interact (UnityEngine.GameObject originator, UnityEngine.Vector3 position, System.String hand) (at Assets/Scripts/Electricity/Inheritance/PowerSupplyControlInheritance.cs:129)
InputTrigger.Interact (UnityEngine.Vector3 position) (at Assets/Scripts/Input System/Triggers/InputTrigger.cs:50)
InputTrigger.Trigger (UnityEngine.Vector3 position) (at Assets/Scripts/Input System/Triggers/InputTrigger.cs:35)
```
## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Host from build, join from editor as an engineer
2. Try touching SMES

### PR DESCRIPTION
**Pull request by fomalsd**
### Purpose
Fixes #1823 

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [x]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### Notes:
Keep the bounty

### CODE REVIEW

File: UnityProject/Assets/Scripts/Electricity/Inheritance/PowerSupplyControlInheritance.cs [hunk 1]
```diff
@@ -1,306 +1,313 @@
...
+		ConstructionInteraction(originator, position, hand);
+		return true;
+	}
+	public virtual void _Interact(GameObject originator, Vector3 position, string hand)
+	{
+	}
+	public virtual void ConstructionInteraction(GameObject originator, Vector3 position, string hand) {
+		var slot = InventoryManager.GetSlotFromOriginatorHand(originator, hand);
+
+		if ( slot == null || slot.Item == null )
```
Comment (fomalsd) [inline UnityProject/Assets/Scripts/Electricity/Inheritance/PowerSupplyControlInheritance.cs:138]: that's the change, rest is formatting

**Comment by fomalsd** [comment]
Tested in multiplayer
