### PR TITLE
Admin healing will now revive dead players instead of healing dead bodies.

### LINKED ISSUE #6595: You can heal a dead player as an admin, but that won't bring them back to life
### Environment
- Game Version: upstream/develop (May 21th, 2021)
- OS Version: Win10

### Detailed description of bug

Using the new "heal up player" button on a dead player but it won't bring them back to life.

### Steps to reproduce

1. Be admin
2. Kill player
3. Go to your dashboard, heal up dead player, profit.

### PR DESCRIPTION
**Pull request by MaxIsJoe**
### Purpose
fixes #6595

### Changelog:
CL: [Improvement] - Admins now can now revive dead players instead of forcing their character to respawn.
CL: [Fix] - Admins no longer can heal dead bodies.

### CODE REVIEW

File: UnityProject/Assets/Scripts/HealthV2/Living/LivingHealthMasterBase.cs [hunk 1]
```diff
@@ -849,6 +849,32 @@ public void ResetDamageAll()
...
+
+		/// <summary>
+		/// Revives a dead player to full health.
+		/// </summary>
+		public void RevivePlayerToFullHealth(PlayerScript player)
+		{
+			Extinguish(); //Remove any fire on them.
+			ResetDamageAll(); //Bring their entire body parts that are on them in good shape.
+			healthStateController.SetOverallHealth(maxHealth); //Set the player's overall health to their race's maxHealth.
+			healthStateController.SetConsciousState(ConsciousState.CONSCIOUS); //They're allliiivveee!
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/HealthV2/Living/LivingHealthMasterBase.cs]: you have to restart the hearts manually, this doesn't work

Comment (Bod9001) [reply UnityProject/Assets/Scripts/HealthV2/Living/LivingHealthMasterBase.cs]: since it's determined in an update loop

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/HealthV2/Living/LivingHealthMasterBase.cs]: then why do defibs use the same logic if they don't work?
I took this straight out of the defib logic.

Comment (Bod9001) [reply UnityProject/Assets/Scripts/HealthV2/Living/LivingHealthMasterBase.cs]: I'm just saying it technically doesn't need it since the update loop will catch it, in CalculateOverallHealth

**Comment by MaxIsJoe** [comment]
And it's done, we can merge now.

**Comment by Bod9001** [comment]
healthStateController.SetConsciousState(ConsciousState.CONSCIOUS); 
			I meant this bit

**Comment by MaxIsJoe** [comment]
> ```
> 		healthStateController.SetConsciousState(ConsciousState.CONSCIOUS); 
> 		I meant this bit
> ```

calculate overhealth does seem to restart the heart tho

**Comment by MaxIsJoe** [comment]
> > ```
> > 		healthStateController.SetConsciousState(ConsciousState.CONSCIOUS); 
> > 		I meant this bit
> > ```
> 
> calculate overhealth does seem to restart the heart tho

Nope, it's very inconstant. the old code worked better.

**Comment by MaxIsJoe** [comment]
Alright, now it's done.

**Comment by waffielz** [comment]
lmao thanks for this, really good for pranking people when you stand back up without a head
