### PR TITLE
Fix Dead Gasps

### LINKED ISSUE #7730: The Gasping Dead
### Environment
- Game Version: Staging 21110300
- OS Version: Arch Linux

### Detailed description of bug

When players die their corpses wont stop gasping out and bleeding out.

https://user-images.githubusercontent.com/80334192/140237358-6fc15e52-b20f-48a5-966b-fb1a47d26c3f.mp4

### Steps to reproduce

1. kys by any means available
2. as a ghost watch the chat getting spammed with your corpse gasping for air

### PR DESCRIPTION
**Pull request by tomasalves8**
### Purpose
Fixes #7730 

### Notes:

Disabled TryBreathing() by doing a death check, removed efficiency check while attempting to gasp.

### Changelog:
CL: [Fix] Dead Players Gasping

### CODE REVIEW

**Comment by tomasalves8** [comment]
Github was down for a second while the labels workflow was running causing it to fail, LOL.

File: UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs [hunk 1]
```diff
@@ -284,13 +283,10 @@ private bool BreatheIn(GasMix breathGasMix, ReagentMix blood, float efficiency)
 			else if (bloodSaturation <= RelatedPart.HealthMaster.CirculatorySystem.BloodInfo.BLOOD_REAGENT_SATURATION_BAD)
 			{
 				RelatedPart.HealthMaster.HealthStateController.SetSuffocating(true);
-				if (efficiency < 0.5f)
```
Comment (ThatDan123) [inline UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs:287]: @Bod9001 was this needed for something or is it fine to remove?

File: UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs [hunk 2]
```diff
@@ -107,10 +107,9 @@ public bool TryBreathing(IGasMixContainer node, float efficiency)
 			{
 				return false;
 			}
-
-			if (RelatedPart.HealthMaster.CirculatorySystem.BloodPool[RelatedPart.bloodType] == 0)
+			if (RelatedPart.HealthMaster.CirculatorySystem.BloodPool[RelatedPart.bloodType] == 0 || RelatedPart.HealthMaster.IsDead)
```
Comment (ThatDan123) [inline UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs]:
```suggestion
			if (RelatedPart.HealthMaster.IsDead || RelatedPart.HealthMaster.CirculatorySystem.BloodPool[RelatedPart.bloodType] == 0)
```

Just invert that as its more likely to fail on death than no blood first. Very minor optimisation

Comment (ThatDan123) [reply UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs]: Might be better to move the death check to the beginning of the `ImplantPeriodicUpdate()`

File: UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs (hunk 1 above)
Comment (tomasalves8) [reply UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs:287]: I removed it because players wouldn't gasp unless they had lung damage, and I couldn't find any reason for it to be there.

File: UnityProject/Assets/Scripts/Objects/Engineering/TeslaCoil.cs [hunk 3]
```diff
@@ -75,7 +75,20 @@ private void TeslaCoilUpdate()
 		{
 			if(CustomNetworkManager.IsServer == false) return;
 
-			if(CurrentState == TeslaCoilState.Grounding || IsWrenched == false) return;
+
+			if (CustomNetworkManager.IsServer)
```
Comment (ThatDan123) [inline UnityProject/Assets/Scripts/Objects/Engineering/TeslaCoil.cs]: Did you mean to commit this?

Comment (ThatDan123) [reply UnityProject/Assets/Scripts/Objects/Engineering/TeslaCoil.cs]: And those prefab changes too

**Comment by tomasalves8** [comment]
Ah dammit, I'll reverse it

File: UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs (hunk 1 above)
Comment (Bod9001) [reply UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs:287]: you could make it linked directly to the brain being too damaged?

**Comment by tomasalves8** [comment]
There you go.

File: UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs (hunk 1 above)
Comment (tomasalves8) [reply UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs:287]: Hmm if the brain is too damaged there shouldn't be any breathing at all, let alone gasping right? @Bod9001

Comment (Bod9001) [reply UnityProject/Assets/Scripts/Items/Implants/Organs/Lungs.cs:287]: yeah

**Review by ThatDan123 — DISMISSED** [review]

**Review by Bod9001 — APPROVED** [review]

**Review by corp-0 — APPROVED** [review]
