### PR TITLE
Items now highlight Correctly  on order

### LINKED ISSUE #2439: Locker/crate content appearance order doesn't reflect pick up order
# Description
Easy to reproduce in botany crate: you'll see grape seeds on top, but will get other seeds when clicked
crate_annoy

It should be "WYSIWYG"

### LINKED ISSUE #2864: Assign unique sorting indexes to items
When hovering a bunch of items you expect to pick up item at the top of the pile.
Selection outline reveals that it is often not the case and instead you pick up the bottom one...
Scr 2020-02-03 at 22 58 12 2020-02-03 23_01_28

### PR DESCRIPTION
**Pull request by Bod9001**
fixes : #2439
fixes : #2864
also optimises optimise register tile location update
note won't work for matrix to matrix, but that's a rare enough circumstance
CL: highlighting should be consistent now

### CODE REVIEW

File: UnityProject/Assets/Scripts/Core/Input System/MouseUtils.cs [hunk 1]
```diff
@@ -88,14 +94,22 @@ public static IEnumerable<GameObject> GetOrderedObjectsAtPoint(Vector3 worldPoin
 			.Select(go => IsPixelHit(go.transform))
 			.Where(r => r != null)
 			//order by sort layer
-			.OrderByDescending(r => SortingLayer.GetLayerValueFromID(r.sortingLayerID))
+			.OrderByDescending(r =>
+				SortingLayer.GetLayerValueFromID(r.GetComponentInParent<SortingGroup>()?.sortingLayerID == null
```
Comment (ThatDan123) [inline UnityProject/Assets/Scripts/Core/Input System/MouseUtils.cs]:
```suggestion
				SortingLayer.GetLayerValueFromID(r.GetComponentInParent<SortingGroup>().OrNull()?.sortingLayerID == null
```

File: UnityProject/Assets/Scripts/Core/Input System/MouseUtils.cs [hunk 2]
```diff
@@ -88,14 +94,22 @@ public static IEnumerable<GameObject> GetOrderedObjectsAtPoint(Vector3 worldPoin
...
+					? r.sortingLayerID
+					: r.GetComponentInParent<SortingGroup>().sortingLayerID))
 			//then by sort order
-			.ThenByDescending(renderer => renderer.sortingOrder)
+			.ThenByDescending(renderer =>
+				renderer.GetComponentInParent<SortingGroup>()?.sortingOrder == null
```
Comment (ThatDan123) [inline UnityProject/Assets/Scripts/Core/Input System/MouseUtils.cs]:
```suggestion
				renderer.GetComponentInParent<SortingGroup>().OrNull()?.sortingOrder == null
```

File: UnityProject/Assets/Scripts/Tilemaps/Utils/TileList.cs [hunk 3]
```diff
@@ -41,23 +42,51 @@ public class TileList
...
+			offset = position.y % 2 != 0 ? 1 : 0;
+		}
+		else
+		{
+			offset = position.y % 2 != 0 ? 3 : 2;
 		}
+		int i = 0;
+		foreach (var register in _objects[position])
+		{
+			if (register?.CurrentsortingGroup == null) continue;
```
Comment (ThatDan123) [inline UnityProject/Assets/Scripts/Tilemaps/Utils/TileList.cs]:
```suggestion
			if (register.OrNull()?.CurrentsortingGroup == null) continue;
```
