### PR TITLE
do the deeds needed to fix random item generation

### LINKED ISSUE #6851: Random item spawners should work with cargo crates, syndicate uplink and admin spawning tool. B: 60
### Description

Currently, if you place a random item spawner inside of a cargo crate that is purchaseable in the cargo console, when the crate arrives on the cargo shuttle, the random items will not spawn inside the cargo crate. They do not have sufficient logic support spawning inside of objects except on initialization of the map. Photo for reference:

In addition, if an admin were to select a random item spawner from the admin spawning tool, it does not successful generate a random object. Spawners should also work with the syndicate uplink and and container storage populators. Random item spawners would be a lot more useful and flexible if they could work intuitively in these situations.

## What is needed to fulfill the bounty:

- [x] random item spawner items should spawn inside of cargo crates when purchased from the cargo console.
- [x] random item spawners should work with the admin spawning tool.
- [x] random item spawners should work with storage populators
- [x] random item spawners and pools should spawn the item in player hands like other syndicate uplink items when purchased from the uplink.

example screenshot of how random item spawners are currently not compatible with cargo crates bought from the cargo console:
Screenshot_2021-06-21_151856

### PR DESCRIPTION
**Pull request by VernaSaurus**
should close #6851 

CL: [Improvement] random item spawners now work with cargo crates, the syndicate uplink, and admin spawn tools.

### CODE REVIEW

File: UnityProject/Assets/Scripts/Items/PDA/PDALogic.cs [hunk 1]
```diff
@@ -458,6 +458,9 @@ public void SpawnUplinkItem(GameObject objectRequested, int cost)
 			{
 				UplinkTC -= cost;
 				var item = result.GameObject;
+				if(item.TryGetComponent<RandomItemSpot>(out var randomItem)){
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/Items/PDA/PDALogic.cs]: it would be better before you spawned the random object spawn, then you spawn it in, 
you pick the object before Spawn it in I mean

Comment (VernaSaurus) [reply UnityProject/Assets/Scripts/Items/PDA/PDALogic.cs]: It might just be because I'm tired, but I have no idea what this means.

Comment (VernaSaurus) [reply UnityProject/Assets/Scripts/Items/PDA/PDALogic.cs]: Requested changes made. Marking this as resolved.

**Review by NoooneyDude — DISMISSED** [review]

**Review by Bod9001 — APPROVED** [review]

**Comment by Bod9001** [comment]
did you test admin spawning tool and storage populators?

**Comment by VernaSaurus** [comment]
> did you test admin spawning tool and storage populators?

Yes, I tested every case the bounty specified.

**Comment by Bod9001** [comment]
added it to  chemists inventory populater and it didn't work, that needs to be done

**Review by Bod9001 — CHANGES_REQUESTED** [review]
get the storage populaters working,
you could properly add a thing on start ,
that checks if it's in an inventory and then does the appropriate swapping

**Comment by VernaSaurus** [comment]
huh, it worked before, musta broken it somehow

**Comment by VernaSaurus** [comment]
fixed the thing, now it works

**Comment by Bod9001** [comment]
seems a bit hacky, I think what would be the best thing would be in 
SpawnablePrefab : ISpawnable, IClientSpawnable
SpawnablePrefab For(GameObject prefab)
adding the check there, and thenadding a bool override if you just want it to spawn the random item spawner 
what do you think?

**Comment by VernaSaurus** [comment]
I think it's fine, and I already felt uncomfortable enough modifying the populator script, I don't think I could mentally handle changing something as central as SpawnablePrefab

**Comment by Bod9001** [comment]
ill do it

**Comment by VernaSaurus** [comment]
thank you bod, you're a hero

**Review by Bod9001 — APPROVED** [review]
should be good now

**Comment by VernaSaurus** [comment]
sweet, so this can finally be committed?

**Comment by Bod9001** [comment]
yeah, just got to have someone else review

**Review by corp-0 — APPROVED** [review]
