### PR TITLE
FIX | Shutters insta kill

### LINKED ISSUE #3265: Killing shutters.
# Issue Template
You can be smashed by closing shutter
## Description
They insta killing you! Beware them!
### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  
1.  Step under the shutter
2.  Press button to close it.
3.  Die

### PR DESCRIPTION
**Pull request by ReiderJack**
# Purpose
Fixes #3265

### Notes:
ShutterDamage

### CODE REVIEW

File: UnityProject/Assets/Scripts/Doors/DoorController.cs [hunk 1]
```diff
@@ -37,6 +37,9 @@ public enum OpeningDirection
 		[Tooltip("Toggle damaging any living entities caught in the door as it closes")]
 		public bool damageOnClose = false;
 
+		[Tooltip("Amount of damage when closed on someone.")]
+		public float damageClosed = 30;
```
Comment (fomalsd) [inline UnityProject/Assets/Scripts/Doors/DoorController.cs]:
```suggestion
		public float damageClosed = 90;
```
