### PR TITLE
Pull fix02

### LINKED ISSUE #725: Pulled items/objects jumping all over the place at high ping B: 30
# Preliminary information

## Category
BUG

## Bug: Release or Development?
Develop

# Report
## Current Behavior
When pulling an object or item with a high ping client, it jumps,rubberbands and lags all over the place. Including pushing the player etc.

## Expected/Wanted/Requested Behavior
Pulling should not trip out.

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. log into a server with 200 ping client
2. pull stuff
3.

## OS used:
OSX

## System specifications
Macbook pro, quadcore, dedigpu, 8gbram, ssd

## Network
200 ping, same pc.

## Note
Maybe it's the lack of client side prediction that bites us in the ass.

### LINKED ISSUE #764: Pull not send to other player
# Preliminary information

## Category
BUG

## Bug: Release or Development?
Develop

# Report
## Current Behavior
When pulling the other item does not experience being pulled and can continue to walk arround, making the pulling player trip-out when he tries to walk the same tile as the (invisable) player he is supposed to be pulling

## Expected/Wanted/Requested Behavior
The other player experiences being pulled

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Pull other player
2. See you pulling the player
3. Look on screen of other player, not experiencing pull
4. Try stop pulling, didn't work

## OS used:
OSX

## System specifications
Macbook pro retina 2012 (late)

## Network
Same pc, no higher ping

### LINKED ISSUE #808: Players appear on original position after being moved in closed container B: 10
# Preliminary information

## Category
BUG

## Bug: Release or Development?
0.2.2A5

# Report
## Current Behavior
In title

## Expected/Wanted/Requested Behavior
Player should appear at container's position instead 

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Get in closet and lock yourself
2. Make someone push that closet
3. Open closet
portacloset

## Network
Test server

### PR DESCRIPTION
**Pull request by DooblyNoobly**
### Purpose
Fixing pull behaviour, Chat window, Clothing squash bug, Player position on closet exit, Camera change on corpse entering closet bug and also started the methods to be used for the future space push feature

### Open Questions and Pre-Merge TODOs

- [x]  I read the contribution guidelines and the wiki.
- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  This PR does not include files without specific need to do so.
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [x]  This PR has been tested in multiplayer

### Notes:
Fixes #725, Fixes #764, Might of had an effect on #800 (forgot to test) and Fixes #808

### CODE REVIEW

File: UnityProject/Assets/Scripts/Objects/PushPull.cs [hunk 1]
```diff
@@ -152,31 +146,37 @@ public void BreakPull()
 		pulledBy = null;
 	}
 
+	//This is to turn off CNT while pulling an object
+	[ClientRpc]
+	public void RpcToggleCnt(bool activeState){
```
Comment (fomalsd) [inline UnityProject/Assets/Scripts/Objects/PushPull.cs:151]: The whole idea of turning CNT off is very questionable (it's not meant to be turned off), but we'll see how it will perform in practice. 
This can potentially cause problems: what happens if server forces a SetPosition via CNT, but it will be disabled on client's side? (I suspect it will be ignored)

File: UnityProject/Assets/Scripts/Objects/PushPull.cs [hunk 2]
```diff
@@ -31,118 +34,109 @@ public override void OnStartClient()
...
 				CancelPullBehaviour();
-			}
-			else
-			{
+			} else {
 				CancelPullBehaviour();
 				PlayerManager.LocalPlayerScript.playerNetworkActions.CmdPullObject(gameObject);
+				//Predictive pull:
+				if (customNetTransform != null) {
+					customNetTransform.enabled = false;
```
Comment (fomalsd) [inline UnityProject/Assets/Scripts/Objects/PushPull.cs:72]: where do you turn it back on?

**Review by fomalsd — COMMENTED** [review]
Changes look good in general, but I don't like CNT toggling: that could cause unexpected problems in the future

**Comment by DooblyNoobly** [comment]
All those concerns I thought of also, over a period of about a month. I came to the conclusion that fixing the existing code was better and switching off CNT in pull mode would not cause any problems. Checkout the PR and play around with it. Also foma its switched back on via the server.

**Comment by DooblyNoobly** [comment]
If you want to see some attempts if trying to integrate with cnt look at my previous branches that went to shit. Pull code is like trying to jump through a pinhole with breaking anything
