### PR TITLE
Fixes machine connectors getting duplicated

### LINKED ISSUE #7554: machine connectors seem to be duplicated by unwrenching them.
### Environment
- Game Version: latest staging

### Steps to reproduce

1. find a placed machine connector
2. unwrench it

### PR DESCRIPTION
**Pull request by MaxIsJoe**
Fixes #7554

## Changelog : 

CL: [Fix] - Fixed machine connectors getting duplicated.
CL: [Improvement] - Adds a 1 second progress bar to remove machine connectors.

### CODE REVIEW

File: UnityProject/Assets/Scripts/Systems/Electricity/Wire/CableCategories/LowVoltageMachineConnector.cs [hunk 1]
```diff
@@ -40,6 +44,17 @@ public bool WillInteract(PositionalHandApply interaction, NetworkSide side)
 
 		public void ServerPerformInteraction(PositionalHandApply interaction)
 		{
+			void Remove()
+			{
+				if (removedOnce) return;
+				removedOnce = true;
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/Systems/Electricity/Wire/CableCategories/LowVoltageMachineConnector.cs]: This doesn't really matter since it should be destroyed right On server side?

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Systems/Electricity/Wire/CableCategories/LowVoltageMachineConnector.cs]: It doesn't get destroyed, there can be a long delay where or some sort of hidden error that causes this to stay up on both the server and the client so this is a counter measure to stop duping for players who double click quickly or are desynced.

Comment (Bod9001) [reply UnityProject/Assets/Scripts/Systems/Electricity/Wire/CableCategories/LowVoltageMachineConnector.cs]: maybe just have a on spawn server hook to reset it, in case it's getting pooled

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Systems/Electricity/Wire/CableCategories/LowVoltageMachineConnector.cs]: wdym?

Comment (Bod9001) [reply UnityProject/Assets/Scripts/Systems/Electricity/Wire/CableCategories/LowVoltageMachineConnector.cs]: the object getting poolled, as in it gets reused

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Systems/Electricity/Wire/CableCategories/LowVoltageMachineConnector.cs]: if it is indeed getting pooled currently, wont that stop this fix because it will be spawned again and will let people spawn another one again?

Comment (Bod9001) [reply UnityProject/Assets/Scripts/Systems/Electricity/Wire/CableCategories/LowVoltageMachineConnector.cs]: that's only if it's getting instantly spawned in again, but that would be a separate bug

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Systems/Electricity/Wire/CableCategories/LowVoltageMachineConnector.cs]: done
