### PR TITLE
Fixes PDA TC count not updating after using a telecrystal

### LINKED ISSUE #7053: Uplink TC count doesn't update in the PDA when adding TC until you close the uplink and reopen.
### Detailed description of bug

The counter for how much TC is left in your uplink does not update when you add more TC to the uplink until you close the uplink and reopen it. Then it updates to the amount you put in. It should update immediately after putting in extra TC.

### PR DESCRIPTION
**Pull request by Aranclanos**
### Purpose
Fixes PDAs not updating its TC counter UI once a telecrystal is used on them.
Fixes #7053

### CODE REVIEW

File: UnityProject/Assets/Scripts/Items/PDA/PDALogic.cs [hunk 1]
```diff
@@ -356,6 +359,7 @@ private void ServerInsertItem(GameObject item, ItemSlot fromSlot, GameObject pla
 						$"After a moment it disappears, your Telecrystal counter ticks up a second later";
 
 					Chat.AddExamineMsgFromServer(player, uplinkMessage);
+					PDAGui.uplinkPage.UpdateTCCounter();
```
Comment (ThatDan123) [inline UnityProject/Assets/Scripts/Items/PDA/PDALogic.cs]: Could this null if you spawn a PDA in and then use a telecrystal without first opening the UI?

Comment (Aranclanos) [reply UnityProject/Assets/Scripts/Items/PDA/PDALogic.cs]: no, its set in the prefab of the tab

Comment (ThatDan123) [reply UnityProject/Assets/Scripts/Items/PDA/PDALogic.cs]: But the tab wont be created until it has been opened the first time

Comment (Aranclanos) [reply UnityProject/Assets/Scripts/Items/PDA/PDALogic.cs]: yeah whoops
