### PR TITLE
Multiple Bug Fixes

### LINKED ISSUE #1277: Shortcut keys are still working when writing in chat
# Description

## Category
BUG

## Detailed Bug Report
Shortcut keys are still working when writing in chat, although they probably shouldnt.

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Pick up an item
2. open chat
3. Press 'Q' (item will drop)

### LINKED ISSUE #1335: Paper window closes and breaks when tab button is pressed
# Description
Switching to nettab while paper window is activated makes it close and not open until it's moved to pocket slot and back (swapping hands, dropping and picking up doesn't work)

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Join as captain
2. Pick up and activate paper
3. Press any button in tab bar (Like "More")

https://cdn.discordapp.com/attachments/438708245268267028/511125863841136640/Scr_2018-11-11_13.25.13.mov

### LINKED ISSUE #1340: NRE when trying to equip clothes with E button
# Description
Glasses, helmet, gloves and possibly other slots throw following NRE when they are in your hand and `E` button is pressed for quick equip:
```
NullReferenceException: Object reference not set to an instance of an object
Hands.Swap (UI_ItemSlot slot1, UI_ItemSlot slot2) (at Assets/Scripts/UI/UI Bottom/Hands.cs:159)
Hands.SwapItem (UI_ItemSlot itemSlot) (at Assets/Scripts/UI/UI Bottom/Hands.cs:90)
Hands.Use () (at Assets/Scripts/UI/UI Bottom/Hands.cs:125)
ControlAction.CheckKeyboardInput () (at Assets/Scripts/UI/UI Bottom/ControlAction.cs:63)
ControlAction.Update () (at Assets/Scripts/UI/UI Bottom/ControlAction.cs:23)
```
Drag and drop works fine.

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Go to cloth vending machines and spawn some clothes
2. Pick up glasses/helmet/gloves in your hand and press E to quick equip

### PR DESCRIPTION
**Pull request by DooblyNoobly**
- Fixes #1340 
- Fixes #1335 
- Fixes #1277 

for #1340:
Wrong event names were being used in the HandSwap component and suit storage was named incorrectly in the UI

for #1335:
Added a IsPopOut check for the deselect nettabs method

for #1277 
Added a UIManager.IsInputFocus for all of the ControlAction shortcuts

### CODE REVIEW

File: UnityProject/Assets/UI/InventorySlotCache.cs [hunk 1]
```diff
@@ -132,10 +132,10 @@ public static UI_ItemSlot GetSlotByItemType(ItemType type)
 				eventName = "glasses";
```
Comment (fomalsd) [inline UnityProject/Assets/UI/InventorySlotCache.cs:132]: it should probably be called `eyes`
