### PR TITLE
Fixes for character creator

### LINKED ISSUE #9988: Character names should be allowed to have capital letters in the middle of their names
Related to #7878

image

### PR DESCRIPTION
**Pull request by MaxIsJoe**
fixes #9988

CL: [Fix] Fixed an issue where players could roll for the ability to play as a cow.
CL: [Fix] The strict filter for names have been loosened to allow for names that have capital letters in the middle of them.

### CODE REVIEW

**Comment by corp-0** [comment]
I would remove the restriction completely, honestly.

**Comment by MaxIsJoe** [comment]
Lucky for you, It is removed!

File: UnityProject/Assets/Scripts/Clothing/RaceSOSingleton.cs [hunk 1]
```diff
@@ -22,4 +22,14 @@ public static bool TryGetRaceByName(string raceName, out PlayerHealthData race)
 		race = null;
 		return false;
 	}
+
+	public static List<PlayerHealthData> GetPlayerRaces()
+	{
+		var list = new List<PlayerHealthData>();
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Clothing/RaceSOSingleton.cs]: embrace LINQ

```suggestion
		return Instance.Races.Where(race => race.Base.CanBePlayerChosen).ToList();
```

as a second suggestion, I would replace any future mention of "race" with "specie" since it is more semantically correct.

File: UnityProject/Assets/Scripts/UI/Systems/Lobby/CharacterCustomization.cs [hunk 2]
```diff
@@ -130,7 +131,7 @@ private void GrabAllSpecies()
 				Loggy.LogError("UNABLE TO GRAB ALL SPECIES!! CHARACTER CREATION SCREEN IS SURELY GOING TO BE BROKEN!!!");
 				return;
 			}
-			allSpecies = RaceSOSingleton.Instance.Races.Where(alien => alien.Base.CanBePlayerChosen).ToList();
+			allSpecies = RaceSOSingleton.GetPlayerRaces();
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/UI/Systems/Lobby/CharacterCustomization.cs]: wait, you did change this perfectly fine LINQ with that new method, why?

File: UnityProject/Assets/Scripts/Util/Independent/FluentRichText/StringExtensions.cs [hunk 3]
```diff
@@ -38,5 +38,17 @@ public static class StringExtensions
 		public static string Superscript(this string text) => new SuperscriptStrategy().ApplyStyle(text);
 		public static string VerticalOffset(this string text, string amount) => new VerticalOffsetStrategy(amount).ApplyStyle(text);
 		public static string Width(this string text, string amount) => new WidthStrategy(amount).ApplyStyle(text);
+
+		public static string ToUpperFirstLetter(this string source)
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Util/Independent/FluentRichText/StringExtensions.cs]: there is an extension method that does this already, if I'm not mistaken it is ``.Capitalize()``

File: UnityProject/Assets/Scripts/UI/Systems/Lobby/CharacterCustomization.cs (hunk 2 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/UI/Systems/Lobby/CharacterCustomization.cs]: We needed a general function to grab all player species without rewriting the same code over and over again.

Comment (corp-0) [reply UnityProject/Assets/Scripts/UI/Systems/Lobby/CharacterCustomization.cs]: fair, but I still consider the LINQ version to be nicer.

File: UnityProject/Assets/Scripts/Util/Independent/FluentRichText/StringExtensions.cs (hunk 3 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Util/Independent/FluentRichText/StringExtensions.cs]: fixed

File: UnityProject/Assets/Scripts/Clothing/RaceSOSingleton.cs (hunk 1 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Clothing/RaceSOSingleton.cs]: done 👍

File: UnityProject/Assets/Scripts/Clothing/RaceSOSingleton.cs [hunk 4]
```diff
@@ -22,4 +23,9 @@ public static bool TryGetRaceByName(string raceName, out PlayerHealthData race)
 		race = null;
 		return false;
 	}
+
+	public static List<PlayerHealthData> GetPlayerRaces()
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Clothing/RaceSOSingleton.cs]:
```suggestion
	public static List<PlayerHealthData> GetPlayerSpecies()
```

**Comment by MaxIsJoe** [comment]
Also, regarding the LINQ comment:

It's fine if we use LINQ with client-sided stuff because we don't really care about the extra GC that clients can easily deal with, but I generally prefer if we avoid LINQ as much as possible so we don't accidentally slip into a habit of overusing it, or giving newcomers the false sense that they can use LINQ freely.

https://unitystation.github.io/unitystation/contribution-guides/Development-Standards-Guide/#2-performance-gotchas

**Comment by corp-0** [comment]
> Also, regarding the LINQ comment:
> 
> It's fine if we use LINQ with client-sided stuff because we don't really care about the extra GC that clients can easily deal with, but I generally prefer if we avoid LINQ as much as possible so we don't accidentally slip into a habit of overusing it, or giving newcomers the false sense that they can use LINQ freely.
> 
> https://unitystation.github.io/unitystation/contribution-guides/Development-Standards-Guide/#2-performance-gotchas

in your case, it was going to generate the same amount of GC because you also did a discardable list

**Comment by MaxIsJoe** [comment]
better be safe than sorry ¯\_(ツ)_/¯

**Review by corp-0 — APPROVED** [review]
