### PR TITLE
Flickering wall items

### LINKED ISSUE #1571: closing and opening a locker on yourself makes wall objects visible
# Description
Player can see wall objects on the other side of walls after closing and opening a locker on themselves
## Category
BUG

## Detailed Bug Report
[example](https://imgur.com/uaL0Dij)
## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. get in a locker and close and open the door rapidly
2. notice some objects flicker into existence

### PR DESCRIPTION
**Pull request by coolcat1711**
Implemented solution to issue #1571 by preventing use of the HiddenPos for position calculations

### Purpose
Fixes #1571 
Uses parent ObjectBehavior to set valid position.

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [x]  This PR has been tested in multiplayer

### Notes:
PR creates a "lastNonHiddenPosition" that is used to rectify intermittent transform.position sets to the HiddenPos when the position is updated after exiting a locker.

### CODE REVIEW

**Comment by DooblyNoobly** [comment]
I'll ask foma to look at this one, I'm not too familiar with playersync

File: UnityProject/Assets/Scripts/Objects/ObjectBehaviour.cs [hunk 1]
```diff
@@ -14,15 +14,23 @@ public class ObjectBehaviour : PushPull
 
 	//The object that this object is contained inside
 	public ObjectBehaviour parentContainer = null;
+	private Vector3 lastNonHiddenPosition = new Vector3();
+	//Location where objects are sent to when hidden
+	private readonly Vector3Int HiddenPos = new Vector3Int(0, 0, -100);
```
Comment (fomalsd) [inline UnityProject/Assets/Scripts/Objects/ObjectBehaviour.cs]: Just use TransformState.HiddenPos, no need to declare it in more than one place

**Comment by fomalsd** [comment]
Did you test if push/pull and space interactions still work properly? And a high ping multiplayer test is a must when messing with player positions:
[Ping Simulation](https://github.com/unitystation/unitystation/wiki/Building-And-Testing#set-up-ping-simulation)

File: UnityProject/Assets/Scripts/Objects/WallmountSpriteBehavior.cs [hunk 2]
```diff
@@ -36,9 +36,11 @@ private void OnWillRenderObject()
 		{
 			return;
 		}
+		//Allows getting parent's assumed position if inside object
+		objectBehaviour = PlayerManager.LocalPlayer.GetComponent<ObjectBehaviour>();
```
Comment (fomalsd) [inline UnityProject/Assets/Scripts/Objects/WallmountSpriteBehavior.cs]: This code won't compile, you forgot to define a variable.
But most importantly you **really** don't want to call `GetComponent` for each wallmount every frame!
instead refer to local player script where there's already a reference to PushPull (and ObjectBehaviour is its subclass)
So just access it instead and don't forget to change `pushPull` field type in PlayerScript to ObjectBehaviour as well
```suggestion
				var objectBehaviour = PlayerManager.LocalPlayerScript.pushPull;
```

**Review by fomalsd — CHANGES_REQUESTED** [review]
The code doesn't compile as is, but it seems to work with suggested changes (see above)

**Comment by coolcat1711** [comment]
Updated with suggested changes

**Comment by fomalsd** [comment]
cool, good job!

**Review by fomalsd — APPROVED** [review]
