### PR TITLE
Movement improvements

### LINKED ISSUE #8761: Thrown lockers and other big object can't recover from scuffed rotation
### Environment
- Game Version: 220600122
- OS Version: win10

### Detailed description of bug

Similar to mobs, when throwing lockers or other big objects they will stay in messed up rotation forever.

### Steps to reproduce

1. Grab locker
2. Throw locker
3. See it wrongly rotated for the rest of its existence.

### LINKED ISSUE #8764: Facehuggers (and apparently the queen) glitch and leap through walls sometimes
### Environment
- Game Version: 22060401
- OS Version: win10

### Detailed description of bug

Facehuggers and the xeno queen can go through walls sometimes, and facehuggers leap onto players despite having a wall between them if both entities are close to said wall.
Not unlikely that other xenos can do the same or anything that shares their movement AI

### Steps to reproduce

1. Have a facehugger exist in an enclosed space
2. Maybe it will glitch out of said space, it is random
3. To test the leap, stand near a wall while a facehugger is on the other side. It happened to me between a plasma window

### PR DESCRIPTION
**Pull request by Bod9001**
Movement improvements
no pulling in containert
fixes face huggers glitching through walls

fixes #8764
fixes #8761

### CODE REVIEW

**Comment by corp-0** [comment]
Link the issues this will close

File: UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs [hunk 1]
```diff
@@ -142,15 +142,27 @@ public ObjectContainer ContainedInContainer
 			{
 				if (CashedContainedInContainer == null)
 				{
-					CashedContainedInContainer =
-						NetworkIdentity.spawned[parentContainer].GetComponent<ObjectContainer>();
+					if (NetworkIdentity.spawned.TryGetValue(parentContainer, out var Net))
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs]:
```suggestion
					if (NetworkIdentity.spawned.TryGetValue(parentContainer, out var net))
```

File: UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs [hunk 2]
```diff
@@ -142,15 +142,27 @@ public ObjectContainer ContainedInContainer
...
+					{
+						CashedContainedInContainer = Net.GetComponent<ObjectContainer>();
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs]:
```suggestion
						CashedContainedInContainer = net.GetComponent<ObjectContainer>();
```

File: UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs [hunk 3]
```diff
@@ -142,15 +142,27 @@ public ObjectContainer ContainedInContainer
...
 				}
 				else
 				{
 					if (CashedContainedInContainer.registerTile.netId != parentContainer)
 					{
-						CashedContainedInContainer =
-							NetworkIdentity.spawned[parentContainer].GetComponent<ObjectContainer>();
+						if (NetworkIdentity.spawned.TryGetValue(parentContainer, out var Net))
+						{
+							CashedContainedInContainer = Net.GetComponent<ObjectContainer>();
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs]:
```suggestion
							CashedContainedInContainer = net.GetComponent<ObjectContainer>();
```

File: UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs [hunk 4]
```diff
@@ -953,6 +977,8 @@ public void CheckMatrixSwitch()
 
 	public void PullSet(UniversalObjectPhysics ToPull, bool ByClient, bool Synced = false)
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs]:
```suggestion
	public void PullSet(UniversalObjectPhysics toPull, bool byClient, bool synced = false)
```

File: UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs [hunk 5]
```diff
@@ -953,6 +977,8 @@ public void CheckMatrixSwitch()
...
 	{
+		if (ToPull != null && ContainedInContainer != null) return; //Can't pull stuff inside of objects)
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs]:
```suggestion
		if (toPull != null && ContainedInContainer != null) return; //Can't pull stuff inside of objects)
```

File: UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs [hunk 6]
```diff
@@ -953,6 +977,8 @@ public void CheckMatrixSwitch()
...
+
 		if (isServer && Synced == false)
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs]:
```suggestion
		if (isServer && synced == false)
```

**Review by corp-0 — CHANGES_REQUESTED** [review]
Please make sure that are all the usages in your IDE

**Review by corp-0 — APPROVED** [review]
