### PR TITLE
Fixes mouse traps and by extension pickable floorhazards

### LINKED ISSUE #9018: Moussetrap, clap, in your hands
**Environment**

**- Game Version:** 22-06-17-04
**- OS Version:** Lubuntu 18.04.6x64
**- Linux version**  `5.17.0-14.1-liquorix-amd64 (steven@liquorix.net) (gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, GNU ld (GNU Binutils for Ubuntu) 2.30) #1 ZEN SMP PREEMPT liquorix 5.17-18ubuntu1~bionic (2022-06-10)`
**- Server:** Locale

**Detailed description of bug**
**Context**
Head Officer, in fallstation, At corridor

take a box of mousseetrap
take a mossetrap
activate it
drop to the ground

if someone steps on it, it has a chance to take damage and deactivate the trap.

if they pick up the foam trap
and move to the (empty) tile where it was, it activates in your hands and does damage.

If you pick up a mouse and move to the empty tile where the mousetrap was, the mousetrap will activate in your hands and take damage.
https://youtu.be/MDpxs4E7KHI

### PR DESCRIPTION
**Pull request by MaxIsJoe**
Fixes #9018

## Changelog:

CL: [Fix] - Floor hazards now update their positions when picked up.

### CODE REVIEW

File: UnityProject/Assets/Scripts/Objects/FloorHazard.cs [hunk 1]
```diff
@@ -33,6 +33,7 @@ public override bool WillAffectPlayer(PlayerScript playerScript)
 
 		public override void OnPlayerStep(PlayerScript playerScript)
 		{
+			if(objectPhysics.registerTile.LocalPosition == Vector3Int.zero) return;
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/Objects/FloorHazard.cs]: surely you mean hidden pos?

File: UnityProject/Assets/Scripts/Objects/FloorHazard.cs [hunk 2]
```diff
@@ -92,6 +93,12 @@ protected void ApplyDamageToPartyType(LivingHealthMasterBase health, BodyPartTyp
 		{
 			health.ApplyDamageToBodyPart(gameObject, damageToGive, attackType, damageType, type, armorPentration, traumaChance, traumaType);
 		}
+
+		public void OnInventoryMoveServer(InventoryMove info)
+		{
+			OnLocalPositionChangedServer(info.FromPlayer != null ? info.FromPlayer.LocalPosition : Vector3Int.zero,
```
Comment (Alainx277) [inline UnityProject/Assets/Scripts/Objects/FloorHazard.cs]:
```suggestion
			OnLocalPositionChangedServer(info.FromPlayer.OrNull()?.LocalPosition ?? Vector3Int.zero,
```

File: UnityProject/Assets/Scripts/Objects/FloorHazard.cs (hunk 1 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Objects/FloorHazard.cs]: Done

**Review by Bod9001 — APPROVED** [review]
