### PR TITLE
Now when the player tries to unbuckle while handcuffed, it is possible to do so (in a minute)

### LINKED ISSUE #5757: Cuffing and buckling someone else into a chair often traps them there permanently
### Environment
- Game Version: 4608

### description of bug

when a person is cuffed and buckled into a chair, they are often trapped there and cannot escape without help from another player. The resist key does nothing. It won't even say that the player starts to break out of their cuffs. The unbuckle button also is unclickable.

### Steps to reproduce

1. cuff another player
2. buckle that player into a chair
3. that player's resist key and unbuckle action button usually will not the majority of the time

### PR DESCRIPTION
**Pull request by Lizurt**
### Purpose

fixes #5757 

- If a player is handcuffed, when he tries to get up from the chair, a message will be displayed that it will not be possible to unbuckle immediately
- If the player is handcuffed, when he tries to get up from the chair, the action "attempt to unbuckle from the chair" begins. After 60 seconds, the player will get up from the chair(but the handcuffs will remain on him).

P.S. well, it was partly my fault: https://github.com/unitystation/unitystation/pull/4772

### CODE REVIEW

File: UnityProject/Assets/Scripts/Player/PlayerMove.cs [hunk 1]
```diff
@@ -128,8 +129,12 @@ public bool IsSwappable
 
 	[HideInInspector] public PlayerNetworkActions pna;
 
-	[HideInInspector] [SyncVar(hook = nameof(SyncRunSpeed))] public float RunSpeed;
-	[HideInInspector] [SyncVar(hook = nameof(SyncWalkSpeed))] public float WalkSpeed;
+	[HideInInspector] [SyncVar(hook = nameof(SyncRunSpeed))]
```
Comment (Lizurt) [inline UnityProject/Assets/Scripts/Player/PlayerMove.cs:132]: This and other cosmetic changes were made automatically by JB Rider (I pressed the alignment buttons and forgot that they would apply to the entire file).

If it's not OK, tell me.

**Comment by ThatDan123** [comment]
Have you built tested with two a client and headless server?

**Comment by Lizurt** [comment]
> Have you built tested with two a client and headless server?

Tested only through unity... Well, I mean, these buttons:

image

(also, is this a headless server?)

File: UnityProject/Assets/Scripts/Player/PlayerMove.cs [hunk 2]
```diff
@@ -443,10 +445,30 @@ private void SyncWalkSpeed(float oldSpeed, float newSpeed)
...
+			StandardProgressAction.Create(
+				new StandardProgressActionConfig(StandardProgressActionType.Unbuckle),
+				Unbuckle
+			).ServerStartProgress(
+				buckledObject.RegisterTile(),
+				buckledObject.GetComponent<BuckleInteract>().ResistTime,
+				playerScript.gameObject
+			);
+			return;
+		}
```
Comment (ThatDan123) [inline UnityProject/Assets/Scripts/Player/PlayerMove.cs]: Its just that this stuff reads to me as being serverside code, which is being called on the client so wont work.

**Comment by ThatDan123** [comment]
Running in editor isnt headless, you would need to build the game and the run it with the headless command

File: UnityProject/Assets/Scripts/Player/PlayerMove.cs (hunk 2 above)
Comment (ThatDan123) [reply UnityProject/Assets/Scripts/Player/PlayerMove.cs]: You'll just need to move all that code into the CmdUnbuckle()

Comment (Lizurt) [reply UnityProject/Assets/Scripts/Player/PlayerMove.cs]: Can I just move this to `CmdUnbuckle()` without having to build the game? (because it takes a REALLY HUGE AMOUNT OF TIME without an SSD drive). Or is it mandatory?

Comment (ThatDan123) [reply UnityProject/Assets/Scripts/Player/PlayerMove.cs]: Its best to test stuff like this so broken stuff doesnt get merged

Comment (ThatDan123) [reply UnityProject/Assets/Scripts/Player/PlayerMove.cs]: But since this is minor change, you should be fine

Comment (Lizurt) [reply UnityProject/Assets/Scripts/Player/PlayerMove.cs]: > Its best to test stuff like this so broken stuff doesnt get merged

Understood, thanks. Then I'll test and migrate the code in about a day or a little more(I hope still a day). So it's not safe to merge this PR yet, carefully

UPD: damn, i didn't notice your last answer. Well, in any case, I'll try to test this more thoroughly

File: UnityProject/Assets/Scripts/Player/PlayerMove.cs (hunk 1 above)
Comment (NoooneyDude) [reply UnityProject/Assets/Scripts/Player/PlayerMove.cs:132]: This is fine.

File: UnityProject/Assets/Scripts/Player/PlayerMove.cs (hunk 2 above)
Comment (Lizurt) [reply UnityProject/Assets/Scripts/Player/PlayerMove.cs]: Done. I moved the code and tested it all on a headless server with two clients, everything seems to work well
