### PR TITLE
Fixes Facehugger not changing sprite after impregnation (#7132)

### LINKED ISSUE #7132: Facehuggers don't change sprites after they successfully infect someone and die.
### Environment
- Game Version: Production 4120
- OS Version: Windows 10

### Detailed description of bug
Title. Facehuggers don't change sprites after they latch onto someone's face die after successfully impregnating them. This can result in terror and confusion when a dead facehugger continues to wiggle about as if still alive.

### Steps to reproduce
1. Get impregnated by a facehugger.
2. After you get back up after being knocked down, examine the facehugger to see its dead description.
3. Notice that the dead facehugger is still wiggling.

### PR DESCRIPTION
**Pull request by AtnerNT**
### Purpose
Fixes  #7132 causing facehuggers to once again change sprites after they impregnate a host, the code was updating the clothing data but not the sprite itself

### Changelog:
CL: [Fix] Fixes a bug where facehuggers will still have their alive animation even after dying from impregnating a host.

### CODE REVIEW

File: UnityProject/Assets/Scripts/Clothing/FacehuggerImpregnation.cs [hunk 1]
```diff
@@ -27,6 +27,9 @@ public class FacehuggerImpregnation : NetworkBehaviour, IServerInventoryMove, IC
 		[Tooltip("Reference to larvae gameObject so we can spawn it")] [SerializeField]
 		private GameObject larvae = null;
 
+		[Tooltip("The SpriteHandler the facehugger should use once it successfully impregnates a host")] [SerializeField]
```
Comment (corp-0) [inline UnityProject/Assets/Scripts/Clothing/FacehuggerImpregnation.cs]: all items should only use one sprite handler except for layered sprites. Could you get the sprite handler on awake instead?
