### PR TITLE
Finally fixes the jukebox

### LINKED ISSUE #8813: jukebox
jukebox broken, push play and you have 2-3 jukebox in same time

### PR DESCRIPTION
**Pull request by MaxIsJoe**
fixes #8813.

CL: [Fix] - The Jukebox will no longer play multiple songs at the same time.
CL: [Improvement] - The Jukebox will now loopback to the first song once it reached the end of the playlist in autoplay and in navigating.

### CODE REVIEW

File: UnityProject/Assets/Scripts/Objects/Machines/Jukebox.cs [hunk 1]
```diff
@@ -207,39 +191,40 @@ public async Task Stop(bool autoplay = false)
...
-				if (IsPlaying) _ = Play();
+				SoundManager.StopNetworked(id);
 			}
+			guid.Clear();
+
+			return Task.CompletedTask;
 		}
 
-		public bool NextSong()
+		public async void PreviousSong()
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/Objects/Machines/Jukebox.cs:211]: this unity safe async?

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Objects/Machines/Jukebox.cs:211]: yes

Comment (Bod9001) [reply UnityProject/Assets/Scripts/Objects/Machines/Jukebox.cs:211]: how is it referenced? as in not picking up the default c# version

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Objects/Machines/Jukebox.cs:211]: its not using anything related to unity so its fine

Comment (Bod9001) [reply UnityProject/Assets/Scripts/Objects/Machines/Jukebox.cs:211]: isn't the issue there that it goes into a different thread and then unity complains about, trying to access it from non-unity thread?

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Objects/Machines/Jukebox.cs:211]: unity only complains if you accessing the `gameObject` variable, also we've been using tasks forever now with jukeboxes and it works fine.

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Objects/Machines/Jukebox.cs:211]: hewwo??

File: UnityProject/Assets/Scripts/Objects/Machines/Jukebox.cs [hunk 2]
```diff
@@ -168,34 +167,19 @@ private void UpdateMe()
...
-				SoundManager.StopNetworked(guid);
-				IsPlaying = true;
-				spriteHandler.SetSpriteSO(SpritePlaying);
-				guid  = await SoundManager.PlayNetworkedAtPosAsync(musics[currentSongTrackIndex], registerTile.WorldPositionServer, audioSourceParameters, false, true, sourceObj: gameObject);
-				startPlayTime = Time.time;
-				UpdateGUI();
-			}
+			if (integrity.integrity < integrity.initialIntegrity / 2) return;
+			IsPlaying = true;
+			spriteHandler.SetSpriteSO(SpritePlaying);
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/Objects/Machines/Jukebox.cs]: this will error from different thread I think

File: UnityProject/Assets/Scripts/Objects/Machines/Jukebox.cs [hunk 3]
```diff
@@ -168,34 +167,19 @@ private void UpdateMe()
...
+			guid.Add(await SoundManager.PlayNetworkedAtPosAsync(musics[currentSongTrackIndex], registerTile.WorldPositionServer, audioSourceParameters, false, true, sourceObj: gameObject));
+			startPlayTime = Time.time;
+			UpdateGUI();
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/Objects/Machines/Jukebox.cs:183]: this to maybe

File: UnityProject/Assets/Scripts/Objects/Machines/Jukebox.cs (hunk 2 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Objects/Machines/Jukebox.cs]: Wont error because it's done entirely on the server + hasn't errored before

File: UnityProject/Assets/Scripts/Objects/Machines/Jukebox.cs (hunk 3 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Objects/Machines/Jukebox.cs:183]: same comment as above

**Comment by Bod9001** [comment]
UpdateGUI(); what about that?

**Comment by MaxIsJoe** [comment]
> ```
> 		UpdateGUI(); what about that?
> ```

Never had any issues with the UI and from the way its coded i assume whoever did this was aware that there are some issues with referencing the GUI stuff directly so they made a special function that handles all that on the main thread.

**Comment by Bod9001** [comment]
ok cool

**Review by Bod9001 — APPROVED** [review]
