### PR TITLE
Bunch of fixes and QoL changes for bombs, mousetraps, and SBRs

### LINKED ISSUE #7957: Mousetraps can be infinitely triggered by opening a bag
### Environment
- Game Version: 21121104

### Detailed description of bug

Armed mousetraps do not disarm when they are set off inside a bag, meaning they can be infinitely triggered. 

-this part needs more thorough testing- They may also possibly be triggered by opening the bag *after they have been removed from the bag itself*

### Steps to reproduce

1. arm a mouse trap
2. place it inside a container
3. open the container as many times as you want, the mousetrap endlessly triggers.

### LINKED ISSUE #7958: Armed mousetraps should prevent a character from opening a bag until all the mousetraps have been triggered or the player uses disarm intent
### Environment
- Game Version: 21121104

### Detailed description of bug

When you place armed mousetraps inside a bag, they act as a frustrating denial mechanic by snapping on players unless they use the proper procedure (using disarm intent) to open the bag. Otherwise, it prevents them from properly opening it.

With the current implementation, a character will get snapped by the first trap, but can simply remove and disarm the rest once they have the bag open

### Steps to reproduce

1. open a bag with multiple armed mousetraps
2. get snapped by first trap
3. you are now free to remove the rest without incident.

### LINKED ISSUE #7959: Station Bounced Radio chat message format is a mess
### Environment
- Game Version: 21121104

### Detailed description of bug

the SBR sprite is cut off, the message repetition number picks a different spot to show with each message, 

Screenshot 2021-12-11 142232

In this example, we had 2 radios adjacent to eachother, hence the chat repeated 4 times. 

### Steps to reproduce

1. use a station bounced radio

### LINKED ISSUE #7960: Picking exact frequencies with the Station Bounced Radio is difficult.
### Environment
- Game Version: 21121104

### Detailed description of bug

When me and Potato tried to pick the same radio frequency on a pair of SBRs, we found it very difficult to accurately get the same number. Perhaps it would benefit from allowing players to type the frequency they want in addition to using the slider, or perhaps adding more weight or length to the slider. I think screen resolution may have had something to do with the problem with using the slider effectively

### Steps to reproduce

1. try to pair 2 radios together with someone else

### PR DESCRIPTION
**Pull request by MaxIsJoe**
CL: [Fix] - Fixed an issue with mousetrap not being set to be inactive after triggering due to a code step execution oversight ( fixes #7957 )
CL: [Fix] - Fixed an issue where I forgot to re-add the disarm intent logic for mousetraps (twice! whoops)
CL: [New] - Mousetraps will now prevent the UI slots from appearing when they are active ( closes #7958 )
CL: [New] -Added a text field to the frequency changer UI for more precise and quick channel changes ( closes #7960 )
CL: [Improvement] - Replaced the radio icon with frequency text ( closes #7959 )
CL: [Improvement] -  Pairing a bomb with an emitter now copies the emitter frequency.
CL: [New] - Added the ability to detach bombs from surfaces.
CL: [Improvement] - Replaced the old explosion method with the new one; resulting in smaller code and fixing an issue where bombs couldn't harm walls.
CL: [Balance] - C4s have been rebalanced to be less deadly, but they're still harmful enough to tear some limbs apart if placed directly ontop of a player.
CL: [Fix] - Fixed an issue where bombs couldn't follow moveable objects like players and lockers.
CL: [Improvement] - The explosive UI is now treated as a normal tab and will not be draggable around the screen.

### CODE REVIEW

File: UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs [hunk 1]
```diff
@@ -85,17 +88,32 @@ private void Detonate()
...
+			}
+
+		}
 
-				// Explosion here
-				var explosionGO = Instantiate(explosionPrefab, explosionMatrix.transform);
-				explosionGO.transform.position = worldPos;
-				explosionGO.Explode(explosionMatrix);
+		[Server]
+		private void CmdAttachExplosive(GameObject target, Vector2 targetPostion)
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs]: so,  CMD how do you check that  the interaction is valid?

Comment (Bod9001) [reply UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs]: and not just made up by a hacked client to cheat

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs]: It's set to `[server]` only so i don't know how a client can trigger it

Comment (Bod9001) [reply UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs]: change the name then  since CMD is reserved for cmds

File: UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs [hunk 2]
```diff
@@ -85,17 +88,32 @@ private void Detonate()
...
+		{
+			if (target.TryGetComponent<PushPull>(out var handler))
+			{
+				Inventory.ServerDrop(pickupable.ItemSlot);
+
+				transform.SetParent(handler.transform);
```
Comment (ThatDan123) [inline UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs]: Dont do this as its not networked, and we shouldnt be parenting networked object.

Luckily i recently found a solution, Constraints!

https://docs.unity3d.com/Manual/Constraints.html

Make a new NetworkedConstraints script, have a sync var of gameobject and then in the hook do the constraint stuff

Remember to remove the constraint if the item is picked up

Comment (ThatDan123) [reply UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs]: Actually thinking about it, this is gonna be more tricky as the tilemap position of the object isnt moved. 

I think theres an event you can subscribe to the attached objects custom transform or register tile for when it is moved.

And then have the C4 move when that event is invoked.

Don't need to use the constraints/transform this way.

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs]: I can't find the event that allows this

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs]: there is one on custom net transform but it doesn't accept functions

**Review by Bod9001 — DISMISSED** [review]

**Comment by MaxIsJoe** [comment]
Don't approve this just yet!
Bomb attachment is still broken!

File: UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs [hunk 3]
```diff
@@ -98,16 +100,21 @@ private void Detonate()
...
 				//TODO : Figure out why the position keeps getting offset to it's last position inside the parent's hierarchy (it doesn't want to 0,0)s
-				transform.localPosition = new Vector3(0, 0, 0);
-				transform.position = new Vector3(0, 0, 0);
+				attachedObjectTile = target.RegisterTile();
+				netTransform.OnTileReached().AddListener(pos => {
+					if(attachedObjectTile != null)
+					{
+						registerItem.ServerSetLocalPosition(attachedObjectTile.customNetTransform.ServerLocalPosition);
+					}
+				});
```
Comment (ThatDan123) [inline UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs]: You'll need to make the inside a proper function so you can remove the listener

**Comment by Bod9001** [comment]
ok

File: UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs (hunk 3 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs]: You can't make this a function
it won't accept a function

Comment (ThatDan123) [reply UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs]: It does, you just need to have a pos parameter

**Comment by PerfectTangent** [comment]
> Don't approve this just yet! Bomb attachment is still broken!

If you're PR is unfinished, make it a draft next time

File: UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs (hunk 3 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs]: image

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs]: this returns an error when setting the location, any idea why?

Comment (ThatDan123) [reply UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs]: `netTransform.OnTileReached().AddListener(UpdateBombPosition);`

`private void UpdateBombPosition(Vector3Int pos)`

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs]: That doesn't work
"Expected a method with  UpdateBombPosition(Vector3Int pos) signature"

Comment (ThatDan123) [reply UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs]: `netTransform.OnTileReached().AddListener(UpdateBombPosition());`

Try with the backets after `UpdateBombPosition`, i always forget if its needed

File: UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs [hunk 4]
```diff
@@ -123,6 +118,15 @@ private void AttachExplosive(GameObject target, Vector2 targetPostion)
 			if (spriteHandler != null) spriteHandler.transform.localScale = new Vector3(0.6f, 0.6f, 0.6f);
 		}
 
+		public Vector3Int UpdateBombPosition(Vector3Int pos)
```
Comment (ThatDan123) [inline UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs]: Dont need the return

**Comment by MaxIsJoe** [comment]
Done, pls review

File: UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs [hunk 5]
```diff
@@ -85,17 +88,35 @@ private void Detonate()
...
-				explosionGO.transform.position = worldPos;
-				explosionGO.Explode(explosionMatrix);
+		[Server]
+		private void AttachExplosive(GameObject target, Vector2 targetPostion)
+		{
+			if (target.TryGetComponent<PushPull>(out var handler))
+			{
+				Inventory.ServerDrop(pickupable.ItemSlot, targetPostion);
+				attachedToObject = target;
+				UpdateManager.Add(CallbackType.UPDATE,UpdateBombPosition);
```
Comment (ThatDan123) [inline UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs]: wut, did the tile reached not work?

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs]: > wut, did the tile reached not work?

It didn't because it's not constantly invoked.

Comment (ThatDan123) [reply UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs]: why is that needed?

Comment (ThatDan123) [reply UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs]: Humm i guess, it is needed. Can you add a check in UpdateBombPosition for if the position of the attachedToObject is the same as the explosive to not call `SetPosition`

File: UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs [hunk 6]
```diff
@@ -85,17 +88,35 @@ private void Detonate()
...
+				if (spriteHandler != null) spriteHandler.transform.localScale = new Vector3(0.6f, 0.6f, 0.6f);
```
Comment (ThatDan123) [inline UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs]: Don't think scale is sync'd.

Not even sure we have a component that does it already, you're gonna have to make a new component to do it using a sync var.

File: UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs [hunk 7]
```diff
@@ -107,6 +128,16 @@ public void ToggleMode(bool mode)
 			detonateImmediatelyOnSignal = mode;
 		}
 
+		private void DeAttachExplosive()
+		{
+			isOnObject = false;
+			pickupable.ServerSetCanPickup(true);
+			objectBehaviour.ServerSetPushable(true);
+			if (spriteHandler != null) spriteHandler.transform.localScale = new Vector3(1f, 1f, 1f);
+			UpdateManager.Remove(CallbackType.UPDATE,UpdateBombPosition);
```
Comment (ThatDan123) [inline UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs]: Can you also add a Remove in `OnDisable`

File: UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs (hunk 6 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs]: if i turn the scale thing into a command function called by the server; would it work on both the client and server? or will it try kicking the player again?

File: UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs (hunk 5 above)
Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs]: Good point, will add it

File: UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs (hunk 6 above)
Comment (ThatDan123) [reply UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs]: > if i turn the scale thing into a command function called by the server; would it work on both the client and server? or will it try kicking the player again?

Will need to be a sync var for late joiners. And make a new script for it as it could be useful in the future, call it NetworkScale or something like that

Comment (ThatDan123) [reply UnityProject/Assets/Scripts/Items/Weapons/Explosive.cs]: Also might be better to make it a periodic update on like `0.1f` as it doesnt need to be every frame

**Comment by MaxIsJoe** [comment]
Done, review pls

**Review by Bod9001 — DISMISSED** [review]

File: UnityProject/Assets/Scripts/Core/Transform/ScaleSync.cs [hunk 8]
```diff
@@ -0,0 +1,35 @@
...
+using System.Collections.Generic;
+using Mirror;
+using UnityEngine;
+using UnityEngine.Networking;
+
+
+namespace Scripts.Core.Transform
+{
+
+    public class ScaleSync : NetworkBehaviour
```
Comment (ThatDan123) [inline UnityProject/Assets/Scripts/Core/Transform/ScaleSync.cs:11]: Where did you put this on the explosive, on the sprite object or the top level object?

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Core/Transform/ScaleSync.cs:11]: On the sprite itself.

Comment (ThatDan123) [reply UnityProject/Assets/Scripts/Core/Transform/ScaleSync.cs:11]: You'll need to move it to the parent and then select the wanted transform in the editor as having it on the sprite will add a network identity to the child object.

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Core/Transform/ScaleSync.cs:11]: Done.

**Comment by MaxIsJoe** [comment]
review pls

**Review by ThatDan123 — APPROVED** [review]

**Review by NoooneyDude — APPROVED** [review]
