### PR TITLE
Fixes sounds and jitter for shuttle movement

### LINKED ISSUE #8741: Sound doppler effect is broken on moving shuttles
### Environment
- Game Version: 22052105
- OS Version: Windows 10

### Detailed description of bug
Currently, the doppler effect for moving towards and away from sounds is based on your global position, rather than your matrix position. This causes problems where you can have an entire shuttle's worth of people screaming, but thanks to the speed, you hear essentially nothing.

### PR DESCRIPTION
**Pull request by MaxIsJoe**
Partially addresses #2423 and fixes #8741

CL: [Fix] Fixed an issue that caused sounds to physically fall off moving shuttles, which resulted in sounds being broken or outright silent at times from the perspective of the people inside the moving shuttle.
CL: [Fix] Reduced the amount of jitter moving shuttles have significantly.

### CODE REVIEW

File: UnityProject/Assets/Scripts/Shuttles/MatrixMove.cs [hunk 1]
```diff
@@ -602,7 +575,7 @@ private void AnimateMovement()
 		{
 			//Only move target if rotation is finished
 			//predict client state because we don't get constant updates when flying in one direction.
-			clientState.Position += (clientState.Speed * Time.deltaTime) * clientState.FlyingDirection.LocalVector;
+			clientState.Position += (clientState.Speed * Time.fixedDeltaTime) * clientState.FlyingDirection.LocalVector;
```
Comment (Bod9001) [inline UnityProject/Assets/Scripts/Shuttles/MatrixMove.cs:578]: Is matrix on fixed update?

Comment (MaxIsJoe) [reply UnityProject/Assets/Scripts/Shuttles/MatrixMove.cs:578]: The function is called from fixed update yea

**Review by Bod9001 — APPROVED** [review]
