### PR TITLE
Removes the ability to shoot inside a locker

### LINKED ISSUE #2072: You can shoot guns inside lockers
# Description
You can shoot inside lockers.

And it doesn't look too good, you actually just get recoil effect and literally nothing else happens, not even bullets appear.

## Category
BUG

## Detailed Bug Report
TODO: Remove shooting insided locker.

## Steps to Reproduce
Get in the locker with a machine gun and ratatatatatata

### PR DESCRIPTION
**Pull request by zrparsons**
### Purpose
Removes the ability to shoot inside lockers fixes #2072 
### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [x]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### Notes:
I'm still not super familiar with the code base so this might not be the best way to do this but it is my understanding that 'IsHidden' is used exclusively for being inside lockers.

### CODE REVIEW

**Comment by zrparsons** [comment]
just saw that this one might have been fixed already by #2092 so you can probably close this one

**Comment by fomalsd** [comment]
haven’t checked if it’s the case, but I didn’t do it on purpose

**Comment by zrparsons** [comment]
oh sorry you referenced it in that issue thought you might have fixed it.

**Comment by fomalsd** [comment]
yeah, it was a typo in an issue number but the reference didn’t go away for some reason

File: UnityProject/Assets/Scripts/Weapons/Gun.cs [hunk 1]
```diff
@@ -179,6 +179,10 @@ protected override bool WillInteract(AimApply interaction, NetworkSide side)
 			return false;
 		}
 
+		if (interaction.Performer == PlayerManager.LocalPlayer && PlayerManager.PlayerScript.IsHidden){
+			return false;
+		}
+
```
Comment (Aranclanos) [inline UnityProject/Assets/Scripts/Weapons/Gun.cs]: grab the playerscript with a getcomponent() call so both the server and client can do the check, this specific function acts like that

**Review by Aranclanos — CHANGES_REQUESTED** [review]

**Comment by Aranclanos** [comment]
though at the same time im not sure about making this check here, since all other items would need it but chairbender would know better

File: UnityProject/Assets/Scripts/Weapons/Gun.cs (hunk 1 above)
Comment (zrparsons) [reply UnityProject/Assets/Scripts/Weapons/Gun.cs]: I just pushed another commit anyway with what i think you wanted and yea thats a much better way of doing it, sorry still learning.

**Comment by fomalsd** [comment]
@chairbender could you take a look at this PR? maybe “inside locker” check should be added to default validations for PositionalHandApply or something like that?

**Comment by chairbender** [comment]
I would suggest adding it to the default AimApply validation, since that's the interaction used for shooting.

**Review by chairbender — COMMENTED** [review]
I would suggest adding it to the default AimApply validation, since that's the interaction used for shooting.

That can be found in DefaultWillInteract.AimApply

**Comment by zrparsons** [comment]
just pushed a new commit moving it to defaultWillInteract tell me if that boolean expression is too gross.

also thanks for all the help guys.

File: UnityProject/Assets/Scripts/Input System/InteractionV2/DefaultWillInteract.cs [hunk 2]
```diff
@@ -72,7 +72,9 @@ public static bool MouseDrop(MouseDrop interaction, NetworkSide side)
 	/// </summary>
 	public static bool AimApply(AimApply interaction, NetworkSide side)
 	{
-		return Validations.CanInteract(interaction.Performer, side);
+		return  Validations.CanInteract(interaction.Performer, side) &&
```
Comment (fomalsd) [inline UnityProject/Assets/Scripts/Input System/InteractionV2/DefaultWillInteract.cs]: Yeah, the idea seems right. That bool inversion is hard to spot though and it's best to avoid calling GetComponent when it's not required. How about this:
```cs
		if ( !Validations.CanInteract(interaction.Performer, side) )
		{
			return false;
		}

		bool? isNotHidden = !interaction.Performer.Player()?.Script.IsHidden;
		return isNotHidden.GetValueOrDefault( true );
```

Comment (zrparsons) [reply UnityProject/Assets/Scripts/Input System/InteractionV2/DefaultWillInteract.cs]: yea that does look a lot better just pushed another commit, thanks.

**Comment by fomalsd** [comment]
sweet, cheers
