### PR TITLE
Science Improvements and Fixes

### LINKED ISSUE #9801: [Mapping] Maintrooms doors are all unpowered and bolted.
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Map

Other

### Description of the problem

The doors that spawn as part of the maze generation bit (not the preplaced rooms) have doors all throughout that are all bolted and unpowered making it much hard to traverse. The doors should be powered and unbolted.

### Pictures/videos

image
what the door looks like idk it requires a image.

### PR DESCRIPTION
**Pull request by AtnerNT**
Fixes #9801

### Changelog:

CL: [New] Added particle effects for Artifacts on players they are attempting to affect. If the artifact fails to effect the player (possibly due to the player wearing anomaly armour) different particles will play, indicating the artifact triggered but failed. Done with the aim of reducing confusion from certain artifact effects.
CL: [New] Cyborg chassis's can now be secured with a screwdriver - turning the chasis into a valid body that surgery can be performed on.
CL: [Improvement] All high energy / laser lab objects have received new artwork.
CL: [Improvement] All high energy / laser lab objects have been given new, more appropriate names and descriptions.
CL: [Improvement] Gave R&D Laser projector tooltips for accessibility.
CL: [Improvement] Refactored R&D laser projector to be controlled via a GUI.
CL: [Improvement] Ministation science remapped with a proper high energy lab.
CL: [Fix] Fixed BYD GUI not updating bounty list and graph correctly.
CL: [Fix] Fixed maintroom doors being unpowered and bolted

### CODE REVIEW

File: UnityProject/Assets/Scripts/UI/Objects/Research/BlastYieldDetector/ExplosiveBountyUIEntry.cs [hunk 1]
```diff
@@ -31,7 +31,9 @@ public void Initialise(ExplosiveBounty bountyData, int index)
 				label_text.Append($"\n\t-{reagent.RequiredReagent.Name}: {reagent.RequiredAmount}u");			
 			}
 
-			bountyDetails.MasterSetValue(label_text.ToString());
+			Debug.Log(label_text);
```
Comment (MaxIsJoe) [inline UnityProject/Assets/Scripts/UI/Objects/Research/BlastYieldDetector/ExplosiveBountyUIEntry.cs]: remove debug.log
if you need it, use Logger instead.

**Review by MaxIsJoe — CHANGES_REQUESTED** [review]

**Comment by MaxIsJoe** [comment]
Aside from the debug.log one, LGTM.
Will approve once removed.

**Comment by MaxIsJoe** [comment]
Also can we get screenshots/video of everything added?

**Comment by AtnerNT** [comment]
> Also can we get screenshots/video of everything added?

Ill get on it

**Comment by AtnerNT** [comment]
Ready for merge. Gonna get some sc and vids

**Review by MaxIsJoe — APPROVED** [review]

File: UnityProject/Assets/Scripts/Systems/Research/LaserPuzzle/LaserProjection.cs [hunk 2]
```diff
@@ -203,6 +203,13 @@ public void CleanupAndDestroy(bool Reshoot = false)
 		{
 			Destroy(Line.gameObject);
 		}
+
+		if (CustomNetworkManager.Instance._isServer)
```
Comment (MaxIsJoe) [inline UnityProject/Assets/Scripts/Systems/Research/LaserPuzzle/LaserProjection.cs:207]: you know you can just do `CustomNetworkManager.IsServer` instead of this, right?
