### PR TITLE
Prevents dead or unconscious people from removing handcuffs.

### LINKED ISSUE #2993: You can remove your handcuffs when dead
## Description

When you're dead or unconscious, you can remove handcuffs. 

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Die handcuffed.
2.  Stay in your body
3.  Uncuff yourself normally.

### PR DESCRIPTION
**Pull request by Ruzihm**
### Purpose
Fixes #2993

### Notes:
Problem was caused by a reference to `PlayerHealth.serverPlayerConscious` which doesn't seem to actually do anything.

### CODE REVIEW

File: UnityProject/Assets/Scripts/Clothing/RestraintOverlay.cs [hunk 1]
```diff
@@ -98,9 +98,11 @@ IEnumerator UncuffCountDown(CancellationToken cancelToken)
 
 	bool CanUncuff()
 	{
-		if (!thisPlayerScript.playerHealth.serverPlayerConscious ||
+		PlayerHealth playerHealth = thisPlayerScript.playerHealth;
```
Comment (DooblyNoobly) [inline UnityProject/Assets/Scripts/Clothing/RestraintOverlay.cs:101]: Pretty sure PlayerHealth is null if you are a ghost. Is there anyway CanUncuff() might get called if you are a ghost? Maybe you should check that playerHealth exists and if it doesn't then return false. To be safe.

**Review by DooblyNoobly — CHANGES_REQUESTED** [review]

File: UnityProject/Assets/Scripts/Clothing/RestraintOverlay.cs (hunk 1 above)
Comment (Ruzihm) [reply UnityProject/Assets/Scripts/Clothing/RestraintOverlay.cs:101]: Great point. `playerHealth` was already being dereferenced before this pull request but now is as good a time as any to have that check.
